### ISSUE TITLE
Wrong test runs on the first attempt

### ISSUE THREAD

**Issue by varnk** [nunit/nunit3-vs-adapter#1002]
* NUnit 3.13.3, NUnit3TestAdapter 4.2.1
* Visual Studio Enterprise 2017 15.9.49
* .Net Framework 4.6.1

Steps to reproduce:
1.  Startup Visual Studio
2.  Load my test solution.
3. Right-click in Test Explorer or right-click on the test method in the code.
4. Select Debug Test

At this time, the wrong test will run.  Usually it is the first test that is found in the test DLL.  

Sometimes if I do a rebuild of the solution, then attempt to debug the selected test again, the correct test will run.  This does not always work and may require one or more attempts before the selected test is actually run.

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".

**Comment by varnk** [comment]
Sorry it took so long to get back on this.  I have attached a zip file with a sample project that reproduces the issue.
Note that for some reason the tests won't run unless you select the .runsettings file in Visual Studio. 

I don't know if all of these steps are necessary, but this is how I reproduced it:

1. Start Visual Studio and load the solution.
2. Select the CoverageNoParallel.runsettings file using Test->Test Settings->Select Test Settings File.
3. Build the solution.
4. Exit Visual Studio
5. Start Visual Studio back up again.
6. Load the solution.
8. Using Test Explorer, right-click on TestMethod2 and select Debug Selected Test.
9. At this point, TestMethod1 will run even though I selected only TestMethod2.

[Issue#1002.zip](https://github.com/nunit/nunit3-vs-adapter/files/9251464/Issue.1002.zip)
.

**Comment by varnk** [comment]
I have provided a sample repo, but am still waiting for a response on this issue.   Can someone verify this issue and provide a response?

**Comment by OsirisTerje** [comment]
Old csproj format => Non.SDK style format
Old package format => packages.config
New csproj format => SDK style format
New package format => PAckageReferences
Default for .Net framework is Non-sdk style format,  default for .Net core and .Net 5 and above is SDK style format. But you can run .net framework also using SDK format and in particular package references. 
You can also migrate over, see https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference 
Visual Studio 2017 can be configured for either packages.config or PackageReferences.  The latter is recommended.

**Comment by OsirisTerje** [comment]
I just copied your code into a new VS2022 project, SDK style and PackageReferences, and it works as it should.  If I debug the second method just after startup, it jumps to that method. 

My VS2017 is defunct, but I'll try to get it working to check that out.  

However, if there is something wrong there, Microsoft will not fix that - VS2017 is no longer fully supported, it is on Extended support, meaning basically only security fixes will be done.  (And I don't think the adapter is doing any of this, what happens in the Test Explorer and running of the tests is handled by the Visual Studio components.) 
Is there any reason why you can't use the latest version of Visual Studio ?

**Comment by varnk** [comment]
Although I have MSDN and can install any version of Visual Studio, there are some people on my team who only have licenses for VS 2015 or VS 2017.  Eventually we will upgrade the VS licenses, but we are not there yet.  Thus, I need to maintain compatibility with the older versions of VS until they are upgraded.  
Keep in mind that we didn't have this issue when we were using VSTest.  It only started happening when I switched is over to use NUnit.

**Comment by OsirisTerje** [comment]
Do you see the same if you use e.g. version 3.17.0 ?

**Comment by OsirisTerje** [comment]
@varnk I have just checked your repo with VS 2017, 15.9., and with Adapter 4.2.1 I am not able to run the tests at all, when doing one-by-one.  Downgrading to version 3.17.0, and it all works as it should. 

However, if you have the Discover Tests in real-time option turned on, the sequence of tests in the Test Explorer may vary.  But, if you select a given test, that test will be run (e.g. in Debug).  

Can you please try on your side?

Wrt version 4.2.1, there is something going on with resolving the FQN, and it doesn't match the way it should.  The adapter can be configured to use the legacy discoverer, which requires a .runsettings file to be present and the correct options set there.  (DiscoveryMode).  It will probably be better to use version 3.17 simply.

**Comment by varnk** [comment]
That's odd.  I am using the 4.2.1 adapter and it runs the tests, just not the selected test on the first run.  I tried turning on Legacy mode and it still has the same issue - The wrong test runs on first try.

However, I did go ahead and install VS 2022 and tried the same solution in there.  The selected test does run correctly on the first try.  So, it does seem to be isolated to VS 2017 (at least in my case).

**Comment by OsirisTerje** [comment]
@varnk 
Can you reproduce this on more than one machine?  (The VS2017 dysfunction with 4.2.1, and if it works with 3.17 or not.)

If you can,  there must be some difference between your installation and the one I have.

**Comment by varnk** [comment]
> @varnk Can you reproduce this on more than one machine? (The VS2017 dysfunction with 4.2.1, and if it works with 3.17 or not.)
> 
> If you can, there must be some difference between your installation and the one I have.

Sorry, I completely missed your response.  Didn't get notified about it for some reason.  Anyhow, I've decided to bite the bullet and upgrade to VS 2022.  The problem does not seem to exist there.  Our team will be moving to newer versions of VS soon.
