### ISSUE TITLE
Possible Bug: Unexpected Exception with Aysnc methods

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#101]
This was filed mistakenly against the NUnit project.

See issue nunit/nunit#1149 for details.

**Comment by JoshuaKrstic** [comment]
Any updates on this issue? I read nunit#1149, my problem is exactly the same. My test is making a single async HTTP request and getting the same failure: 

`End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult) at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)`

Code sample:

`var fullUri = new Uri(uriString, UriKind.Absolute);

using (var client = new HttpClient())
{
    using (var requestMessage = new HttpRequestMessage(httpMethod, uri))
    {
        requestMessage.Headers.Authorization = authHeader;
        requestMessage.Headers.Add(SessionIdHeader, sessionId);
        Logger.Info($"Request sent to Uri {uri} with sessionId {sessionId}.");

        if (requestContent != null)
        {
            requestMessage.Content = new StringContent(
                requestContent,
                Encoding.UTF8,
                "application/json");
        }

        var response = await client.SendAsync(requestMessage);

        Assert.IsNotNull(response, "Response was null, expected it to be defined");
        Assert.AreEqual(response.StatusCode, HttpStatusCode.OK,
            $"Expected {HttpStatusCode.OK}, got {response.StatusCode}.");
        Assert.IsTrue(response.RequestMessage.RequestUri.ToString().Contains("/core/login"),
            $"Expected redirect location to contain /core/login, got {response.Headers.Location}");
    }
}`

**Comment by OsirisTerje** [comment]
@JoshuaKrstic  Can you provide the above code as a complete compilable repro project ?   
This issue has been in Confirm state since 2015, and should really have been closed.  
A complete repro would be good, because we have not been able to repro this ourselves.
