### ISSUE TITLE
Package VS2012 assemblies as a private NuGet Package

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#102]
I tried to do some work on the adapter the other day, but I can't build because I don't have VS2012 installed. In the past, I have updated the references to 2013, but that is less than ideal. 

I checked what some other projects do and they have created a NuGet package of the VS assemblies they need and uploaded it to MyGet for their use only. I have already setup a MyGet feed to use, so we just need to create the NuGet package and update the references.

Sam Harwell has packaged most of the VS assemblies as NuGet packages and Microsoft made him an MVP for it and points people to his packages, so I assume they are fine with it.

**Comment by CharliePoole** [comment]
This makes sense to me. @OsirisTerje what do you think?

**Comment by CharliePoole** [comment]
Alternatively, one of us can just send you a copy of the assembly.

**Comment by OsirisTerje** [comment]
I like Robs idea of adding it up to a MyGet feed.

**Comment by CharliePoole** [comment]
@rprouse Let's do it then. We'll also have to make sure that one of us keeps testing it in VS2012.
