### ISSUE TITLE
update root folder links

### ISSUE THREAD

**Issue by Arhell** [nunit/nunit3-vs-adapter#1021]
http=>https

**Comment by OsirisTerje** [comment]
Hi!   There is very little value in raising issues of this kind.  Would really appreciate if you just added a few more words around this, or, if you just fix a few things in the files, like the last PR, just skip the issue all together and just do the PR. :-)

**Comment by OsirisTerje** [comment]
Thanks for the 1st PR!  And for the second, you could just do the delete of that file there - that would be ok too :-)
