### ISSUE TITLE
Problem if OutputXmlFolderMode setting is not in .runsettings

### ISSUE THREAD

**Issue by varnk** [nunit/nunit3-vs-adapter#1030]
* NUnit 3.13.1 
* NUnit3TestAdapter 4.3.0
* Visual Studio 2022 Enterprise Version 17.4.0
* .NET Framework 4.6.1 

When I have a .runsettings file selected in VS with a missing OutputXmlFolderMode setting, I cannot run or debug any tests.  Visual Studio starts the test for a short time, and then the debug session just ends without any message or without hitting any of the code in the test.  Once I added the OutputXmlFolderMode into the .runsettings file, the test started working again.

local.runsettings file attached with OutputXmlFolderMode set.  Remove the OutputXmlFolderMode line to reproduce the problem.

[local.zip](https://github.com/nunit/nunit3-vs-adapter/files/10006131/local.zip)

**Comment by OsirisTerje** [comment]
@varnk That's correct.  It is fixed in the 4.3.1, ETA 1-2 days or so.  See #1026 and #1027.  There is an alpha there too, if you want to try.

**Comment by varnk** [comment]
Looks like this problem also exists in Visual Studio 2022 Version 17.4.0 with the NUnit3TestAdapter 4.2.1 also.  I don't believe this version of the TestAdapter supports the OutputXmlFolderMode, so maybe this is a different issue.

**Comment by OsirisTerje** [comment]
Released here https://www.nuget.org/packages/NUnit3TestAdapter/4.3.1

**Comment by netcorefactory** [comment]
we should not presume everyone is on net.core?

**Comment by OsirisTerje** [comment]
@netcorefactory  No :-)
