### ISSUE TITLE
net461 tests don't run with Nunit3TestAdapter 4.3.x

### ISSUE THREAD

**Issue by ermshiperete** [nunit/nunit3-vs-adapter#1040]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions
  NUnit 3.13.3, NUnit3TestAdapter 4.3.1, Microsoft.NET.Test.Sdk 17.4.0
* Visual Studio edition and full version number (see Help About)
  n/a since I run from the command line, but `dotnet --version` gives `7.0.100`
* A short repro, preferably attached or pointing to a git repo or gist
  https://gist.github.com/ermshiperete/820a93a320e300a52ab569e00329a397
* What .net platform and version is being targeted
  net461

I have a project that targets net461. With that and NUnit3TestAdapter 4.3.0 and 4.3.1 no tests are discovered when I run `dotnet test`. Things work if I explicitly specify the path test dll: `dotnet test bin\debug\net461\NUnitAdapterBug.dll`

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".

**Comment by ermshiperete** [comment]
Ha, you were faster than I! I still worked on the repro. Here it is: https://gist.github.com/ermshiperete/820a93a320e300a52ab569e00329a397

Thanks!

**Comment by OsirisTerje** [comment]
I was first going to comment that the Microsoft.NET.Test.Sdk version 17.4.0 doesn't support .net 4.6.1, the lowest is 4.6.2, see https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/17.4.0#supportedframeworks-body-tab  

But, then I just ran your repro to prove the point, and it actually ran in Visual Studio.  
![image](https://user-images.githubusercontent.com/203432/206791447-25c11513-00f4-46b7-985b-579defb0df7b.png)

That means it somehow finds what it should with Visual Studio, but then, this is not really supported anymore.  So this may or may not work. 

With dotnet test I get the same as you with 17.4.0-
Then, if you lower it down to 17.3.2, that one supports all the way down to net40,  https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/17.3.2#supportedframeworks-body-tab

Running dotnet test with 17.3.2 finds your tests:
![image](https://user-images.githubusercontent.com/203432/206792396-680ccf9d-1bf6-47ad-8def-6bd438dec32a.png)


So this is not related to the adapter, but to the test.sdk.  There should however have been a warning, or actually an error, saying that combining the version 17.4.0 with targeting anything lower than 4.6.2 doesn't work.   
You could raise an issue in the  [VSTest repo](https://github.com/microsoft/vstest/issues), point it to this issue, and ask for such an error.  
I'm pretty sure more people will hit this one, so thanks for raising the issue!

**Comment by ermshiperete** [comment]
Thanks @OsirisTerje!
