### ISSUE TITLE
How to append date_timestamp in the test result file name?

### ISSUE THREAD

**Issue by Suban5** [nunit/nunit3-vs-adapter#1041]
I am currently using '.runsettings' to generate XML output file from visual studio. Is there any way to append the timestamp in the filename?

I am using the following runsettings file:

```
<RunSettings>
	<NUnit>
		<TestOutputXml>C:\TestResults</TestOutputXml>
		<OutputXmlFolderMode>RelativeToResultDirectory</OutputXmlFolderMode>
		<NewOutputXmlFileForEachRun>true</NewOutputXmlFileForEachRun>
	</NUnit>
</RunSettings> 
```

**Comment by OsirisTerje** [comment]
Sorry for the late reply, Christmas holidays :-) 

No, it is currently no way to append timestamps.  Not sure if this is something we would do either.  It could be an option for an extension, currently, we don't have that possibility, but it is something that could be useful. If that was in, you could add such a feature directly yourself.
