### ISSUE TITLE
NuGet package web page: broken link

### ISSUE THREAD

**Issue by BrainCrumbz** [nunit/nunit3-vs-adapter#105]
In NuGet package web page (https://www.nuget.org/packages/NUnit3TestAdapter/) the **Project Site** link seems broken. It points to some http://nunit.org/index.php?p=vsTestAdapter&r=3.0 URL, which in turn show some:

> Not Found
> The page vsTestAdapter could not be located on this site.
>
> Current directory is /home/nunit331/public_html

HTH

**Comment by CharliePoole** [comment]
Thanks! It's fixed now.
