### ISSUE TITLE
First unit test console entry causes VS Test Explorer Warning

### ISSUE THREAD

**Issue by jrod567** [nunit/nunit3-vs-adapter#1053]
In VS Test Explorer, a warning is being logged from the first entry of any console output.  For example, creating a brand new NUnit test project, using two Console.WriteLine messages causes a warning from the very first entry:

 [Test]
        public void Test1()
        {
            Console.WriteLine("test1"); //<-- Warning will occur (see log below)
            Console.WriteLine("test2"); //<-- No Warning
            Assert.Pass();
        }

[2/8/2023 4:00:39.254 PM]  Logging TestHost Diagnostics in file: C:\Users\zzz\AppData\Local\Temp\TestPlatformLogs\2023_02_08_15_46_39_28564\logs.host.23-02-08_16-00-38_93749_32.txt
[2/8/2023 4:00:39.379 PM]  NUnit Adapter 4.2.0.0: Test execution started
[2/8/2023 4:00:39.412 PM]  Running selected tests in C:\Users\zzz\Source\repos\TestProject1\TestProject1\bin\Debug\net6.0\TestProject1.dll
[2/8/2023 4:00:39.527 PM]     NUnit3TestExecutor discovered 1 of 1 NUnit test cases using Current Discovery mode, Non-Explicit run
**[2/8/2023 4:00:39.599 PM] [Warning] test1**
test2

[2/8/2023 4:00:39.610 PM]  NUnit Adapter 4.2.0.0: Test execution complete
[2/8/2023 4:00:39.679 PM]  Attachments processing not needed
[2/8/2023 4:00:39.682 PM]  ========== Test run finished: 1 Tests (1 Passed, 0 Failed, 0 Skipped) run in 253 ms ==========
[2/8/2023 4:00:39.690 PM]  Update Test run progress to 50/100.
[2/8/2023 4:00:39.691 PM]  Update Test run progress to 100/100.
[2/8/2023 4:00:39.724 PM]  Test run animation has stopped.
[2/8/2023 4:00:39.726 PM]  Test run progress has stopped.

* NUnit and NUnit3TestAdapter versions - NUnit 3.13.3, NUnit3TestAdapter 4.2.1
* Visual Studio edition and full version number - VS2022Pro, v17.3.1 x64
* A short repro, preferably attached or pointing to a git repo or gist - see attached picture
* What .net platform and version is being targeted - .net6.0

![VSWarning](https://user-images.githubusercontent.com/48925899/217663073-b031b556-13a5-4da8-9303-b9c180c91a42.png)

**Comment by OsirisTerje** [comment]
If you enable adapter execution Dumps, what does that file show?

**Comment by jrod567** [comment]
Hi OsirisTerje - Interesting; I'd be happy to share.  I have not done this before - are there steps showing how to do this?

**Comment by OsirisTerje** [comment]
The different properties for the runsettings are shown https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html
Dump of execution is : https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#dumpxmltestdiscovery-and-dumpxmltestresults

If you add a file to your solution, called just `.runsettings` (note the dot, this is just a long extension), and add the following to it:
```xml
<RunSettings>
   <NUnit>
       <DumpXmlTestResults>true</DumpXmlTestResults>
   </NUnit>
</RunSettings>
```
That file should be automatically used by the test explorer (by convention), if not, just ensure the auto is enabled, 
![image](https://user-images.githubusercontent.com/203432/219164257-170edbcb-9d16-4a19-ba50-d10d9f4e80d1.png)

or select from the Test menu:
![image](https://user-images.githubusercontent.com/203432/219164927-83bb3eda-cf79-4896-9835-48e9c451a614.png)

You will find the dump file, which is a readable xml'ish file, in a subfolder named `Dump` to the output bin folder.

**Comment by jrod567** [comment]
Thanks Osiris!!  I've attached the xml dump here.  Interestingly, there's no warnings listed in it that I see... strange.

[E_TestProject1.dll.dump.txt](https://github.com/nunit/nunit3-vs-adapter/files/10759011/E_TestProject1.dll.dump.txt)

**Comment by OsirisTerje** [comment]
Ok, that means there is no error in neither the framework nor the engine.  So far so good.

I have uploaded your repro here:  https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1053 

When running it I dont get any such warnings as you get, so not sure where it comes from.

![image](https://user-images.githubusercontent.com/203432/219455286-65e5c91b-6b75-4d53-8d50-1cfce29668df.png)

I do get the same message in the TE, 1 Warning, but it only says there is output for me:

![image](https://user-images.githubusercontent.com/203432/219455553-bb03dcb8-b07d-462d-ac37-8310d8534ab2.png)

I have tried with both the 4.2.1 and the 4.3.1 adapter.

Can you clone down the repro repo and try to run the Issue1053 sln and see if that behaves identical?

Since I don't see this, it is not that likely it is the adapter, but I have never seen anything that could inject in something like what you see.  So a bit curious to what that can be.

Looking at your output, I see you have something diagnostics enabled, and also something in the end there about Test Run animation ?  What is that?
![image](https://user-images.githubusercontent.com/203432/219456617-561d9a15-1aa1-47fd-8fb7-b1dd1750376e.png)

**Comment by jrod567** [comment]
Thanks for the information!  I cloned the repo and I get identical results - 1 Warning like you do that just shows the output.  The extra logging you're seeing is from the logging level I changed to Trace here:

![image](https://user-images.githubusercontent.com/48925899/219483466-4fd4a2f2-0d9a-4720-995f-36d343bb0c4b.png)

I turned these on b/c it was driving me crazy where this warning was coming from - when on, it's what is showing us the [Warning] for that first console entry.  

Here's my Tests output running twice - one with Default logging and one with Trace:

![image](https://user-images.githubusercontent.com/48925899/219483994-717c9537-9f51-42f6-97a1-98ca4697a997.png)

I suppose this begs the question, are we supposed to get a Warning for any type of console output?  From your current response it appears you get this as well and have the same symptom.

**Comment by OsirisTerje** [comment]
In the first message you have here, there is a warning in the Test Output window. That one is **not** in mine, and not either in when you run the repro I uploaded.  Where does that come from in your first example ? 

The warning in the Test Explorer is something the MS came up with some time ago, together with the Errors there.  I really don't know the purpose of those, and I mostly just ignore it - it might go away or they might make it more clear what it really is.  It is anyway confusing.

**Comment by OsirisTerje** [comment]
@jrod567  Just for fun I asked the ChatGPT about this.  And I was rather taken back that I actually got a meaningful answer back, look at this:
![image](https://user-images.githubusercontent.com/203432/219490728-749a5aee-adf8-4c5b-b39d-51f70f377b44.png)

**Comment by OsirisTerje** [comment]
And, when I think about it, I created a library way back to cover cases like unit testing code with certain system functions.  It wraps the calls to these and you can then substitute (using NSubstitute or equals) the output.  The library is here:  https://www.nuget.org/packages/WrapThat.System, https://github.com/WrapThat/WrapThat.System, and a blog post of its use is here https://hermit.no/wrapthat-system-wrappers-for-system-io-to-simplify-unit-testing/     Just a thought :-)

**Comment by nohwnd** [comment]
NUnit itself is collecting that output and writes it as warning based on settings. I don't know how `settings.ConsoleOut` is determined. Test Explorer then just picks up that message and puts it in the summary. 

https://github.com/nunit/nunit3-vs-adapter/blob/master/src/NUnitTestAdapter/NUnitEventListener.cs#L163-L171

> The warning in the Test Explorer is something the MS came up with some time ago, together with the Errors there. I really don't
know the purpose of those, and I mostly just ignore it - it might go away or they might make it more clear what it really is. It is anyway confusing.

The goal here was to make errors and warnings that normally show up in Tests output (which is often hidden by Build output stealing the focus) more visible. So you know why TE sometimes does "nothing" and runs no tests.

**Comment by OsirisTerje** [comment]
@nohwnd Thanks! 
So it picks up warnings from the adapter too, cool!  That makes sense.   
I could not find any docs that mention this, can you point to some?

The ConsoleOut is a runsetting, so it can be set either by a runsettings file or on the command line for `dotnet test`.

The warning also seems to check other things not reported by the adapter, 
![image](https://user-images.githubusercontent.com/203432/220074027-fa4c70aa-62e3-45fb-a0c6-3050f5ec5be4.png)

**Comment by OsirisTerje** [comment]
@jrod567 
It seems this is clear now, as @nohwnd explained, it does come from the way the ConsoleOut is being set.  Default currently is 2, which is identical to a warning. Setting it to 1 will set it to information.
One could argue that the default should be 1, but from earlier discussions, some didn't like that.  I believe that was before the new Warnings Errors came up, so possibly the default should be changed back to 1.  
Thinking about it, that is possibly the best setting when using the Test Explorer, although it would mean changes to some that use this for command line output, as dotnet test then would not output anything without a logger setting.  
There are a lot of SO and github questions around this topic, and no real good answers.

**Comment by jrod567** [comment]
Wow, thank you so much OsirisTerje (and nohwnd) for looking into this!!  Super helpful and makes sense now - setting ConsoleOut to 1 definitely addresses the issue and I do see the tradeoffs; though for our environment, I think this will work well.

In practice, we use Serilog with both console and file sinks - so I can see how the console sink logging is getting captured here in how you explain it.

Again, much appreciated!!!  I'm going to close this one as I think we've got a great workaround and explanation.

**Comment by nohwnd** [comment]
> I could not find any docs that mention this, can you point to some?

I am not aware of any documentation, but it simply picks up the messages that you (or us - vstest) send via message logger. You have access to the logger it in Discovery, and via IFrameworkHandle in Execution.
