### ISSUE TITLE
Number of parameterized tests is incorrect.

### ISSUE THREAD

**Issue by Magadan84** [nunit/nunit3-vs-adapter#1054]
Hello there!

A small but unpleasant issue appears with the NUnit3VsTestAdapter.
In a case when there are a bunch of parameterized tests, a basic test with no parameters is listed in the playlist along with the rest ones. This issue breaks statistics by calculating and adding all 'empty' tests, which are extra, to the list of tests.

I have a parameterized test with TestCaseSource. TestCaseSource is provided by several static IEnumerable **yield** properties.
After building the solution, eventually, the test is shown with all expected test parameters in the test explorer, but, one more extra test is listed without parameters in the test explorer.
When I try to run that particular test something weird happens - some unexpected tests are started running randomly, and, what is more, tests from other test fixtures, but not even from this specific fixture or test.

`
public class FooTestData
{
    public static IEnumerable<TestCaseData> BarTypes_Tests
        {
            get
            {
                yield return new TestCaseData("some data1", "some data 2", true).SetArgDisplayNames("Test with data set 1");
                yield return new TestCaseData("some data3", "some data 4", false).SetArgDisplayNames("Test with data set 2");              
            }
        }
}`

`[Test, TestCaseSource(typeof(FooTestData), nameof(FooTestData.BarTypes_Tests))]
public void ThisIsReasonableTestName(string param1, string param2, bool param3)
{}`

How it looks in the Test Explorer:

- ThisIsReasonableTestName("Test with data set 1")
- ThisIsReasonableTestName("Test with data set 2")
- ThisIsReasonableTestName

The last test is redundant and should not be listed in test explorer, strictly speaking how it worked a few versions ago.

NUnit 3.13.3
NUnit3TestAdapter 4.3.1
MS VS Pro 2019 - 16.11.18
.Net Fr 4.8.04084
Target Framework .NET Core 3.1

**Comment by OsirisTerje** [comment]
Have you tried switching off the real time discovery feature ?
![image](https://user-images.githubusercontent.com/203432/218473495-a5aaf738-276c-4421-8803-288335328d2f.png)

**Comment by Magadan84** [comment]
> Have you tried switching off the real time discovery feature ? ![image](https://user-images.githubusercontent.com/203432/218473495-a5aaf738-276c-4421-8803-288335328d2f.png)

Thank you, Osiris for your comment!

I've tried to switch off this option and it helps! The 'redundant' tests are not shown in the test explorer anymore. 
However, the drawback of this approach is that tests are not shown at all after cleaning the project and it needs every time to switch on/off that option to see some tests or reload VS.
Anyway, it helps to circumvent the problem.

**Comment by OsirisTerje** [comment]
When you switch that option off, you need to run the discovery phase.  That is run when building the project, that should be enough to populate the tree.  You should not need to restart VS.   VS in earlier versions didn't have the real time discovery, so then test discovery was always after build. 

The real time discovery doesn't understand datadriven tests, so it will give you a strange-looking tree, and those other faults you experience.

**Comment by Magadan84** [comment]
> That is run when building the project, that should be enough to populate the tree.

It does not work that way for me. When I clean the solution and then build it again, the test explorer remains empty until I change the state of the test discovery option.

**UPD**
It works properly, it just takes a quite long time for my solution where 2K+ tests and most of them have parameters.
Thank you, and I'm closing the issue if it is not worth fixing it - it worked properly some time(or versions) ago.
