### ISSUE TITLE
NUnit failed to load dll

### ISSUE THREAD

**Issue by nmfernandes** [nunit/nunit3-vs-adapter#1057]
* NUnit 3.13.3
* NUnit3TestAdapter 4.3.1.0
* Visual Studio Professional 17.4.5
* TargetFramework .NET Framework 4.8

Since I updated Visual Studio to the version 17.4.0, I started having this error when I build my project:
NUnit Adapter 4.3.1.0: Test discovery starting
NUnit failed to load C:\myproject\Tests\MyTests\bin\Debug\MyTests.dll
NUnit Adapter 4.3.1.0: Test discovery complete
[Warning] No test is available in C:\myproject\Tests\MyTests\bin\Debug\MyTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

The processor architecture is set to x64:
![image](https://user-images.githubusercontent.com/8987944/220325307-762facda-1b74-40ec-b5f4-8631293bc181.png)
![image](https://user-images.githubusercontent.com/8987944/220325465-43548839-8e5c-4ad2-b6a5-1355a5157836.png)

I have changed the logging level to "Diagnostic", but even with that level, I cannot see exactly what's the issue.

**Comment by OsirisTerje** [comment]
I assume you mean NUnit 3.13.3.

Anyway, can you upload a small repro project for this?
Also, verify that it doesn't work when arch is et to Auto.

**Comment by nmfernandes** [comment]
> I assume you mean NUnit 3.13.3.
> 
> Anyway, can you upload a small repro project for this? Also, verify that it doesn't work when arch is set to Auto.

Yes, 3.13.3, sorry for the mistake. Edited.

**Comment by OsirisTerje** [comment]
@nmfernandes  Any chance of a repro?

**Comment by nmfernandes** [comment]
Hi @OsirisTerje, it happens that the error disappeared when I removed SpecFlow+ Runner from my project. The SpecFlow+ Runner is out of maintenance.
