### ISSUE TITLE
Abstract Fixture with Tests and Derived Fixture without Tests

### ISSUE THREAD

**Issue by Laser42** [nunit/nunit3-vs-adapter#1083]
Hello. I'm trying to create base abstract fixture.
The goal was to write an base abstract generics test fixture which incapsulates a set of obligatory test for all concrete BaseMgr Implementations. And child test fixture just supplies an object to tests as well as TestCases which hides TetsCases from Base test fixture.
So, BaseMgrTests is abstract class with TextFixture attr. It contains [Test] methods which consumes a Test Case Source.
The child class, MyConcreteMgrTests cointais a return of Mgr, and overrides (a little bit tricky) the Test Cases.
```
    [TestFixture]
    public abstract class BaseMgrTests<TMgr>
        where TMgr: BaseMgr
    {
        [SetUp]
        public void Setup()
        {
            Mgr = GetMgr();
            Assert.IsNotNull(Mgr);
        }

        protected TMgr Mgr { get; private set; }

        protected abstract TMgr GetMgr ();

        protected static IEnumerable<MgrTestCase> TestCases()
        {
            return null;
        }

        [Test]
        [TestCaseSource(nameof(TestCases))]
        public async Task RunAsync_Succeeds_IfInputIsValid(MgrTestCase testCase)
        {
            await Mgr.RunAsync(testCase.TestContext, CancellationToken.None);

            Assert.AreEqual(testCase.ExpectedContext.IsSuccess,
                testCase.TestContext.IsSuccess);
        }
    }

    [TestFixture]
    public sealed class MyConcreteMgrTests : BaseMgrTests<ConcreteMgr>
    {
        protected override ConcreteMgr GetMgr()
        {
            return new ConcreteMgr();
        }

        private static new IEnumerable<MgrTestCase> TestCases()
        {
            return new List<ChainTestCase<SampleChainContext>>(1)
            {
                new()
                {
                    TestContext = new ConcreteContext() { Foo = 1 },
                    ExpectedContext = new ConcreteContext
                    {
                        Foo = 2,
                        IsSuccess = true
                    }
                }
            };
        }
    }
```

This approach is working, but the double-click navigations to files from VS2022 Test Explorer doesn't work (as well a CodeLens doesn't show a test result in testing class) - that's because inherited test fixture class doesn't contain `[Test]` attr itself, because all of the tests are in base fixture only.

Is it the way of fixing this behavior, maybe with some NUnit attributes or by slightly changing the concept?

**Comment by Laser42** [comment]
@OsirisTerje Hello! Exactly, I have base tests in NuGet package (which is made to provide this universal set of tests to any app).

**Comment by OsirisTerje** [comment]
Can you please create a repro for this?
I tried your code example above as a repro, but it doesn't compile on its own.
