### ISSUE TITLE
Visual studio test explorer hierarchies

### ISSUE THREAD

**Issue by fkpama** [nunit/nunit3-vs-adapter#1087]
Support for visual studio [TestExplorer hierarchies](https://github.com/microsoft/vstest-docs/blob/main/RFCs/0033-Hierarchy-TestCase-Property.md).

While writing unit test I want to be able to specify the hierarchy in test explorer. With this commit the steps to do so would be the following.

1- Create a class inheriting from TestFixtureAttribute
2- Create the tests as usual
3- Set specific (optional) properties on the test that will be passed to MSTest TestCase (and then to TestExplorer window).

By doing so, the user should be able to override the default behavior of TestExplorer.

**Comment by OsirisTerje** [comment]
Your demo seems to just mimic the existing functionality.  I do get the possibilities here, but it would be good to see an example that is showing the possibilities better.
