### ISSUE TITLE
NUnit 2 tests are detected as errors

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#109]
When a project has both NUnit 2 and NUnit 3 tests, the adapter give an error message instead of a informational message.  
See #57 and https://github.com/nunit/nunit-vs-adapter/issues/84

**Comment by CharliePoole** [comment]
@OsirisTerje You added a commit to change the error message to a warning. Is there a reason you didn't close the issue?

**Comment by OsirisTerje** [comment]
No, closed now.
