### ISSUE TITLE
Doesn't split in ADO parallel agent tests

### ISSUE THREAD

**Issue by jimmycartrette** [nunit/nunit3-vs-adapter#1106]
nunit 3.12.0 (same issue with 3.13.3)
Issue occurs with nunit3testadapter 4.4.0 and 4.5.0, did not test other 4.* versions
Issue does not occur with nunit3testadapter 3.17.0

This is an ADO on-premise parallel test job with 4 agents. In "Visual Studio Test", the broken versions see this:

[RunStatistics]This execution slice with id '1231672', received '4242' testcases to execute out of which '4253' is discovered.
**************** Starting test execution *********************
Using new test platform for test execution
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper instance will be created
RunMessage : NUnit Adapter 4.4.0.0: Test execution started
RunMessage : Running all tests in C:\agent\_work\165\s\src\xxx\bin\Debug\xxx.dll
RunMessage :    NUnit3TestExecutor discovered **17339** of **17339** NUnit test cases using Current Discovery mode, Non-Explicit run

While the working versions see this:
[RunStatistics]This execution slice with id '1233766', received '4242' testcases to execute out of which '4253' is discovered.
**************** Starting test execution *********************
Using new test platform for test execution
Microsoft.TestPlatform.VsTestConsole.TranslationLayer.VsTestConsoleWrapper instance will be created
RunMessage : NUnit Adapter 3.17.0.0: Test execution started
RunMessage : Running selected tests in C:\agent\_work\84\s\src\xxx\bin\Debug\xxx.dll
RunMessage :    NUnit3TestExecutor discovered **4253** of **4253** NUnit test cases

Because the split does not occur, all jobs run in all agents instead of each agent running just its slice.
Test project targets net48

**Comment by OsirisTerje** [comment]
Sorry, but need a bit more context here.  What is ADO ?   How are the "splits" meant to work, that is how are the ADO (??) splitting the testcases?   
The adapter doesn't have any facilities for splitting tests, so something (ADO?) outside must do something here.
Also note that there are breaking changes between 3.X and 4.X adapters.  
The release notes describe the changes being done.

**Comment by jimmycartrette** [comment]
Apologies for not having more information than the below, I don't have the code, it is a hosted black box and I don't know the mechanism that isn't working, just the behavior. So I can't look at the nunit3adapter change logs and know what vstest is using in the background that might be breaking.
ADO is Azure Dev Ops, CI/CD pipelines used for testing code. We have a test that is supposed to be run in 4 agents, which will batch the total tests between each, so instead of one running 16k, each agent runs 4k of them in parallel.
See here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-vstest?view=azure-devops

Their documentation says this:

> Parallelism offered by test frameworks. All modern test frameworks such as MSTest v2, NUnit, xUnit, and others provide the ability to run tests in parallel. Typically, tests in an assembly are run in parallel. These test frameworks interface with the Visual Studio Test platform using a test adapter and the test framework, together with the corresponding adapter, and work within a test host process that the Visual Studio Test

And we see the batching not work correctly when only making the change from an nunit3adapter version 3 to version 4.4/4.5.

**Comment by OsirisTerje** [comment]
Thanks @jimmycartrette !   I was not aware that Azure DevOps had added this capability.  

What can cause this is the [AssemblySelectLimit](https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#assemblyselectlimit), which has a default of 2000.  If the incoming list of test cases are greater than this limit, it will change the filter to all.   That is because any number of tests higher than this in a test list will probably run slower just due to the parsing of that long list. Slicing is probably done that way (like Team City did, with not so good results).

So can you please try it again and set the limit to a very high number?
