### ISSUE TITLE
NUnit Adapter 3.0.8.0 fails to load tests from an assembly if the assembly contains a method with extern modifier

### ISSUE THREAD

**Issue by sirIrishman** [nunit/nunit3-vs-adapter#111]
The assembly with tests (.Net 4.5.2) references NUnit 3.0.1. A class with the extern method isn't a test fixture, but is placed in the same namespace as the single test fixture in the assembly, which uses this class for testing purposes.

After a solution rebuilding a **Test Explorer** window is empty and a **Output** window for the *Tests* output source contains the following lines:
```
------ Discover test started ------
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit failed to load C:\Users\SomeUser\Documents\Visual Studio 2015\Projects\MyProject.Tests\bin\Debug\MyProject.Tests.dll
NUnit Adapter 3.0.8.0 discovering test is finished
========== Discover test finished: 0 found (0:00:00,1130064) ==========
```
Extern method commenting fixes the issue.

*IDE: VS Community 2015 Version 14.0.24720.00 Update 1*

**Comment by CharliePoole** [comment]
Presumably, .NET is unable to locate the assembly containing the implementation of the extern method. Unless it's in a system assembly, you need to make it available. Where is it located WRT your test assembly at execution time?

**Comment by CharliePoole** [comment]
Also, note that an unmanaged assembly is **not** located using the Appbase and probing path as a managed assembly is. You may need to put it's location on your path.

**Comment by sirIrishman** [comment]
I'd been probing reflection API and had written a target class to test my ideas via NUnit. This class was filled with methods with different modifier combinations thus one of them had `extern` modifier without a `DllImport` attribute. As my code successfully compiled I supposed that everything is OK, but now after some researching, I've realized that the cause of the issue is my invalid code not the NUnit adapter. Sorry for bothering you. Have a nice day!

**Comment by rprouse** [comment]
@sirIrishman thanks for getting back to us with an update. Based on that, I am closing the issue.
