### ISSUE TITLE
Test adapter fails to load an assembly that references a class from NUnit.Framework but contains no tests

### ISSUE THREAD

**Issue by MSK61** [nunit/nunit3-vs-adapter#112]
I have a c# project that contains some testing services and utilities to be used by other testing projects. The project itself doesn't contain any tests but builds upon some classes from nUnit. When I build this project, it builds successfully but then I have this message in the Tests Output console in visual studio:
>NUnit failed to load \<my assembly path>

For a minimal example, consider a dll assembly that only has the following code

    namespace DllTestScan
    {
        class TestClass : NUnit.Framework.TestCaseData
        {
        }
    }
There's only a single reference to class from nUnit, which is in the inheritance from NUnit.Framework.TestCaseData(; using another class from nUnit would work too). Upon build, the aforementioned message appears in the Tests console.

If I comment the inheritance in the above code, I correctly get the expected message
>Assembly contains no NUnit 3.0 tests: \<my assembly path>

Some notes about my use case:
1. I'm using NUnit adapter 3.0.8.0.
2. The problem occurs with both VS2013 update 4 and VS2015.
3. The problem didn't exist with nUnit adapter 2.6.4(with both VS version).

I'm planning to look more closely into this problem. I yet don't know how to make visual studio works with an nUnit adapter built from development sources instead of one installed from a nuget package. Any hints on how to do that or generally where to look for the test discovery mechanism will be much appreciated.

**Comment by CharliePoole** [comment]
We have been treating this as an annoyance up to now. Do your actual tests load and run correctly?

**Comment by MSK61** [comment]
Yes tests from other assemblies are detected and run correctly. Moreover adding any tests to the offending assembly suppresses the message(and the tests are picked up successfully).
