### ISSUE TITLE
Unable to work with Test Driven tests after latest Visual Studio Preview.

### ISSUE THREAD

**Issue by alkampfergit** [nunit/nunit3-vs-adapter#1127]
Nunit: 3.13.3
Test Adapter: 4.5.0
Visual Studio: Version 17.8.0 Preview 2.0

When I use TestCase attribute, tests are executed, but all navigation is broken (double clicking on the test does not bring you to the test) and test output is completely blank.

This happened only after upgrading to 17.8 preview of Visual Studio, something in the test runner was probably changed.

Here is the situation:

![image](https://github.com/nunit/nunit3-vs-adapter/assets/358545/e6c187ed-8500-4539-8d42-a6d8110aa7d9)

**Comment by manfred-brands** [comment]
@OsirisTerje I can confirm this behavior, I tried upgrading `Microsoft.NET.Test.Sdk` to `17.8.0-preview-23424-02` but that didn't make a difference.

Non-parameterized tests work fine.

**Comment by nohwnd** [comment]
running in commandline looks up just 3 tests for me, but latest VS (for me that is internal preview) shows 6 tests.

So this is really a Test Explorer fault most likely. 

@drognanar please have a look on this.

**Comment by alkampfergit** [comment]
Yes, I'm pretty sure that TEst Explorer broke something. The problem is that when such problem happens, usually the test adapter should be updated (unless they really broke the inner working of the test runner)

**Comment by OsirisTerje** [comment]
I have added a repro here:  https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1127 , and can confirm the same.

**Comment by OsirisTerje** [comment]
From the repro:  Running in cmd line (dotnet test) shows all tests, and also stack traces for the 4 failing ones
![image](https://github.com/nunit/nunit3-vs-adapter/assets/203432/58258114-ac0c-4442-a690-f36335e08877)

**Comment by OsirisTerje** [comment]
@nohwnd @drognanar 
I just added XUnit tests to the repro sln, and XUnit works as it should,   So it seems that they have changed something to match whatever change has happened to the test explorer/testhost.  Or, that NUnit sends information slightly different from what you **now** expect.  

![image](https://github.com/nunit/nunit3-vs-adapter/assets/203432/f4bfe952-4293-45d6-a129-dacddcc88c83)

**Comment by alkampfergit** [comment]
Yes I can confirm that if you use TestCase or you use TestFixture attribute with parameter will trigger the problem.

**Comment by OsirisTerje** [comment]
Tried this now the released version, and it seems to work now.
Can you confirm @alkampfergit ?

**Comment by alkampfergit** [comment]
Confirm, everything is working now (it worked on latest preview also)

Thanks to everyone

Il mer 15 nov 2023, 21:59 Terje Sandstrom ***@***.***> ha
scritto:
