### ISSUE TITLE
Installation throwing an error 

### ISSUE THREAD

**Issue by gopich512** [nunit/nunit3-vs-adapter#114]
i tried to install NUnitforVSTS.Installer  file it throwing errors i tried all posibilities

please tell me how can i install it
my error screen shot follows

![error for selenium](https://cloud.githubusercontent.com/assets/16700643/12443256/b77cc9e8-bf7c-11e5-9122-40db9e11c74b.PNG)

**Comment by CharliePoole** [comment]
In spite of it's unfortunate choice of name, this product is not NUnit. Please contact the folks who wrote it and from whom you presumably got it.
