### ISSUE TITLE
Test discovery NUnit4 fails with framework net7.0-windows

### ISSUE THREAD

**Issue by rgroenewoudt** [nunit/nunit3-vs-adapter#1141]
There are no tests found if the targetframework is `net7.0-windows`. However, it works fine without the platform suffix: `net7.0`.

This is a problem as my other projects target windows and thus the unit test project also needs to use it.

This only happens with the new NUnit 4. In the previous 3.14 version it isn't a problem.

Same issue with net8.0-windows. Result is the same in Visual Studio and `dotnet test -t`.

Latest versions of everything:
- VS2022 17.8.2
- .NET SDK 8.0.0
- NUnit 4.0.0
- NUnit3TestAdapter 4.5.0
- Microsoft.NET.Test.Sdk 17.8.0

Example project: [TestProject3.zip](https://github.com/nunit/nunit3-vs-adapter/files/13499696/TestProject3.zip)

**Comment by OsirisTerje** [comment]
> Same issue with net8.0. Result is the same in Visual Studio and dotnet test -t.

Sorry, didn't see this.  Can you explain what you mean?  Using net 8 works fine here.

**Comment by rgroenewoudt** [comment]
@OsirisTerje I meant using `net8.0-windows`. But I can confirm the workaround works :). 

Perhaps keep the issue open until the next NUnit version is released officially, in order to prevent duplicate issues.

**Comment by rgroenewoudt** [comment]
I can confirm the latest 4.0.1 works :)
