### ISSUE TITLE
System.ArgumentException: Unknown framework version 8.0 

### ISSUE THREAD

**Issue by akolhe7** [nunit/nunit3-vs-adapter#1142]
When reporting a bug, please provide the following information to speed up triage:

NUnit3.TestAdapter : 4.3.1.0
NUnit Adapter 4.3.1.0:  
Visual studio version - Version 17.8.2 
.net 8.0

Looking fro a workaround or solution. 

Stacktrace: 

```
  The type initializer for 'NUnit.Engine.Services.RuntimeFrameworkService' threw an exception., reason: System.TypeInitializationException: The type initializer for 'NUnit.Engine.Services.RuntimeFrameworkService' threw an exception. ---> System.ArgumentException: Unknown framework version 8.0
  Parameter name: version
     at NUnit.Engine.RuntimeFramework.GetClrVersionForFramework(Version frameworkVersion)
     at NUnit.Engine.RuntimeFramework..ctor(RuntimeType runtime, Version version, String profile)
     at NUnit.Engine.RuntimeFramework.GetNetCoreRuntimesFromDirectoryNames(IEnumerable`1 dirNames)
     at NUnit.Engine.RuntimeFramework.FindDotNetCoreFrameworks()
     at NUnit.Engine.RuntimeFramework.get_AvailableFrameworks()
     at NUnit.Engine.Services.RuntimeFrameworkService..cctor()
     --- End of inner exception stack trace ---
```

`
ERROR The type initializer for 'NUnit.Engine.Services.RuntimeFrameworkService' threw an exception., reason: System.TypeInitializationException: The type initializer for 'NUnit.Engine.Services.RuntimeFrameworkService' threw an exception. ---> System.ArgumentException: Unknown framework version 8.0 Parameter name: version at NUnit.Engine.RuntimeFramework.GetClrVersionForFramework(Version frameworkVersion) at NUnit.Engine.RuntimeFramework..ctor(RuntimeType runtime, Version version, String profile) at NUnit.Engine.RuntimeFramework.GetNetCoreRuntimesFromDirectoryNames(IEnumerable`1 dirNames) at NUnit.Engine.RuntimeFramework.FindDotNetCoreFrameworks() at NUnit.Engine.RuntimeFramework.get_AvailableFrameworks() at NUnit.Engine.Services.RuntimeFrameworkService..cctor() --- End of inner exception stack trace --- Server stack trace: at NUnit.Engine.Services.RuntimeFrameworkService.ApplyImageData(TestPackage package) at NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework(TestPackage package) at NUnit.Engine.Runners.MasterTestRunner.GetEngineRunner() at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter) at JetBrains.ReSharper.TestRunner.Adapters.NUnit3.NUnitRunner.DiscoverTestsFrom(ITestRunner runner, TestPackage package, RemoteTaskDepot depot) in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.NUnit3\NUnitRunner.cs:line 170 at JetBrains.ReSharper.TestRunner.Adapters.NUnit3.NUnitRunner.<>c__DisplayClass5_0.<RunTests>b__0(NUnitTestAssemblyTask assemblyTask) in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.NUnit3\NUnitRunner.cs:line 67 at JetBrains.ReSharper.TestRunner.Adapters.NUnit3.NUnitRunner.RunTests(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink) in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.NUnit3\NUnitRunner.cs:line 85 at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs) at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg) Exception rethrown at [0]: at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg) at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type) at JetBrains.ReSharper.TestRunner.Abstractions.ITestExecutor.RunTests(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink) at JetBrains.ReSharper.TestRunner.Implementation.UnitTestRemoteAgent.Execute(TestRunRequest request) in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Merged\Implementation\UnitTestRemoteAgent.cs:line 96 at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<>c__DisplayClass4_1.<TryRegisterHandler>b__1() in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 56 at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<RunAndLog>d__10.MoveNext() in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 140``

**Comment by stevenaw** [comment]
Thanks @akolhe7 

I noticed you're using an older version of the adapter. Can you try updating to v4.5.0 of the adapter, `NUnit3TestAdapter`, to see if the issues persist?

**Comment by akolhe7** [comment]
That worked. Thank you. We can close this issue
