### ISSUE TITLE
Microsoft Testing Platform for NUnit

### ISSUE THREAD

**Issue by Evangelink** [nunit/nunit3-vs-adapter#1152]
Dear NUnit team,

As per our previous discussions, we would like to help you onboard NUnit to the new self-contained testing platform that powers MSTest Runner.

We are currently working on the technical documentation for framework authors and extensions authors so sadly for now there isn't much available for you to browse.

The new platform is already OSS and available inside of MSTest repository (at the moment).

Related issue about support NUnit on MSTest repo: https://github.com/microsoft/testfx/issues/2164

MSTest runner blogpost announcement: https://devblogs.microsoft.com/dotnet/introducing-ms-test-runner/
MSTest runner doc: https://learn.microsoft.com/dotnet/core/testing/unit-testing-mstest-runner-intro?tabs=dotnetcli
Platform code: https://github.com/microsoft/testfx/tree/main/src/Platform/Microsoft.Testing.Platform
Sample code: https://github.com/microsoft/testfx/tree/main/samples/mstest-runner

**Comment by OsirisTerje** [comment]
From @Evangelink 

> @OsirisTerje @SeanKilleen How do you guys want me to move on this PR? Not sure if you prefer to discuss on the PR or ticket.

- Ticket, that is here on this issue :-) 

> Are you happy with having the new platform has optional disabled by default on the same nuget package or would you like to have a different package with maybe the runner enabled by default?

- It should be on the same package, we already have enough packages and having it in the same adapter package makes it easier. And it will probably be easier to try it and switch back and forth at least now in the beginning.

> If we move on with a flag to enable, how do you want to name it (current draft uses EnableNUnitRunner)?

- I'm fine with that name

> Not for now but for some future, I'd be happy to start seeing the "VS" part going away (maybe if/when we are able to drop support from VSTest and focus only on the new platform). We are really trying to have the new platform felt more as a dotnet tooling/sdk concept rather than a VS centric feature.

The adapter could stay as it is.  A possible way for a proper (non-bridge) platform runner could be to use the NUnitLite runner and adapt that to return the new protocol. 

> BTW if that's any easier, I'd be happy to setup some call with you (hopefully we have some common timezone time :)) so we can discuss how we can help you.

A call could be nice.  @mikkelbu  and I are CET, @sean is in EST. @stevenaw is also same but @manfred-brands is AWST.  There is only two non-night time hour in common, CET 12-14 = EST 7-9 AM = AWST 20-22.
