### ISSUE TITLE
Version 5-beta crashes with nullref exception

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#1170]
* NUnit 4.1.0 and NUnit3TestAdapter 5.0.0-beta.1
* Repro:  https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1152/1-nunit-runner

Trying to run the dll directly:
![image](https://github.com/nunit/nunit3-vs-adapter/assets/203432/ec4e2881-a174-48bc-83f5-f8525627be62)

using `dotnet run`
![image](https://github.com/nunit/nunit3-vs-adapter/assets/203432/45889a2e-d82d-482f-aede-1ef069f6a75b)

I believe these two have the same root cause, but the message from the latter may be misleading.

**Comment by Evangelink** [comment]
@OsirisTerje As discussed offline, I'll take this one!

**Comment by Evangelink** [comment]
Fixed by #1171

**Comment by Evangelink** [comment]
`dotnet run` issue is still present but doing `dotnet run --project` solves the issue. I have reached out to some people to understand why the "default" gesture isn't working.

**Comment by Evangelink** [comment]
I have talked with the team and checked the docs https://learn.microsoft.com/dotnet/core/tools/dotnet-run and this syntax isn't valid. We should either run `dotnet run` from a folder, and it would execute only if a single project is found (see https://github.com/dotnet/sdk/blob/171723b0d76e60d147d259140adbfd078aa252a1/src/Cli/dotnet/commands/dotnet-run/RunCommand.cs#L294-L305) or `dotnet run --project <path-to-project>`.

**Comment by OsirisTerje** [comment]
Ok, it finds both the sln and the csproj.  Normally they are never in the same folder, so this makes sense. I tested by removing the sln file, and then it works.
