### ISSUE TITLE
dotnet test -- NUnit.Where works but dotnet test --list-tests -- NUnit.Where does not

### ISSUE THREAD

**Issue by pluma9** [nunit/nunit3-vs-adapter#1183]
* Description
In the example below, `dotnet test -- NUnit.Where="name=~Foo"` outputs 2 tests:
```
Passed!  - Failed:     0, Passed:     2, Skipped:     0, Total:     2, Duration: 11 ms - baonyhxtnvx.dll (net8.0)
```

But `dotnet test --list-tests -- NUnit.Where="name=~Foo"` outputs 3 tests:
```
The following Tests are available:
    Bar
    Foo
    FooBar
```

Expectation: `--list-tests` should output only 2 tests.

* NUnit and NUnit3TestAdapter versions
NUnit 4.1.0
NUnit3TestAdapter 4.5.0

* Visual Studio edition and full version number (see Help About)
No Visual Studio

* A short repro, preferably attached or pointing to a git repo or gist

The Tests class:
```
public class Tests
{
    [Test] public void Foo() { Assert.Pass(); }
    [Test] public void Bar() { Assert.Pass(); }
    [Test] public void FooBar() { Assert.Pass(); }
}
```

csproj:
```

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="NUnit" Version="4.1.0" />
    <PackageReference Include="NUnit.Analyzers" Version="3.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
```

* What .net platform and version is being targeted
.NET sdk: 8.0.300-preview.24203.14
Target: net8.0

* If TFS/VSTS issue, what version, hosted or on-premises, and what build task you see this in
N/A

**Comment by OsirisTerje** [comment]
The --list-tests command is only using the Discovery section for tests.  No filters work with that command , not the where command, and not the dotnet `--filter <selection statement>`.  

For normal execution, using the Execution section , which applies the filters.

I don't think we will change this behavior.
