### ISSUE TITLE
Running particular test folders causing other test folders not selected to run.

### ISSUE THREAD

**Issue by nsangeetha-bright** [nunit/nunit3-vs-adapter#1187]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions - **4.0.1 and 4.5.0**
* Visual Studio edition and full version number (see Help About) - **MS Visual Studio Professional 2022 and 17.10.1**
* A short repro, preferably attached or pointing to a git repo or gist  - **If you select and run particular folder such as Integration tests folder but it run multiple other folders (Validation and/or Unit and/or SQLIntegration) at the same time.**  Attached image for reference

![image](https://github.com/nunit/nunit3-vs-adapter/assets/133859672/9ecd24b6-5be6-43d3-b9a4-0a529f85b336)

* What .net platform and version is being targeted **- .Net 6.0**
* If TFS/VSTS issue, what version, hosted or on-premises, and what build task you see this in

**Comment by OsirisTerje** [comment]
What are your folders in this case?  Projects?  
You can look at your grouping settings for the Test Explorer.   
![image](https://github.com/nunit/nunit3-vs-adapter/assets/203432/e6319eea-fccf-4d68-80e1-03031f72ab7d)
You find Grouping at (1),  ensure that in the dialog, the grouping is set as shown (2).

Note also that NUnit doesn't select what tests to run.  It accepts what comes from the test explorer. 
You can check that using a .runsettings file, and enable the Dumps there, see https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html  and https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#dumpxmltestdiscovery-and-dumpxmltestresults

**Comment by nsangeetha-bright** [comment]
This issue happened only when use Grouping as '**Traits**'  Attached image regarding what grouping have used for your reference 

![image](https://github.com/nunit/nunit3-vs-adapter/assets/133859672/11085371-23b3-4f2b-b216-b446797baa91)

**Comment by OsirisTerje** [comment]
If a test has two categories, in this case both Integration and Unit, it may look like this.

Check the filter being sent to the adapter, in the dump file.
Then look at some of the tests that have run and check what their categories are. 

If it still looks wrong, then upload a small repro project.  But again, the adapter just runs what is being sent down to it from the Test Explorer.
