### ISSUE TITLE
Test Explorer Updating Testcase path Of non english character this cases test discovery and test run

### ISSUE THREAD

**Issue by AshuK2297** [nunit/nunit3-vs-adapter#1189]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions **3.13.3 and 4.4.2**
* Visual Studio edition and full version number (see Help About): **MS Visual Studio Professional 2022 and 17.5.3**
* A short repro, preferably attached or pointing to a Git repo or gist: **Not having a Git repo** 
* What .net platform and version is being targeted: **4.8.04**
* If TFS/VSTS issue, what version, hosted or on-premises, and what build task you see this in: **None**
* Description Of Issue :
![IssueScreenShot](https://github.com/nunit/nunit3-vs-adapter/assets/175191920/418be140-4406-4df9-afa5-339013f3e21f)

If We Can See File Path Provided is given below
[TestCase(@"2013\Files\mÃ´ hÃ¬nh hoÃ n thÃ nh\Ä‘Æ°á»ng á»‘ng dáº«n bi 1.SLDPRT")]

And Test Explorer  after reading that adding **\u009dng** in It That Why test is not able to run from Visual Studio

Sw3dSketch("2013\\Files\\mÃ´ hÃ¬nh hoÃ n thÃ nh\\Ä‘Æ°á»**\u009dng** á»‘ng dáº«n bi 1.SLDPRT")

For further investigation, I have checked the file Unicode also but it is By Default **UTF-8**.

Not able to remove that **\u009dng**.

**Comment by OsirisTerje** [comment]
The u009 is a Horisontal tab character.  The folder is readable, but the filename seems weird to me.  If the file name is correct, then  it anyway confuses the FQN requirements of the Test Explorer.  It may be some escaping routine somewhere in the chain that doesn't understand that filename.  
Suggest you use the TestName property on the TestCase to set a better name for it, and then see if it works.

**Comment by OsirisTerje** [comment]
You can write out the path if you like using something like `TestContext.Writeline(filepath);`   That way you can see it in the output.
