### ISSUE TITLE
Run tests in current context runs all tests in fixture instead of running only the test where cursor is

### ISSUE THREAD

**Issue by veeroo** [nunit/nunit3-vs-adapter#119]
It seems there is a bug with some hotkeys. I.e. Ctrl-R + T should run test case in current context only, so for example when cursor is inside of test method, only this test should run. Instead, it runs all tests in test fixture. The same with Ctrl-R + Ctrl+T: it runs debug on all tests in test fixture instead of only the test when mouse cursor is. Sometimes reinstalling NUnit3 Test Adapter solves this problem for a while, sometimes only downgrading to NUnit Test Adapter (2.0) can help

**Comment by veeroo** [comment]
Ok I just figured it out, the problem occurs when Test has [ValueSource] attributes. Problem exists in both NUnit Test Adapter 2 and 3

**Comment by CharliePoole** [comment]
So, with the ValueSourceAttributes, is it running all the tests in the fixture, or only those test cases for the particular method?

**Comment by veeroo** [comment]
Yes, it runs all tests in the fixture, no matter if cursur is inside a test or not which is not expected

**Comment by CharliePoole** [comment]
So, NUnit gives VS the needed info to translate a test method to a test. With a parameterized test, that translation is one to many rather than one to one. My guess, based on other past problems, is that VS is unhappy with that result and is falling back to the fixture.

One final thing to check: If you highlight one of the tests for this method (there should be one for each ValueSource value) does VS indicate the file and line number of the method or does it say "Source not available?"

**Comment by veeroo** [comment]
No it's not, is shows source link properly, and link navigates to proper test. But I have just noticed, that code lens doesn't work for tests with ValueSourceAttribute. No test runs info is displayed like here:
![c2](https://cloud.githubusercontent.com/assets/4293101/12976416/2af20afc-d0c4-11e5-8cd9-2521bfba55fd.PNG)
For other tests, without ValueSourceAttribute, code lens work fine:
![c1](https://cloud.githubusercontent.com/assets/4293101/12976417/2e017ba6-d0c4-11e5-8e4f-6a525cc1e83e.PNG)

**Comment by CharliePoole** [comment]
I'm closing this as not (our) bug. AFAICS VS has all the info it needs to do the right thing here- it just isn't doing it.

**Comment by vamshik85** [comment]
Hi I need some help with frame work, here is my requirement
I have test cases and data in my excel, i want to run only the test cases that are marked "Yes" under Execute column in excel. The ones which are not equal to Yes should not be triggered. can some one please share sample code to achive this
