### ISSUE TITLE
[Enhancement]: The ability to set the LevelOfParallelism attribute through the VS adapter

### ISSUE THREAD

**Issue by ChipV223** [nunit/nunit3-vs-adapter#120]
This related to the following NUnit3 Issue ticket I opened: https://github.com/nunit/nunit/issues/1257

Currently when I run tests through Sauce Labs, I've noticed that when run in parallel, the test launches in groups of 4 even when more than 4 TestFixtures are used in the test. 

I know you can change this by either set it with an assembly level attribute(https://github.com/nunit/docs/wiki/LevelOfParallelism-Attribute) or setting it through the command line with the --workers flag(https://github.com/nunit/docs/wiki/Console-Command-Line), but currently there's no way to change this from the VS adapter.

**Comment by ChipV223** [comment]
Paging @CharliePoole as this has not been given a label yet and assisted me in NUnit3 ticket #1257

**Comment by CharliePoole** [comment]
Well, since you paged me... :-)

Generally issues sit till somebody grabs them. Possibly me, possibly somebody else.

I imagine this one is sitting without motion because nobody here knows what Sauce Labs is - at least that's why I haven't done anything. A quick google indicates it's a third party test framework of some kind. Could you explain how this relates to the NUnit3 VS Adapter?

**Comment by rprouse** [comment]
@CharliePoole, refresh my memory, am I correct in recalling that we run tests in parallel in the adapter if you are running, but with one worker if you are debugging?

Once we support settings, should this be a setting?

**Comment by CharliePoole** [comment]
@rprouse Yes, that's correct - but only if the user has enabled it in the test assembly, of course.

Yes, I think that should eventually be a setting.

That said, I'm still not sure if this request really belongs to us. Waiting for @ChipV223 to reply.

**Comment by CharliePoole** [comment]
The fix to #49 Provided a fix to this. The NumberOfTestWorkers element in the .runsettings file accomplishes what is requested here.

**Comment by ChipV223** [comment]
Hi @CharliePoole, for some reason GitHub never notified me about an update which is a different issue for another day. 

I will definitely try out the NumberOfTestWorkers element to see if that works and will let you know
