### ISSUE TITLE
Counter don't regard test with [TestCase] attribute

### ISSUE THREAD

**Issue by HelpfulWhite** [nunit/nunit3-vs-adapter#121]
I created 3 tests: 2 with [Test] attribute and 1 with 6 [TestCase] attributes.
In Test Explorer I can see all 8 tests but above my function I can see counter with only two of them:
![a](https://cloud.githubusercontent.com/assets/17233063/13033594/e682deae-d31c-11e5-96f8-52be99b938ec.png)

**Comment by CharliePoole** [comment]
This is unfortunately completely out of our control. Test Explorer has the information about all eight tests, as is shown by the display in the left pane. Why VS doesn't show the correct number here is a bit of a mystery. I'm marking it "notabug" because it's not our bug.
