### ISSUE TITLE
No 64-bit libraries support

### ISSUE THREAD

**Issue by LordJZ** [nunit/nunit3-vs-adapter#122]
I'd like to run tests in 64-bit mode only (32-bit is not supported by my application), but when I tried running NUnit adapter from Visual Studio 2015 I got this:

> Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run:
> [list of 64-bit assemblies]

I tried setting library build platform to Any CPU but the test adapter ran tests in 32-bit mode: `Assert.IsTrue(Environment.Is64BitProcess); // failed`

**Comment by OsirisTerje** [comment]
Have you tried to run the test runner in x64?  Goto Visual Studio main menu, Test/Test Settings/DefaultArchitecture/x64

**Comment by LordJZ** [comment]
Ooh silly me. Yes it works. Sorry.

**Comment by dzmitry-lahoda** [comment]
Error message could be as follow
```
Try to change Testing Default Processor Architecture setting to X64.
```
or like.
