### ISSUE TITLE
Explicit test is running, but it shouldn't

### ISSUE THREAD

**Issue by ossysek** [nunit/nunit3-vs-adapter#1223]
Hello,

I wrote one simple test and it should not be run, but it started:

![image](https://github.com/user-attachments/assets/995570e9-df16-423a-94c5-4822f35d9aba)

My code:

```
using NUnit.Framework;

namespace NunitExplicit.Test
{
    [TestFixture]
    public class UnitTest1
    {
        [Test]
        [Explicit]
        public void TestMethod1()
        {
            Assert.True(true);
        }
    }
}
```

My dependencies:
![image](https://github.com/user-attachments/assets/fce20a74-8f7e-4f13-9f64-8d1165fa5580)

It seems, there is a bug, because when I add second test without explicit, everything start to work correctly:
![image](https://github.com/user-attachments/assets/20de0170-fb69-4573-904b-d42de3b52dec)

```
using NUnit.Framework;

namespace NunitExplicit.Test
{
    [TestFixture]
    public class UnitTest1
    {
        [Test]
        [Explicit]
        public void TestMethod1()
        {
            Assert.True(true);
        }

        [Test]
        public void TestMethod2()
        {
            Assert.True(true);
        }
    }
}
```

Next test:
![image](https://github.com/user-attachments/assets/b0761713-c797-4a8c-843d-1971e99ac988)

```
using NUnit.Framework;

namespace NunitExplicit.Test
{
    [TestFixture]
    [Explicit]
    public class UnitTest1
    {
        [Test]
        [Explicit]
        public void TestMethod1()
        {
            Assert.True(true);
        }

        [Test]
        public void TestMethod2()
        {
            Assert.True(true);
        }
    }
}
```

According to the dokumentation, it shouldn't work like that.

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current - Version 17.10.4
Target freamwork: .NET 8.0

**Comment by manfred-brands** [comment]
@ossysek, how are you running your tests?

If I run `dotnet test` from the command line, I get:
```
$ dotnet test --no-build
NUnit Adapter 4.5.0.0: Test execution started
Running all tests in D:\Development\Playground\Explicit\bin\Debug\net9.0\Explicit.dll
   NUnit3TestExecutor discovered 1 of 1 NUnit test cases using Current Discovery mode, Explicit run
NUnit Adapter 4.5.0.0: Test execution complete
  Explicit test succeeded (0.7s)

Test summary: total: 1, failed: 0, succeeded: 0, skipped: 0, duration: 0.7s
```

When I remove the `[Explicit]`, the result shows:
```
Test summary: total: 1, failed: 0, succeeded: 1, skipped: 0, duration: 0.7s
```

However, If I run the tests in Visual Studio by right click on project and selecting 'Run tests', it runs regardless of attribute.
Maybe it is a _feature_ that if there is only one test and you select 'Run tests' that it runs that test.
But it seems to be _one test in a fixture_ as even when I have 3 classes, each with 1 Explicit test they run.

@OsirisTerje Not sure if this is a feature of VS or the adapter.

**Comment by ossysek** [comment]
@manfred-brands thank you for your reply.

I run the tests in two ways:
1. Right mouse click in Test Explorer and "Run"
2. Run whole project in Azure Pipeline

In Pipeline the test are run as well.

**Comment by OsirisTerje** [comment]
When the adapter is called from the testhost, it receives a list of tests to run.   It doesn't know HOW the Test Explorer is being used. And thus it has no knowledge if there are other tests present that are not selected, OR if the tests it receives are all the tests in the solution.   

If **all** the tests are Explicit it will assume that this is an explicit testrun.  When you only have one test, and that test is explicit, it will be an explicit test run.  

When you add the second test, which is not explicit, it will see both tests, and since there is a non-explicit test included, the test is a non-explicit testrun, and all explicit tests will be ignored.

I agree we could improve the documentation though.
