### ISSUE TITLE
TestCaseSource generates incorrect tests when used with tuples within tuples in Visual Studio Test Explorer

### ISSUE THREAD

**Issue by HelenaUdd** [nunit/nunit3-vs-adapter#1224]
When I generate test cases using the `TestCaseSource` attribute with an enumerator that returns value tuples within another tuple, the test cases are not generated correctly in Visual Studio Test Explorer.

NUnit 4.2.2, NUnit3TestAdapter 4.6.0, Visual Studio Professional 17.12.2, .NET 8.

Reproducer:

```C#
namespace NUnitBugRepro
{
    public class Tests
    {
        [TestCaseSource(nameof(MinMaxValuesWithTuples))]
        public void MinMaxValueTestWithTuples((int Value, (int x, int y) MinValue, (int x, int y) MaxValue) _)
        {
            Assert.Pass();
        }

        private static IEnumerable<(int Value, (int x, int y) MinValue, (int x, int y) MaxValue)> MinMaxValuesWithTuples()
        {
            yield return (1, (-9, -9), (9, 9));
            yield return (2, (-99, -99), (99, 99));
        }

        [TestCaseSource(nameof(MinMaxValuesWithoutTuples))]
        public void MinMaxValueTestWithoutTuple((int Value, int MinValue, int MaxValue) _)
        {
            Assert.Pass();
        }

        private static IEnumerable<(int Value, int MinValue, int MaxValue)> MinMaxValuesWithoutTuples()
        {
            yield return (1, -9, 9);
            yield return (2, -99, 99);
        }
    }
}
```
The expectation is 4 generated tests, 2 under `MinMaxValueTestWithTuples` and 2 under `MinMaxValueTestWithoutTuple`.

The Visual Studio Test Explorer generates 5 tests. 2 under `MinMaxValueTestWithoutTuple`, 2 under `MinMaxValueTestWithTuples,` (with an ending comma), and an empty `MinMaxValueTestWithTuples`. I extracted all the tests generated to a playlist file, which looks like this:
```XML
                    <Rule Match="All">
                      <Property Name="TestWithNormalizedFullyQualifiedName" Value="NUnitBugRepro.Tests.MinMaxValueTestWithTuples" />
                      <Rule Match="Any">
                        <Property Name="DisplayName" Value="MinMaxValueTestWithTuples" />
                      </Rule>
                    </Rule>
                    <Rule Match="All">
                      <Property Name="TestWithNormalizedFullyQualifiedName" Value="NUnitBugRepro.Tests.MinMaxValueTestWithoutTuple" />
                      <Rule Match="Any">
                        <Property Name="DisplayName" Value="MinMaxValueTestWithoutTuple((1, -9, 9))" />
                        <Property Name="DisplayName" Value="MinMaxValueTestWithoutTuple((2, -99, 99))" />
                      </Rule>
                    </Rule>
                    <Rule Match="All">
                      <Property Name="TestWithNormalizedFullyQualifiedName" Value="NUnitBugRepro.Tests.MinMaxValueTestWithTuples," />
                      <Rule Match="Any">
                        <Property Name="DisplayName" Value="MinMaxValueTestWithTuples((1, (-9, -9), (9, 9)))" />
                        <Property Name="DisplayName" Value="MinMaxValueTestWithTuples((2, (-99, -99), (99, 99)))" />
                      </Rule>
```

When executed from the Visual Studio Test Explorer, the `MinMaxValueTestWithoutTuple` and `MinMaxValueTestWithTuples,` are run, but the `MinMaxValueTestWithTuples` (which is empty) is not run, as can be seen here.
![vstest](https://github.com/user-attachments/assets/740f0155-e613-40d1-afcf-abe6b5617b28)

When discovering these tests with `dotnet test -t`, I get the expected 4 tests, but not their containing test method, showing no indication if this is a problem or not outside of Visual Studio.
```cmd
C:\source\repos\NUnitBugRepro\NUnitBugRepro>dotnet test -t
Restore complete (0,4s)
  NUnitBugRepro succeeded (0,3s) → bin\x64\Debug\net8.0\NUnitBugRepro.dll
The following Tests are available:
    MinMaxValueTestWithoutTuple((1, -9, 9))
    MinMaxValueTestWithoutTuple((2, -99, 99))
    MinMaxValueTestWithTuples((1, (-9, -9), (9, 9)))
    MinMaxValueTestWithTuples((2, (-99, -99), (99, 99)))
  NUnitBugRepro test succeeded (1,0s)
```

**Comment by OsirisTerje** [comment]
The extra node you see is a ghost node from the Real Time Discovery in VS.  
Th RTD "results" (only discovers tests) may or may not fit with what NUnit delivers back. So in this case the RTD does not **see** things the same way as NUnit.  The RTD just does a rudimentary check and they haven't got the TestCaseSource correct.

You can turn this off in Test/Options. 
![image](https://github.com/user-attachments/assets/f49145fd-e929-4e63-89c7-adb61e2c557e)

Turning that off, you get the result as:

![image](https://github.com/user-attachments/assets/04569fac-8997-4924-b7e7-e37f217cb809)

If you want to see what NUnit is delivering back, you can turn on the Dump feature in a runsettings file.

I have uploaded you repro here, incl a runsettings file: https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1224

In the runsettings file you can also change the DisplayName, default is just test Name, but you can set it to Fullname:
![image](https://github.com/user-attachments/assets/ec1b135d-a4ec-4529-93f8-b6ea7ae94b16)

**Comment by HelenaUdd** [comment]
All right, thank you!
