### ISSUE TITLE
Wish: Ability to get the test cases selected for execution

### ISSUE THREAD

**Issue by HelenaUdd** [nunit/nunit3-vs-adapter#1225]
I am writing an NUnit unit test wrapper around an existing test framework that is cmd based. The existing test framework can take commands such as

    runtest=mytest

which runs the test setup, all the test cases, then the test teardown.

    runtest=mytest tc=tc1

which runs the test setup, test case 1, then the test teardown. 

    runtest=mytest tc=tc1+tc2

which runs the test setup, test cases 1 and 2 (in that order), then the test teardown.

    runtest=mytest tc=tc2+tc4+tc1

which runs the test setup, test cases 2, 4 and 1 (in that order), then the test teardown.

All of these commands create a .com file with commands to execute, based on what test cases were selected, and then executes said com file.

Now, when I want to wrap this in NUnit, I want to be able to, from Visual Studio Test Explorer, select e.g. tc4, tc2 and tc1, and execute them. The same process needs to be done here, I need to know that it's tc4+tc2+tc1 in order to create the right .com file before anything can be executed.

The design of NUnit is that tc4 finishes before tc2 starts. Is there any way, in SetUp or OneTimeSetUp, for the first executing test case in NUnit to find out which test cases that were selected for execution?

**Comment by OsirisTerje** [comment]
NUnit is not designed to execute in any specific order, it is indeterminate.  
In most simple cases you may see it executes in the order that it is written in the source code.
Also be aware that what you see in TestExplorer is normally having the tests alphabetically sorted.
If you want, you can specify the order within a testfixture using the Order attribute, see https://docs.nunit.org/articles/nunit/writing-tests/attributes/order.html

I've uploaded an example of that here:  
https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1225

It then looks like:

![image](https://github.com/user-attachments/assets/ef7db323-d939-4670-aca2-e34e67c1a404)

**Comment by HelenaUdd** [comment]
The most important feature I needed in order to make this work is the
ability to find out what test cases are to be executed, not controlling
their order.

Med vänliga hälsningar / Best regards
--------------------------------------
Helena Staberg Udd, Developer
***@***.*** ***@***.***>


Mimer Information Technology AB
Väderkvarnsgatan 17A
SE-753 29 Uppsala, SWEDEN
www.mimer.com
