### ISSUE TITLE
async TestCaseSource not being ordered in vscode test explorer

### ISSUE THREAD

**Issue by Thaina** [nunit/nunit3-vs-adapter#1226]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions
```json
      "UnityNuGet.Tests/1.0.0": {
        "dependencies": {
          "Microsoft.NET.Test.Sdk": "17.12.0",
          "NUnit.Analyzers": "4.4.0",
          "NUnit3TestAdapter": "4.6.0",
          "UnityNuGet": "0.14.0",
          "NUnit": "4.2.2"
        },
        "runtime": {
          "UnityNuGet.Tests.dll": {}
        }
```

* Visual Studio edition and full version number (see Help About)
vscode 1.95.3

* A short repro, preferably attached or pointing to a git repo or gist
https://github.com/Thaina/UnityNuGet/tree/expand-with-testcasesource

* What .net platform and version is being targeted
```
.NET SDK:
 Version:           9.0.101
 Commit:            eedb237549
 Workload version:  9.0.100-manifests.4a280210
 MSBuild version:   17.12.12+1cce77968
```

The ordering seem random even though it run in alphabetical order, it then jump around

![image](https://github.com/user-attachments/assets/619ee7ca-9849-4b8c-adb1-8d6f9828a3a9)

**Comment by manfred-brands** [comment]
In Visual Studio 2022 17.12.3 the tests are ordered alphabetically:

![{FC320A10-101D-400D-B588-2D097303608E}](https://github.com/user-attachments/assets/f38e1f9c-09b0-4c8b-8686-6e4d0507b2f9)

The sorting is done by the TestExplorer, not by nunit.

Even though your `AllRegistries` method is async, it returns a complete array in one return value.
It is not an `IAsyncEnumerable`. But even then `NUnit` would iterate overall members to create the test cases.

Have you tried making it synchronous. You only have one `await` which you could replace with a `.Wait()`.

**Comment by Thaina** [comment]
I see, if common VS just ordered properly then it seem it should be vscode bug

Thank you very much
