### ISSUE TITLE
Test Adapter causes vstest.console.exe to fail if an assembly does not contain NUnit tests

### ISSUE THREAD

**Issue by qmfrederik** [nunit/nunit3-vs-adapter#124]
My build server hosts multiple projects, some of them running NUnit, others not.

Installing the NUnit test adapter causes all non-NUniit-based tests to fail because the NUnit test discover still runs, but complains it did not find any tests (it shouldn't -- the tests are written using a different framework):

```
Error: NUnit failed to load D:\Build\2\s\src\Quamotion.Test.Devices\bin\x86\Release\Quamotion.Test.Devices.dll
```

I'd argue that the NUnit test discover should not report an error if no tests are found - that can be a perfectly fine condition in a scenario where multiple test frameworks are installed on the build server.

**Comment by CharliePoole** [comment]
This actually duplicates #109 and 116, which are fixed in the current source.

**Comment by qmfrederik** [comment]
Cool, thx!

Any idea when we can expect a new release?

**Comment by CharliePoole** [comment]
I'd say by month end, contemporaneous with and using NUnit 3.2. Not sure if it will be CTP 9 or an actual production release.
