### ISSUE TITLE
Some tests disappear after build VS2015

### ISSUE THREAD

**Issue by replaysMike** [nunit/nunit3-vs-adapter#126]
I've been trying to debug an issue with the nUnit3 adapter but can't find the cause. When I do my first build all tests show up and run in my solution. However the second build half or more of the tests disappear from the Test Explorer (half of the projects, not half within a single project). A clean or restart VS2015 fixes it for one build. The only version referenced in the entire solution is nUnit3, and all of the project settings are identical - same .Net framework versions and build targets.

Is it expected that the tests should show up with only the test adapter nuget package installed? I can only get tests to show up if the extension is installed. (both are version 3)

**Comment by CharliePoole** [comment]
Either one should work. There are some reports of VS2015 showing tests twice if both are installed. What you are describing is something new, however.

Look in your Output window. There should be messages there from every installed adapter indicating the number of tests discovered by that adapter.

**Comment by replaysMike** [comment]
The Tests output indicates 124 tests found on first build, but doesn't indicated which projects they were found in. It seems to only output when a project does not contain tests.

The second build says 0 tests found. Perhaps this is a symbol caching side effect?

I couldn't find much what you were describing outside of the Tests output. The debug/build output only references the test adapter symbol loading, and the Tests output only indicates the total at the end.

With TestAdapter extension:
```
// truncated, more of the same
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering test is finished
========== Discover test finished: 124 found (0:00:04.4677669) ==========
```

With Nuget TestAdapter package:
```
------ Discover test started ------
Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
Optimizer.exe is built for Framework Framework45 and Platform X64.
 Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
NUnit Adapter 3.0.8.0 discovering tests is started
========== Discover test finished: 0 found (0:00:02.6767804) ==========
```

**Comment by replaysMike** [comment]
I'm going to guess that there may be a specific VS2015 setting that is causing this. To clarify I'm actually reporting two issues:

1. nUnit3TestAdapter nuget package doesn't find any tests on it's own (the extension does)
2. Tests disappearing - currently every second build - and only a clean or restart of VS2015 picks them back up again.

**Comment by CharliePoole** [comment]
Pretty strange output. Do the repeated "discovering tests" messages match the number of assemblies in your solution? I didn't think that message apeared more than once.

**Comment by replaysMike** [comment]
Indeed. There are 39 projects in the solution, and 39 lines appear in the Test output. Only 12 of those projects are test projects and contain the nUnit packages. I noticed that there are no "discovering test is finished" messages in the output when not using the extension.

Things I've tried without success:

1. Reset settings to factory default
2. Cleared out the nuget system cache and local solution cache
3. Verify all projects use the same nuget version (NUnit 3.0.1, NUnit3TestAdapter 3.0.8-ctp-8)
4. Check all project settings for architecture and .Net framework version (all 4.5.1, Any CPU)
5. Run in Admin elevated mode / unelevated

**Comment by replaysMike** [comment]
A little more information: the tests that "disappear" could be a VS ide issue. I noticed that when building the second time the Tests output window indicates there are no tests found, yet the ide still continues to show a portion of the tests. There doesn't seem to be any reason or pattern to indicate why some get left in the test explorer (and they run/test fine, through nUnit).

**Comment by RobertK66** [comment]
Your output under 'Nuget TestAdapter package'  looks exactly like I had it with the bug https://github.com/nunit/nunit3-vs-adapter/issues/118 (https://github.com/nunit/nunit3-vs-adapter/issues/117) in version 1.0.8.0.
Have you tried the workaround at end of https://github.com/nunit/nunit3-vs-adapter/issues/117#issuecomment-178612398 ?

**Comment by CharliePoole** [comment]
Taking into account the latest commits, I believe that the only remaining issue is with execution (not discovery) under VS2015. Currently, I'm seeing discovery showing all tests but that execution is erratic. Sometimes all are run, sometimes a subset, sometimes none. Tracing in the code, it appears that all tests are being executed by NUnit but that there is some failure in getting the news back to the explorer.

At this point, I'd like to here from people using the latest code - that is those who build from source. If you are running the ctp-8 release, your comments are no longer applicable. Please wait for ctp-9 and then tell us what you are seeing.

**Comment by replaysMike** [comment]
will test ctp-9 when it's ready, a few people on my team are now experiencing the test discovery failing and would love to see a resolution.

**Comment by CharliePoole** [comment]
@replaysMike That's great. It's out now, so see how it works for you.

**Comment by replaysMike** [comment]
The latest release fixes the problem we were having with unit tests not being discovered, in VS2015 update 2. Excellent work thank you! 

I was also able to remove the nUnit extension in favor of the adapter nuget package and everything worked as expected.

**Comment by CharliePoole** [comment]
Good news! Thanks.
