### ISSUE TITLE
System.AggregateException is thrown on when debuging async calls

### ISSUE THREAD

**Issue by midexsoftware** [nunit/nunit3-vs-adapter#127]
Hello,

I have the following environment:
- Visual Studio 2015 Community Edition
- Framework 4.0 with BCL packages for async calls
- nUnit 3.0.1
- nUnit Adapter 3 installed.

Here is a very simple test case that give me an error
 [Test]
public async Task EqualToTest()
{ 
   Assert.That(5, Is.EqualTo(6));
}

Same failure
 [Test]
public async Task IsTrueTest()
{ 
   Assert.That(false, Is.True);
}

I know async should not be here. But my real test I actually test async methods, therefore I need that async keyword.  The code above just for demonstration purposes

If I run "Run Selected Tests", I will get a correct error  "Test Failed"  with appropriate message.  So no problem there.

But, if I run "Debug Selected Tests", I will get 

"An exception of type 'System.AggregateException' occurred in mscorlib.dll and wasn't handled before a managed/native boundary. Additional information: One or more errors occurred."
Also, "Source Not Available" page opens up

- if I remove async, it will work fine. 
- If Assert passes, then it works fine. Ex: 
Assert.That(5, Is.EqualTo(5));

So the issue is, ONLY if my test case is async, ONLY if I run it in Debug and ONLY if Assert should fail.

**Comment by appel1** [comment]
Perhaps you've configured Visual Studio to break on AggregateException?

**Comment by midexsoftware** [comment]
![nuniterror](https://cloud.githubusercontent.com/assets/3258797/13363137/efe6039a-dc95-11e5-9150-1d1ec7121648.png)

Hi, I think you are the same person replying on Google Group.  Thank you for looking into this.  

I am attaching the screenshot of the error.  No, I do not have a break configured.  

It is possible that this error is thrown by Visual Studio, but it is related to nUnit one way or another.  Maybe there is a problem in the Adapter?

**Comment by CharliePoole** [comment]
The is clear enough. The question is why NUnit doesn't catch it.

What happens if you run your test under the NUnit console runner? What happens if you use a test that directly throws an AggregateException?

**Comment by midexsoftware** [comment]
1. I don't know how to run test through console because I always used Visual Studio.  But here is what I tried and got IndexOutOfRangeException

C:\Program Files (x86)\NUnit.org\nunit-console>nunit3-console.exe --testlist="X:\Clients\AC\AC.Data.Test\DataManagerDoctorTest.cs" --test=EqualToTest

DataManagerDoctorTest.cs is the file where test case EqualsToTest is.

Maybe you can suggest how to properly run the test in console?

In regards to throwing exception I create these 2 tests:
[Test, Category("Doctor Database Test")]
public async Task ThrowAggregateExceptionAsync()
{
     throw new AggregateException();
}

[Test, Category("Doctor Database Test")]
public void ThrowAggregateException()
{
    throw new AggregateException();
}

I put break on the throw line.  If I run the void test, then I will see normal exception (AggregateException was unhandled), but if I run the async test, I get the same error plus "Source Not Available" with exception AggregateException occurred in mscorlib.dll.  Exactly the same as the screenshot I attached earlier.

**Comment by CharliePoole** [comment]
Type nunit3-console -h to get help for the command.

Type nunit3-console myassembly.dll, substituting the path to your test assembly to run tests.

It's simpler if you just create a test assembly that has only the tests you want. But if you want to use an existing assembly and select tests, don't use both --test and --testlist but pick one or the other. To use either, you have to know the name of the test as specified by NUnit. For a test that has no arguments, it's simply the fully qualified name of the method.

Your experiment throwing the exception proves that NUnit doesn't handle it correctly in an async method, at least under the VS adapter. We'll need to figure out whether it's an underlying NUnit error or an adapter error. My guess is that it is NUnit itself and that using the console runner will prove it.

**Comment by midexsoftware** [comment]
As per your suggestion, I created a separate test project with 4 methods:
    [TestFixture]
    public class nUnitBug
    {
        [Test, Category("nUnit Experimer")]
        public async Task IsTrueTest()
        {
            Assert.That(false, Is.True);
        }

        [Test, Category("nUnit Experimer")]
        public async Task IsEqualToTest()
        {
            Assert.That(5, Is.EqualTo(6));
        }

        [Test, Category("nUnit Experimer")]
        public async Task ThrowAggregateExceptionAsync()
        {
            throw new AggregateException();
        }

        [Test, Category("nUnit Experimer")]
        public void ThrowAggregateException()
        {
            throw new AggregateException();
        }

If I run it without --debug flag, I will the following output
![consoleoutput](https://cloud.githubusercontent.com/assets/3258797/13366873/0a939aca-dcac-11e5-808d-484312d8b4fb.png)

But if I run --debug, then I get the following popup.  If I press No, I it shows the same output as above
![error](https://cloud.githubusercontent.com/assets/3258797/13366891/2823e89c-dcac-11e5-93c1-3ab73c1f9a36.png)

**Comment by CharliePoole** [comment]
So, in summary, under the console runner, the results are what you would expect.

The result using the debug option is also correct. The purpose of that option is to allow you to debug the tests.

**Comment by CharliePoole** [comment]
Closing as not reproducible and for lack of further info.
