### ISSUE TITLE
NUnit test adapter not running all tests - only on VS2015

### ISSUE THREAD

**Issue by bbrewder** [nunit/nunit3-vs-adapter#131]
I can't seem to get all of my tests to run in VS 2015. All the tests are displayed in Test Explorer and I can run any test individually just fine, but it won't run them all. Highlighting them all and running selected doesn't work any better.

As an example, I've currently got 79 unit tests. I just clicked "Run All" in Test Explorer and 19 tests passed, the other 60 are in "Not Run Tests". I select the first 6 in "not run" and run selected, 1 is processed. I then run selected again (the ones not run are still highlighted) and 4 more are processed. The numbers are very inconsistent and doesn't seem to be hanging up on any particular unit test.

One odd thing that I've noticed a few times is that it seems that some run (the icon turns green) but then, once the tests are completed, the tests switch back to "not run".

Very odd behavior. I would run the nunit gui, but it doesn't seem to be part of the installation any more (though I can't seem to find any documentation on this changing). Running the tests using the nunit console does complete correctly.

Here is the output when I run all...

------ Run test started ------
NUnit Adapter 3.0.8.0 executing tests is started
Running all tests in D:\Development\BizArk\BizArk.ConsoleApp.Tests\bin\Debug\BizArk.ConsoleApp.Tests.dll
Loading tests from D:\Development\BizArk\BizArk.ConsoleApp.Tests\bin\Debug\BizArk.ConsoleApp.Tests.dll
Running all tests in D:\Development\BizArk\BizArk.Core.Tests\bin\Debug\BizArk.Core.Tests.dll
Loading tests from D:\Development\BizArk\BizArk.Core.Tests\bin\Debug\BizArk.Core.Tests.dll
Collection was modified; enumeration operation may not execute.
NUnit Adapter 3.0.8.0 executing tests is finished
========== Run test finished: 0 run (0:00:11.7906792) ==========

**Comment by CharliePoole** [comment]
We've determined that this is a problem with VS2015 only. It doesn't happen in VS2013. In my own experiments, I find that this only occurs intermittently. However it may happen more regularly on some machines.

**Comment by bullmastiffo** [comment]
I have the same issue on VS2015, though there are only 11 tests, 3 of them for single async method. Test "Act" section looks like: 

`testedClass.testedMethod().Wait()`

As soon as I comment async method call in one of three tests, they all run fine (except that assertion fails for test with commented call).

**Comment by rprouse** [comment]
@bullmastiffo, can you give an example of how you are writing your async tests? Curious why are you calling Wait() and not using await?

**Comment by bullmastiffo** [comment]
@rprouse, I am calling Wait(), because I can't mark test method as async, or probably I've got something wrong while reading NUnit documentation. :) 
There is nothing special about test code:

       [Test(Description = "Some description")]
        public void CheckSetUserOnlineOnOnlineAddsGirlToCurrentOnlineRepo()
        {
            // Arrange
            long girlUserId = 0xF2345A;
            var onlineItemSet = new Mock<IItemsSet<long>>();
            // omited some mock arrangements
            
            var svc = new SomeStateService();
            // Act
            svc.SetUserOnline(girlUserId, true) // this method is async Task
                .Wait();

            // Assert
            onlineItemSet.Verify(i => i.Add(girlUserId), Times.Once);
      }

**Comment by appel1** [comment]
You can have async test methods. See https://github.com/nunit/docs/wiki/Test-Attribute.

**Comment by rprouse** [comment]
@appel1 thanks for including the link. That is why I was asking about using Wait() :smile: 

To use async, you just need to change to

```C#
[Test(Description = "Some description")]
public async Task CheckSetUserOnlineOnOnlineAddsGirlToCurrentOnlineRepo()
{
}
```

You may have been confused by our lack of support for `async void` which we do not support because NUnit must await the results of the test.

**Comment by CharliePoole** [comment]
Everyone... this issue is about tests that are discovered correctly but executed erratically on VS2015 only. Please don't post additional symptoms here unless they occur on VS2015 but not on earlier VS releases. For problems that have some pattern (like async not working) either comment on a different existing issue or create a new one. Keeping this only about problems with VS2015 differences will help us sort things out and fix them much faster.

**Comment by bullmastiffo** [comment]
@appel1 , @rprouse , thank you! I will fix my tests.
@CharliePoole, I wrote in this thread because I have exactly the same issue as described.

**Comment by CharliePoole** [comment]
@bullmastiffo Actually, this issue has nothing at all to do with async tests. It's about VS2015 handling NUnit tests differently from earlier versions. It's a very hard issue that we have not been able to figure out and we need all the help we can get. One small way to help is to keep the issue on topic.

You've already been helped, of course. My comment is intended to keep other folks from piling on with extraneous complaints that just happen to occur in VS2015. I changed the title to try to make it clearer.

**Comment by CharliePoole** [comment]
I discovered that we were getting a COM exception from VS when calling RecordEnd on Explicit Tests for which no RecordStart was called. This does not seem to actually cause a problem for earlier VS products but appears to do so for VS2015. I'm catching the exception and displaying a message. This seems to eliminate the intermittent failures of VS2015 to complete the execution of tests but I'm not certain the problem won't pop up again.

In any case, it still seems like a good idea that we don't propogate exceptions back to NUnit from the listener.

**Comment by bbrewder** [comment]
Just wanted to let you know that I updated the test runner and it seems to be working now! All my tests ran correctly. 

@CharliePoole  Thanks for resolving this and making the updated test runner available so quickly!

**Comment by CharliePoole** [comment]
Cool!

**Comment by kavumbi** [comment]
I think I am facing this issue as well. I had many NUnit tests running under version 2.6.3 and I could see and run them without problem. Then I upgraded the tests to NUnit 3 and they disappeared. I can still run them with NCrunch but I can't see them in Test Explorer.

**Comment by rprouse** [comment]
@kavumbi, is the test explorer window blank? If so, there is a bug in a recent Visual Studio update, search  closed issues here for the fix. Sorry, on phone, otherwise would find the link for you. 

If that isn't it, can you provide us with more information so we can help you?

**Comment by rprouse** [comment]
When you upgraded to NUnit 3, did you also upgrade to the NUnit 3 adapter?

**Comment by kavumbi** [comment]
I installed both NUnit 3 adapter as well.
When I saw that it was not working I uninstalled it and downgraded my tests back to Nunit 2.6.3 but I still could not see the tests.
Finally I uninstalled the other NUnit adaptor as well which has been working fine so far.
I then installed the adaptor as nuget package () in each project and I can now see NUnit 2.6.3 tests.

**Comment by kavumbi** [comment]
Actually I can't run the tests in Test Explorer because the green progress bar on the top of the explorer never stops. It is as if it is still discovering tests but I can't see it found all of them. I don't if this due to the lastest Visual Studio 2015 Update 3 patch but apparently the issue affect only NUnit tests.

I have xunit tests in other projects and I can run them without problem.

**Comment by fredgate** [comment]
I have similar problem with NUnit and Visual Studio 2015 Update 3.

The project.json of my test project :

`klklmkmlk`

```
{
	"version": "1.0.0-*",
	"testRunner": "nunit",

	"frameworks": {
		"netcoreapp1.0": {
			"imports": [ "portable-net45+win8" ],
			"dependencies": {
				"Microsoft.NETCore.App": {
					"type": "platform",
					"version": "1.0.1"
				}
			}
		}
	},

	"dependencies": {
		"dotnet-test-nunit": "3.4.0-beta-3",
		"NUnit": "3.5.0",
		"NUnit3TestAdapter": "3.5.1",
		"Moq": "4.6.38-alpha",
		"MyProject.Services.Impl": { "target": "project" }
	}
}
```

I have one class with two tests. They are well discovered and run.
Then I had a another test in the same class. The new test is well discovered. But if in test explorer, I right click on the project, and select Run selected tests, the two old tests are run but the new is not run.
If I close Visual Studio and reopen it, then run all tests of project, then the 3 tests are executed.

Next I add a second class with a fourth test. All the tests appear in Test Explorer, but when I click on the project to execute all the tests, only 2 tests are executed !

I had others problem :
- if I delete a class containing some tests, it appear again in test explorer with tests of another class.
- if I have a second NUnit test project, some tests appear not in the good project in Test Explorer.

If I replace NUnit by xUnit, all work fine (but I will prefer NUnit).

**Comment by rprouse** [comment]
@fredgate since you are using .NET Core, you only need `dotnet-test-nunit`. Remove `NUnit3TestAdapter`, it currently only runs full framework tests.

What happens if you Run All? Are all tests run?

**Comment by fredgate** [comment]
At first I had not NUnit3TestAdapter. I added it to see if it can solvethe problem. But it changed nothing, so I remove it.

I closed and reopened Visual Studio. I click Run all, and all the 4 tests were run and had the green icon. Then I added two new tests, one in each class. In test explorer the 2 new tests appear, each in the good class. The 2 new tests appear with the blue icon indicating that they are not yet run (it is normal), but two others tests appear also with this blue icon (it is not normal as they had the green icon).
Next I click on Run all; all the 6 tests are run (it is ok).
Next I select the two classes and click Run selected tests : only 5 tests are run (one the 2 first tests is not run).
Next I click again Run All : all the 6 tests are run (it is ok).
Next I select the two class, and click again Run selected tests : again only 5 tests are run (the same as before).

**Comment by CharliePoole** [comment]
@fredgate Can we take the discussion to the repo of the software you are actually using?

**Comment by rprouse** [comment]
I have move the new issue and edited it down to the .NET Core comments.

**Comment by fredgate** [comment]
Yes you are right, my problem is with dotnet core.
