### ISSUE TITLE
Upgrade TestEngine to 3.2.1

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#135]
I'll try to do this for the next CTP - otherwise we can wait for a full release.

**Comment by rprouse** [comment]
Is this because of the API change problems that we ran into?

**Comment by CharliePoole** [comment]
I'd just like to keep up with our actual NUnit releases.

**Comment by CharliePoole** [comment]
Right now, the adapter is hard coded to the engine package it references, so the problem of loading other installed engines doesn't exist. I want to look at using the api assembly to find the engine rather than referencing it directly, but that's not essential for getting a release out.

**Comment by CharliePoole** [comment]
This change has now been reversed. Currently, there is some suspicious behavior with the 3.2 engine used with the adapter. 

We will use the 3.0.1 engine through the final release of the adapter. The 3.2 release of the adapter will use the 3.2 engine, and so forth.

**Comment by CharliePoole** [comment]
Updated title to reflect use of NUnit 3.2.1, the latest version.
