### ISSUE TITLE
Cannot run navigation tests under the console runner

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#138]
The way that the adapter gets navigation info is to create a Diasession object. This is part of the VS object model and requires loading other assemblies that are not present when we are running the tests under the console runner, either locally or on AppVeyor. As a workaround, we can exclude the "Navigation" category.

Ideally, we would figure out where the tests are located in the adapter or the test engine. As is now the case, the info will only be available if debug information is provided in a .pdb file.

**Comment by MSK61** [comment]
This's in response to @CharliePoole's comment here https://github.com/nunit/nunit3-vs-adapter/pull/171#issuecomment-222807386. You're already hard referencing VS test object model in the adapter project, and you're providing its assembly Microsoft.VisualStudio.TestPlatform.ObjectModel through a package from NUnit MyGet Feed. The package however contains the assembly from VS2012 without the other needed helper assemblies. Running navigation tests inside a different(newer) version of visual studio will still not be possible if visual studio 2012 isn't installed on the same machine.

As you can see in the now obsolete #163 I could confirm that msdia110typelib_clr0200(also coming from VS2012), one of the missing assemblies, is needed. So as a first step you can either include msdia110typelib_clr0200 in the Microsoft.VisualStudio.TestPlatform.ObjectModel package in NUnit MyGet Feed, or create a separate package for it. After all I still see the idea of budnling the needed assemblies in a package a viable idea, just if all relevant assemblies are appropriately included in the package.

**Comment by CharliePoole** [comment]
@rprouse You created the ObjectModel package - what do you think of @MSK61 's idea?

**Comment by rprouse** [comment]
As far as I remember, the ObjectModel package is only for building and testing without VS 2012 installed. As long as we are not including the extra packages (or ObjectModel) in the VSIX or NuGet, then I don't see a problem with the idea. A quick test would be to try it out with a new ObjectModel nuget package with a preview prefix and test it. If it works, we switch, if not, we don't merge the PR that uses it. 

@MSK61 are you interested in doing the leg work?

**Comment by MSK61** [comment]
Yes, I'm ready to help with testing the new package. After all this work will save other people from the hassle of getting these tests to run under different visual studio versions. Just notify me here when there's a new package and I'll begin testing it.

**Comment by CharliePoole** [comment]
Another way around  this is to replace use of DiaSession with Mono.Cecil.

The engine is already using Mono.Cecil, and the dll is already present in the adapter package.

I got this idea from here: https://github.com/fixie/fixie/issues/85 and have been talking to the guy who posted the code.

I think I will spike this.

**Comment by MSK61** [comment]
@CharliePoole Feel free to notify me if you craft something and want to test it; I can give a hand with assessing its fitness as a substitute.

**Comment by CharliePoole** [comment]
@MSK61 Thanks... I will do that.

**Comment by CharliePoole** [comment]
This just needs to be tested with the latest fixes to the engine.

**Comment by CharliePoole** [comment]
Fixed as a result of #183

**Comment by jnm2** [comment]
Update: see https://github.com/nunit/nunit3-vs-adapter/pull/450#issue-168421835 for new rationale.
