### ISSUE TITLE
NUnit Adapter 3.0.0.0 throws System.Reflection.TargetInvocationException, even if the solution build is OK

### ISSUE THREAD

**Issue by MironovDmitry** [nunit/nunit3-vs-adapter#14]
After change to default solution namespace, tests cannot be run with the System.Reflection.TargetInvocationException thrown by NUnit Adapter 3.0.0.0.

**Comment by CharliePoole** [comment]
Can you give some more information about how and where the exception is thrown?

**Comment by MironovDmitry** [comment]
when run any test from VS test explorer, in Output window say:
NUnit Adapter 3.0.0.0 executing tests is started
Running selected tests in <dll name>
Loading tests from <dll name>
Exception System.Reflection.TargetInvocationException in <dll name>

no tests are executed.

I rolledback to the latest version before changes - everything works fine.

**Comment by CharliePoole** [comment]
Are the tests discovered without error then? Is there no detail given of
the TargetInvocationException?

Is this the CTP-1 vsix package, or did you build from source?

Charlie

**Comment by MironovDmitry** [comment]
tests are descovered without any errors and displayed in test explorer.
no other information on the exception is given

this the CTP-1 vsix package

**Comment by MironovDmitry** [comment]
one more comment I use SpecFlow for testing with Nunit. If this may help.

**Comment by OsirisTerje** [comment]
Does the error also come when you run a single test or only when you do Run All ?

**Comment by MironovDmitry** [comment]
in both cases: for run all and for selected test(s)

**Comment by MironovDmitry** [comment]
just recreated from scratch all tests that cased exection - no exception

looks like the error was somewhere in namespace change and not directly replated to Nunit.

**Comment by MironovDmitry** [comment]
Hi again.
today got the same error asserting equality of two boolean variables:
Assert.AreEqual(initialCampaignCompareResult, actualResult);
both variables have values of "false".

as soon as I comment this assert statement - everything works fine.

**Comment by CharliePoole** [comment]
Are you sure both are purely bool rather than Nullable<bool>?

**Comment by MironovDmitry** [comment]
Hi Charlie.

Yes, both values are boolables.

**Comment by CharliePoole** [comment]
Boolables? :-)

**Comment by CharliePoole** [comment]
@MironovDmitry I can't determine if that's a typo for 'booleans' or 'nullables'

If you're having trouble with comparing simple booleans I'll be surprised. Nullable<bool> could be a different matter, however.

**Comment by MironovDmitry** [comment]
@CharliePoole I mean Boolean.

AS well It turned out that this exceptions was thrown due to unhandled exception in my code.
My apologies for incorrect information.

**Comment by rprouse** [comment]
@charliepoole, we should be catching all unhandled exceptions in tests, so this is a real issue right? Should be easy enough to confirm if that is the case.

**Comment by rprouse** [comment]
Was the unhandled exception thrown when your test assembly was loaded? Can you give us more info? We should probably give you a better error at least.

**Comment by CharliePoole** [comment]
Yes, and for TargetInvocatonException we should report the inner exception.

Hmmm... I wonder what happens if the SUT throws it.

**Comment by CharliePoole** [comment]
I'll check this.

**Comment by darthKwisatzHaderach** [comment]
Hello! 
I have the same problem. I use NLog in my project.
When I use console output, it's ok. But when I write to file, I recieve
Exception System.Reflection.TargetInvocationException, Exception thrown executing tests in...
about:blank

Here a part of NLog config that changed:
<target name="Console" type="Console" layout="${longdate} ThreadID:${threadid} ${level} - ${message}" />

<target name="File" type="File" fileName="${basedir}/../TestResults/Log.txt" encoding="utf-8" layout="${longdate} ThreadID:${threadid} ${level} - ${message}" />

When I run tests from nunit-console.exe, it's works fine.

**Comment by darthKwisatzHaderach** [comment]
Once again, I found this error when added:
[TestCase("!@#$%^&*()")]
[TestCase("轉注zhuǎnzhù假借jiǎjiè")]

When I run this tests from nunit-console.exe, it's ok.

**Comment by CharliePoole** [comment]
@darthKwisatzHaderach This seems to be the problem just called out in issue #850

**Comment by roboter** [comment]
Have similar problem 
my test look like this
using NUnit.Framework;

namespace UnitTestDemo
{
    public class UnitTest1
    {
        [Test]
        public void TestMethod1()
        {
            Assert.IsTrue(true);
        }
    }
}

I can run All tests and it will give ok
But running one test with run or debug gives

------ Run test started ------
NUnit Adapter 3.0.2.0 executing tests is started
Debugging selected tests in ....bin\Debug\UnitTestDemo.dll
Loading tests from ....bin\Debug\UnitTestDemo.dll
Exception System.Reflection.TargetInvocationException, Exception thrown executing tests in ...bin\Debug\UnitTestDemo.dll
NUnit Adapter 3.0.2.0 executing tests is finished
========== Run test finished: 0 run (0:00:01.8362181) ==========

**Comment by roboter** [comment]
I manage to run tests individually after I change project file


before:
<Reference Include="nunit.framework, Version=3.0.5767.14863, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <HintPath>..\packages\NUnit.3.0.0-beta-5\lib\net45\nunit.framework.dll</HintPath>
      <Private>True</Private>
    </Reference>


after:
<Reference Include="nunit.framework, Version=3.0.5674.19278, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\packages\NUnit.3.0.0-beta-3\lib\net45\nunit.framework.dll</HintPath>
    </Reference>

**Comment by CharliePoole** [comment]
Folks... please stop piling on to this bug report with "I have the same thing" Since the original report was back in **April** using a much earlier beta, it's really unlikely that you have the same thing!

I realize that it's hard for a user to tell whether the bug they are seeing is "the same as" some earlier report, but there are definite hints you can use. For example, are you using the same software as the original reporter? Are your symptoms the same? Does the stack trace show the error coming from the same place?

Specifically, on this issue, the problem with non-XML characters in test names is **not** related even remotely to the original issue here.

Sorry to rant, but the diversity of symptoms being reported on this single issue is one reason why it remains unconfirmed for so long. Individual, clearly stated, issues with repro steps are the best way to get your problems resolved more quickly.

I've added this issue to the next CTP and will try to figure it out for that drop.

**Comment by CharliePoole** [comment]
Any TargetInvocationExceptions will now display the InnerException type and message. For a full stack trace, use the verbosity option as always.
