### ISSUE TITLE
Nunit Can't find any tests if Class name contains "Command"

### ISSUE THREAD

**Issue by mdrobulis** [nunit/nunit3-vs-adapter#140]
When I add this code to my test suit 

```
[TestFixture]
    public class CommandIntegration
    {
        [OneTimeSetUp]
        public void setup()
        {
            Console.WriteLine("Start");
        }
        [Test]
        public void ExecutableCommand()
        {
        }
}
```

Nunit I see this Console Output:

> ------ Run test started ------
> NUnit Adapter 3.0.8.0 executing tests is started
> Running all tests in C:\Dev<confidencial>\Tests\bin\Debug\Tests.dll
> Loading tests from C:\Dev<confidencial>\Tests\bin\Debug\Tests.dll
> NUnit Adapter 3.0.8.0 executing tests is finished
> No test is available in the provided sources. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
> ========== Run test finished: 0 run (0:00:06.1121627) ==========

End Result ZERO Tests executed.

If Class does not begin with "Command" string in the class name, all tests run just fine.

**Comment by CharliePoole** [comment]
Frankly, this makes no sense. NUnit doesn't use the name of the class in recognizing fixtures. However, I've marked it for somebody to confirm or deny, just in case.

**Comment by CharliePoole** [comment]
Is this on VS2015 by any chance?

**Comment by mdrobulis** [comment]
YES

On Fri, Apr 1, 2016 at 4:27 AM, CharliePoole <notifications@github.com>
wrote:

> Is this on VS2015 by any chance?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/nunit3-vs-adapter/issues/140#issuecomment-204199273>
>



-- 
Martynas Drobulis

Email: mdrobulis@gmail.com
Tel.:    +37063057812

**Comment by CharliePoole** [comment]
We have a general issue on tests not being executed on VS2015 - issue #131. Is it possible that this is what you are seeing? The symptom is that the tests are discovered but on execution some or all of them intermittently fail to be executed. Obviously, you would need an assembly with more tests to verify if this is also your case. IOW, I'm thinking the business with "Command" is just a coincidence.

**Comment by OsirisTerje** [comment]
I have checked this code on both VS2015U3 and VS2017RC, and can't repro it.  So possibly @CharliePoole  is right that what you saw was #131 .
