### ISSUE TITLE
Tests not discovered within Visual Studio 2015

### ISSUE THREAD

**Issue by Rasetech** [nunit/nunit3-vs-adapter#149]
I have installed Version 3.0.8.0 of the NUnit3 Test Adapter in Visual Studio 2015 Update 2 and have added NUnit 3.2.0 via NuGet to my Universal Windows Library Project. When the test discovery is running following output is generated: 

> NUnit Adapter 3.0.8.0 discovering tests is started
>  Dependent Assembly nunit.framework of .../Tests.dll not found. Can be ignored if not a NUnit project.
>  NUnit Adapter 3.0.8.0 discovering test is finished

and 0 tests are discovered. I have annotated the test class with [TestFixture] and the method with [Test].

**Comment by rprouse** [comment]
The test adapter uses the NUnit Engine and neither support running UWP yet. Hopefully we will be able to support it in 3.4, sorry.

I am going to close this here as we have several related issues in NUnit itself. Feel free to add comments to this issue if you have any questions.

**Comment by Rasetech** [comment]
So how are these tests executed then?
