### ISSUE TITLE
Make adapter available as nuget package

### ISSUE THREAD

**Issue by b-filip** [nunit/nunit3-vs-adapter#152]
The adapter for NUnit 2 was available as a NuGet package. It would be automatically installed and VS would discover the tests.

This adapter must be installed as an extension. Why is it so?

**Comment by appel1** [comment]
As documented on nunit.org and in the adapter wiki there is a NuGet package. 

https://github.com/nunit/docs/wiki/Adapter-Installation
https://www.nuget.org/packages/NUnit3TestAdapter/
