### ISSUE TITLE
adapter does not detect c++\cli assemblies

### ISSUE THREAD

**Issue by jmecosta** [nunit/nunit3-vs-adapter#16]
seems /clr assemblies are not supported... 

NUnit failed to load Assembly.Test.dll
NUnit Adapter 3.0.0.0 discovering test is finished

**Comment by rprouse** [comment]
@jmecosta, can you retest with version 3.0.2.0 of the adapter? I Just tested this and it works fine for me.

![image](https://cloud.githubusercontent.com/assets/493828/7814064/a5d08942-038d-11e5-95d0-a07aefa04857.png)

A common mistake with testing C++/CLI assemblies in Visual Studio is not setting x86/x64 correctly. It needs to match what you are building your test assembly as.

![image](https://cloud.githubusercontent.com/assets/493828/7814106/e099acfc-038d-11e5-9d9e-3de71658d23d.png)

This is a Visual Studio thing, nothing to do with NUnit :smile:

**Comment by jmecosta** [comment]
Yep am aware, not sure if did change the engine. But will check and report
back

**Comment by CharliePoole** [comment]
@jmecosta Did you check? Can we close this?

**Comment by jmecosta** [comment]
Nop not yet. I try to do this today or tomorrow.

**Comment by jmecosta** [comment]
works as expected. thanks

**Comment by CharliePoole** [comment]
Thank you.
