### ISSUE TITLE
Failing setups and teardowns aren't shown correctly in TFS website

### ISSUE THREAD

**Issue by overeemm** [nunit/nunit3-vs-adapter#161]
We have builds (vnext in TFS 2015) dat fail because of setup methods. The build is correctly flagged as failed, and the logs show the stacktraces.
However, the reported test results in the website do not report failing tests (it reports 0 failing tests). It instead shows them as not-executed. However, because the setup failed, you could say the tests failed. That used to be the behavior (test adapter v2), but has changed in v3.

**Comment by CharliePoole** [comment]
Yes, you could say that. :-) And as you noted, we used to say that in NUnit V2. But it always seemed a bit wrong and was motivated by our focus on only reporting test case results. We would list 20 test failures all with the same message!

With V2, we made two changes that support one another. We now skip tests under a failing fixture setup. But we also report the fixture as failing, so the user has a message.

[By the way, we are talking about OneTimeSetUp here, formerly known as TestFixtureSetUp. There is no change in how failures in methods marked [SetUp] are reported.]

That's how NUnit works. Now to the adapter...

Unfortunately, Visual Studio gives us no effective way to report any failures except at the test case level. We have been trying to deal with this by displaying a message in the Output window when fixture or higher-level setup fails. Are you not seeing that? Or is it not sufficiently discoverable?

Do be sure you are using the latest (final production) release of the adapter, btw. Some changes in reporting are fairly recent.

**Comment by CharliePoole** [comment]
We haven't heard back about this so I'm closing. We can re-open if further information comes up.
