### ISSUE TITLE
Visual Studio 15 support

### ISSUE THREAD

**Issue by xperiandri** [nunit/nunit3-vs-adapter#162]

**Comment by CharliePoole** [comment]
Not a clue what this is about!

**Comment by rprouse** [comment]
@xperiandri I assume that you mean that the test adapter does not work in Visual Studio '15'. Do you get errors or does it just not install? A bit more info and we can reopen this issue.

**Comment by rprouse** [comment]
I checked the manifest for this too. We need to add 15.0. Reopening.

**Comment by xperiandri** [comment]
I'm about installation into Visual Studio 15.
I modified manifest and installed adapter but I haven't check yet if it works.

**Comment by CharliePoole** [comment]
You should be able to install the NUnit 3 adapter on VS2015 without modification. You can use either the vsix or the nuget package. If you had to modify something, then it's possible you have the wrong package.

**Comment by rprouse** [comment]
@charlipoole, confusing, but 15 is the next version of Visual Studio, not 2015. It is the internal number, like 2015 is 14.0

On Apr 23, 2016 1:09 PM, CharliePoole <notifications@github.com> wrote:

You should be able to install the NUnit 3 adapter on VS2015 without modification. You can use either the vsix or the nuget package. If you had to modify something, then it's possible you have the wrong package.

**Comment by CharliePoole** [comment]
Sorry... misunderstood completely.

Historically, we have waited for final release before trying to support it. This is at least on part due to resource constraints. Currently one guy supports the nunit3 adapter. Interested folks are welcome to contribute. :-)

**Comment by CharliePoole** [comment]
I'll fix the package in the milestone release but I have no way to test it. @xperiandri Did it work for you?

**Comment by xperiandri** [comment]
I was managed to install it.
But I have not tested it.

**Comment by CharliePoole** [comment]
OK, I'll at least change the manifest, then folks can give feedback.

**Comment by CharliePoole** [comment]
No idea what the "Editions" for VS 15 will be, so I used Ultimate, Premium and Pro as for the earlier versions.

**Comment by xperiandri** [comment]
Ultimate, Premium and Pro still work
However it is better to use Enterprise, Pro and Community.
Actually if you specify Community every higher edition will work.
