### ISSUE TITLE
NUnit 3 Test Adapter fails to run tests in parallel on a TFS Build Agent or VS2013 Test Explorer

### ISSUE THREAD

**Issue by benlaan** [nunit/nunit3-vs-adapter#166]
I have TFS 2012 build agents successfully running Nunit 3 tests, however, they run very fast on my dev box via the console-runner, (approx 3 mins), but take 12 minutes on the build agent (via VS Test Runner)

When I run the tests within VS 2013 via the Test Explorer, the vstest.executionengine.x86.exe process only takes up one core too - I assume this is the same exe that the TFS agent is using..

I have 10 test assemblies and the total time on the build agent is approx the sum of running them individually, whereas on my dev box it is approx the time of the largest assembly. From this I can conclude that the console runner is running in parallel, but the test adapter is running in series.

Is it possible to get the nunit vs adapter to run all tests in parallel? If so, do I have to configure it somehow?

I have found the discussion on #49 that seems relevant, however I don't see any actual example configuration. Is there any documentation on this?

**Comment by CharliePoole** [comment]
There is an issue in the docs repo to create a page about how to specify test settings, as discussed in #49. However, parallel execution is not yet available because we don't bundle the NUnit components needed to run in parallel with the current version of the adapter.

**Comment by benlaan** [comment]
Thanks @CharliePoole. I thought I'd mention that the discussion (and code) mentioned leveraging a configuration element called MaxCpuCount under RunConfiguration - I did try this, but that element is not legal in VS2013 - I found some documentation on the .runsettings file which indidates it was introduced with VS2015

**Comment by CharliePoole** [comment]
The run settings file can be used with VS2012 or 2013 but some elements supported in 2015 will cause an error. The NUnit element works the same in all VS versions.

Pending real docs look at the settings file for NUnit3TestDemo.

**Comment by OsirisTerje** [comment]
You can find documentation here https://blogs.msdn.microsoft.com/visualstudioalm/2016/02/08/parallel-and-context-sensitive-test-execution-with-visual-studio-2015-update-1/

Both VS and TFS Build (using VSTest) will run sequentially if there is no runsettings file there.  The parallel run that VSTest has implemented in Update 1 is only handling parallel run of test assemblies.  

There is no such mechanism for VS2012 - VS 2015 RTM, it is only VS 2015 Update 1 that has this feature.  

If you run in VS you can see this in the Output/Test window.  When it is running in parallel you see the info there coming on top of each other, whereas in sequential they come ... well sequentially :-)  

The MaxCpuCount was also introduced with Update 1 to set this, see the blog post above.
