### ISSUE TITLE
Error - Has no TestFixtures

### ISSUE THREAD

**Issue by ilyubin** [nunit/nunit3-vs-adapter#169]
I try to use Akka.net TestKit  and Nunit 3.
I have simple test:
```
    [TestFixture]
    public class AkkaExample : TestKit
    {
        protected AkkaExample() : base(ConfigurationFactory.Load())
        {
        }

        [Test]
        public void TestExample()
        {
            Assert.True(true);
        }
    }
```
When I run it (from VS or console) - error occur:
```
Unit Test Runner failed to run tests
Has no TestFixtures
Failed to start test runner.
```
http://screencast.com/t/315oIgAf

packages.config is here:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Akka" version="1.0.6" targetFramework="net45" />
  <package id="Akka.TestKit" version="1.0.6" targetFramework="net45" />
  <package id="Akka.TestKit.NUnit" version="1.0.6" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="8.0.3" targetFramework="net45" />
  <package id="NLog" version="4.3.3" targetFramework="net45" />
  <package id="NUnit" version="3.2.1" targetFramework="net45" />
  <package id="System.Collections" version="4.0.0" targetFramework="net45" />
  <package id="System.Collections.Immutable" version="1.1.37" targetFramework="net45" />
  <package id="System.Diagnostics.Debug" version="4.0.0" targetFramework="net45" />
  <package id="System.Globalization" version="4.0.0" targetFramework="net45" />
  <package id="System.Linq" version="4.0.0" targetFramework="net45" />
  <package id="System.Resources.ResourceManager" version="4.0.0" targetFramework="net45" />
  <package id="System.Runtime" version="4.0.0" targetFramework="net45" />
  <package id="System.Runtime.Extensions" version="4.0.0" targetFramework="net45" />
  <package id="System.Threading" version="4.0.0" targetFramework="net45" />
</packages>
```

**Comment by appel1** [comment]
What VS runner? What console runner? You must use one that supports NUnit3. 

Also, the test fixture class must have a public constructor.

**Comment by CharliePoole** [comment]
Akka.net does not yet support NUnit 3. Google "akka.net nunit3"

**Comment by ilyubin** [comment]
Why you close issue?

Akka.net support nunit3 - here examples - https://github.com/akkadotnet/Akka.TestKit.Nunit/blob/dev/src/Akka.TestKit.NUnit3.Tests/TestKitTestFixtureTest.cs

I use VS runner from resharper.

**Comment by ilyubin** [comment]
And nunit3-console as command-line runner

**Comment by CharliePoole** [comment]
I found several issues that indicate they don't.

**Comment by CharliePoole** [comment]
Do you believe these are all resolved? If so and if you are using the latest nunit3 testkit, we can reopen.

**Comment by ilyubin** [comment]
I've download mentioned examples from official akka repository. It works with nunit3, it all start and pass. Please, reopen issue. Let's try to find problem. I can investigate better and provide more info as you need.

**Comment by CharliePoole** [comment]
I'd fell most comfortable if someone associated with that project indicated it's supposed to work. Are you?

**Comment by CharliePoole** [comment]
OK, reopened. Going back to bed now. :-)

**Comment by appel1** [comment]
It looks like you are using Akka.TestKit.NUnit NuGet package which is for NUnit 2 and not [Akka.TestKit.NUnit3](https://www.nuget.org/packages/Akka.TestKit.NUnit3/) that works with NUnit3.

**Comment by ilyubin** [comment]
Yes, you right, now I am in progress update to use Akka.TestKit.NUnit3
