### ISSUE TITLE
Can't read app.config settings within test methods

### ISSUE THREAD

**Issue by infl3x** [nunit/nunit3-vs-adapter#17]
Hello,
I'm attempting to use the latest CTP release of the VS adapter and am running into issues reading app settings from my app.config file in the test project.

I've created a simple test project with the following test:

```
        [Test]
        public void ShouldReadAppConfigSetting()
        {
            Assert.That(ConfigurationManager.AppSettings["TestConfigSetting"], Is.Not.Null);
        }
```

...And added the following to the app.config file for the test project:

```
  <appSettings>
      <add key="TestConfigSetting" value="omg" />
  </appSettings>
```

I have been able to get around this issue using the console runner by specifying `-domain:multiple`.

If I switch Visual Studio back to the the old v2.x test adapter, the test passes.

**Comment by CharliePoole** [comment]
This is confirmed. The test adapter does not set the config file location for the test domain.

**Comment by marklam** [comment]
Would a fix for this also make bindingRedirect work?

**Comment by CharliePoole** [comment]
Yes, so long as it's in the config file named for the assembly being loaded.

**Comment by marklam** [comment]
It's in the .exe.config for an exe using NUnitLite 3, so I think so.
Thanks.

**Comment by ravensorb** [comment]
This issue seems to still exist.  Did something change recently that would cause it to no longer work?

**Comment by OsirisTerje** [comment]
@ravensorb There are 2 tests in the NUnit Demo project for this, and they both are working.  
Please check https://github.com/nunit/nunit3-vs-adapter-demo and the tests in class ConfigFileTests

If you still have a fail, please raise a new issue with a small repro project

**Comment by ravensorb** [comment]
Hmm, I looked at that and I don't see any test that is reading from ConfigurationManager.AppSettings  -- am I missing something?

Note -- these tests also fail in VS2019

**Comment by OsirisTerje** [comment]
Did you look at https://github.com/nunit/nunit3-vs-adapter-demo/blob/master/src/csharp/ConfigFileTests.cs  ?

If it still doesn't work for you, can you please create a small repro and upload it ?   It should work "as is".

**Comment by ravensorb** [comment]
Ok, I was looking in the .netcore test project. 

Few things observed
- CSharpTestDemo
  - project will not execute in VS2019 (test discovery doesn't seem to work). Adding reference to test adapter for visual studio allows it to run inside VS
  - 20 test cases fail in VS2019 (some might be expected to fail though so its hard to tell if this is a correct result)
- NUnit3CoreTestDemo
  - AppDomain.CurrentDomain.SetupInformation doesn't exist in anything newer than core 1.0 (fails in core 1.1 and 2.0 as well as netstandard 2.0).  I think the code needs to move to using ConfigurationBuilder correct?

From my side, I am switching over my code to using ConfigurationBuilder as well so I think I am good now.

Thanks!

**Comment by OsirisTerje** [comment]
@ravensorb I just checked with VS 2019, and it works.  Discovery is working, and so is running them. 

![image](https://user-images.githubusercontent.com/203432/52227073-d2f1e700-28ae-11e9-89d6-5823ef53880c.png)

I see a couple of tests there (marked red) that has unexpected results, but I havent checked them in VS2017 yet.  But all in all, this works.

**Comment by ravensorb** [comment]
Yep that aligns for the most part with what I was seeing after I added the test runner. So that makes complete sense.  For the netcore one, I could probably do a PR for the new configuationbuilder if that would be useful.

**Comment by OsirisTerje** [comment]
Absolutely!  Please do!

**Comment by jilani-blend** [comment]
My App.Config file is not readable in Test Project.  it works fine in the simple class library.

**Comment by OsirisTerje** [comment]
This is a closed issue. Your comment doesn't seem to address anything here.
