### ISSUE TITLE
More Information link in vsix broken

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit3-vs-adapter#176]
Looks like the name of the wiki page has changed, which broke the link. Perhaps it should point to the main page of docs/wiki instead, to be more stable? Or, should it point to the main page of this repo, and the README here contain a link to the docs? As this repo page is presumably the most stable option.

@CharliePoole - I thought this seemed sensible to squeeze in to 3.2, please move it out if you disagree!

**Comment by CharliePoole** [comment]
Makes sense
