### ISSUE TITLE
TFS Build 2015 (vNext) fails when all test pass but Nunit throws a System.Threading.ThreadAbortException

### ISSUE THREAD

**Issue by edoua** [nunit/nunit3-vs-adapter#177]
Hello,

The software I work on is built using TFS Build 2015 (vNext) on premise.
We use NUnit 3 (Nuget version=3.2.1) and NUnit3TestAdapter (Nuget version=3.0.10).
Part of the build process is to execute unit tests.

The problem is that the build fails even if all the unit tests pass.
An exception is apparently generated by NUnit which fails the VSTest Runner.

Here the output from TFS Build 2015:
```
Information: Running all tests in XXX.UnitTests.dll 
##[error]Error: System.Threading.ThreadAbortException: Thread was being aborted. 
##[error]   at NUnit.Engine.Services.DomainManager.DomainUnloader.UnloadOnThread() 
##[error]   at System.Threading.ThreadHelper.ThreadStart_Context(Object state) 
##[error]   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) 
##[error]   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) 
##[error]   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) 
##[error]   at System.Threading.ThreadHelper.ThreadStart() 
##[error]
Information: NUnit3TestExecutor converted 9 of 9 NUnit test cases
9 test passing
##[error]Test Run Failed.
Total tests: 181. Passed: 181. Failed: 0. Skipped: 0.
Test execution time: 2,1249 Minutes
##[error]VSTest Test Run failed with exit code: 1
Publishing Test Results...
Test results remaining: 181
```

I then checked in Visual Studio, where both the Visual Studio Runner and Resharper Runner report successful test run.

**But** the "Test Output" output from Visual Studio is showing: 

```
------ Discover test started ------
NUnit Adapter 3.0.10.0: Test discovery starting
NUnit Adapter 3.0.10.0: Test discovery complete
========== Discover test finished: 2 found (0:00:01,8681868) ==========
------ Run test started ------
NUnit Adapter 3.0.10.0: Test execution started
Running selected tests in XXX.UnitTests.dll
NUnit3TestExecutor converted 9 of 9 NUnit test cases
Running selected tests in XXX.UnitTests.dll
NUnit3TestExecutor converted 172 of 172 NUnit test cases
System.Threading.ThreadAbortException: Thread was being aborted.
   at NUnit.Engine.Services.DomainManager.DomainUnloader.UnloadOnThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
NUnit Adapter 3.0.10.0: Test execution complete
========== Run test finished: 181 run (0:01:00,5270521) ==========
```

I have used xUnit on other project before with TFS Build 2015, and have seem some exceptions not related to the actual unit test being thrown but it did not fail the build.

Could that be related to https://github.com/nunit/nunit-vs-adapter/issues/92 and/or https://github.com/nunit/nunit-vs-adapter/issues/97 ?
Which I have encountered too. (I had to comment those ignored tests for our build to succeed)

Thanks

**Comment by CharliePoole** [comment]
This is an exception thrown asynchronously by the NUnit thread that unloads AppDomains. The TestEngine should be handling it, but isn't. I'm closing this here but will create an NUnit issue to deal with it.

**Comment by CharliePoole** [comment]
Turns out there was an old NUnit issue. I raised its priority.

**Comment by KirillSelyukov** [comment]
@CharliePoole Not sure if I can proceed in this thread or should create a separate. I got similar problem (TFS thinks build has failed) with ThreadAbortException, but with 3rd part library code. The output is:

> System.Threading.ThreadAbortException: Thread was being aborted.
>    at VoltDB.Data.Client.CallbackExecutor.BackgroundThreadRun() in C:\WORK\voltdb-client-csharp-master\VoltDB.Data.Client\Connections\Internal\CallbackExecutor.cs:line 207
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
>    at VoltDB.Data.Client.CallbackExecutor.BackgroundThreadRun() in C:\WORK\voltdb-client-csharp-master\VoltDB.Data.Client\Connections\Internal\CallbackExecutor.cs:line 207
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()

From what I saw the library authors are okay with the workflow of aborting threads. Is there a way to make runner not to tread these as a reason to fail build?

**Comment by CharliePoole** [comment]
We closed this "wontfix" here because it doesn't seem like this is a job for the runner. The logic behind that is simple: either a test run is an error in it isn't. It shouldn't matter which runner is used to execute it - the job of the runner is to simply report what happened.

In general, such errors should be fixed either in the test engine or the framework itself. It depends where the error arises in the first place. The error originally reported on this issue came from the engine and was fixed there. This one seems to be a bit different but it's hard to tell because the stack trace doesn't show any NUnit entries. Do you have any more information?
