### ISSUE TITLE
Use Mono.Cecil to retrieve source code locations

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#183]
There are various complications with use of DiaSession to retrieve navigation data in the adapter. One of the greatest is that we cannot easily use the console to run our navigation data tests.

I have created a branch `cecil-spike` that demonstrates how we could use cecil for this purpose.

We need to make some decisions...

1. Whether to go this route. I think we should.

2. Whether to implement it in the adapter or as an engine service the adapter can use. There are pros and cons...

If we do it in the adapter, it wil work with the current engine and will work even better with the 3.4 engine, which will return the correct declaring classname in the xml. No further engine changes will be needed.

If we do it in the engine itself, we will need to expose a service that works like the existing NavigationDataProvider and will probably want to do some caching in the engine as well. This would make the functionality available to all runners.

**Comment by CharliePoole** [comment]
Of course, we could implement this in the adapter and migrate it into the engine in a future release.

**Comment by CharliePoole** [comment]
Still hoping for a comment from @OsirisTerje 

However, based on the discussion so far (see #182) I'm inclined to follow my own suggestion. :-)

That is, I would 

1. Do a clean implementation of the spike approach in the NUnit 3 Adapter
2. Back-port it to the NUnit 2 Adapter
3. Plan on looking at it as a possible engine service in the future (i.e. an Idea)

This has the benefit of being doable right away, rather than causing this issue to be blocked while waiting for an engine change. Also, doing it twice (I think with minimal change) may surface issues of detail that we won't discover by merely speculating. Finally, it follows that old maxim of mine: "Create duplication in order to remove it."

**Comment by OsirisTerje** [comment]
This makes sense to me, will try to test it asap.  Diasession is a mess, and the sooner the better. 
It could be tried out with the V3 as you say, back porting makes sense too, since there are still so many users of V2.    Makes sense to create it as an  engine service, but if that takes times, good to have a first version in the adapters to replace the current Diasession
