### ISSUE TITLE
How can I debug adapter?

### ISSUE THREAD

**Issue by GeertVL** [nunit/nunit3-vs-adapter#187]
I want to help to fix some bugs we are dealing with.

How do I debug it with my current project. Experimental hive is working correctly except the breakpoints in the adapter code.

Any help would be welcome to fix them (and send a pull request).

**Comment by CharliePoole** [comment]
Thre are various approaches, but this seems simplest to explain...

Depending on whether you want to debug discovery or execution, uncomment this line at the top of either NUnit3TestDiscoverer.cs or NUnit3TestExecutor.cs:

```C#
//#define LAUNCHDEBUGGER
```

Run the tests without debugging. Assuming you have it set up to launch devenv with the experimental hive, it will run and put up a dialog for you to select the debugger. Pick the original instance of VS, with the adapter code. 

Make sure your breakpoints are set and tell it to continue.

That should do it!
