### ISSUE TITLE
Nunit30Settings.xml is used by other process leads to hidden tests

### ISSUE THREAD

**Issue by a-jaeger** [nunit/nunit3-vs-adapter#190]
I am using NUnit Adapter 3.2.0.0.
I have two testing projects in my solution. When I start testing, I sometimes get the following error:

```
Error: Unable to get runner for this assembly. Check installation, including any extensions.
NUnitEngineException: Error loading settings C:\Users\developer\AppData\Local\NUnit\Nunit30Settings.xml. Der Prozess kann nicht auf die Datei "C:\Users\developer\AppData\Local\NUnit\Nunit30Settings.xml" zugreifen, da sie von einem anderen Prozess verwendet wird.
```

The second part is in german and means that the process cannot access the file "C:\Users\developer\AppData\Local\NUnit\Nunit30Settings.xml" because it is used by another process.

This results in the fact, that not all tests are shopwn in visual studio and I can see a lot of the following messages in the output: 
```
Test adapter sent back a result for an unknown test case. Ignoring result for '...'.
```

**Comment by mwadams** [comment]
I can confirm that I see this issue too, during test discovery after a build, with NUnit Adapter 3.2 and VS2015 Update 2 with latest prod patches.

**Comment by mwadams** [comment]
Similarly, the error is sometimes that the settings file is missing a root node.

**Comment by CharliePoole** [comment]
Here's a theory... it's possible to tell VS to keep the executor process open after a run. If you then trigger a new discovery, then there may be multiple processes trying to write the file at once. Can either of you confirm this experimentally?

**Comment by CharliePoole** [comment]
See nunit/nunit#1560

**Comment by CharliePoole** [comment]
Engine no longer throws an exception if it can't write. This is feasible because there is currently no need for the engine to write out the settings file. The existing runners only read settings.

It's possible that this will change with the GUI runner, but there's no need to try to deal with it in the current codebase.
