### ISSUE TITLE
After installing nunit3 and nunit adapter nunit does not show in create unit tests

### ISSUE THREAD

**Issue by merrua** [nunit/nunit3-vs-adapter#191]
Visual Studio Community 2015, Version 14.0.25123.00 Update 2
NuGet Package Manager 3.4.3

The versions I installed were, 
NUnit 3 Test Adapter 3.2.0

`  <package id="NUnit" version="3.2.1" targetFramework="net461" />
  <package id="NUnit.ConsoleRunner" version="3.2.1" targetFramework="net461" />
  <package id="NUnit.Extension.NUnitProjectLoader" version="3.2.1" targetFramework="net461" />
  <package id="NUnit.Extension.NUnitV2Driver" version="3.2.1" targetFramework="net461" />
  <package id="NUnit.Extension.NUnitV2ResultWriter" version="3.2.1" targetFramework="net461" />
  <package id="NUnit.Extension.VSProjectLoader" version="3.2.1" targetFramework="net461" />
  <package id="NUnit.Runners" version="3.2.1" targetFramework="net461" />
`

Steps to replicate.
1. Install the above to a blank project
2. Create/copy paste a simple class
3. Right click on the class name > Create Unit Tests 
4. NUnit 3 is not in Test Framework dropdown.

**Comment by ChrisMaddock** [comment]
Hi - sounds like you are getting the Test adapter and test generator mixed up.

The test adapter you've installed is for _running_ tests - you need the Test Generator extension to use the automated creation. Take a look here for more details: https://github.com/nunit/docs/wiki/Visual-Studio-Test-Generator

I'll close this issue now, but feel free to comment more if you need any more help getting set up.

**Comment by merrua** [comment]
Test Generator looks to be another extension. If you look at the screenshot, its the one above it that is 'Create Unit Tests '. This link seems to be someones custom unit test generator.

**Comment by ChrisMaddock** [comment]
The NUnit Test Generator extension actually wraps two different things. It should add the functionality to both "Create Unit Test" and "Create IntelliTest".

**Comment by merrua** [comment]
Thanks! I installed the  NUnit Test Generator extension and it generated the skeletons correctly.
