### ISSUE TITLE
The predefined type 'System.Runtime.CompilerServices.ExtensionAttribute' is defined in multiple assemblies in the global alias

### ISSUE THREAD

**Issue by NecroFilja** [nunit/nunit3-vs-adapter#194]
After adding NUnit3TestAdapter to project (nuget) with tests stops building:

The predefined type 'System.Runtime.CompilerServices.ExtensionAttribute' is defined in 
multiple assemblies in the global alias; using definition from 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.5.1\mscorlib.dll'  C:\Projects\WebProject\WebProject.Tests\error CS1685    WebProject.Tests

**Comment by CharliePoole** [comment]
What references to test adapter classes exist in your project after adding the package?

**Comment by NecroFilja** [comment]
Hello,

I just minimized number of refereferences and it still fails. We have quite agressive error treatment - all warnings are considered as errors (due of management requirements). May be this is due of this fact.
I attached whole project, for me references looks like standard.
[WebProject.Tests.zip](https://github.com/nunit/nunit3-vs-adapter/files/345773/WebProject.Tests.zip)

**Comment by CharliePoole** [comment]
Your project contains a bunch of MS test references as well as NUnit references. Why is that? Are you trying to use both kinds of tests in the same assembly?

**Comment by NecroFilja** [comment]
Generally we are migrating from MSTest to NUnit. So some artifacts could remain.
But not sure they affect logic. The only way it works for me - removing all this Mono.*, nunit.* staff.
Leaving only NUnit3.TestAdapter reference. Strange but look like it works without all this.

**Comment by CharliePoole** [comment]
Can we close this or is there still an issue?

**Comment by NecroFilja** [comment]
Still have error.

**Comment by CharliePoole** [comment]
So,if you still have the error after removing the extraneous references, does it indicate to you __which__ assemblies provide duplicate definitions or is only one assembly listed in the message?

**Comment by fredericDelaporte** [comment]
Got same issue.
As a workaround, I have changed in my test project on the `nunit.engine` reference the `Aliases` property to `nuinit` instead of `global`.
So the offending nunit reference looks to be this `nunit.engine` assembly.

My test project targets .Net fx 4.5.2.
NUnit3TestAdapter v3.4.1 has been added with NuGet.

**Comment by CharliePoole** [comment]
Are you saying your test project has a reference to nunit.engine? If so did you add it or did the nuget install do so? The adapter has a reference to the engine, but your project should have no need of it.

**Comment by fredericDelaporte** [comment]
Yes, the test project does have a direct reference to `nunit.engine`.
I can not say precisely how it was added, the colleague having set up the test project is currently on holidays. I had supposed it was added by NuGet, but well, maybe not.
Since it looks like it should not be there, I will try wiping the project NuGet and nunit references and set them again tomorrow (I am no more at work currently). I will report the result here.

**Comment by fredericDelaporte** [comment]
I confirm that adding the NuGet `<package id="NUnit3TestAdapter" version="3.4.1" targetFramework="net452" />` add this `nunit.engine` dependency`to the test project, along with a bunch of other dependencies (`nunit.engine.api`, `Mono.Cecil`, `Mono.Cecil.Mdb`, `Mono.Cecil.Pdb`, `Mono.Cecil.Rocks` ; and of course `NUnit3.TestAdapter`).

**Comment by maikhanns** [comment]
I had the same problem on my tfs build machine. There was a warning because of the nunit.engine reference. After removing the reference the warning is gone. I think the reference was set by nuget install.

**Comment by ChrisMaddock** [comment]
I believe the nuspec should be specifying the intended project references with `<references>`, or else everything in the `/lib/` dir will be added as a project reference.

I don't use the adapter. I assume it's just the `NUnit3.TestAdapter.dll` that should be referenced by a test project?

**Comment by CharliePoole** [comment]
The adapter is a tool and shouldn't be referenced at all. However, it was originally created using the lib directory because some old version of VS needed it to be there. We have an issue to fix this for 3.5.

**Comment by OsirisTerje** [comment]
@CharliePoole Afaic see, this is fixed.  The adapter is no longer added as reference to the project, so we should have no such issues.  Suggest we can close this.

**Comment by CharliePoole** [comment]
I agree.
