### ISSUE TITLE
CI Build

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#2]
This should have the same targets - as appropriate, that is - as our nunit script. We should be able to build, test and package from the script. This will replace the existing nant script.

**Comment by CharliePoole** [comment]
Changed the title to reflect the fact that it may not be an msbuild script. I'm now experimenting with Cake.

**Comment by enricosada** [comment]
may i sugget [fake](http://fsharp.github.io/FAKE/)? i use that for lot of c# proj and work really well (like rake+albacore, without ruby) and fantastic doc ( /cc @forki ).

is really nice for build+package. you can also add command to publish to visual studio gallery](https://github.com/fsprojects/Paket.VisualStudio/blob/231b6b686c170b0e89810f73000d1a6b6712e702/build.fsx#L194) if you want to

if you want to evaluate it and can be ok, i can migrate the nant script and send a pr with the build script

**Comment by rprouse** [comment]
We are currently trialing Cake. We thought it might be easier for C#
developers to maintain. If it doesn't work out, Fake is probably next on
our list.

**Comment by enricosada** [comment]
sure, if doesnt work or want to evaluate fake, ping me :smile: glad to help

btw good work with nunit v3, upgrading now in visualfsharp repo, lots of cleanups done, easier to use :+1:

**Comment by CharliePoole** [comment]
@enricosada 

Actually, I set aside work on the Cake script for the adapter because of issues building. I'm working on a script for NUnit itself, which is more complicated but also more straightforward.

I don't think the issues with the adapter script are particularly related to which scripting engine we use. It's the more general problem of how to get a VS extension to build under Appveyor! Can you offer any advice about that?

**Comment by forki** [comment]
https://github.com/fsprojects/Paket.VisualStudio/blob/master/build.fsx 

Is a build that creates the VS addin for paket and runs on appveyor. It's probably also the only existing project that automatically uploads releases to VS gallery (usign browser automation since there is no API).

**Comment by forki** [comment]
Actually just remembered: Visual F# Powertools has similar script ;-)
https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/build.fsx

**Comment by rprouse** [comment]
My Visual Studio extension for GitHub also builds automatically in AppVeyor just using the solution file. I have been planning on adding a Cake script to it to add functionality, but it was nearly out of the box for me. i can compare my settings there to what we have in the adapter if you want. I had started to look at it, but didn't want to step on your toes.

**Comment by CharliePoole** [comment]
Take a look please. The error I was getting was about missing some targets for the VS SDK. I would have to restore that branch to get a more exact error right now.
