### ISSUE TITLE
Upgrade NUnit to beta-2

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#20]
The adapter tests currently use the beta-1 release of the framework. Upgrade to beta-2.

**Comment by CharliePoole** [comment]
The framework API changes with Beta 2. We need to include a warning that all tests must be recompiled before running them through the engine.

**Comment by oznetmaster** [comment]
What framework API changes are you referring to?

**Comment by CharliePoole** [comment]
The constructor for FrameworkController has changed.

This will impact anyone who is directly using FrameworkController but not those using the engine provided the test assembly is rebuilt against the new beta. We have done this several times through the pre-release cycle.

Of course, we wouldn't break it for a production release but there seems no reason to provide backward compatibility with earlier betas.

**Comment by oznetmaster** [comment]
So this has no effect on test assemblies for the Silverlight, Portable or NetCF builds, since they do not include the FrameworkController?

**Comment by CharliePoole** [comment]
Precisely. FrameworkController's type names and constructors represent the public/published framework API. NUnitLite can bypass this, since it uses a reference to the framework and is rebuilt for every release.
