### ISSUE TITLE
Fail to execute tests in VS 2015 Update 2

### ISSUE THREAD

**Issue by camtechnet** [nunit/nunit3-vs-adapter#200]
Hi,
this is a problem that has been reported by others [(170](https://github.com/nunit/nunit3-vs-adapter/issues/170) [,85)](https://github.com/nunit/nunit3-vs-adapter/issues/85) mine is a slightly different flavour, which I resolved in a different way to others. (Apologies for the lengthy post, but thought it best to provide the logs up)

To summarise I had two related problems
1) Local Dev environment: tests not being discovered and run (this one got resolved by latest [release 3.4](https://github.com/nunit/nunit3-vs-adapter/releases)!)
2) CI build agent: tests still not being discovered and run (still not resolved)

I have the following setup
- VS 2015 Update 2
- solution with multiple projects, all of them targeting .NET 4.61
- NUGET pkgs: NUnit.3.2.1 and NUnit3TestAdapter.3.2.0
- the reason I went with NUGET pkg for NUnit3TestAdapter is to be able to run unit tests as part of CI on build agent, without need for VSIX pkg
- Whenever I try and build I get the AssemblyResolutonException error, no tests are found by discovery, as shown in log below (I've removed multiple instances of error for the multiple projects in the solution)

`------ Discover test started ------
NUnit Adapter 3.2.0.0: Test discovery starting
Error: Unable to get runner for this assembly. Check installation, including any extensions.
AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
NUnit Adapter 3.2.0.0: Test discovery starting
========== Discover test finished: 0 found (0:00:08.6488648) ==========`
- Following suggestion by @OsirisTerje in [(170](https://github.com/nunit/nunit3-vs-adapter/issues/170), I went and installed the NUnit3TestAdapter VSIX extension. 
- It appears that the NUnit3TestAdapter is now being run as 3.2 and/or 3.4. In the latter case I am no longer getting the AssemblyResolutonException, but at least now all tests are discovered and correctly executed.

`------ Discover test started ------ 
NUnit Adapter 3.4.0.0: Test discovery starting
NUnit Adapter 3.2.0.0: Test discovery starting
Error: Unable to get runner for this assembly. Check installation, including any extensions.
AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
**NUnit Adapter 3.2.0.0: Test discovery starting**
Assembly contains no NUnit 3.0 tests: C:\Source\cie-tsl-website\branches\ProjectSetup\src\CIE.Data.Tridion\bin\Debug\CIE.Data.Tridion.dll
Error: Unable to get runner for this assembly. Check installation, including any extensions.
AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
**NUnit Adapter 3.4.0.0: Test discovery complete**
Assembly contains no NUnit 3.0 tests: C:\Source\cie-tsl-website\branches\ProjectSetup\src\CIE.Data.CloudSearch\bin\Debug\CIE.Data.CloudSearch.dll
NUnit Adapter 3.4.0.0: Test discovery complete
....
**NUnit Adapter 3.4.0.0: Test discovery starting**
Assembly contains no NUnit 3.0 tests: C:\Source\cie-tsl-website\branches\ProjectSetup\src\CIE.TSL.Data.CloudSearch\bin\Debug\CIE.TSL.Data.CloudSearch.dll
Assembly contains no NUnit 3.0 tests: C:\Source\cie-tsl-website\branches\ProjectSetup\src\CIE.TSL.Data.Web\bin\Debug\CIE.TSL.Data.Web.dll
**NUnit Adapter 3.4.0.0: Test discovery complete**

========== Discover test finished: 6 found (0:00:11.641164) ==========
------ Run test started ------
NUnit Adapter 3.4.0.0: Test execution started
Running all tests in C:\Source\cie-tsl-website\branches\ProjectSetup\src\CIE.TSL.Web.Tests\bin\Debug\CIE.TSL.Web.Tests.dll
NUnit3TestExecutor converted 6 of 6 NUnit test cases
NUnit Adapter 3.4.0.0: Test execution complete
========== Run test finished: 6 run (0:00:06.4936493) ==========

`
- At that point, I disabled VSIX package, and upgraded NUGET package to NUnit3TestAdapter 3.4.0
- Everything now works locally, with the following log 

`------ Discover test started ------
NUnit Adapter 3.4.0.0: Test discovery starting
NUnit Adapter 3.4.0.0: Test discovery complete
========== Discover test finished: 6 found (0:00:00.8780878) ==========
------ Run test started ------
NUnit Adapter 3.4.0.0: Test execution started
Running all tests in C:\Source\cie-tsl-website\branches\ProjectSetup\src\CIE.TSL.Web.Tests\bin\Debug\CIE.TSL.Web.Tests.dll
NUnit3TestExecutor converted 6 of 6 NUnit test cases
NUnit Adapter 3.4.0.0: Test execution complete
========== Run test finished: 6 run (0:00:05.290529) ==========`

and the following packages.config

`<package id="NUnit" version="3.2.1" targetFramework="net452" />
  <package id="NUnit3TestAdapter" version="3.4.0" targetFramework="net461" />`

**CONCLUSION**

**1. Why don't tests run on CI agent, even after update of NUGET Package to 3.4.0.0?**

**Comment by CharliePoole** [comment]
Part of your initial server problem is that you ended up with two different versions of the adapter installed, one using the vsix and one from nuget. So long as we support the two different install packages, there's no way to prevent that happening and it will probably cause trouble if it does.

We already knew that VS2015 runs the tests twice if you have both package types installed. That was new behavior, not seen in earlier versions. I hadn't run into this with differing versions, but it makes sense that it would work that way.

Have you made the same changes on your server? What do you now see?

Can you add more info about what sort of ci server you are using and how it runs tests?

**Comment by camtechnet** [comment]
Hi,
thanks for the speedy response.
I have not installed the VSIX on the server because I was hoping it would just work with the NUGET package.
The CI build agent is running
- TeamCity 9.1.3
- Test runner: VSTest 2015
- Test executable: 
`Microsoft Visual Studio 4.0\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe`
- Test additional params: NONE; Alternatively `/UseVsixExtensions:false` (just to be safe)
- Build log
`[VSTest] Warning: No test is available in D:\BuildAgent\work\2e43c3eabcd4d39a\src\CIE.TSL.Web.Tests\bin\Release\CIE.TSL.Web.Tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.`

**Comment by CharliePoole** [comment]
AFAIK (@OsirisTerje please correct me) vstest.exe doesn't know anything about nuget!

Why are you using vstest.exe rather than nunit3-console.exe? You have to deal with TC => VsTest => NUnit in this configuration. Using TC => Nunit skips one step, which seems to make sense unless there is something else you are getting from vstest.

**Comment by camtechnet** [comment]
Hmmm, ok did not consider that at all. So is the following post the right way to [install nunit3-console.exe](http://stackoverflow.com/questions/33876102/how-to-install-nunit-3-nunit3-console-exe-in-teamcity-9-x) on CI agent?

**Comment by CharliePoole** [comment]
Yes, that's definitely the way to do it because it requires no pre-configuration of the server. The NUnit.Console package is the new name for NUnit.Runners. Both work now but the latter will be phased out.

**Comment by camtechnet** [comment]
OK. I am afraid that I am also getting up to speed with my first TeamCity 9.1 project. So could you please clarify how I get TeamCity agent to recognise NUnit 3 as an available test runner, as shown [here](https://confluence.jetbrains.com/display/TCD9/Getting+Started+with+NUnit#GettingStartedwithNUnit-Case3.NUnitBuildStep)? After all, the package is only restored within the build directory, so how does TeamCity now I can use an NUnit 3.0 runner?

**Comment by CharliePoole** [comment]
I'm not a teamcity user at all, so I would probably do as you did.

**Comment by camtechnet** [comment]
@CharliePoole ok, thanks very much for your help. I may pursue this discrepancy on TC forums just to clarify.
