### ISSUE TITLE
VS Text Explorer only shows 20 tests

### ISSUE THREAD

**Issue by pgrm** [nunit/nunit3-vs-adapter#203]
> moved from https://github.com/nunit/nunit-vs-adapter/issues/121

Hi, 

I'm using .net core with this kind of project.json:

```
{
  "version": "1.0.0-*",
  "testRunner": "nunit",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Moq": "4.6.25-alpha",
    "dotnet-test-nunit": "3.4.0-beta-1",
    "System.Diagnostics.TraceSource": "4.0.0",
    "NUnit": "3.4.1"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
}
```

I have 4 Test projects and for one of them (the above project.json) I know for sure, that Visual Studio cannot find all the tests. Currently it finds 20 tests, but there should be 20 just in the new test project.

For instance, given these test cases:

```
[TestCase(null, null, null, false)]
[TestCase(null, null, "..", true)]
[TestCase(null, "..", null, false)]
[TestCase(null, "..", "..", false)]
[TestCase(1234, null, null, false)]
[TestCase(1234, null, "..", false)]
[TestCase(1234, "..", null, false)]
[TestCase(1234, "..", "..", false)]
public void CodeNextValueConfigurationValidationTest(int? step, string customNextNumber, string customNextCode, bool isValid)
{
    Assert.AreEqual(isValid, ...);
}
```

It finds the test case 

```
Test Name:  CodeNextValueConfigurationValidationTest(1234,"..","..",False)
```

but not the others.

Other TestCases are found as a whole and again other simple tests, just functions marked with `[Test]` cannot be found at all.

But if I run `dotnet test` in the command line, all tests are run. I tried reloading the project, restarting VS, ... but nothing helped. I have NUnit 3 Test Adapter Version 3.4.0 installed.

Any thoughts what else I can try? thx

**Update:**

I just disabled NUnit 2.0 and restarted VS and saw the 20 test from my current file. After rebuilding the solution again, I see the same as before. It seems to me that I always see a more or less random subset of 20 tests. That's weird, isn't it?

And when I try to run all tests, it also just runs those 20

The pattern seems to be, that for this file I'm analyzing it takes the last 9 tests / testcases

**Comment by pgrm** [comment]
Actually running the tests in the UI at first works without any problems. All I needed to do was adding the info about nunit inside `project.json` and it worked.

**Comment by CharliePoole** [comment]
So does this resolve your problem?

**Comment by rprouse** [comment]
@pgrm, it sounds like you had an older version of the NUnit 2 adapter. Is that possible? It sounds like you got it working, can we close or should I move this to the `dotnet-test-nunit` repo? You don't have to reenter, we can move issues.

**Comment by OsirisTerje** [comment]
No further response, so closing it.
