### ISSUE TITLE
Adapter fails to find Mono.Cecil when targeting .NET 3.5

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#205]
Entering an issue to investigate issues reported by @bbi-yggy and @mariuszjamro in #195 

> I'm having the same problem when using adapter 3.4.0.0 and nunit 3.2.1 on .net 3.5. Adapter is complaining about not found Mono.Cecil.Rocks.

> I noticed that it works correctly when project has target framework version set to .net 4.5 - seems like a workaround.

and 

>@CharliePoole, we recently upgraded to the 3.4.1 version of NUnit and the Visual Studio 2015 test adapter, and now we are periodically getting test discovery failures with an error about not being able to load the Mono.Cecil.Rocks assembly. Has anyone else seen this? I will try to track down more details on the repro steps, as it has been frustratingly inconsistent.

**Comment by bbi-yggy** [comment]
Note that Mono.Cecil.Rocks is the specific assembly that's not being found.

**Comment by CharliePoole** [comment]
@bbi-yggy Is this using the vsix install, the nuget package or both?

**Comment by bbi-yggy** [comment]
As I mentioned on #195, I believe I used the vsix package.

**Comment by CharliePoole** [comment]
@bbi-yggy Yes... I thought you were checking on that. I'll give it a try with the vsix.

**Comment by bbi-yggy** [comment]
Oh, sorry, I will try and find time to investigate further. Unfortunately it's milestone week, so looking into intermittent unit test failures is unfortunately not quite at the top of my to-do list. What I really want to do is create a small repro project. Our current solution has over 40 projects in it, using a mix of .NET 3.5 and 4+, so it's a bit of a bear to experiment with.

**Comment by Andrey-Bushman** [comment]
I have the same problem. I created topic [here](http://stackoverflow.com/questions/38378313/why-nunit3testadapter-doesnt-work-correctly-for-net-3-5-sp1) before. I can provide both variants for the sample (if it can help for learning and solving this problem). Am I to do it?

**Comment by CharliePoole** [comment]
@Andrey-Bushman Your 3.5 sample project - the one that fails - would be very helpful in figuring this out.

**Comment by CharliePoole** [comment]
@OsirisTerje Do you know if VS is using a different process to run the tests, depending on the target framework?

**Comment by Andrey-Bushman** [comment]
@CharliePoole I upload this [here](https://yadi.sk/d/mI1Y1RvotJXuK). Look it, please.

**Comment by Andrey-Bushman** [comment]
@CharliePoole, I don't see "@OsirisTerje" member in this topic. If it is missprint and you asked to me, then my answer is "no".

**Comment by CharliePoole** [comment]
@Andrey-Bushman @OsirisTerje is one of our developers, but thanks for the info. :-)

The proxy I'm working with won't let me download your example due to a certificate problem.
I'll have to wait till I am connected elsewhere and see what happens.

**Comment by Andrey-Bushman** [comment]
Hm... @CharliePoole, I can send it to your email, if you want.

**Comment by CharliePoole** [comment]
@Andrey-Bushman Got it now - just a problem with the proxy in the coffee shop.

**Comment by Andrey-Bushman** [comment]
@CharliePoole What about my code sample? Did you reproduce this problem?  If 'yes', then did you find the reason of such wrong behaviour?

**Comment by CharliePoole** [comment]
I can definitely confirm the bug. I'm checking it out further.

**Comment by CharliePoole** [comment]
Somehow, the vsix package is using the 4.0 builds of Mono.Cecil.Pdb, Mono.Cecil.Mdb and Mono.Cecil.Rocks. I'm checking the nuget package now.

**Comment by CharliePoole** [comment]
I see the same issue with the nuget package for the same reason, so there's no workaround.

**Comment by CharliePoole** [comment]
I have a build that should solve the problem. Can somebody give this a try?

https://ci.appveyor.com/project/CharliePoole/nunit3-vs-adapter/build/3.5.0-CI-230-issue-205/artifacts

If it looks good I'll do a hotfix release.

**Comment by CharliePoole** [comment]
@bbi-yggy @Andrey-Bushman Have you been able to try this build?

**Comment by Andrey-Bushman** [comment]
@CharliePoole I didn't work this weekend. Now I am ready to try to use your hotfix.

1. I removed the `AcApps_solution\packages\NUnit3TestAdapter.3.4.0\NUnit3TestAdapter.3.4.0.nupkg` file.
2. I copied the `NUnit3TestAdapter.3.5.0-CI-230-issue-205.nupkg` into `AcApps_solution\packages\NUnit3TestAdapter.3.4.0\` directory and renamed it to `NUnit3TestAdapter.3.4.0.nupkg`.
3. I extracted the `NUnit3TestAdapter-3.5.0-CI-230-issue-205\bin\*` files of your `NUnit3TestAdapter-3.5.0-CI-230-issue-205.zip` archive into the `AcApps_solution\packages\NUnit3TestAdapter.3.4.0\lib\` directory with replacement of existing files.
4. I switched target .Net Framework version of my unit tests project back from 4.0 to 3.5.
5. I edited the `packages.config` file: 
```
<packages>
  <package id="NSubstitute" version="1.10.0.0" targetFramework="net40" requireReinstallation="True" />
  <package id="NUnit" version="3.4.1" targetFramework="net35" requireReinstallation="True" />
  <package id="NUnit3TestAdapter" version="3.4.0" targetFramework="net35" />
</packages>
```
instead of 

```
<packages>
  <package id="NSubstitute" version="1.10.0.0" targetFramework="net40" requireReinstallation="True" />
  <package id="NUnit" version="3.4.1" targetFramework="net40" requireReinstallation="True" />
  <package id="NUnit3TestAdapter" version="3.4.0" targetFramework="net40" />
</packages>
```

But I see this problem:

![Alt text](http://s8.hostingkartinok.com/uploads/images/2016/07/b2f0f87468396a61f0da0f92603beee5.png)


I removed this reference and added the reference to your fixed dll manually, but id didn't help me:

![Alt text](http://s8.hostingkartinok.com/uploads/images/2016/07/1ec5b05640d9ddb9c354404d87f22620.png)

What I did wrong? Or maybe your fixed version was compiled for .net 4 instead of .net 3.5?

**Comment by Andrey-Bushman** [comment]
I removed all NuGet packages and tried to install your fixed version through such way:

![Alt text](http://s8.hostingkartinok.com/uploads/images/2016/07/72958ac51888b856cf84373f476751cd.png)

But I had a problem again as you see.

**Comment by Andrey-Bushman** [comment]
@CharliePoole Yes, it works for me (for .Net 3.5 SP1).

**Comment by pvlakshm** [comment]
**>> Do you know if VS is using a different process to run the tests, depending on the target framework?**

Yes, we use a different process when executing tests targeting .NET Framework 3.5 and lower.
For e.g. in the recently released VS 2015 Update 3, we use "vstest.executionengine.clr20.exe" if the framework specified is 3.5 and lower. For everything else we use “vstest.executionengine.exe”. Note that there are x86 versions for these exe’s as well.

**Comment by CharliePoole** [comment]
@pvlakshm Thanks for the info. I made the assumption that something like that was happening. Turns out that by building the adapter using 2.0 but running tests using 4.5 so as to be able to have async tests, I managed to introduce confusion about which version got bundled into the packages.

**Comment by CharliePoole** [comment]
@Andrey-Bushman I'll put out a 3.4.1 release of the adapter shortly. I'm checking to see if there's anything else outstanding to include in it.

**Comment by samdeman22** [comment]
It seems like this is ready to be fixed soon, but if it's any help, using a fresh clone of my open source repo here https://github.com/samdeman22/OpenFM/tree/develop - before or after building the nunit test adapter will not find any tests using both Nunit 3.2.1 *or* Nunit 3.4.1. I get these error messages:

```
========== Load Playlist finished (0:00:00.0020016) ==========
------ Discover test started ------
NUnit Adapter 3.4.0.0: Test discovery starting
NUnit Adapter 3.4.0.0: Test discovery starting
Assembly contains no NUnit 3.0 tests: C:\Users\Sam\workspace\OpenFM\bin\Debug\OpenFM.dll
NUnit Adapter 3.4.0.0: Test discovery complete
Exception System.IO.FileNotFoundException, Exception converting FM.Test.Genetics.TestGene.TestCreateGene
Could not load file or assembly 'Mono.Cecil.Rocks, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
Exception System.IO.FileNotFoundException, Exception converting FM.Test.Genetics.TestGene.TestCrossForDifferentGene
Could not load file or assembly 'Mono.Cecil.Rocks, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
Exception System.IO.FileNotFoundException, Exception converting FM.Test.Genetics.TestGene.TestCrossForSameGene
Could not load file or assembly 'Mono.Cecil.Rocks, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
Exception System.IO.FileNotFoundException, Exception converting FM.Test.Genetics.TestGene.TestSelect
Could not load file or assembly 'Mono.Cecil.Rocks, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
Exception System.IO.FileNotFoundException, Exception converting FM.Test.Learning.NeuralNets.TestMLPFeedForward.TestNandGate
Could not load file or assembly 'Mono.Cecil.Rocks, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
Exception System.IO.FileNotFoundException, Exception converting FM.Test.Learning.NeuralNets.TestMLPFeedForward.TestNandHalfAdder
Could not load file or assembly 'Mono.Cecil.Rocks, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
NUnit Adapter 3.4.0.0: Test discovery complete
========== Discover test finished: 0 found (0:00:00.8888802) ==========
```

The project in question contains two sub-projects, OpenFM.Test is specifically for Nunit tests. Like I said though, you might already have this in-the-bag ;)
