### ISSUE TITLE
NUnit Adapter discovers tests, but VS test explorer doesn't show anything

### ISSUE THREAD

**Issue by jochenwezel** [nunit/nunit3-vs-adapter#208]
This is the output of the VS Tests box:
```txt
------ Ermittlungstest gestartet ------
NUnit Adapter 3.4.0.0: Test discovery starting
NUnit Adapter 3.4.0.0: Test discovery complete
========== Ermittlungstest abgeschlossen: 116 gefunden (0:00:00,2739974) ==========
```

But my test explorer shows nothing:
![image](https://cloud.githubusercontent.com/assets/3033827/17248168/da39b632-5598-11e6-8f4a-cb859dd61704.png)

Have you got any advise for me? Is it a bug in NUnit test adapter? Or in VS 2015 Update 3? Or something in my project?

I already played around with several NUnit and NUnit TestAdapter versions, but no luck :-(

System environment:
- My test project targets .Net Framework 3.5. 
  
![image](https://cloud.githubusercontent.com/assets/3033827/17248333/23e880c8-559a-11e6-8aa4-580db2c99fe8.png)
![image](https://cloud.githubusercontent.com/assets/3033827/17248343/35af200a-559a-11e6-8eeb-191400b77480.png)
![image](https://cloud.githubusercontent.com/assets/3033827/17248352/44e3c7e2-559a-11e6-8251-2963fe9b32d0.png)

- VS2015 Entrprse Update 3
- Windows 10 Pro

**Comment by rprouse** [comment]
The fact that the Test Explorer window is completely blank leads me to believe that it is Visual Studio. You should see the Run Tests and other links at the top of the window. Try closing Visual Studio and deleting the MEF cache, `%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache`

**Comment by CharliePoole** [comment]
This looks like a duplicate of #205.

@jochenwezel You can try the latest I development build from our nuget feed to verify this. The fix will be in the 3.4.1 adapter release, coming in a few days.

**Comment by jochenwezel** [comment]
In fact, it's a problem of VS2015 Update 3 with German language (only):

https://social.msdn.microsoft.com/Forums/vstudio/en-US/04be3174-4811-4f35-930a-d1766e4d8b3a/my-uni-tests-disappeared-after-updating-visual-studio?forum=vsunittest
https://connect.microsoft.com/VisualStudio/feedbackdetail/view/2979953/uni-tests-disappeared-after-updating-visual-studio-2015-update3-kb

**Comment by rprouse** [comment]
Thanks for the update.
