### ISSUE TITLE
DLLs are locked by vstest.executionengine or vstest.discoverengine

### ISSUE THREAD

**Issue by exhau** [nunit/nunit3-vs-adapter#209]
I am using nunit3.4 and vs-adapter3.4 on VS2015.
DLLs are either locked by vstest.executionengine or vstest.discoverengine. So you can't compile.

TestAdapter is supposed to unload the test dll (and its dependencies) after each execution or discovery.
This might be a bug.

**Comment by OsirisTerje** [comment]
Are you running with the Test setting "Keep Test Execution engine running" ?
![image](https://cloud.githubusercontent.com/assets/203432/17269330/b492c8da-5645-11e6-9326-6c972e8d9516.png)

If so, try to uncheck this first, that should keep the executionengine from locking.  

It is very strange that the discoveryengine is locking your dll's.  That one is mostly always running, and should not lock the dlls.  I dont see the same thing here, so, is there something special with your tests, or does this happen with any test you have, also on new projects?

**Comment by exhau** [comment]
When "Keep Test Execution Engine Running" option is uncheck, discoveryEngine still locks the dlls.

If there is anything special, my testing dll depends on several native C++ projects.

And TestDataSource is used to set up tests with different parameters.

**Comment by exhau** [comment]
Thanks for your time, I figured it out. One of the native headers includes <boost/thread/once.hpp>. I think /clr doesn't work with <thread/**> in boost or <mutex> in STL. But it's weird this time that the compiler gives no warning.

**Comment by exhau** [comment]
@OsirisTerje 
I am asking to reopen this issue.
Last time this issue was caused by a thread related header in boost.

But today i met it again because of C++ native file operation.
```
std::ofstream errorFile;
std::string errorFilePath= "dddd.txt";
errorFile.open (errorFilePath);
errorFile << "Error!" << std::endl << e.what() << std::endl;
errorFile.close();
```

If I remove these lines, dll won't be locked.
Is that reasonable?

**Comment by OsirisTerje** [comment]
Just revisiting this.  
If seems these kinds of things may happen if you mix debug and release versions, or mixes single threaded and multi threaded libraries.  Not sure at all, just found some hints here http://stackoverflow.com/questions/20374299/ofstream-operator-access-violation-error   
There is little we can do when a native called function misbehaves, so I am closing this now, as not our bug.
