### ISSUE TITLE
Not finding any UnitTest in Test-Explorer-Tab

### ISSUE THREAD

**Issue by PythonSmith** [nunit/nunit3-vs-adapter#210]
I could not find any UnitTest in the Test-Explorer-Tab.
However all tests are executed if i click test->Debug->All.
I didnt have any problem with NUnit 2.0. But NUnit 3 never worked.
I'm using Visual Studio 2015 Community Update 3(Windows 10 Pro).
Screenshot of my TestClass:
http://prntscr.com/bzqoxl
Installed packets in the Project:
http://prntscr.com/bzqp3z
Installed packets in VS:
http://prntscr.com/bzqpc4

I also tried to install the Nunit3-TestAdapter into the project but it didnt work.

**Comment by CharliePoole** [comment]
What displays in the output window when discovery takes place?

**Comment by CharliePoole** [comment]
The initial exception is in VS itself. You could try removing all test adapters you may have installed to see if it goes away and then re-install what you actually need. You could also try re-installing Visual Studio.

The output of running all tests seems to be correct, assuming that the listed assemblies don't have any tests and that there are only two in the test assembly.

**Comment by rprouse** [comment]
@PythonSmith this is a known bug in Visual Studio 2015 German edition. See #208 for links to the fix.

**Comment by rprouse** [comment]
Sorry, should have said **Update 3** of Visual Studio 2015 German edition.
