### ISSUE TITLE
nunit Test Adapter Not Compatible with TFS 2015 Build and Release Manager

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#229]
@theMickster commented on [Mon Sep 12 2016](https://github.com/nunit/nunit-vs-adapter/issues/128)

We've recently upgraded our nunit tests to 3.0 and are now seeing all test executions during the build and release process fail to execute. We are running **TFS 2015 Update 3** using the new Build and Release Manager products, and, specifically, the **Visual Studio Test** task to execute our tests. The task executes this tool  C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe and is failing to find and execute any tests regardless of whether we point to the full path of the test adapter or the packages folder. See the attached series of tests not found messages. 

Any suggestions about what can be done to get these tests to run? 
![error](https://cloud.githubusercontent.com/assets/19419392/18437944/753e5c6e-78bc-11e6-9722-95185dbd6b60.png)

---

@CharliePoole commented on [Mon Sep 12 2016](https://github.com/nunit/nunit-vs-adapter/issues/128#issuecomment-246385185)

I see from your console output that you are using the NUnit 3 Test Adapter rather than the NUnit Test Adapter, so I'm moving this issue there. Unfortunately, the names are a bit close and VS refers to both of them as the "NUnit Adapter".

**Comment by CharliePoole** [comment]
The adapter is being found and executed, since it is producing messages. One message indicates that a `.pdb` file is not found. I'm not clear why this is happening but it appears that the dll can't be loaded without the pdb present. Would one of your execution options explain that?

**Comment by theMickster** [comment]
First, question: what's the correct nuget package that TFS and the test runner/test adapter should be referencing? 

Second question, the console specifically says that if the test is nunit that the .pdb can be ignored? We build and deploy in release and don't normally carry around .pdb files unless necessary. Does nunit require these?

**Comment by OsirisTerje** [comment]
1.  You have upgraded your tests to 3.0, so the correct adapter is the 3.4.1 adapter, https://www.nuget.org/packages/NUnit3TestAdapter/  
2. No

**Comment by OsirisTerje** [comment]
Are you targeting and running AnyCPU, x86 or x64 ?

**Comment by CharliePoole** [comment]
The message from nunit is our interpretation of a file not found error. It just happens that it lists a pdb rather than an assembly.

The message indicates that you can ignore the failure of it **isn't** an NUnit test. That's because sometimes the adapter is passed non-test assemblies. That's not the case here.

You need to ascertain why your assembly requires the pdb to be present. Consider trying to run the tests without other options like coverage in order to see what happens.

**Comment by theMickster** [comment]
Updating the project configuration to include debug symbols in the building of the test project appeared to give vstest.console.exe everything that it needed to run the tests. Feel free to close this issue.

**Comment by ppejovic** [comment]
I was experiencing the exact same problem because the default TF build template includes `/p:DebugType=None` in the _MSBuild Arguments_ of the _Visual Studio Build_ build step. Removing this got the tests working in TF Build. 

Disabling pbd generation in the project properties also prevents the tests being discovered in the Visual Studio. This was for a very basic test project (class library type) I created to test NUnit 3.0. The test project has no dependencies aside from NUnit and NUnit3TestAdapter. It doesn't seem right that pbd's are required for the test discovery?

**Comment by ppejovic** [comment]
I believe the problem code is [here](https://github.com/nunit/nunit3-vs-adapter/blob/8a9b8a38b7f808a4a78598542ddaf557950c6790/src/NUnitTestAdapter/NavigationDataProvider.cs#L79)

**NavigationDataProvider.cs#L79**

`var readerParameters = new ReaderParameters() { ReadSymbols = true };`

The [docs ](https://github.com/jbevain/cecil/wiki/Debug-symbols) from Cecil state:

> From an API standpoint, there are two ways of interacting with debug symbols. The easiest is to simply pass `True` to ReaderParameters.ReadSymbols or WriterParameters.WriteSymbols. Cecil will try to load the debug store support assembly depending on the runtime (pdb on .net, mdb on Mono) and read and write the appropriate symbols.
