### ISSUE TITLE
vNext Build: Tests Pass, but Test Run Failing

### ISSUE THREAD

**Issue by alpacamybags118** [nunit/nunit3-vs-adapter#233]
Hi all,

I'm running into some strange errors while running Nunit tests during a vNext build. I reached out on the Nunit Google Groups page, and tried the suggested fix of referencing the pre-release test adapter package from https://www.myget.org/F/nunit/api/v2, but that did not work.

There are two specific errors that are happening, which differ depending on the solution that is being built. In both cases, all the tests are passing locally on the dev's machine with no errors being thrown. On the build boxes, the tests are fully passing as well, but the one of the two errors is thrown at the end and the test run overall fails.

1st is an App Domain error. Here is the entry in the build log:

```
2016-09-26T15:17:54.1947564Z ##[error]Error: Exception NUnit.Engine.NUnitEngineException, Exception thrown executing tests
2016-09-26T15:17:54.1947564Z ##[error] 
2016-09-26T15:17:54.1947564Z ##[error]Error: Exception encountered unloading AppDomain
2016-09-26T15:17:54.1947564Z ##[error]
```

I looked up this error and saw that people were pointing towards threading issues. I worked with the dev to check their code and they aren't doing any threading during any of their tests.

The 2nd error has literally no description. Here is the entry in the build log: 

```
2016-09-29T13:23:39.9812364Z ##[error]Error: --------------------------------------------------------------------------------

2016-09-29T13:23:39.9812364Z ##[error]
```

Obviously, there is really no place to start with this error. The only lead I have is that it is happening with only 1 of their test dlls.

I've isolated the builds to run on a single build box for debugging purposes, but all the build boxes we use produce the same result. I've checked the configuration on the boxes, and as far as I can tell, everything is configured fine. There are many other applications that build on these boxes and use Nunit tests and they all run without errors, but I won't entirely rule out a configuration issue.

As a last bit of context, these tests are being executed during a vNext Build which runs on an onprem server running Windows Server 2012 R2 with Team Foundation Server 2015 Update 3 and Visual Studio 2015 Update 3. The projects are using Nunit 3.4.1 and Nunit3TestAdapter 3.4.1

Let me know if any additional information is needed. Any help would be appreciated!

Thanks,

Kyle

**Comment by CharliePoole** [comment]
That's a very thorough report! One more bit of info would help: when you run on the dev machine, are you running in the same way as on the build server? That is, assuming the build server uses vstest-console.exe, have you tried doing the same on the dev machine or are you using either the IDE or nunit-console. I have often found it helpful to have a script available for devs to run a build using the same tools, as much as possible anyway, as are used on the server.

**Comment by alpacamybags118** [comment]
Right now, they are just running the tests in the IDE. The build script is using vstest-console to run the tests. I will reach out to them and have them try running it via vstest-console on their local build output and report back.

**Comment by alpacamybags118** [comment]
I was able to get one of the devs to run the tests for one of the applications from their local build output. On the build server, it is giving the ------- error. When running it locally via vstest console, it is also giving the same ------- error while passing all the tests. We tried having vstest console write the results to a trx file, but there was no additional information in the result file on the error.

**Comment by CharliePoole** [comment]
Thanks, that's useful information.

**Comment by alpacamybags118** [comment]
I was wondering if there is any update on this. The engineers I'm working with have been asking about it, so I wanted to see if there is any information I can give them as an update. Let me know if you need anything else from me to move forward.

**Comment by CharliePoole** [comment]
Right now we're in the midst of the 3.5 release, so I haven't completed the triage of the issue, but I'm suspecting that it's really another instance of issue #204. That could result either from your tests writing to stderror, by NUnit itself doing so or by the adapter writing to the error log. 

Status of the release process is that the framework is out. We are working on the engine and console next and the VS adapter last.

**Comment by alpacamybags118** [comment]
Awesome, thank you. I'll let the team know.

**Comment by OsirisTerje** [comment]
@alpacamybags118 Hi!  Can you check please if this issue now is fixed  with the latest nunit and adapter ?

**Comment by alpacamybags118** [comment]
@OsirisTerje Yes, it issue has been resolved with the latest version. Thank you guys so much for getting a fix in!
