### ISSUE TITLE
[MS] Allow to change SynchronousEvents and DomainUsage settings

### ISSUE THREAD

**Issue by drognanar** [nunit/nunit3-vs-adapter#234]
At the moment there is no way of changing the SynchronousEvents and DomainUsage settings passed to NUnit as they are hardcoded into the adapter.
Perhaps they could be specified using the DiscoveryContext's RunSettings xml together with other settings.

**Comment by CharliePoole** [comment]
Could you specify a bit more of what you would like to accomplish? Simply providing a setting isn't going to do anything unless we add code to the adapter to deal with them.

Synchronous events is a somewhat obscure setting with little real use. We could easily recognize the setting and turn it on but I'm not sure what impact it would have within the VS environment. Perhaps you could elaborate?

DomainUsage is a much larger change. The code of the adapter doesn't use the engine to select a way of running the tests, it simply uses a separate test domain per assembly for the purpose. That's the equivalent of specifying `domain=Multiple`. What setting would you like to use?

**Comment by drognanar** [comment]
What I'm trying to accomplish is to make the adapter run tests one at a time and execute an `Action` after each test runs.

I tried to execute the `Action` when `TestStartedEvent` and `TestFinishedEnded` events are triggered, however, its only when events are synchronous that other tests do not keep on running while the `Action` is executing.

Regarding the app domain setting the value I wanted to set was `"None"` since it allows the `Action` to execute within the same `AppDomain` as the test.

**Comment by CharliePoole** [comment]
If you have not enabled your assembly for parallel execution, test cases run one at a time. However, the execution of OneTimeSetUp and OneTimeTearDown methods can be scattered around in a way that is sometimes unexpected, although they are guaranteed to run, respectively, before and after the tests that they control. You can avoid this mixing by setting NumberOrWorkers to zero in the `.runsettings` file.

I'm not clear on how you are triggering your `Actions` since we don't provide any hook for that in the adapter.

As far as I have seen in past releases, it's necessary for the test to run in a separate AppDomain in order for it to be loaded correctly. A solution may have many test assemblies that reside in different output directories. We create an AppDomain that specifies the output directory as it's AppBase in order to load the tests. When running under the IDE, the AppBase for the initial domain is somewhere inside of the VS installation.

**Comment by drognanar** [comment]
I use the messages generated by the adapter as a hook that triggers an `EventHandler` when an event gets dispatched.
For example `TestPlatform` has a `TestCaseEnd` event, which gets invoked from the `NUnitEventListener`, which gets invoked from the test event dispatcher.
When messages are synchronous all of this gets executed on a single thread and results in the following stack trace:

```
Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.EventHandlers.TestCaseEventsHandler.SendTestCaseEnd(Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase testCase, Microsoft.VisualStudio.TestPlatform.ObjectModel.TestOutcome outcome)	Unknown
Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Adapter.TestExecutionRecorder.RecordEnd(Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase testCase, Microsoft.VisualStudio.TestPlatform.ObjectModel.TestOutcome outcome)	Unknown
NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(System.Xml.XmlNode resultNode) Line 117	C#
NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(string report) Line 55	C#
NUnit.Engine.Runners.TestEventDispatcher.OnTestEvent(string report)	Unknown
NUnit.Engine.RunTestsCallbackHandler.ReportProgress(string state)	Unknown
NUnit.Engine.CallbackHandler.RaiseCallbackEvent(string eventArgument)	Unknown
NUnit.Framework.Internal.TestProgressReporter.TestFinished(NUnit.Framework.Interfaces.ITestResult result)	Unknown
NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete()	Unknown
NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()	Unknown
NUnit.Framework.Internal.Execution.WorkItem.RunTest()	Unknown
NUnit.Framework.Internal.Execution.WorkItem.Execute()	Unknown
NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.Dispatch(NUnit.Framework.Internal.Execution.WorkItem work)	Unknown
NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren()	Unknown
```

As a result by attaching an `EventHandler` for the `TestPlatform`'s `TestCaseEnd` event I can execute an `Action` that gets called whenever a test case ends. It also means that another test will not start until the handler completes.

On the other hand, if the messages are not synchronous then the test finished event is queued to a message pump, and the `OnTestEvent` method will execute on a separate thread. As a result another test may start executing before the `TestCaseEnd` event is triggered and the event handler executes (even if the tests run one at a time).

**Comment by CharliePoole** [comment]
@droganar I just got a note that clued me in to who you are and what you are working on. Your request made no sense coming from a direct user of the adapter, which is the reason for my questions. Let me take another look at what you are asking and get back to you.

**Comment by CharliePoole** [comment]
I've reviewed this further with an eye on what I understand you are trying to do. Tentative conclusions, which we can talk about later this week:

1. Synchronous Event Handling
    1.1 The feature is there and we can make it accessible in runsettings.
    1.2 It will degrade performance if your Action takes any time at all, so you should queue any significant work you are doing for another thread.
    1.3 It will degrade performance if __any other__ listener is active that takes significant time to process. This is a potential problem because don't normally have to worry about this since they are called on a separate thread.
    1.4 Any test that changes the thread context has the potential of crashing the application if we use remoting at all. That's actually the main reason we use a different thread for sending events.
    1.5 The setting is passed on to the framework. Consequently, it will only affect NUnit 3 tests. NUnit 2 (or any third-party driver) won't recognize it.

2. Use of DomainUsage=None
    2.1 The feature is there and we can make it accessible in runsettings
    2.2 Tests won't run with this setting unless the adapter is guaranteed that both the test assembly and nunit.framework.dll are located in the AppBase. This seems impossible to guarantee, since a solution may contain multiple test assemblies located in different output directories.

If you are in a position to consider other ways of accomplishing this, let's talk about it this week.

**Comment by ManishJayaswal** [comment]
#235 is an attempt to fix this.
