### ISSUE TITLE
Adapter runs other tests in VS2015 for .Net Core

### ISSUE THREAD

**Issue by sm-g** [nunit/nunit3-vs-adapter#237]
Sometimes running particular test ("Run Selected tests") executes others (in same assembly). Restart VS fixes this.

Even worse, two tests under one line: [screenshot](http://i.imgur.com/NoUYRFA.png). Second is always from other test aseembly.

project.json:
```
{
  "dependencies": { 

    "NUnit": "3.5.0",
    "NUnitLite": "3.5.0",
    "dotnet-test-nunit": "3.4.0-alpha-2"
  },

  "frameworks": {
    "net461": {
    }
  },

  "testRunner": "nunit",

  "buildOptions": {
    "emitEntryPoint": true
  }
}
```

**Comment by CharliePoole** [comment]
The nunit3-vs-adapter doesn't support .NET Core. If you are actually using the dotnet-test-nunit program, I can move your issue there.

**Comment by rprouse** [comment]
I am moving this to the `dotnet-test-nunit` repo, the `project.json` indicates he is using that runner.

**Comment by CharliePoole** [comment]
I figured it meant he __should__ be using that runner, but I thought he might be using the adapter, since he filed an adapter issue. Isn't it possible to be using the wrong adapter in this situation?

**Comment by rprouse** [comment]
@CharliePoole I don't think it is possible to be using the wrong adapter. I've tested with a solution with a mix of .NET Core and Full Framework test projects and `dotnet-test-nunit` installed via NuGet and the VSIX installed both via NuGet and through extensions. Each adapter only picks up the tests it understands.

He is targeting 4.6.1 though, I should test that with the VSIX although I have a project with the same setup and it works fine and only runs under `dotnet-test-nunit`.

This is also similar to other issues we are seeing with `dotnet-test-nunit` which I am unsure if they are tooling issues or issues with my code.

**Comment by CharliePoole** [comment]
@rprouse I don't think I'm detecting .NET Core and declining to load the tests in the adapter. That may mean that VS never passes it to me, since it's a different interface anyway. We should check this out at some point.
