### ISSUE TITLE
System.MissingMethodException Thrown when Test Adapter does Discovery

### ISSUE THREAD

**Issue by BgRva** [nunit/nunit3-vs-adapter#24]
I have a solution in which I am using NUnit 3.0 b2 and have installed the NUnit3 Test Adapter.  The solution builds just fine.  When I open the test explorer a series of System.MissingMethodException are thrown from each of the test projects.  While all projects started out with the 4.6 framework, I added a test project using the 4.5 framework when this started but with the same results.  I've tried uninstalling/reinstalling both the adapter and nunit from the projects.  Despite what the output below shows, the missing dependent assemblies are in the respective Debug folders, but the adapter is unable to pick them up.  Included below are the results from the Output tab for Build and Tests.

Once this error occurs, the nunit.framework.dll cannot be deleted from the Debug folder of the test projects and warnings indicate that "Access is denied to the path".  When I uninstalled the Test Adapter, the locking of the nunit.framework.dll no longer occurred.

My environment:

Win7 x64
VS2015 Community RC version 14.0.22823.1 D14REL
NUnit: "3.0.0-beta-2"

******************** OUTPUT TAB (Show output from: Build) ********************
All packages are already installed and there is nothing to restore.
NuGet package restore finished.
1>------ Rebuild All started: Project: XGraph.Scenarios, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: XGraph, Configuration: Debug Any CPU ------
4>------ Rebuild All started: Project: XGraph.Tests, Configuration: Debug Any CPU ------
4>  XGraph.Tests -> D:\_dev\XGraph\XGraph.Tests\bin\Debug\XGraph.Tests.dll
2>  ClassLibrary1 -> D:\_dev\XGraph\ClassLibrary1\bin\Debug\ClassLibrary1.dll
3>  XGraph -> D:\_dev\XGraph\XGraph\bin\Debug\XGraph.dll
5>------ Rebuild All started: Project: XGraph.Tests.Support, Configuration: Debug Any CPU ------
1>  XGraph.Scenarios -> D:\_dev\XGraph\XGraph.Scenarios\bin\Debug\XGraph.Scenarios.dll
6>------ Rebuild All started: Project: ClassLibrary1.Tests, Configuration: Debug Any CPU ------
5>  XGraph.Tests.Support -> D:\_dev\XGraph\XGraph.Tests.Support\bin\Debug\XGraph.Tests.Support.dll
7>------ Rebuild All started: Project: XGraph.Scenarios.Tests, Configuration: Debug Any CPU ------
6>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4603,5): warning MSB3061: Unable to delete file "D:\_dev\XGraph\ClassLibrary1.Tests\bin\Debug\nunit.framework.dll". Access to the path 'D:\_dev\XGraph\ClassLibrary1.Tests\bin\Debug\nunit.framework.dll' is denied.
6>  ClassLibrary1.Tests -> D:\_dev\XGraph\ClassLibrary1.Tests\bin\Debug\ClassLibrary1.Tests.dll
7>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4603,5): warning MSB3061: Unable to delete file "D:\_dev\XGraph\XGraph.Scenarios.Tests\bin\Debug\nunit.framework.dll". Access to the path 'D:\_dev\XGraph\XGraph.Scenarios.Tests\bin\Debug\nunit.framework.dll' is denied.
7>  XGraph.Scenarios.Tests -> D:\_dev\XGraph\XGraph.Scenarios.Tests\bin\Debug\XGraph.Scenarios.Tests.dll
========== Rebuild All: 7 succeeded, 0 failed, 0 skipped ==========

******************** OUTPUT TAB (Show output from: Test) ********************
------ Load Playlist started ------
========== Load Playlist finished (0:00:00.0020001) ==========
------ Discover test started ------
NUnit Adapter 3.0.0.0 discovering tests is started
Exception System.MissingMethodException, Exception thrown discovering tests in D:\_dev\XGraph\ClassLibrary1.Tests\bin\Debug\ClassLibrary1.Tests.dll
NUnit Adapter 3.0.0.0 discovering test is finished
NUnit Adapter 3.0.0.0 discovering tests is started
Dependent Assembly nunit.framework of D:\_dev\XGraph\ClassLibrary1\bin\Debug\ClassLibrary1.dll not found. Can be ignored if not a NUnit project.
NUnit Adapter 3.0.0.0 discovering test is finished
NUnit Adapter 3.0.0.0 discovering tests is started
Exception System.MissingMethodException, Exception thrown discovering tests in D:\_dev\XGraph\XGraph.Scenarios.Tests\bin\Debug\XGraph.Scenarios.Tests.dll
NUnit Adapter 3.0.0.0 discovering test is finished
NUnit Adapter 3.0.0.0 discovering tests is started
Dependent Assembly nunit.framework of D:\_dev\XGraph\XGraph.Scenarios\bin\Debug\XGraph.Scenarios.dll not found. Can be ignored if not a NUnit project.
NUnit Adapter 3.0.0.0 discovering test is finished
NUnit Adapter 3.0.0.0 discovering tests is started
Dependent Assembly nunit.framework of D:\_dev\XGraph\XGraph.Tests.Support\bin\Debug\XGraph.Tests.Support.dll not found. Can be ignored if not a NUnit project.
NUnit Adapter 3.0.0.0 discovering test is finished
NUnit Adapter 3.0.0.0 discovering tests is started
Dependent Assembly nunit.framework of D:\_dev\XGraph\XGraph.Tests\bin\Debug\XGraph.Tests.dll not found. Can be ignored if not a NUnit project.
NUnit Adapter 3.0.0.0 discovering test is finished
NUnit Adapter 3.0.0.0 discovering tests is started
Dependent Assembly nunit.framework of D:\_dev\XGraph\XGraph\bin\Debug\XGraph.dll not found. Can be ignored if not a NUnit project.
NUnit Adapter 3.0.0.0 discovering test is finished
========== Discover test finished: 0 found (0:00:01.364078) ==========

**Comment by CharliePoole** [comment]
As mentioned in the announcement, the NUnit framework API has changed in the beta 2 release. The current release of the test adapter uses that API and therefore can't load tests compiled against beta-2. We are working to get a new adapter release out as quickly as possible. Meanwhile, you can only run beta-2 tests using the console runner.

**Comment by CharliePoole** [comment]
The second CTP may now be used to run beta-2 tests under the adapter.
