### ISSUE TITLE
Retrieving a random sample of data from TestCaseSource in NUnit 3.0 attribute doesn't work?

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#240]
@nadvolod commented on [Wed Oct 19 2016](https://github.com/nunit/nunit/issues/1852)

I'm having a strange issue utilizing this combination of technologies: 

 - Nunit(3.4.1.0)
 - NUnit 3 Visual Studio Test Adapter
 - TestCaseSource attribute

My test uses the attribute like this:

            [Test, TestCaseSource(nameof(GetSmallSampleSizeOfTestDataForScratchwork))]
        public void TestMe(string accessionNumber, string loginId)
        {
            var studentAssessmentPage = OpenAdminResetPageAndGoToBookletLocation(accessionNumber, loginId);
            studentAssessmentPage.OpenScratchworkTool();
            Assert.IsTrue(studentAssessmentPage.IsScratchworkToolOpen(), "The scratchwork tool did not open succesfully.");
        }

The implementation of GetSmallSampleSizeOfTestDataForScratchwork() doesn't run any tests whenever I try to execute the test. Even though in debug mode it works as expected.

    protected static IEnumerable<string[]> GetSmallSampleSizeOfTestDataForScratchwork()
        {
            var filePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            filePath = Path.GetFullPath(filePath + @"\TestData\TestData.csv");

            using (var sr = new StreamReader(filePath))
            {
                var reader = new CsvReader(sr);
                IEnumerable<CsvRecord> records = reader.GetRecords<CsvRecord>().OrderBy(x => Guid.NewGuid());

                foreach (var record in records.Take(10))
                {
                    string column1 = record.AccessionNumber;
                    string column2 = record.LoginId;
                    yield return new[] { column1, column2 };
                }
            }
        }

However, this implementation works just fine and runs all of the tests without a problem.

            protected static IEnumerable<string[]> GetAllTestDataForScratchwork()
        {
            var filePath = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            filePath = Path.GetFullPath(filePath + @"\TestData\TestData.csv");

            using (var sr = new StreamReader(filePath))
            {
                var reader = new CsvReader(sr);
                IEnumerable<CsvRecord> records = reader.GetRecords<CsvRecord>();

                foreach (var record in records)
                {
                    string column1 = record.AccessionNumber;
                    string column2 = record.LoginId;
                    yield return new[] { column1, column2 };
                }
            }
        }

The only difference between these 2 methods are that 1 returns a random subset of data and the other returns all of the data. 

**Therefore, why is it that GetAllTestDataForScratchwork() works just fine when I execute the tests and GetSmallSampleSizeOfTestDataForScratchwork() doesn't run a single test?**

---

@CharliePoole commented on [Wed Oct 19 2016](https://github.com/nunit/nunit/issues/1852#issuecomment-254867879)

This is a well-known issue with the Visual Studio adapter. I'm moving it to that repo where the info will be helpful to others and will comment further there.

**Comment by CharliePoole** [comment]
As part of the architecture of the VS Test Explorer, the adapter is called twice, in two different processes, to load the tests. The first time is for initial discovery and the second time for execution. No information is available at execution time from the initial discovery unless we save it somewhere. 

Upon initial discovery, your test case data source makes a random selection of 10 cases, generating guids for them. At execution time, we are forced by the VS architecture to re-discover the tests and your source is called again. A _different_ set of 10 cases is found. VS notes the first set of 10 as not executed and the second set as unknown tests. If you are using the IDE, you will see the first set in the explorer window as not run and the second set will cause error messages to appear in the output window.

As you may imagine, this architecture wrecks havoc with random parameters. To resolve the problem, we save the initial random seed in a file the first time and re-use it the second time. This repeatable seed is also available for your use if you get random values from the NUnit TestContext. However, any direct use of Random - or indirect use in the case of the Take(10) call - is not repeatable the second time.

I'm marking this as "Wont Fix" because it could theoretically be fixed by setting up some sort of repository where the results of the discovery were saved for use at execution time, eliminating the need to run it a second time. We have already evaluated this and determined it's more effort than we want to put into the adapter. NUnit itself is designed to do all it's discovery and execution in one execution and passing info between these two executions is of no benefit to the engine itself or to any of our other runners. FWIW, I believe that the Test Explorer architecture is designed to compensate for some weaknesses in MsTest, which won't allow a test assembly to be changed while it is loaded.

**Comment by CharliePoole** [comment]
@nadvolod Hopefully, you can use the info in the above comment to figure out a workaround that uses TestContext to generate your random selection. It won't be as clean as using `Take(10)` but if you get the random values to select from NUnit, the test should be made to work. Although closed, you can still post questions here and I'll try to help.

**Comment by nadvolod** [comment]
@CharliePoole thanks for that recommendation and I appreciate the explanation! I'm trying to think how I would do it, but not coming up with any good ideas. Do you have a suggestion of a starting point?

**Comment by CharliePoole** [comment]
Looking more closely, it all depends on your random guid. TestContext.Random won't give you a random guid, but it doesn't appear that you actually need a guid, just a random value to use in sorting.

You could use `TestContext.Random.NextULong()` to generate an unsigned long for use in the sort. There is a small enough chance of duplication in a small sample that it probably isn't a problem.

Alternatively, it may be more efficient to avoid the sort and simply generate a set of ints to match the index of the items to be selected. Here's some pseudo-code that might help....

```C#
   var selected = new int[10];
   int count = 0;
   while (count < 10)
   {
       for(;;)
       {
           int index = TestContext.Random.NextInt(0, total_number_of_records)
           if index was not already selected
           {
               selected[count++] = index;
               break;
           }
       }
   }

   // Here, selected contains the indices of the 10 selected records
```

Interestingly, this shows up a few gaps in what we can do using TestContext.Random. Retrieval of a number of random values without duplicates might be useful as would random selection from a collection.

**Comment by dstj** [comment]
I know that this is flagged as `wontfix` (and #15, #97, #331 are closed), but it's quite an annoying a bug!

I have a test that checks that all public Controller methods have the `[Authorize]` attribute. It uses reflection to discover the method to test. It won't run in Visual Studio. :(

**Comment by CharliePoole** [comment]
Not Clear how your problem relates to random data.

I certainly have tests that use reflection to check attributes on methods.

**Comment by dstj** [comment]
Woops! You're right, I had 6 tabs open and wrote in the wrong one. My bad! I meant to write in #97... But your answer still puzzles me. I run more that an open a new issue.

**Comment by eFse7en** [comment]
I had a similar problem when test was driven by random 10 entity ids found in database.
In order to run the same test locally multiple times I had to cleanup the solution before each run (or in later VS version cleanup test results) to have the same test discovery result as an execution.

But I've found a thread safe workaround using `Range` attribute combined with `Lazy` data provider below:

```csharp
private const int RECENT_ASSET_MAX_COUNT = 10;
private static readonly Lazy<List<long>> RECENT_ASSET_IDS = new(() => FindRecentAssetIds(take: RECENT_ASSET_MAX_COUNT));

[Test]
public void Recent_assets_Should_have_expected_data([Range(0, RECENT_ASSET_MAX_COUNT - 1)] int index)
{
    IgnoreTestIfListContainsLessItemsThanSelectedIndex(RECENT_ASSET_IDS, index); //in case less than RECENT_ASSET_MAX_COUNT items are found by "FindRecentAssetIds"

    //Given 
    var assetId = RECENT_ASSET_IDS.Value[index];

    //Then
    ShouldGetExpectedDataForAsset(assetId);
}

//in AbstractTest
protected static void IgnoreTestIfListContainsLessItemsThanSelectedIndex<TElement>(Lazy<List<TElement>> lazyList, int index)
{
    if (lazyList.Value.Count <= index)
    {
        throw new NUnit.Framework.IgnoreException($"Only {lazyList.Value.Count} items were found");
    }
}
```
Test discovery only uses Range attribute, so you'll see following test cases on the list, and `FindRecentAssetIds` method is guaranteed by `Lazy` to be executed max once.
```
Recent_assets_Should_have_expected_data(0)
Recent_assets_Should_have_expected_data(1)
Recent_assets_Should_have_expected_data(2)
Recent_assets_Should_have_expected_data(3)
Recent_assets_Should_have_expected_data(4)
Recent_assets_Should_have_expected_data(5)
Recent_assets_Should_have_expected_data(6)
Recent_assets_Should_have_expected_data(7)
Recent_assets_Should_have_expected_data(8)
Recent_assets_Should_have_expected_data(9)
```
