### ISSUE TITLE
Adapter fails to discover tests

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#248]
@brunoss commented on [Mon Oct 24 2016](https://github.com/nunit/nunit-vs-adapter/issues/131)

The following messages appears on `output` Window after trying to rebuild my `Nunit` test project

```
------ Discover test started ------
NUnit Adapter 3.5.0.0: Test discovery starting
Error: Unable to get runner for this assembly. Check installation, including any extensions.
RemotingException: Found two different objects associated with the same URI, '/ad6409a5_eed6_4df5_b143_6aea6249e17e/TestAgency'.
An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Found two different objects associated with the same URI, '/ad6409a5_eed6_4df5_b143_6aea6249e17e/TestAgency'.
========== Discover test finished: 0 found (0:00:00.4420455) ==========
```

Interestingly the last change that I made to my visual studio is that I put a product key on it. Before that the tests were able to be found.

This happened for me with Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Running as administrator

.Net Framework 4.5.2

NUnit version 3.5.0

I am using the visual studio extension test adapter 3.5.0

I already tried to reinstall the adapter after putting my product key.

The following message also appears at the very end of test discovery, if I rebuild my solution (which has tests with other testing frameworks)

`An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Format of the executable (.exe) or library (.dll) is invalid.`

---

@brunoss commented on [Mon Oct 24 2016](https://github.com/nunit/nunit-vs-adapter/issues/131#issuecomment-255699574)

The test discovery was successful after I changed the test to prefer 64 bits

Test -> Test Settings -> Default processor architecture -> x64

I'm going to leave this open if you want to pursue why it didn't work for x86

---

@CharliePoole commented on [Mon Oct 24 2016](https://github.com/nunit/nunit-vs-adapter/issues/131#issuecomment-255743373)

Since this is about the NUnit 3 adapter, I'm moving the issue to that project.

**Comment by CharliePoole** [comment]
The remoting error indicates that two instances of the NUnit TestAgency were running on your system. This could happen if you were running tests using two copies of NUnit at the same time or were running the tests of NUnit itself. It should not happen using the VS adapter, since it's embedded copy of the NUnit engine does not use a TestAgency.

Does any of this ring a bell?

**Comment by brunoss** [comment]
Not at all since I was only using the Vs adapter and I do not have the Adapter nuget package installed.

**Comment by anttirt** [comment]
Hi, I just ran into this issue with our mixed solution containing both managed and native projects. The issue seems to be that `GetRunner` for native images throws `BadImageFormatException`, for which there is a catch clause but because the `GetRunner` call is outside the `try-catch` the exception aborts the discovery process. Later discovery runs result in the `RemotingException`; I assume that when the exception escapes, something is not properly disposed of which causes the duplicate URI problem.

I built a VSIX of the current master + the following patch which works for me.

```patch
From 0f35b4b3065783391d2734c28a18a079143c1293 Mon Sep 17 00:00:00 2001
From: Antti Tuppurainen <antti.tuppurainen@rovio.com>
Date: Mon, 24 Oct 2016 16:43:14 +0300
Subject: [PATCH] Properly handle BadImageFormatException when discovering
 tests

---
 src/NUnitTestAdapter/NUnit3TestDiscoverer.cs | 15 +++++++++------
 1 file changed, 9 insertions(+), 6 deletions(-)

diff --git a/src/NUnitTestAdapter/NUnit3TestDiscoverer.cs b/src/NUnitTestAdapter/NUnit3TestDiscoverer.cs
index 990c24f..d9e3fac 100644
--- a/src/NUnitTestAdapter/NUnit3TestDiscoverer.cs
+++ b/src/NUnitTestAdapter/NUnit3TestDiscoverer.cs
@@ -49,10 +49,10 @@ namespace NUnit.VisualStudio.TestAdapter
 
                 ITestRunner runner = null;
 
-                runner = GetRunnerFor(sourceAssembly);
-
                 try
                 {
+                    runner = GetRunnerFor(sourceAssembly);
+
                     XmlNode topNode = runner.Explore(TestFilter.Empty);
 
                     // Currently, this will always be the case but it might change
@@ -105,11 +105,14 @@ namespace NUnit.VisualStudio.TestAdapter
                 }
                 finally
                 {
-                    if (runner.IsTestRunning)
-                        runner.StopRun(true);
+                    if(runner != null)
+                    {
+                        if (runner.IsTestRunning)
+                            runner.StopRun(true);
 
-                    runner.Unload();
-                    runner.Dispose();
+                        runner.Unload();
+                        runner.Dispose();
+                    }
                 }
             }
 
-- 
2.6.1.windows.1
```

**Comment by GiottoVerducci** [comment]
I have the exact same issue (same message etc.) with one (large) solution.
I have another small solution with only one project and one unit test project and I don't have the issue.
Last week, both were working fine.
Microsoft Visual Studio Enterprise 2015 Version 14.0.25431.01 Update 3

**Comment by CharliePoole** [comment]
@anttirt @GiottoVerducci 
What happens if you downgrade your copy of the adapter to version 3.4.1?

**Comment by brunoss** [comment]
@CharliePoole  Actually I had that problem on a 3.4.(unknown minor version) and then upgraded to see if it solved anything.

**Comment by GiottoVerducci** [comment]
@CharliePoole : I couldn't install the older version. No vsix is available for older versions which is a shame, and the `Install-Package NUnit3TestAdapter -Version 3.4.1` command doesn't work.

**Comment by brunoss** [comment]
@GiottoVerducci  I think you should be able to use the adapter as nuget package instead of VS extension

@CharliePoole I just tried now running the adapter as nuget package. Test discovery was not successful for 3.5.0 but it was after downgrading to 3.4.1

**Comment by CharliePoole** [comment]
@GiottoVerducci vsix files for older versions can be downloaded from the release on GitHub for local install.

**Comment by bcachet** [comment]
Hello,
Installing version 3.4.1 Extension (and ensuring Automatic Update is not activated for NUnit Adapter extension) fix this issue.

**Comment by CharliePoole** [comment]
Well, that's a bummer! Will try to fix and get out an update as soon as possible.

**Comment by CharliePoole** [comment]
@anttirt Thanks for the patch, which I used. I've been digging and I can't figure out what changed or even why it worked before!

**Comment by gedeh** [comment]
hopefully this released soon. got similar issue just today:
`Error: Unable to get runner for this assembly. Check installation, including any extensions.
RemotingException: Found two different objects associated with the same URI, '/dca3adc2_5044_43ca_9d43_1fa0cd65cc2e/TestAgency'.
An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Found two different objects associated with the same URI, '/dca3adc2_5044_43ca_9d43_1fa0cd65cc2e/TestAgency'.`

**Comment by CharliePoole** [comment]
Should be out tomorrow

**Comment by gedeh** [comment]
Thanks a lot!
