### ISSUE TITLE
How you debug the adapter?

### ISSUE THREAD

**Issue by GeertVL** [nunit/nunit3-vs-adapter#250]
Could somebody explain to me how I can debug the adapter? 
So I could detect and fix the bugs I encounter myself and help out a little bit with the open issues.

Sorry if it is already posted somewhere. I could not find it.

**Comment by CharliePoole** [comment]
Good idea! I'm moving this to our docs repo.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/docs #133](https://github.com/nunit/docs/issues/133) via [**ZenHub**](https://www.zenhub.com/)
