### ISSUE TITLE
Warnings about $RANDOM_SEED$ during build

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#253]
@waldimen commented on [Fri Oct 28 2016](https://github.com/nunit/docs/issues/134)

I am using Nunit adapter with during TFS build.
In the build log file I got warnings for each assembly:

Exception System.IO.FileNotFoundException, Unable to restore random seed.
Could not find file  [DLLDIR]\$RANDOM_SEED$
[DLLDIR] is path to directory with TestAssembly.

Is it possible to disable the warnings ?
---

@CharliePoole commented on [Fri Oct 28 2016](https://github.com/nunit/docs/issues/134#issuecomment-256986343)

We don't want to disable that, but fix it! The $RANDOM_SEED$ file should be created by the adapter in discovery. If it isn't, then test cases using random parameter values won't work correctly. Is it possible that the test assembly directory is write-protected?

This is a potential adapter bug, so I'm moving the issue to that repo.

**Comment by OsirisTerje** [comment]
The directory it tries to write to is the binary output directory, so we *know* it is writeable.  I see this:
![image](https://cloud.githubusercontent.com/assets/203432/19832903/a5ba95ee-9e30-11e6-9a68-88e606eeaa76.png)
which is the same directory as all other nbianries are written on the TFS build machine.

**Comment by CharliePoole** [comment]
The fact that it isn't there is clear. The issue is why didn't it get written? It should be written in at the start of discovery, unless we are somehow bypassing that initialization on TFS.

**Comment by OsirisTerje** [comment]
I can't see any traces of discovery being run in the logs.  It seems to go directly to execution, which sort of makes sense, since it is just running assemblies.  Waiting for confirmation from the softies.

**Comment by OsirisTerje** [comment]
Just got it confirmed, running vstest.console for a bunch of assemblies, like TFS/VSTS build does, will not run the discoveryphase.  So it that case we should not react to the missing file, or create it if it missing the first time.

**Comment by CharliePoole** [comment]
We should be able to observe that in the debugger as well.

I see two courses:
1. Detect tfs and act differently.
2. Give an error in discovery if we fail to write it and ignore it if it's missing.

Number 2 seems better to me. If we are only run once, in a single process, then the problem that the file is designed to solve doesn't exist.

**Comment by CharliePoole** [comment]
Seems like a low priority to me.

**Comment by OsirisTerje** [comment]
I can repro it in command line.  I see an option is to just check in execution if the file exist, and is supposed to exist (Checking the settings the same way as in discovery), and then just create it the first time we detect it is missing.  I tried this, and it worked.  Btw, what is the effect when it is missing?  This file was added in 3.0.

**Comment by OsirisTerje** [comment]
I've pushed my changes to an  Issue-253 branch.

**Comment by OsirisTerje** [comment]
Added fix with commit 8dd7fb49d24aded232a2abe2c9cab073e4de573a

**Comment by CharliePoole** [comment]
As I said, there's no point in creating it if it's missing. The purpose it serves is to transfer information from one process to the other. If we are only called in one process, we don't need it. If the tests include use of the Random attribute and they run OK with only a warning, that will prove there is no problem.

**Comment by OsirisTerje** [comment]
Ok, but then we should remove the warning.  You said in the first post here " If it isn't, then test cases using random parameter values won't work correctly."  Now we have the case where it is legitimate that discovery is not run, and since the warning comes from the executor, it doesn't know if discovery have been run or not.  So, either remove the warning, or check the existence in the discoverer.

**Comment by CharliePoole** [comment]
See my earlier comment: "Give an error in discovery if we fail to write it and ignore it if it's missing."

We do need to issue a warning someplace. Since we try to write it in discovery, the warning there should be sufficient for the IDE.

**Comment by OsirisTerje** [comment]
From the code now, it does give a warning  "Failed to save random seed".  That should be sufficient, right?

**Comment by CharliePoole** [comment]
Yes, that's what I think. Will you do a PR?

**Comment by CharliePoole** [comment]
We should also verify that it runs correctly without the seed file - I'm 99% sure it will. If you run the nunit3testdemo from the command-line under vstest, it should tell you. Probably, we should add some test case to the adapter tests themselves.

**Comment by OsirisTerje** [comment]
I have already done the testing, also checked with a tfs build, and the annoying messages are gone, and the tests works.    Agree with adding test cases for this though. 
Yes, making a PR now

**Comment by CharliePoole** [comment]
Closed by #254

**Comment by jnm2** [comment]
I just hit this problem and it's preventing my Cake targets from running which depend on unit tests. I saw $RANDOM_SEED$ in my installer output and tracked it back and deleted it from two *non-test* projects because I couldn't figure out what had created the files. Later, I find NUnit doesn't work. Is there a workaround? I tried cleaning the solution.

**Comment by jnm2** [comment]
I'm not actually sure what's causing the error but it seems related to the random seed file. Here's what I'm actually getting:

```
Warning: Exception System.IO.FileNotFoundException, Unable to restore random seed.

Warning: Could not find file 'C:\Users\****\****.Tests\obj\Release\$RANDOM_SEED$'.

Error: Error: Unable to get runner for this assembly. Check installation, including any extensions.

Error: FileNotFoundException: Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified.

Warning: Exception System.IO.FileNotFoundException, Exception thrown executing tests

Warning: Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified.

Warning: Exception System.IO.FileNotFoundException, Unable to restore random seed.

Warning: Could not find file 'C:\Users\****\****.Tests\bin\Release\$RANDOM_SEED$'.
```

**Comment by jnm2** [comment]
Erm... scratch that. `$RANDOM_SEED$` warnings right before `nunit.framework` file not found errors aren't actually related, because when I use v3.5.0 I get the latter and not the former.
