### ISSUE TITLE
Rename $RANDOM_SEED$

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#256]
I noticed a bit of confusion over the purpose of this file at http://stackoverflow.com/q/40364171/4026748

Perhaps we should rename it to $NUNIT_RANDOM_SEED$ so people will know who creates it.

**Comment by OsirisTerje** [comment]
Isn't this file only needed by the execution run?  Can we simply delete it when execution have finished?

**Comment by CharliePoole** [comment]
It's possible to have multiple execution runs without a new discovery.

**Comment by OsirisTerje** [comment]
Good point.   I  agree it need to have nunit it its name.  But,  the current spelling, $ and capital case makes it stand out very much, and makes it look more important than it is.   I see VS makes some temp files with only a dot in front and lower case letters.  And also making it hidden.  Could we call it simply   ".nunit", or even ".nunit.tmp" to make it even more obvious it is a temporary file,   and perhaps even make it hidden ?

**Comment by CharliePoole** [comment]
I think we are demonstrating how different people see things differently. :smile: For me `$CAPS$` means an unimportant temporary file. I'm OK to change the name but I think we should not be so generic. In cases of some error, we may want to ask users to look at it. For the same reason, I don't think it should be hidden. I could go for `.nunit_random_seed` if that seems OK to you.

**Comment by CharliePoole** [comment]
Extension `.tmp` is OK for me as well.
