### ISSUE TITLE
Stackoverflow in test makes test runner unreliable

### ISSUE THREAD

**Issue by dotnetjunkie** [nunit/nunit3-vs-adapter#257]
When a code base under test throws a stackoverflow exception the VS adapter doesn't report this back. Instead the adaper stops running and the non-run tests are greyed out, but no error is shown. This might be fine when the number of tests fit within the Test Explorer window (about 20 to 30), but when there are a large amount of tests to run (over 3000 in my case), the greyed-out tests are sorted below the succeeded tests. Since no warning or error is given and the stackoverflowed test that broke the test suite is not reported as failing test, there is no visual indication that there is a problem. This caused me to release a broken product recently.

Here is a simple test suite that allows reproducing this problem:

``` c#
[TestFixture]
public class UnitTest1
{
    [Test]
    public void TestMethod1()
    {
        Thread.Sleep(1);
    }

    [Test]
    public void TestMethod2()
    {
        Thread.Sleep(1000);
        Stackoverflow();
    }

    [Test]
    public void TestMethod3()
    {
        Thread.Sleep(1);
    }

    private void Stackoverflow()
    {
        this.Stackoverflow();
    }
}
```

**Comment by OsirisTerje** [comment]
It is the vstest.executionengine that crashes.  The adapter have no control over it.  Even if we managed to catch it, it would not reach the test explorer, since the executionengine have crashed.  
This has to be fixed there, if possible.
