### ISSUE TITLE
Modify adapter to display multiple assert information

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#258]
@CharliePoole commented on [Sun Nov 06 2016](https://github.com/nunit/nunit-console/issues/127)

Currently, the adapter uses the single failure message created for compatibility in order to display the result of a test using multiple asserts. It should display separate results for each assert, provided that VS is able to handle it.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #135](https://github.com/nunit/nunit-console/issues/135) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CharliePoole** [comment]
I guess this was actually intended to refer to the adapter. Edited title and description.

**Comment by CharliePoole** [comment]
This is completed as far as it can be given the limitations of the Test Explorer window. Multiple assert failures and warnings are permitted. Warnings show as Skipped, which may be a problem, but that at least gets them a warning icon.

**Comment by Kira-Lappo** [comment]
@CharliePoole could you help me help me with that feature?
As I understood this feature was implemented by desing, which came from nunit project.
But I didn't understand if multiple UnitTest results are supported and expected by vstest.exe.

**Comment by CharliePoole** [comment]
The feature itself is an nunit framework feature so it should be available if you are using a version of the framework that supports it, i.e. 3.7 or higher.

The runner you use can give better reports if it recognizes multiple asserts. For "old" runners like vstest.exe you should get the legacy failure message that the framework creates. It simply joins all the different assert failures together in a single message.

Note that multiple asserts does not mean multiple test results. There is still only one test and one test result. You'll only see something different if you have more than one failure within a multiple assert block.

**Comment by Kira-Lappo** [comment]
@CharliePoole thanks, this is what I wanted to know.
Yeah, I meant `Assert.Multiple(() => {})` with several failed Assert actions, which causes several `TestResult` items in trx for the same `testMethod` value.
vstest.console.exe is used by dotnet-test.exe underneath and retrieves data from adapters, that's why I wrote `vstest.exe`

**Comment by CharliePoole** [comment]
It sounds like the nunit adapter, which I no longer work on, is now translating multiple assertion failures to multiple vs test results. That makes sense.
