### ISSUE TITLE
Support for VS 15

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#262]
The adapter needs to be updated to support VS 15.  That requires changes to the VSIX format, and the specified verson range.

**Comment by CharliePoole** [comment]
Not that I doubt Microsoft, but lets test this with VS2012, 2013 and 2015. :smile:

**Comment by OsirisTerje** [comment]
I think we can close this now, since version 3.6 is out.

**Comment by rprouse** [comment]
Yes, I was waiting for the outstanding PR to merge the changes back into master to be merged though. @OsirisTerje can you review the PR and merge when ready?
