### ISSUE TITLE
This extension is not installable on any currently installed products

### ISSUE THREAD

**Issue by SzymonSel** [nunit/nunit3-vs-adapter#270]
Failed to install extension on VS 2013 Ultimate Update 5, despite:

> The NUnit3TestAdapter extension works with the Visual Studio Unit Test window to allow integrated test execution under Visual Studio 2012 and newer.

**Comment by OsirisTerje** [comment]
Can you please check if you still have this issue with the released hotfix of the nunit3testadapter, version 3.6.1 ?
It solved the issue #260 which may be related.

**Comment by CharliePoole** [comment]
We have had no response from @SzymonSel for several weeks and it should have been fixed by the 3.6.1 release. I'm closing.
