### ISSUE TITLE
Status of .runsettings

### ISSUE THREAD

**Issue by Osipion** [nunit/nunit3-vs-adapter#274]
I'd like to pass parameters to NUnit tests run from visual studio via a .runsettings file. I believe that this [feature has been added](https://github.com/nunit/nunit3-vs-adapter/pull/197), though I can't get it to work. I tried using the [demo.runsettings](https://github.com/nunit/nunit3-vs-adapter/blob/master/demo/demo.runsettings) file in my solution folder, but couldn't access the parameters from within a test (`TestContext.Parameters` etc), whilst I could access them in a test run through nunit3-console when they were passed on the command line. Has this feature been released/am I doing something wrong?

I'm using NUnit 3.5 with test adapter [3.6](https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter).

**Comment by CharliePoole** [comment]
Simply placing a file in the folder is insufficient. You have to tell VS to use it. Check the menus in the IDE or the command-line options if using vstest-console.exe.

**Comment by Osipion** [comment]
Thanks - the option is in Test> TestSettings>Select Test Settings File
