### ISSUE TITLE
Error: Unable to get runner for this assembly. Check installation, including any extensions.

### ISSUE THREAD

**Issue by sam-wheat** [nunit/nunit3-vs-adapter#280]
I am receiving the error message below.

I've traced the issue to a single project reference in my test project:
"ProjectManager.API": "1.0.0-*",

ProjectManager.API is a .netcoreapp web project (project.json shown below).  If I remove that reference my tests will run.  However I need that reference to create a Microsoft.AspNetCore.TestHost.TestServer
Other things I've tried
Changed architecture to x64
Delete bin/obj/project.lock.json folders in all projects
Install/uninstall NUnit3TestAdapter .vsix
Reinstall .net core Tooling for VS

Environment
Visual Studio 2015 R3

Tests project Project.Json 

	{
	  "version": "1.0.0-*",
	  "dependencies": {
		"Autofac": "4.2.1",
		"dotnet-test-nunit": "3.4.0-beta-3",
		"Microsoft.AspNetCore.TestHost": "1.1.0",
		"Microsoft.Extensions.PlatformAbstractions": "1.1.0",
		"Moq": "4.6.38-alpha",
		"NETStandard.Library": "1.6.1",
		"NUnit": "3.5.0",
		"NUnit.Console": "3.5.0",
		"NUnit3TestAdapter": "3.6.0",
		"ProjectManager.API": "1.0.0-*",
		"ProjectManager.Core": "1.0.0-*",
		"ProjectManager.Domain": "1.0.0-*",
		"ProjectManager.Gateway": "1.0.0-*",
		"ProjectManager.Model": "1.0.0-*",
		"ProjectManager.Services": "1.0.0-*",
		"ProjectManager.Services.REST": "1.0.0-*",
		"ProjectManager.Services.WCF": "1.0.0-*"
	  },

	  "frameworks": {
		"netcoreapp1.1": {
		  "imports": [
			"netcoreapp1.1",
			"portable-net45+win8"
		  ],
		  "dependencies": {
			"Microsoft.NETCore.App": {
			  "type": "platform",
			  "version": "1.1.0"
			},
			"System.ServiceModel.Duplex": "4.3.0",
			"System.ServiceModel.Http": "4.3.0",
			"System.ServiceModel.NetTcp": "4.3.0",
			"System.ServiceModel.Security": "4.3.0",
			"System.Xml.XmlSerializer": "4.3.0"
		  }
		},
		"net462": {
		  "frameworkAssemblies": {
			"System.Runtime.Serialization": "4.0.0.0",
			"System.ServiceModel": "4.0.0.0",
			"System.Xml": "4.0.0.0"
		  },
		  "dependencies": {}
		}
	  },
	  "testRunner": "nunit"
	}

Web app project.json

	{
	  "dependencies": {
		"Autofac": "4.2.1",
		"Autofac.Extensions.DependencyInjection": "4.0.0",
		"Microsoft.AspNetCore.Mvc": "1.1.0",
		"Microsoft.AspNetCore.Routing": "1.1.0",
		"Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
		"Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
		"Microsoft.AspNetCore.Session": "1.1.0",
		"Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
		"Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
		"Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
		"Microsoft.Extensions.Configuration.Json": "1.1.0",
		"Microsoft.Extensions.DependencyInjection": "1.1.0",
		"Microsoft.Extensions.Logging": "1.1.0",
		"Microsoft.Extensions.Logging.Console": "1.1.0",
		"Microsoft.Extensions.Logging.Debug": "1.1.0",
		"Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
		
		"ProjectManager.Core": "1.0.0-*",
		"ProjectManager.Domain": "1.0.0-*",
		"ProjectManager.Gateway": "1.0.0-*",
		"ProjectManager.Model": "1.0.0-*",
		"ProjectManager.Services": "1.0.0-*",
		"ProjectManager.Services.REST": "1.0.0-*"
	  },

	  "tools": {
	  },
	 
	  "frameworks": {
		"netcoreapp1.1": {
		  "imports": [
			"dotnet5.6",
			"portable-net45+win8"
		  ],
		  "dependencies": {
			"Microsoft.NETCore.App": {
			  "type": "platform",
			  "version": "1.1.0"
			}
		  }
		},
		"net462": {}
	  },

	  "buildOptions": {
		"emitEntryPoint": true,
		"preserveCompilationContext": true
	  },

	  "runtimeOptions": {
		"configProperties": {
		  "System.GC.Server": true
		}
	  },

	  "publishOptions": {
		"include": [
		  "wwwroot",
		  "Views",
		  "Areas/**/Views",
		  "appsettings.json",
		  "web.config"
		]
	  },

	  "scripts": {
		"postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
	  }
	}

Error Message:

		------ Discover test started ------
		Discovering tests in 'C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Tests\project.json" --output "C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Tests\bin\Debug\netcoreapp1.1" --port 51620 --parentProcessId 10632 --no-build]
		'test-nunit' returned '-2'.
		NUnit Adapter 3.6.0.0: Test discovery starting
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.API\bin\Debug\netcoreapp1.1\ProjectManager.API.dll
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Components\bin\Debug\net462\ProjectManager.Components.dll
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Core\bin\Debug\net462\ProjectManager.Core.dll
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Domain\bin\Debug\net462\ProjectManager.Domain.dll
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Gateway\bin\Debug\net462\ProjectManager.Gateway.dll
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Model\bin\Debug\net462\ProjectManager.Model.dll
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Services.REST\bin\Debug\net462\ProjectManager.Services.REST.dll
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Services.WCF\bin\Debug\net462\ProjectManager.Services.WCF.dll
		Error: Unable to get runner for this assembly. Check installation, including any extensions.
		FileNotFoundException: Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified.
		Dependent Assembly nunit.framework of C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Tests\bin\Debug\netcoreapp1.1\ProjectManager.Tests.dll not found. Can be ignored if not a NUnit project.
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.WCF\bin\ProjectManager.WCF.dll
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.Web\bin\Debug\netcoreapp1.1\win10-x64\ProjectManager.Web.dll
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.WPFClient\bin\Debug\ProjectManager.WPFClient.exe
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\ProjectManager.WPFComponents\bin\Debug\ProjectManager.WPFComponents.dll
		Assembly contains no NUnit 3.0 tests: C:\Git\ProjectManager\ProjectManager\src\TwitterAPI\bin\Debug\netstandard1.6\TwitterAPI.dll
		NUnit Adapter 3.6.0.0: Test discovery complete
		========== Discover test finished: 0 found (0:00:01.0000102) ==========

A couple related issues I've looked at:

http://stackoverflow.com/questions/29890768/nunit-doesnt-discover-tests-no-error-message
https://github.com/nunit/nunit3-vs-adapter/issues/248

**Comment by sam-wheat** [comment]
Charlie are you sure the ticket you closed this against indicates the same root cause?

**Comment by CharliePoole** [comment]
@sam-wheat I can't see my comment here any longer, explaining why I closed it. Can you see it?

**Comment by sam-wheat** [comment]
No I never did see a comment.

**Comment by CharliePoole** [comment]
Well that must be confusing! :smile: Maybe I exited without sending it.

Issue #242 is about actual support for .NET core, which we don't support.

Issue #232 is about recognizing and giving an intelligent warning while skipping .NET core assemblies. That's the one I considered to be a duplicate. The functionality for this will have to be in the engine but the adapter is involved in recognizing the situation when it occurs and not freaking out.

**Comment by sam-wheat** [comment]
Thank you Charlie.   Yes its confusing - every time I fire up Visual Studio something has changed.  So based on [this post](http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/), .net core used to be supported but now that MS is moving back to .csproj you no loger support it.  Is that correct?  If so can we rig up an earlier release of the adapter as suggested [here](https://github.com/nunit/nunit3-vs-adapter/issues/248)?  (I actually tried it before I wrote my original question and it did not work which further lead me to believe it was a problem with my code/project config).

**Comment by CharliePoole** [comment]
Actually, if you re-read @rprouse's post you'll see that it doesn't have any connection to the NUnit 3 Test Adapter. He shows how to run .NET Core using self-executing tests (exes) that use NUnitLite.

Our three mainstream runners (Console, Gui and VS Adapter) do not yet support .NET Core - and have never supported it, just to be clear. They all run tests using the NUnit TestEngine, which would need to have that support added before the runners can use it.

Rob has done a lot of experimental work with the original .NET Core implementation and will be coming back to it now that Microsoft's plans seem to have stabilized. Eventually, it will be non-experimental and will get added to our standard runners.
