### ISSUE TITLE
Test parameters containing semicolons are truncated

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit3-vs-adapter#288]
@CharliePoole in https://github.com/nunit/nunit/issues/1885#issuecomment-268872044:

> @jnm2 I'm assigning this issue to you. Is there already an nunit 3 adapter issue? If not there should be.

**Comment by jnm2** [comment]
The work is simple, but getting the Cake build task to complete so I can test seems not to be.

When it tries to build `NUnit3TestAdapterInstall.csproj`:

```
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018: The "GetExtensionsPath" task failed unexpectedly.\r [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Settings.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.\r [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018: File name: 'Microsoft.VisualStudio.Settings.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'\r [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018:    at Microsoft.VsSDK.Build.Tasks.GetExtensionsPath.Execute()\r [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()\r [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018: \r [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018: WRN: Assembly binding logging is turned OFF.\r [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.\r [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018: Note: There is some performance penalty associated with assembly bind failure logging.\r [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\VSSDK\Microsoft.VsSDK.targets(602,5): error MSB4018:  [C:\Users\Joseph\Source\Repos\nunit3-vs-adapter\src\NUnit3TestAdapterInstall\NUnit3TestAdapterInstall.csproj]
```

I'm using latest VS2017 (15.0.26014.0) with workloads ".NET desktop development", "Desktop development with C++", "Web development", ".NET Core and Docker (Preview)", and "Visual Studio extension development."
I even did a full repair to make sure nothing was corrupted.

`NUnit3TestAdapterInstall.csproj` says minimum VS version is 15.0, so I know you must have been using VS2017.

@nunit/contributors Any wisdom on this?

**Comment by jnm2** [comment]
Oddly enough it builds fine in Visual Studio, just not Cake.

**Comment by Sebazzz** [comment]
Do you have the extension SDK for VS2015 installed? It appears Cake is specifically looking for an older version.

**Comment by jnm2** [comment]
Oh, I probably don't. I'll try that. But since `NUnit3TestAdapterInstall.csproj` has `<MinimumVisualStudioVersion>15.0</MinimumVisualStudioVersion>` and VS2015 is version 14.0, I'm confused.

Otoh I just remembered that Cake doesn't support msbuild 15.0 yet because of https://github.com/Microsoft/msbuild/issues/1377. Now I'm really curious what you did to get it to run, since I wrote something like [this](https://github.com/Microsoft/msbuild/issues/1377#issuecomment-267792928).

**Comment by jnm2** [comment]
I do have the VS2015 extension SDK installed, but I'll repair the installation.

**Comment by jnm2** [comment]
I do have the VS2015 extension SDK installed, and repairing the installation has had no effect.
I just remembered that Cake doesn't support msbuild 15.0 yet because of https://github.com/Microsoft/msbuild/issues/1377. This could be a problem.

Now I'm noticing it pulling in `Microsoft.VSSDK.BuildTools.15.0.25907-RC2` which is an older RC version of VS2017, while I have 15.0.26014. The newest package on NuGet is only [15.0.25929](https://www.nuget.org/packages/Microsoft.VSSDK.BuildTools/15.0.25929-RC2).

**Comment by jnm2** [comment]
I guess I'll test via ReSharper and skip using Cake for now.

**Comment by CharliePoole** [comment]
@jnm2 I have been unable to build locally with Cake ever since we upgraded
to the v3 vsix format. However, when I push AppVeyor is able to build it
just fine. I've been thinking it was my installation, because I'm using a
new machine. If it turns out that you have a similar problem, then I guess
it's something we should look into.

**Comment by CharliePoole** [comment]
@jnm2 Looks like this was still a "new issue" without any review. I assigned it to you since you've already done all the work. :smile:
