### ISSUE TITLE
Test Explorer fails to Open Test when using nested test fixture

### ISSUE THREAD

**Issue by rvuistin** [nunit/nunit3-vs-adapter#291]
It is no longer possible to navigate to a test method contained in a test fixture nested in an outer class using the test explorer (this was possible with NUnit Test Adapter version 2).

```
namespace NUnit3VsAdapter.Tests
{
	public class Class1Test
	{
		[TestFixture]
		public class Method1Test
		{
			[Test]
			public void NavigateToThisCodeWithTestExplorer_AlwaysFails()
			{
				Assert.Fail ();
			}
		}
	}
}
```

**Comment by rvuistin** [comment]
@CharliePoole : this bug happens when the adapter is referenced as a nuget package only. When the adapter is installed as an extension too, the bug disappears.

**Comment by CharliePoole** [comment]
Make sure you have exactly the same version installed in both cases.

**Comment by OsirisTerje** [comment]
@rvuistin I can't repro this using adapter 3.7.0 (as a nuget package).

**Comment by CharliePoole** [comment]
There is a conflict between ECMA and Microsoft naming of nested classes. We've run into this and fixed it on several occasions - in various places.

**Comment by jnm2** [comment]
Is that the `+` vs `.`?

**Comment by CharliePoole** [comment]
Yup.

**Comment by jnm2** [comment]
I wouldn't say ECMA vs Microsoft then so much as CLR representation `+` (which follows ECMA) and C# language name `.`, which is also following ECMA for C#.

**Comment by jnm2** [comment]
It's on my mind because of https://github.com/dotnet/csharplang issue 701.

People were conflating the two in https://github.com/dotnet/roslyn/issues/15983#issuecomment-268565261

**Comment by OsirisTerje** [comment]
@jnm2 @CharliePoole You've lost me, guys.  I'm not on to what you're talking about at all.  What has the ternary operator to do with nested classes?  
If what you're looking for is the class naming with '.', it still works.

![image](https://user-images.githubusercontent.com/203432/27515042-cd67d248-599a-11e7-81e4-4613e81f5142.png)

Given the  repro as:
![image](https://user-images.githubusercontent.com/203432/27515047-e61a6fb2-599a-11e7-98ec-92be725a0d38.png)

So do you agree this issue can be closed, or is there something here I have missed?

**Comment by jnm2** [comment]
@OsirisTerje I'm sorry, yes the issue should be closed. I balked at labeling Microsoft as wrong unfairly since both `ContainingClass+InnerClass` and `ContainingClass.InnerClass` are ECMA, the former for the language-agnostic runtime representation, the latter for the language.
