### ISSUE TITLE
$RANDOM_SEED$ is appearing in non-test project build output

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#298]
@jnm2 commented on [Sat Jan 14 2017](https://github.com/nunit/nunit/issues/1982)

This is messing up the installer generated by CI. Now I _can_ update my build script to find and exclude those files, but they should not be appearing at all because there are no test assemblies in those folders.

---

@CharliePoole commented on [Sat Jan 14 2017](https://github.com/nunit/nunit/issues/1982#issuecomment-272667441)

What installer, for what project?

This file has nothing to do with NUnit but is created by the NUnit3 adapter. There is an adapter issue that renamed this file so you must be using the last adapter release to get that name. Anyway, the file will appear in the output directory for any nunit3 test assembly. It should not be created for other assemblies that don't share the same output directory. If it does, that's an adapter bug.

Do I need to move this or just close it?

---

@jnm2 commented on [Sat Jan 14 2017](https://github.com/nunit/nunit/issues/1982#issuecomment-272667854)

Oh, I didn't know this was an adapter thing. Can I turn it off? If the console runner doesn't need it, why do I want it?

> Do I need to move this or just close it?

Depends- is the fact that it's showing up in the build output of a non-test project a  bug?

---

@CharliePoole commented on [Sat Jan 14 2017](https://github.com/nunit/nunit/issues/1982#issuecomment-272671755)

Erase it and figure out what you do that creates it. It should only be created by running the NUnit3 adapter on that project. Of course, if you have it installed as a vsix, it is run every time you open the project.

---

@CharliePoole commented on [Sat Jan 14 2017](https://github.com/nunit/nunit/issues/1982#issuecomment-272671808)

Does the output directory contain any test projects, in addition to the non-test project?

**Comment by CharliePoole** [comment]
Examining the code, I see that the random seed file is saved when discovery starts. Discovery is actually run on every assembly, as directed by VS, so we don't know if it's a test assembly until discovery ends. That's when we should save it.

**Comment by jnm2** [comment]
The output directory does not contain any DLLs that reference a testing framework.

**Comment by jnm2** [comment]
I have files from 2 pm yesterday in both Debug and Release, so I know those are from IDE. For some reason my Cake script which also uses the VS adapter is not generating new ones.

Nowhere under https://github.com/nunit/docs/wiki/Visual-Studio-Test-Adapter does it mention $RANDOM_SEED$. I have no idea what it accomplishes or why this is the only runner that needs it. I'll look at the code and find out.

**Comment by CharliePoole** [comment]
As I said, it's explained in some issues and hasn't made it to any docs. IMO, we shouldn't need to indicate the purpose of temporary files in the docs, but if others think we should, they can update them. The newest issue changes the name so it's clearer.

https://github.com/nunit/nunit3-vs-adapter/issues/168
https://github.com/nunit/nunit3-vs-adapter/issues/253
https://github.com/nunit/nunit3-vs-adapter/issues/256

I'm keeeping this issue to fix the problem of generating the file for non-test assemblies.

**Comment by jnm2** [comment]
I have a bit of a feature request for a new issue. How hard would it be to lazily generate the file only if there is a test that uses randomness?

**Comment by jnm2** [comment]
So that whatever component it is that generates the test cases is also responsible to send a random seed if a test needs it and not to specify a seed if no tests need it?

**Comment by CharliePoole** [comment]
The framework is responsible for generating any random tests. It can use a random value as the seed or it can be passed a seed. In either case, it reports the random seed it used in the XML. If you rerun an assembly using the same random seed, then the same random cases are generated. That's how we get repeatability when it's necessary to replicate a bug that has been observed in a test run.

In order to deal with the fact that NUnit under the adapter must generate the  tests twice, the adapter sets the random seed. Since there is no other provision for the two processes, which run at different times, to communicate with one another, it saves the seed to a file. Random features are completely unusable under the adapter without this.

The adapter is two layers above the framework in our architecture. It has no idea what the framework will do or what features are used in the tests. Discovering all uses of randomness prior to test execution would mean a global analysis of the code, not just an examination of the attributes, because tests can use NUnit's random features programatically from code as well.

It's just an extra `.tmp` file in your output directory!

**Comment by jnm2** [comment]
During the discovery phase, the adapter has the framework generate the test xml.
If randomness is used, `RandomAttribute.RandomDataSource<>` calls Randomizer.GetRandomizer ([code](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/RandomAttribute.cs#L259)).
That could be the point at which the framework makes a note that randomness is actually used, which would be reported back in the test XML which the adapter receives.
The adapter, as it parses the tests during the discovery phase, could see that the framework specified a seed and beside the seed, specified that the seed is actually used.
Since the adapter sees that the framework indicates that the seed is actually used, it takes the opportunity to save it to disk so that when execution happens, it can send the seed to the framework.

> It's just an extra .tmp file in your output directory!

It does become more than an irritation though...
For example, Cake's globbing is experimental and cannot match the `$` character, so I had to write a bunch of not-the-nicest code in order to get the installer building correctly. Anywhere *but* the output directory and I'd be fine with it. :smile:

**Comment by jnm2** [comment]
> because tests can use NUnit's random features programatically from code as well.

That part puts an end to it it though.

**Comment by CharliePoole** [comment]
@jnm2 Did you look at the PRs and issues I pointed to? The file no longer has any $s in it's name.

**Comment by jnm2** [comment]
@CharliePoole Yes, I was giving an example. Someone else's may be different. But the main thing is that when this issue is fixed, it'll only show up in output directories containing DLLs which reference NUnit. That will solve my problems since I don't distribute any DLLs which reference NUnit. :-)

**Comment by CharliePoole** [comment]
So when you package your app, you simply include everything that's in the output directory? That seems a little risky, although I understand it saves you having to maintain a list of what to distribute. In that case, I suggest you simply ignore *.tmp files until this is resolved. 😄

**Comment by jnm2** [comment]
> In that case, I suggest you simply ignore *.tmp files until this is resolved.

I think I realized why I still continually get `$RANDOM_SEED$ files. I think ReSharper bundles the NUnit adapter.

**Comment by CharliePoole** [comment]
Interesting! Do you think they use it when you run through resharper?

**Comment by CharliePoole** [comment]
@jnm2 BTW you shouldn't use R# or any other third party tool when working on nunit itself. Even our own adapter counts as third party if you're working on the framework.

**Comment by jnm2** [comment]
> Interesting! Do you think they use it when you run through resharper?

It's a guess, but yes because when Visual Studio has no adapter installed and VS does not discover any NUnit tests, ReSharper discovers and executes them and `$RANDOM_SEED$` keeps on showing up.

> BTW you shouldn't use R# or any other third party tool when working on nunit itself. Even our own adapter counts as third party if you're working on the framework.

That makes sense, but this issue like most others I'm having while working on a project that is not nunit.

**Comment by CharliePoole** [comment]
@jnm2 IMHO that's a very strange choice. That means NUnit output is filtered through the adapter, munging (falsifying?) the results to deal with what the Test Explorer is capable of understanding. Then R# tries to reconstitute them.

We did communicate with JB and suggest two APIs they could use with NUnit 3. Instead they invented a third way to go for TeamCity and (apparently) a fourth for their test runner. Neither of the two is a way of interfacing with NUnit that we actually support (i.e. guarantee for the future) of course.

I figured you were working on "work" when you ran into the problem you saw but I wanted to make sure you knew not to rely on R# when modifying/testing NUnit. That's true for any third-party software, but it's especially the case when it's a company that doesn't reveal how they interface with us. 😄

**Comment by jnm2** [comment]
Btw for the last few months it's been `nunit_random_seed.tmp` that keeps appearing in our deployable non-test assembly bin folders and wandering into release packages and installers.

It's hard to remember that I have to exclude it because the file is never around when setting up a new build script. It certainly hasn't gotten less aggravating over time.

**Comment by CharliePoole** [comment]
Do you want to take this one on? Are you able to build the adapter?

**Comment by jnm2** [comment]
You could say I have an incentive =) Yes.

I was able to build the adapter a few months ago. Don't see why not.

**Comment by jnm2** [comment]
I cannot assign myself in this repo.

**Comment by CharliePoole** [comment]
Assigned to you - just ask if you need any pointers.

**Comment by fabianPas** [comment]
+1 It's really annoying to have those random files suddenly in my Release build directories.

**Comment by OsirisTerje** [comment]
@jnm2 Any chance of looking into this?   I can't really see how that file could end up in a non-test output, as long as the output folders are separated.

**Comment by jnm2** [comment]
I will move this up on my list. It's still happening.

**Comment by CharliePoole** [comment]
@jnm2 Did you ever solve problems you were having with building the adapter? If not, one of us can take it on.

**Comment by CharliePoole** [comment]
@OsirisTerje This is happening when we start discovery for each assembly.

**Comment by jnm2** [comment]
No, I haven't revisited the adapter code yet. Whatever you think, I'm happy for it to be done quicker.

**Comment by jnm2** [comment]
@OsirisTerje ❤️
