### ISSUE TITLE
Tests with Testnames containing a dot are wrongly grouped into a class

### ISSUE THREAD

**Issue by Timmitry** [nunit/nunit3-vs-adapter#304]
I have tests with Attributes of the form: `[TestCase(TestName = "Name of my supercool test")]`.
Now, in the Visual Studio Test-Explorer, I can group all shown tests by "Class" ("Klasse" in the screenshot, german version). This works in general, however, if my TestName contains a dot ("."), it groups that test under a class corresponding to the TestName up to the dot-character. See the screenshots for an example:

The tests in the test class with Name "Test_Nullstellen"...
![correspondingtests](https://cloud.githubusercontent.com/assets/20927653/23214766/387e00d4-f910-11e6-8530-18c675fc1832.png)

... are shown to be in the class "Nullstellen von Polynomen - Gleichung 1", which corresponds to their test names up to the dot:
![testnamewithdots](https://cloud.githubusercontent.com/assets/20927653/23214765/387d7a60-f910-11e6-8c8b-eeaec0ee0efb.png)

**Comment by CharliePoole** [comment]
I"m regrettably rejecting this as an NUnit issue. 😞

For NUnit, test names are arbitrary strings even though they most commonly resemble a class or method name. Visual Studio's IDE insists on treating the test name as if it were a class or method name and deduces the "class" from the name we pass it. This is out of our control.

The problem has been brought to the attention of the Microsoft folks over the years but there approach seems to be too fully "baked in" for them to change it, particularly as NUnit is the only framework supported that allows for arbitrary names.

Best advice is not to use any dots in your names if you will be running with the test adapter.

**Comment by Timmitry** [comment]
Thank you for the information, I'll try not to use dots then ;-)

**Comment by TheRealFlif** [comment]
@ksokolowski7 suggested this: (see https://github.com/nunit/nunit/issues/2333)
"Solution for this case is to replace dot with \u2024. So just before naming the test use .Replace(".", "\u2024")"
and I can confirm that it works
