### ISSUE TITLE
Question: (VS2017) dotnet test --test-adapter-path parameter always necessary?

### ISSUE THREAD

**Issue by qrli** [nunit/nunit3-vs-adapter#307]
Is the --test-adapter-path parameter always necessary when using Nunit3TestAdapter? It makes the command line usage somewhat cumbersome. Although I use VS typically, I still VS Code time to time, in which case the cli has to be used to run tests.

**Comment by Metamorphus** [comment]
What's the default adapter path by the way? I'm struggling to find it :(

**Comment by CharliePoole** [comment]
It depends how you install it. Installed as a vsix, it's in a directory under the VS install, which makes it a bit inconvenient to use. If you install it using the nuget package, it's in your

**Comment by rprouse** [comment]
I haven't tested yet, but I thought that if you install the adapter as a NuGet package to your test project, the `--test-adapter-path` option shouldn't be needed. If you have a chance to test that, I would appreciate feedback.

Also note that the adapter currently only works when targeting the full CLR. It does not work when targeting .NET Core or Standard yet, we are working on that.

**Comment by Metamorphus** [comment]
> It does not work when targeting .NET Core or Standard yet, we are working on that
:( That's a pity. I ported my application from .NET Framework to preview of .Net Core 2.0 and was hoping to port the NUnit tests for it too.
I installed the adapter as NuGet package and then the command "dotnet test -a <path-to-adapter>" gave me the following output:
`Starting test execution, please wait...
NUnit Adapter 3.7.0.0: Test execution started
An exception occurred while invoking executor 'executor://nunit3testexecutor/': Could not load type 'System.Runtime.Remoting.Channels.IChannel' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.`

**Comment by qrli** [comment]
@rprouse I did install it as NuGet package and it works fine in VS. But from the command line, it cannot find any test if I did not include the `--test-adapter-path` parameter.

**Comment by rprouse** [comment]
I am going to leave this as open for confirmation until we finish the .NET Standard work in #297.

**Comment by qrli** [comment]
I found the subtle difference:
* In VS, only one test project need to have test adapter nuget referenced, and all test projects will have tests show up and run in VS test explorer.
* In CLI, only test projects which have test adapter nuget reference will be able to find the tests without --test-adapter-path

**Comment by jnm2** [comment]
@rprouse Think we should emphasize that in https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard?

**Comment by rprouse** [comment]
Sounds good to me. Can you add it @jnm2?

**Comment by jnm2** [comment]
Yes.

**Comment by jnm2** [comment]
Closed in https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard/738854a3fab904bd09d701cf451a9b6564216bb5

**Comment by jnm2** [comment]
@rprouse The entire page says "Testing .NET Core and .NET Standard projects," so it sounds like it's saying test projects can be .NET Standard projects.

**Comment by CharliePoole** [comment]
OR... it says you can test .NET Standard projects using a .NET Core or .NET framework test 😸 , which is what it should say. I don't think the title can cover everything, but the text needs to explain that the SUT may actually be .NET Standard, just not the test project.
