### ISSUE TITLE
Consistent Category Display in Test Explorer Window

### ISSUE THREAD

**Issue by sailro** [nunit/nunit3-vs-adapter#310]
Hi,

When mixing tests using different test frameworks, it would be great to have consistency when displaying "by traits" in the test explorer window.

See the following image:
MSTest is using {Category}
NUnit adapter is using Category [{Category}]

![image](https://cloud.githubusercontent.com/assets/638167/24370465/5eee0904-12dc-11e7-8c20-26f77f8b2bf7.png)

Regards
Seb

**Comment by OsirisTerje** [comment]
Now that MSTest have been open-sourced we can have a look what they have done.  Following the standard Traits mechanism give the results you see for NUnit, but MSTest seems to have another way for categories.

**Comment by sailro** [comment]
Thanks!
