### ISSUE TITLE
Test case containing U+001A is not executed

### ISSUE THREAD

**Issue by aristotelos** [nunit/nunit3-vs-adapter#312]
Using a `TestCase` or `TestCaseSource` containing the substitute character (U+001A) displays a test case in the test runner, but the test does not show any result when trying to execute it. Example code:

```
[TestCase("\u001a")]
public void SomeTestMethod(string value)
{
    // This method does not show a result (no success, failure, or ignore)
}
```

**Comment by OsirisTerje** [comment]
Works on VS 2017 U2 , with NUnit 3.7.1 and adapter 3.7.0
