### ISSUE TITLE
CodeLens not discovering nested tests - Test Explorer can see them 

### ISSUE THREAD

**Issue by twenzel** [nunit/nunit3-vs-adapter#316]
NUnit Version : 3.6.1.0           
NUnit Source : Nuget
NUnit-Adapter-Version : 3.7.0.0           
Visual Studio Version : Visual Studio 2017 Pro

I've following unit test structure:
```
[TestFixture]
public class BusinessManagerTests
{
	public class ConstructorTests : BusinessManagerTests
	{			
		[Test]
		public void Registered_StatementGenerator_Is_Created_Using_Default_Constructor()
		{
			Assert.Fail();
		}
	}
}
```

Unfortunately there's no "Test status" code lens indicator for the test method.
It's working in VS2015.

**Comment by CharliePoole** [comment]
This duplicates the old issue #55 and I'm closing it in the same way.

Essentially it's probably a bug, but not one of ours. The NUnit adapter does absolutely nothing to make tests visible to CodeLens. It discovers tests for test explorer. After that it's up to Visual Studio to make the connection.
