### ISSUE TITLE
Nunit adapter 3.7.0.0 targetInvocationException

### ISSUE THREAD

**Issue by Vytaras** [nunit/nunit3-vs-adapter#317]
Hi, I get this error:

------ Discover test started ------
NUnit Adapter 3.7.0.0: Test discovery starting
NUnit Adapter 3.7.0.0: Test discovery complete
========== Discover test finished: 8 found (0:00:00,4203748) ==========
------ Run test started ------
NUnit Adapter 3.7.0.0: Test execution started
Running selected tests in D:\StrongPoint\FISKALAS\VKPOS02Tests\Tests\bin\Debug\Tests.dll
NUnit3TestExecutor converted 8 of 8 NUnit test cases
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

This error appeared only if I "Run selected test", if I "Debug selected test" everything is ok, no error or exception is found. 
Same exception I was get before, but then I get inner exception, but in this case this exception is only shown in Output window.
Are solution for this problem?

**Comment by OsirisTerje** [comment]
Do yous till have this issue?   If so, can you provide a repro?
