### ISSUE TITLE
Tried 3.8.0-alpha1 With No Luck

### ISSUE THREAD

**Issue by JasonBock** [nunit/nunit3-vs-adapter#321]
I tried the new runner with my Rocks solution that has a test project using the new CPS format and multiple targets. Unfortunately none of the tests within that project show up in the Test Explorer. You can get the code here: https://github.com/nunit/nunit3-vs-adapter/releases/tag/3.8-alpha1. I may have done something wrong as well, but I think I followed the instructions from here: https://github.com/nunit/nunit3-vs-adapter/releases/tag/3.8-alpha1.

**Comment by rprouse** [comment]
@JasonBock you linked to our release, not your code. I assume you are working on your master branch and this is one of the tests? https://github.com/JasonBock/Rocks/blob/master/Rocks.Tests/Rocks.Tests.csproj

Multi-targeting is really buggy in Visual Studio. I've found that putting `net462` first often helps.

Can you also run from the command line to see if it is a Visual Studio or adapter problem? `dotnet test Rocks.Tests/Rocks.Tests.csproj` from your solution dir.

**Comment by JasonBock** [comment]
Sorry, yes, I copied/pasted the URL wrong. You're correct, that's the test project.

I tried running `dotnet test` and it seems to try and run tests for both .NET Core and .NET Framework, but I get so many errors I can't tell from the output (I could pipe to a file but I didn't do that at first). Note that I have two projects that use NUnitLite to run the tests for each target and those both run all tests and they pass, so I'm not sure why `dotnet test` doesn't work.

Putting `net462;` first makes Test Explorer see the .NET Framework tests, but not for .NET Core, and 1/2 of them fail.

**Comment by rprouse** [comment]
In test explorer, you will only see tests for one platform. That is a current Visual Studio limitation that they will hopefully fix soon.

As for tests failing using the adapter, NUnit doesn't set the current working directory for your test runs although with NUnitLite it probably set to the bin directory because that is where you run it. Are any of your tests dependent on the location of files or directories? What sorts of failures are you seeing?

**Comment by OsirisTerje** [comment]
For what it is worth:  I tried your solution, and found a bunch of tests failing as you say, but it points to what I would believe is the correct directory, your Rocks.Tests/bin/debug folder, but the file it asks for - one of the dependencies, a Microsoft dll, is not present there.  Not sure where it should be, but at first glance, it don't seem to be an adapter failure.   Normally the cure is to use the TestContext.CurrentContext.TestDirectory, but you figure it out yourself, and it seems correct too.
