### ISSUE TITLE
NUnit3TestAdapter 3.8.0-alpha1 Could not find symbol provider type Mono.Cecil.Pdb.NativePdbReaderProvider

### ISSUE THREAD

**Issue by michael-x** [nunit/nunit3-vs-adapter#325]
When setting

```
<DebugType>Full</DebugType>
```

the test adapter does not discover tests anymore. In `dotnet test` I get a message

```
Could not find symbol provider type Mono.Cecil.Pdb.NativePdbReaderProvider
```

Unfortunately full debug information is currently required by OpenCover in order to get coverage information.

**Comment by rprouse** [comment]
Thanks, should be an easy fix. I didn't include the native PDB reader because I didn't think it was needed, but I didn't think of your use case.

**Comment by maartenoosterhoff** [comment]
Any news on this issue? Any info is much appreciated.

**Comment by jiaxuyang** [comment]
I solve it by adding reference to "Mono.Cecil".
```xml
<PackageReference Include="Mono.Cecil" Version="0.10.0-beta6" />
```
env:
netcoreapp2.0
NUnit3TestAdapter 3.8.0

**Comment by rlordcardano** [comment]
Referencing that version of Mono.Cecil works for me too. Will this be included in a future version of NUnit3TestAdapter?

**Comment by rprouse** [comment]
We copy Mono.Cecil into the adapter NuGet package. We did that for two reasons, first, we use different versions for running .NET Framework tests and for .NET Core tests. The second reason is that Mono.Cecil 10.0 is still pre-release and NuGet raises warnings when a non-pre-release package depends on a pre-release package.

**Comment by rlordcardano** [comment]
Hi @rprouse - I see that you've added Mono.Cecil into the package. Strangely enough, even though it's the same version as I've referenced (0.10.0-beta6), the test runner (console or through ReSharper) doesn't pick up the unit tests if Mono.Cecil isn't added as a NuGet reference, as @jiaxuyang mentioned. At least, that's what I'm experiencing...

**Comment by tswiftma** [comment]
Adding the <PackageReference Include="Mono.Cecil" Version="0.10.0-beta6" /> reference to my test csproj worked for me

**Comment by jnm2** [comment]
This was fixed in https://github.com/nunit/nunit3-vs-adapter/pull/454 and is available now at https://www.nuget.org/packages/NUnit3TestAdapter/.
