### ISSUE TITLE
Test detection

### ISSUE THREAD

**Issue by ImoutoChan** [nunit/nunit3-vs-adapter#326]
Hi

I'm not sure if it's an adapter problem, but if I have test cases like this:

```
[TestCase("https://ll.userapi.com/c626224/v626224431/6291e/z3mBzT9q104.jpg")]
[TestCase("https://ll.userapi.com/c626224/v626224431/5f1bf/v4xwKIUIaaM.jpg")]
[TestCase("https://ll.userapi.com/c626224/v626224431/5d89e/vdcpu2qHqWc.jpg")]
[TestCase("https://ll.userapi.com/c626224/v626224431/5dc6b/QqJkFerqHso.jpg")]
[TestCase("https://ll.userapi.com/c626224/v626224431/5f89c/dGIwli6c92s.jpg")]
[TestCase("https://ll.userapi.com/c626224/v626224431/5decf/VvTpyU8A0Zc.jpg")]
```

Some of them are not counted as separate tests
```
------ Discover test started ------
NUnit Adapter 3.8.0.0: Test discovery starting
NUnit Adapter 3.8.0.0: Test discovery complete
A test with the same name 'IqdbApi.Test.IqdbApiTest.SearchUrlSuccess("https://ll.userapi.com/c626224/v62622...")' already exists. This test is not added to the test window.
A test with the same name 'IqdbApi.Test.IqdbApiTest.SearchUrlSuccess("https://ll.userapi.com/c626224/v62622...")' already exists. This test is not added to the test window.
A test with the same name 'IqdbApi.Test.IqdbApiTest.SearchUrlSuccess("https://ll.userapi.com/c626224/v62622...")' already exists. This test is not added to the test window.
A test with the same name 'IqdbApi.Test.IqdbApiTest.SearchUrlSuccess("https://ll.userapi.com/c626224/v62622...")' already exists. This test is not added to the test window.
A test with the same name 'IqdbApi.Test.IqdbApiTest.SearchUrlSuccess("https://ll.userapi.com/c639830/v63983...")' already exists. This test is not added to the test window.
A test with the same name 'IqdbApi.Test.IqdbApiTest.SearchUrlSuccess("https://ll.userapi.com/c626224/v62622...")' already exists. This test is not added to the test window.
========== Discover test finished: 15 found (0:00:00.8405149) ==========
```
I don't think that argument trimming is a good idea.

**Comment by CharliePoole** [comment]
Suppose the argument were 1000 characters long? Would trimming be a good idea then? 😉 

In order for arguments to be reasonable to view and also to keep the test name within the limit accepted by VS, we truncate to 40 chars. It used to be 20, but that seemed to cause too many collisions. You can use the TestName parameter of TestCase to change this limit or to give the test some arbitrary name. Since the long name is probably not that good for you to read, I would suggest a meaningful name be used.

**Comment by grokky1** [comment]
Pity, agree with OP 40 chars is too little when testing URLs. The workaround is nice but makes the tests ugly. 😆

**Comment by ChrisMaddock** [comment]
Last time this came up, we added `PackageSettings.DefaultTestNamePattern` to the EngineSettings to allow the amount of trim to be configured by the test runner (in this case, the VS adapter). 

This is currently hardcoded in the adapter, but it would be feasible to expose it via a .runsettings file, if someone was interested enough to do a PR, and @nunit/vs-extensions-team were willing to accept it. 🙂 

https://github.com/nunit/nunit3-vs-adapter/blob/18d0d2bab627e6c568bc34482e5a621133176df9/src/NUnitTestAdapter/NUnitTestAdapter.cs#L208

**Comment by jnm2** [comment]
IMO we should let VS be the bad guy and impose no length limit that VS doesn't.
We could also be smarter about what part of the string to trim, _if_ VS is forcing a trim.

**Comment by jnm2** [comment]
If the generated test name was 1000 chars and it doesn't break VS, I say keep it. It should be up to the test writer's judgment whether it's a problem worth fixing by specifying a custom name.

**Comment by OsirisTerje** [comment]
@ChrisMaddock What is the format for the PackageSettings.DefaultTestNamePattern ?
And what happens if this setting is *not* set from the adapter?  What is the NUnit default?

**Comment by ChrisMaddock** [comment]
@OsirisTerje - I'm not totally sure, and it's difficult to check on my phone, but I believe the default format is with no max-length.

**Comment by ChrisMaddock** [comment]
The format follows the NUnit template based naming stuff. There's docs for this - afraid, links are awkward from my app, but it's linked from the SetName() method in the TestCaseAttribute docs page. :-)

**Comment by OsirisTerje** [comment]
Thanks, for ref, I found it here https://github.com/nunit/docs/wiki/Template-Based-Test-Naming .
I see no reason not to let this too be optionally set from the runsettings, but I think the default should stay, just so we don't introduce a breaking change in naming.
