### ISSUE TITLE
NUnit 3 adapter doesnt fire RecordStart and RecordEnd Synchronously

### ISSUE THREAD

**Issue by acesiddhu** [nunit/nunit3-vs-adapter#328]
In Nunit3 adapter we see that RecordStart and RecordEnd events are not fired Synchronously. It used to work in NUnit2. Ideally the test case should not start till RecrodStart call comes backs. 

This is needed for data collectors (data collectors that work at test case level) to work fine. Ideally the event should be in below order (for two test cases)

Nunit Fire RecordStart for TestCase1
Process Start at Data collector level for for TestCase1
Execute test TestCase1
NUnit Fire RecordEnd for TestCase1
Prcoess End at Data collector level for TestCase1

Nunit Fire RecordStart for TestCase2
Process Start at Data collector level for TestCase2
Execute test TestCase2
NUnit Fire RecordEnd for TestCase 2
Prcoess End at Data collector level for TestCase2

**Comment by CharliePoole** [comment]
NUnit's own events are intrinsically synchronous and the adapter is merely an adapter, passing those same events on to VS. Obviously, it's not possible to transform asynchronous events to synchronous at the adapter level.

We previously accepted a PR from from Microsoft, which involved changes to multiple levels (adapter, engine and framework) to force the events to be synchronous when called with specific settings. The PR for the adapter part of it is #235. See issue #234 for a more extended discussion.

You should pay attention to the fact that __multiple__ settings are needed to make this work. You must not only use the SynchronousEvents setting that @drognanar  added but must also ensure that no parallelism is used by setting the number of test workers to zero. These settings should __only__ be used when you need them, unless you want to degrade performance for users.

**Comment by acesiddhu** [comment]
I tried following runsettings and it didn't work for me. Anything I am missing?

<RunSettings>
  <Nunit>
    <NumberOfTestWorkers>0</NumberOfTestWorkers>
    <SynchronousEvents>true</SynchronousEvents>
  </Nunit>  
</RunSettings>

**Comment by CharliePoole** [comment]
NUnit does not recognize the SynchronousEvents setting in the run file - sorry if my earlier comment led you to believe that. If you examine the referenced PR, you will see that this facility may only be activated by setting `RunSettings/InProcDataCollectionRunSettings/InProcDataCollectors`. This is __not__ a setting we make available to users.

A bit of history may help...

This capability was originally needed by one of the Microsoft product groups. We did not wish to  support it, for two reasons:
1. Our events are asynchronous for performance reasons and we didn't want to change that.
2. The request was for support of a feature that is only available in certain higher-level Visual Studio SKUs. Our policy is to add support only for VS features that are available in the community edition.

A compromise was reached, whereby someone from the Microsoft group would add the needed code in a way that did not affect any users directly and maintain it as needed in the future. Hopefully, that explains why I can't tell you a lot about how it works, except by reading the code.

If you need to use this feature for data collectors - I assume you are doing this for a Microsoft product - you will have to figure out if the hook added by @drognanar is something you can use.

One question... are you using the start and end events to time tests? If so, why not just use the time reported by NUnit. NUnit knows the elapsed time for each test, even when tests are run in parallel, and reports it as part of each result.
