### ISSUE TITLE
Test Fixture Name is not displayed in TFS Test Results

### ISSUE THREAD

**Issue by mike9182** [nunit/nunit3-vs-adapter#330]
The build results in TFS show only the method name. They do not show the test fixture name or the fully qualified name. I did not find this information in the TRX file attached to the test run. Perhaps this is part of the issue?

`<UnitTestResult executionId="ca54fe17-1c39-4e36-aad5-831ae78aeeb6" testId="07d9fc54-97f1-4928-914a-d8781d141956" testName="Record_should_be_created" computerName="TFS1" duration="00:00:32.1470000" startTime="2017-05-17T22:15:51.0000000-04:00" endTime="2017-05-17T22:16:23.0000000-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="ca54fe17-1c39-4e36-aad5-831ae78aeeb6" />`

**Comment by CharliePoole** [comment]
The adapter passes the test name in full to VS, which includes the fullname of the method, plus any arguments. I'm not sure what we can do about how the results are represented in the TRX file. Does anyone else have any suggestions?

**Comment by jnm2** [comment]
Doesn't the .trx have elements similar to `<TestMethod codeBase="test_assembly.dll" className="Name.Of.Fixture" name="Name_of_test_method" />`?

**Comment by OsirisTerje** [comment]
I got this from Pratap: 
I tried a repro; here is what gets emitted to the trx file:

    <UnitTest name="TestMethod" storage="c:\users\pratapl\source\repos\nunit.tests1\nunit.tests1\bin\debug\nunit.tests1.dll" id="4f4e894e-0a59-498b-8e1f-bbd55488b455">
      <Execution id="ea0de0aa-d7f5-4050-b946-087155a5f1f5" />
      <TestMethod codeBase="C:\Users\pratapl\Source\Repos\NUnit.Tests1\NUnit.Tests1\bin\Debug\NUnit.Tests1.dll" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter" className="NUnit.Tests1.TestClass" name="TestMethod" />
    </UnitTest>

I see that the fixture information is there in the trx file.

pratap
