### ISSUE TITLE
Tests using TestCaseSource will not run in adapter

### ISSUE THREAD

**Issue by Nicholi** [nunit/nunit3-vs-adapter#331]
Maybe this is more of a question, are they supposed to be able to run in VS Test Explorer?

I see the tests listed under "Not Run Tests" and they even display the value of the parameters in TestCaseSource. But seemingly no way to run them. I noticed they run fine with the console runner (dotnet test).

I **do not** have the VS extension adapter installed, running everything from nuget packages.

Barebones sample
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.6.1" />
    <PackageReference Include="NUnit.ConsoleRunner" Version="3.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0-alpha1" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
  
</Project>
```

```csharp
using System;
using NUnit.Framework;

namespace TestCaseSourceFails
{
    [TestFixture]
    public class Tests
    {
        [Test]
        public void NormalTest()
        {
            Assert.Pass();
        }

        public static Guid GetRandomGuid()
        {
            return Guid.NewGuid();
        }

        private static readonly Guid Test1Guid = GetRandomGuid();

        private static readonly Object[] RandomGuidSource = new Object[]
            {
                new Object[] { Test1Guid }
            };

        [TestCaseSource(nameof(RandomGuidSource))]
        public void TestCaseSourceTest(Guid testGuid)
        {
            // never runs in vs test adapter
            // but will run fine in console runner
            Assert.Fail();
        }
    }
}

```

**Comment by OsirisTerje** [comment]
The adapter differs from the console runner in it being a two-phase run when used in VS, one for discovery and one for execution, whereas the console runner only do one run.   So for the adapter in VS  it gets one value from discovery, and try to find that on its second visit, but then the value have changed.   This would btw also work on TFS/VSTS builds, which do it the same way.

The issue #97 has more information on this.

**Comment by CharliePoole** [comment]
Actually, there's a way for this to work. Just use NUnit's random facilities rather than external facilities. I'm not looking at the code right now and I can't remember what we support for Guids. Look at RandomAttribtue and TestContext.Random as two places to get random values.

If you get the random values from NUnit, both passes of the adapter will use the same values.

**Comment by OsirisTerje** [comment]
Just checked the Random wiki page (https://github.com/nunit/docs/wiki/Randomizer-Methods)  , and there is no Guid generator there.  Perhaps an idea to add that?

Changing code to return a long from the Random gen, makes it work:
![image](https://user-images.githubusercontent.com/203432/27108019-8e613ef2-509b-11e7-9280-6e7a0290b584.png)

**Comment by jnm2** [comment]
We should perhaps consider adding a `NextGuid()`. It's not as straightforward as setting all 128 bits randomly.

**Comment by jnm2** [comment]
https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29

**Comment by CharliePoole** [comment]
I'd be in favor of that as a low-pri backlog item.

**Comment by Nicholi** [comment]
I attempted to use the Randomizer in TestContext, however it is throwing a null reference exception while running the test. I essentially made the same changes as @OsirisTerje 

> Message: System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
>   ----> System.TypeInitializationException : The type initializer for 'TestCaseSourceFails.Tests' threw an exception.
>   ----> System.NullReferenceException : Object reference not set to an instance of an object.

Are we sure this is actually working? Also sidenote in my IDE (vs2017 with latest updates) has a red squiggly line under the usage of the randomizer (not an error though), and hints that I should reference System.Private.CoreLib. I attempted to add Microsoft.NETCore.Runtime.CoreCLR to the project (which I assume is the correct package for netcore), but the "warning" remains. The project builds and runs fine otherwise.

Code spam again
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.7.1" />
    <PackageReference Include="NUnit.ConsoleRunner" Version="3.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0-alpha1" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
  
</Project>
```
```csharp
using System;
using NUnit.Framework;

namespace TestCaseSourceFails
{
    [TestFixture]
    public class Tests
    {
        [Test]
        public void NormalTest()
        {
            Assert.Pass();
        }

        public static Int64 GetRandomGuid()
        {
            var ctx = TestContext.CurrentContext;
            var randomizer = ctx.Random;
            // the following line has weird squiggly error in vs
            // Module 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' should be referenced
            return randomizer.NextLong();
        }

        private static readonly Int64 Test1Guid = GetRandomGuid();

        private static readonly Object[] RandomGuidSource = new Object[]
            {
                new Object[] { Test1Guid }
            };

        [TestCaseSource(nameof(RandomGuidSource))]
        public void TestCaseSourceTest(Int64 testGuid)
        {
            // never runs in vs test adapter
            // but will run fine in console runner
            Assert.That(testGuid, Is.Not.Zero);
        }
    }
}
```

**Comment by CharliePoole** [comment]
By use the current context unless one has been established by NUnit. When you use it in a static constructor, the odds are that NUnit has not created anything yet. Since there are a few things in the context that __can__ be used in this situation, we create one for you. I can see that we need to do some work to make it clear that certain things are __not__ usable.

Your RandomGuidSource is used after a context is established. Just change it to a method and create the guid there.

**Comment by Nicholi** [comment]
However if I remove static from the method it can't be used with TestCaseSource, as it requires static members to be used (I believe this is correct?).

So really the main requirements in order to use TestCaseSource **with the vs adapter** is that any data loaded in the two phases must be the same. With that in mind that all data fed to TestCaseSource must also be initialized within a static context. Is there anyway to initialize NUnit's TestContext manually in order to use it in static members?

**Comment by jnm2** [comment]
@Nicholi, @CharliePoole is saying to change this
```c#
        private static readonly Int64 Test1Guid = GetRandomGuid();

        private static readonly Object[] RandomGuidSource = new Object[]
            {
                new Object[] { Test1Guid }
            };
```

Into this:
```c#
        private static Object[] RandomGuidSource = new Object[]
            {
                new Object[] { GetRandomGuid()}
            };
```

It's still static, but it doesn't run `GetRandomGuid` as part of the static type initializer. Rather, it runs `GetRandomGuid` when NUnit is calling `RandomGuidSource`.

**Comment by jnm2** [comment]
@CharliePoole I would like NUnit to be careful to not cause the type initializer to run without the test context in place. This is not the first time this has come up.

**Comment by Nicholi** [comment]
The same null reference exception is thrown for both of these examples

```csharp
        public static Int64 GetRandomGuid()
        {
            var ctx = TestContext.CurrentContext;
            var randomizer = ctx.Random;
            return randomizer.NextLong();
        }

        private static Object[] RandomGuidSourceMethod1()
        {
            return new Object[]
                {
                    new Object[] { GetRandomGuid() }
                };
        }

        private static Int64 Test2GuidAlt;

        private static Object[] RandomGuidSourceMethod2()
        {
            if (Test2GuidAlt == default(Int64)) Test2GuidAlt = GetRandomGuid();
            return new Object[]
                {
                    new Object[] { Test2GuidAlt }
                };
        }

        [TestCaseSource(nameof(RandomGuidSourceMethod1))]
        [TestCaseSource(nameof(RandomGuidSourceMethod2))]
        public void TestCaseSourceTest(Int64 testGuid)
```

**Comment by CharliePoole** [comment]
@jnm2 Only your second example is guaranteed to work. That's because anything we do to control when the Type initializer runs is runtime-dependent. It's a similar problem to ordering of attributes, where you can deduce the textual order of attributes for a particular runtime type and version, but not in general. Same thing here. Use of a method that is __called by NUnit__ at a particular point in the test lifecycle is the only way to guarantee it.

**Comment by jnm2** [comment]
@CharliePoole It's possible you caught me mid-edit, but I'm not catching on, I'm sorry! How is either example (as copied by Nicholi) is causing `GetRandomGuid` to run as part of the type initializer? He says both examples are causing NRE.

**Comment by CharliePoole** [comment]
@jnm2 Did you edit after posting? I thought your first example was __not__ a method but a static field. Let's move on to what @Nicholi is doing in his code. 😄

**Comment by Nicholi** [comment]
From what I can see while debugging the TestExecutionContext wrapped inside the TestContext itself is what is null.

**Comment by jnm2** [comment]
@jnm2 Did you edit after posting?

😳 yerp...

**Comment by CharliePoole** [comment]
@Nicholi Your first method "should" work. So should your second, but it has unneeded extra stu
In this case, by "should", I mean something like "I'd really like it to." I see it doesn't. 😄 At the point where you are calling it there is no TestExecutionContext established. There is a Randomizer for the test but you don't have any way to access it, because we haven't put it anyplace where you can get at it. We do that when we execute the test, not when we create it. This is one of those "concept bugs" meaning "I never imagined anyone would try to do this, so I didn't allow for it!"

The `RandomAttribute` could be made to work for this, bugt looking at it makes me wish for an overload with no arguments, to get a single datapoint. Then this would work...

```C#       
        public void TestCaseSourceTest([Random] Int64 testGuid)
```

Currently, I think this works...

```C#       
        public void TestCaseSourceTest([Random(Int64.MinValue, Int64.MaxValue, 1)] Int64 testGuid)
```

But that's pretty awful!

I think there is a fairly deep problem here with use of random values in TestCaseSource and even with the RandomAttrbiute.

**Comment by Nicholi** [comment]
I think I may have found where the NRE is occuring.

First I had to manually initialize the TestExecutionContext.
```csharp
        static Tests()
        {
            var executionCtx = new TestExecutionContext();
            executionCtx.EstablishExecutionEnvironment();
        }
```

Then I saw how the Randomizer was initialized, and it pulls the seed from the **CurrentTest**. However since we are not within the context of a test (everything being initialized statically), CurrentTest is also null. And not really seeing any way to manually initialize that.

**Comment by CharliePoole** [comment]
Note the problem I'm describing is in the framework... has an extra-bad effect in the adapter due to the two-pass issue. I'll create a framework bug.

**Comment by Nicholi** [comment]
The problem being in here I am guessing?

```csharp
        public Randomizer RandomGenerator
        {
            get
            {
                if (_randomGenerator == null)
                     // CurrentTest is null
                    _randomGenerator = new Randomizer(CurrentTest.Seed);
                return _randomGenerator;
            }
        }

```

**Comment by CharliePoole** [comment]
@Nicholi Yup!

We are not checking for null context at all there and we should. However, that will only give you a different error message, which isn't much help.

I think this is fairly fundamental. What we did in the past was to create CUrrentCOntext on the fly if it was null. However, that leads to hard to understand errors, since the context can't actually be initialized correctly. I made the decision to stop doing that and fix whatever came up as a result. Lots of stuff got fixed, in fact, but this is a new one.

**Comment by Nicholi** [comment]
Just noticed that CurrentTest.Seed is never initialized or ever modified either. I had thought maybe the seed would still be different between runs, and there was just some magic for the two phase vs-adapter caching the seed. But it's actually all very simple in the end.

So if I did want to continue using TestCaseSource with random data I could use any old class based off of Random or RandomNumberGenerator as long as I seed with an unchanging value, correct?

**Comment by Nicholi** [comment]
Just noticed that CurrentTest.Seed is never initialized or ever modified either. I had thought maybe the seed would still be different between runs, and there was just some magic for the two phase vs-adapter caching the seed. But it's actually all very simple in the end.

@CharliePoole So if I did want to continue using TestCaseSource with random data I could use any old class based off of Random or RandomNumberGenerator as long as I seed with an unchanging value, correct? At least until the bug/design issue you mentioned is resolved and we can use TestContext from a static area.

**Comment by CharliePoole** [comment]
@Nicholi That's correct. You would get repeatability that way, just as NUnit gives you. What you wouldn't get is __non-repeatability__ which NUnit also gives you if you __don't__ provide a seed on the command line. Still, it would be a good way to go while waiting for an enhancement from us.

**Comment by Nicholi** [comment]
For anyone that reads this issue in the future, to stay within the NUnit ecosystem you can easily create and use NUnit's Randomizer class as it has its own factory constructor (also handling the seed generation).

```csharp
        public static Int64 GetRandomGuid()
        {
            var randomizer = Randomizer.CreateRandomizer();
            return randomizer.NextLong();
        }
```

**Comment by jnm2** [comment]
Note to all: `TestContext.CurrentContext.Random.NextGuid()` will be available in for the next release, thanks to @MikeFH's contribution. That will be the ideal way to handle this scenario going forward.
