### ISSUE TITLE
Add Test Attachment functionality

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit3-vs-adapter#332]
See https://github.com/nunit/nunit/issues/1670

**Comment by kdubau** [comment]
Is this available in any preview yet?

**Comment by ChrisMaddock** [comment]
@kdubau - if, like in https://github.com/nunit/nunit/issues/1670#issuecomment-303217309, you're just interested in the entry being in the XML, that was just released in NUnit Framework 3.7. 🙂 I'm afraid I haven't got round to writing any docs yet, but just use `TestContext.AddTestAttachment(string filepath, string description = null)`.

Integration with the VS adapter I'm afraid I haven't got round to yet.

**Comment by ChrisMaddock** [comment]
In terms of timescales, it's probably going to be a few weeks before I can get on to it - I can only really get stuff like this done at weekends, and have a busy few coming up. More than happy for someone else to take over this part, and do the PR though. 😄 I'll unassign myself for now to show that, although will come back to it in time, if nobody else wants to do it!

**Comment by kdubau** [comment]
Hey, @ChrisMaddock - yep I found the source for adding the attachment to XML. I was just being greedy by looking for it in VS test explorer 😛. Perhaps I can take a look at this adapter integration if i'm feeling ambitious, but it'd be my first experience in the realm of VS extension development.

**Comment by CharliePoole** [comment]
@kdubau You would even be helping us quite a bit if you outlined what you want to see in the adapter!

**Comment by kdubau** [comment]
I was really just looking for something like the screenshot here: https://github.com/nunit/nunit/issues/1670#issuecomment-232896282

**Comment by ChrisMaddock** [comment]
Please feel free, @kdubau 👍 

@CharliePoole @kdubau - I was hoping to just emulate the MSTest adapter, and use the Visual Studio interface for attachments like in that screenshot. I did a little digging, the Visual studio TestResult object has an Attachments property, which holds and Attachment set. Hopefully, we can interface with it in the same way as the MSTest adapter does [here ](https://github.com/Microsoft/testfx/blob/a0cfbcffe9f292064bf57d784eae9e2bc3ea2103/src/Adapter/MSTest.CoreAdapter/ObjectModel/UnitTestResult.cs#L178) - I haven't tried it out yet though!

**Comment by CharliePoole** [comment]
@ChrisMaddock Amazing! I had no idea that the MSTest adapter was open source. And it's even MIT-licensed, so I don't have to be afraid to look at it! 😸

**Comment by Daniel-Svensson** [comment]
Sorry for no heads up if anybody else has been working on this, but I ran into this yesterday and wanted to se how hard it would be so I gave it a try and think I have a working solution. 

I haven't tried it from within visual studio or vsts/tfs yet.
If it makes it into alpha-2 I can test how it works in tfs 2017 at work

**Comment by OsirisTerje** [comment]
Awesome!    When you think you have it sort of working, just give us a Pull-Request :-)

**Comment by skliamis** [comment]
@CharliePoole would it be possilble to pass/map the added attachment to VSTS through NUnit Testadapter? see also screenshot
![2017-11-16 10_40_23_testautomation - microsoft visual studio](https://user-images.githubusercontent.com/24651933/32884638-49ef3ffe-cabb-11e7-928b-4aefae4e0471.png)

At the moment i see the attachments only in Visual Studio Test Explorer.

**Comment by CharliePoole** [comment]
@OsirisTerje Any idea why this doesn't work for VSTS?

**Comment by OsirisTerje** [comment]
@CharliePoole Strange, it should "just work".....  Got to try to repro it.

**Comment by CharliePoole** [comment]
@skliamis Make sure it's running the corrected version.

**Comment by acesiddhu** [comment]
@skliamis Are you using Visual Studio test task?
Also can you share the trx file with me? you could get it by clicking 1/1 Passed..... (then check right side of the screen)

**Comment by skliamis** [comment]
Problem solved. Thank u @CharliePoole.
Local i had NUnit Testadapter 3.9 but in VSTS Repo there was still 3.4 & 3.9. So Test task took 3.4 per default.
