### ISSUE TITLE
NUnit Test Adapter Reports OutOfMemoryException while detecting tests in VS2017

### ISSUE THREAD

**Issue by stefanhendriks** [nunit/nunit3-vs-adapter#333]
I installed the NUnit 3 Test Adapter plugin today (released today I believe, 28/05/2017). I had to re-open my Solution. I use VS2017 Then the following appears:

![image](https://cloud.githubusercontent.com/assets/1332066/26529486/d2c3e6a4-43c0-11e7-93cd-5b9cc333cb42.png)

Any ideas what is going on?

If you need any more information, tell me where to look for it and I'll dig it up.

**Comment by OsirisTerje** [comment]
No release today, you're using the 3.7, released January 2017, and no known error like you have, so most likely an issue in your own code.  
Have you tried a simple example to check if your installation is ok?

**Comment by stefanhendriks** [comment]
ah yes, I was looking at the wrong date field (installed date :)). 

The unit tests are straight forward, and works ok for a friend of mine on his machine. Any log I can look at to see the stacktrace?

**Comment by stefanhendriks** [comment]
Interestingly, when creating a new project (.net core, with 4.6) I also cannot get anything to work. Just installing NUnit (3) in the project. Create a new test. Use the Nunit test adapter. It won't find any tests to run. (no mentioning of OutOfMemoryException or whatsoever).

Something is seriously messed up but I don't have any feedback :/

**Comment by OsirisTerje** [comment]
I just looked at the message above, it said .net 461, so I assume you had a .net framework 4.6.1 project. If you want to run .net core, then you should try the 3.8.0-alpha01 version, which is the first one supporting .net core. 
Does a .net 4.6 unit test work?

**Comment by stefanhendriks** [comment]
I tried running with alpha 3.8.0 on command line:

![image](https://cloud.githubusercontent.com/assets/1332066/26541269/51cfe288-4455-11e7-82b9-f15cb3ca578b.png)

**Comment by OsirisTerje** [comment]
If you create a new *small* test project, using first standard .net framework 4.6.1, does that run?  If so, check the same for .net core?  If these works, then you know your  setup is correct, and the error you see above comes from your own code.  
If we assume that:  Have you tried debugging your code?  Does the breakpoints work?  
Can you create a small repro project for this case?

**Comment by stefanhendriks** [comment]
I created a new small test project. Basically created 'new project' from VS2017 template. I'll prepare a repository for this. It works out of the box with the Microsoft Testing framework. I'll change it into Nunit and see if it also works.

Unfortunately the standard generated project uses the old `csproj` format. So I also need to change that. I'll try to keep the commits in such a way so you can replay several scenario's.

**Comment by rprouse** [comment]
@stefanhendriks I have posted information on testing .NET Core using the adapter on my blog at http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/. Have you been through that yet?

The OutOfMemoryException is likely a duplicate of #296

Things to check,

- .NET Core tests need to target .NET Core (not .NET Standard)
- .NET Core tests should use the new CSPROJ format
- Check your NuGet references match those in my blog post
- If you are multi-targeting, it is very buggy in Visual Studio. I think putting .NET Core first tends to work.

**Comment by rprouse** [comment]
@stefanhendriks if you can, post a copy of your failing CSPROJ file here so we can take a look.

**Comment by stefanhendriks** [comment]
@rprouse thx for replying. I've been pretty ill the past few days. I'll try to get back to you asap.

**Comment by OsirisTerje** [comment]
@stefanhendriks Did you have any luck in repro'ing this?  Or can it be closed?

**Comment by stefanhendriks** [comment]
all, Unfortunately I had been sick again for a long time. I did not do anything about this. I did ask around for others which used the same (private) project on a fresh machine. They did not have any issues. They also did not need to install any Nunit related adapter. 

So I guess it is a combination of things on my machine. If no-one else had this issue I suppose you can close this. If I ever get back into it - I'll comment here.
