### ISSUE TITLE
Category at class level hides Category at Test Method level in NUnit v3.7

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#336]
@VirendraSinghRathore24 commented on [Mon Jun 05 2017](https://github.com/nunit/docs/issues/209)

Issue with NUnit Category attributes. (Verson 3.7)
 - Add one Category for Test Method 
 - Add one Category for same Class
 - Run test case and you will not see Method level Category under traits 

---

@CharliePoole commented on [Mon Jun 05 2017](https://github.com/nunit/docs/issues/209#issuecomment-306223279)

This repository is for the nunit documentation and issues here are about errors in the docs.

I'm moving this to the nunit 3 adapter repo.

**Comment by OsirisTerje** [comment]
I can't repro this:
![image](https://user-images.githubusercontent.com/203432/27106081-26538756-5092-11e7-8b39-2555ec28a67a.png)

Do you have a repro?

Which VS version ?

**Comment by CharliePoole** [comment]
@OsirisTerje The OP filed this under docs and I moved it here because it sounded like the adapter. Maybe we don't actually know what software he is using and having problems with. 😦 

@VirendraSinghRathore24 Can you help us out here?

**Comment by ocmyhome** [comment]
I'm seeing the same issue as the OPer.

VS = 2015
NUnit = 3.8.1
NUnit.ConsoleRunner = 3.6.1
NUnit3TestAdapter = 3.8.0

Set the class category to something, and set the test method category to something else.  When running the test and I get the "Category" property from the TestContext, it'll only return the class property category.

![000230](https://user-images.githubusercontent.com/24324485/31294502-f1cefe18-aa8f-11e7-8e38-d77a95ad6f1b.png)

![untitled](https://user-images.githubusercontent.com/24324485/31294517-0331eaa8-aa90-11e7-8c5b-3ee4a0062097.png)

**Comment by ocmyhome** [comment]
After further testing, I found the following:

When you run a single test from the test explorer in VS...

1) Only class categories are visible in the [OneTimeSetUp] phase of the test.
2) By the time you reach the [SetUp] part of the test, only test method categories are now visible.  Class categories are no longer visible.
3 By the time you reach the test itself, only the test method categories are visible.
4 At the [TearDown] part of the test, still only the test method categories are visible.
5 Finally at the [OneTimeTearDown] part of the test, only the class category is visible.

If possible, having access to all categories (class of the test and test method) at all phases of the test, would be ideal.  If not, then all categories between the [SetUp] and [TearDown] phase of the test, should give testers enough to work with...

**Comment by CharliePoole** [comment]
@ocmyhome Your issue is a different one. The OP was reporting that the category does not show up as a trait in the Test Explorer.

In your case, you are asking for the category of the fixture to appear as if it were a category of the test case. It isn't, so it doesn't.

NUnit properties and categories are not "inherited" by child tests. In order to satisfy VS, we create "traits" from them, but NUnit still works internally as it always has. You will only see the class category in the context for the fixture. That is only available to you in the OneTimeSetUp and OneTimeTearDown methods.

**Comment by CharliePoole** [comment]
@ocmyhome BTW we have several framework issues asking for visibility of the parent properties from the cold test.

**Comment by ocmyhome** [comment]
@CharliePoole Thanks for the clarification.  I'll design our test framework accordingly.

**Comment by jnm2** [comment]
> NUnit properties and categories are not "inherited" by child tests.

Why would inheritance of categories be a bad thing? So far, everyone's intuition seems to be that specifying most attributes on the fixture is a shortcut for specifying them on every method.

**Comment by OsirisTerje** [comment]
@jnm2 It is, in the context of VSTest.  See my comment and screenshot near the top.  But it is not if you try to extract the categories in the test code afterwards.

**Comment by jnm2** [comment]
So far, I do wish we had an inheritance model in NUnit framework itself. If it makes sense not to inherit categories, I'd like to gain an understanding of why.

**Comment by CharliePoole** [comment]
Saying that categories are not inherited in NUnit is obviously (I should have thought) not saying it's a bad idea. Saying that the adapter isn't the place to discuss changing it, ditto.

**Comment by jnm2** [comment]
Sure, we can start an issue to discuss it at nunit/nunit. I wanted to point out yet another case where people expect inheritance.

**Comment by CharliePoole** [comment]
Fine. Just stop misquoting other folks in order to strengthen your argument.

**Comment by jnm2** [comment]
😕 I certainly wish to continue being conscientious about it. An example might help me?

**Comment by jnm2** [comment]
😕 I certainly wish to continue being conscientious about it. If you believe I've done something in poor faith, I'd prefer (and welcome) an email. If you don't believe that, but I'm simply missing the point, I'd like to know so I can correct it.

**Comment by jnm2** [comment]
😕 Charlie, I apologize. I certainly wish to continue being conscientious about it. I've done something that comes across to you in poor faith, I'd prefer (and welcome) an email. If you don't believe that, but I'm simply missing the point, I'd like to know so I can correct it.

**Comment by CharliePoole** [comment]
@jnm2 Sorry you are missing the point. I thought the context was clear and I don't have an easy way to do links on my phone. I edited my comment to point to yours.

**Comment by jnm2** [comment]
Oh! I'll try to be clearer next time. I did not think you had called inheritance a bad idea when I wrote that, and that wasn't my point. Like you said, you obviously didn't say it was a bad idea and I didn't imagine anyone would think I was saying that. This is hard for me.
If it helps clear the air, that was an attempt to use deferential language when talking about the status quo: there are probably reasons why we are where we are, I respect that even though I don't know what they are yet, and I'm asking to know those reasons.

**Comment by jnm2** [comment]
@CharliePoole My wife confirmed that she would have understood my wording the same way you did. I'm really sorry for the annoyance I caused.

**Comment by CharliePoole** [comment]
@jnm2 At the very least, I imagine our wife knows you about 10000 times better than I do. I only know your emails and I'm never likely to actually know __you__. Neither do you know me, for that matter. I only have actions and words in this and other online forums to go by, just like you.

As I stated, we can discuss this privately if you like. I believe it's inappropriate to go any further here.

**Comment by jnm2** [comment]
Since she agreed with you, it's ironic that you would cut that down. 😁

As far as I can tell, you did not state that. I however did state that, before your second-to-last comment; I felt it had already uncomfortably crossed the line of propriety. You continued here, twice, after sincere apologies. Please don't end this awkward and unnecessary public conflict by taking credit for asking for a private discussion.

**Comment by CharliePoole** [comment]
@jnm2 I'm sorry, but I literally didn't understand the last comment. I'm definitely not taking credit for anything - if there is anything to take credit for here. I also don't know what it means to "cut down" a comment. Mock it? Refute it? I wasn't doing either of those things, but saying that your wife has the benefit of knowing you and can make more accurate comments. I don't. That seems reasonable still.

I do understand that you were offended by what I wrote originally wrote and are still reacting to it. But you did ask that we communicate about it privately, didn't you?

**Comment by jnm2** [comment]
'Cut down'- you were explaining it away and communicating condescension.

Yes, I did ask to communicate privately, which you ignored by continuing here. You later said, "As I stated, we can discuss this privately," which is factually incorrect. That makes it sound like you were thoughtful party and I was not, when it was exactly reversed.

Last, I'm *not* the one who took offense. I'm alarmed and mystified as to the best course of action, which I usually guess to be apology. What you are calling me taking offense is actually me giving it time, thinking it might be time to start standing up and start calling out what appear to be unfair or harmful actions, and hoping you become aware of the effect you are having.

If this was the first time this dynamic became a problem, I would certainly not be speaking up. I prefer to back down but I'm afraid that is enabling the atmosphere. I hope you don't just explain away this appeal as me being offended because these actions matter; to me, and from what I've seen on this forum, to others.

**Comment by CharliePoole** [comment]
I didn't intend to  communicate condescension, nor is that a feeling I have. I'm sorry - but also puzzled - that you took it that way - I made a lot of effort to be clear.

With respect, I think you are making a big deal out of a pronoun. You suggested, I agreed. It didn't happen. I believe that it's up to you to make it happen, mainly because you're the guy with something to say but also because there are various ways to do it. It could be private to just the two of us, or to the Core Team or between you, me and the project leader. It could be via email, chat or voice. It all kind of depends on what you think will work.

Your last comment suggests some pretty nasty things about me. It's hard not to respond publicly, and I admit I'm wondering if that might be your intent. Anyway, I'm not going to respond. In a private discussion, I will.

I'm happy to discuss anything more here, so long as it's part of #336.

**Comment by jnm2** [comment]
I'm sorry, and thank you. I appreciate your comment.
