### ISSUE TITLE
3.7.0 does not output NUnit3.TestAdapter.dll to the bin

### ISSUE THREAD

**Issue by madaz** [nunit/nunit3-vs-adapter#337]
Building a .Net 4.6.1 Windows Classic Desktop class library project in VS2017 does not copy the NUnit3.TestAdapter.dll library to the bin folder.

This is a problem when using the VsTest build task in Visual Studio Online Services as it looks in the project build output folders.

I have tried creating a class library project using a `project.json` format for nuget packages and also a separate class library project using the `packages.config` nuget format.

**Comment by rprouse** [comment]
Have you tried `3.8.0-alpha1`? Normally the VSTest build task in VSTS looks in the packages folder when using the packages.config.

**Comment by madaz** [comment]
I haven't tried the alpha version.

I did downgraded my project to use nuget NUnit3TestAdapter v3.4.1 
as that version puts the NUnit3.TestAdapter.dll into the class library bin output folder and works in VSTS.

From the VSTS logs , the Nuget Restore task would put all packages into a `C:\Users\buildguest\.nuget` folder and the VsTest task would look in the Source working folder (solution root and below)  and would never find the NUnit3.TestAdapter.dll.  Previous nunit versions would place NUnit3.TestAdapter.dll into the bin folder during build. MSTestv2Adapter also puts their dlls into the bin output folder too.

**Comment by rprouse** [comment]
Have you tried adding the .nuget folder in the advanced options for the VSTest task?

Adding the adapter to the bin folder is actually the wrong behavior, that is why it was changed. Earlier versions caused your tests to reference the adapter which is wrong, it is just a tool. You just need to specify the root directory for VSTest to search for adapters.

**Comment by madaz** [comment]
I did hard set the test adapted path to the buildguest .NuGet folder but they don't have a build variable for that path, and it seemed like a hack to hard code drive letter in a path.

 I did create an issue on their GitHub repo regarding this problem, but closed it when I thought this was the problem.

**Comment by madaz** [comment]
Linking vs-task issue https://github.com/Microsoft/vsts-tasks/issues/4463

**Comment by OsirisTerje** [comment]
What is changed in your build versus a default VSTS build?
A default VSTS build works with NUnit adapter 3.7 out of the box.  If you select the default VS build sequence, you don't even need to change any parameters to make this work:
Build result:
![image](https://user-images.githubusercontent.com/203432/27105807-369d0476-5091-11e7-8d91-e9cf558b93f4.png)
Build def:
![image](https://user-images.githubusercontent.com/203432/27105823-46c3a7ba-5091-11e7-97e7-0d3b30fee641.png)
Build settings for test (all defaults)
![image](https://user-images.githubusercontent.com/203432/27105851-5b548668-5091-11e7-9fa7-00533ff8bfcd.png)

Log file for package restore:
![image](https://user-images.githubusercontent.com/203432/27105869-6b3eb7ec-5091-11e7-83c5-10e0d184c52c.png)

So @madaz , what is different in your setup ?
