### ISSUE TITLE
Unhandled Exception when running through vstest.console.exe /listtests

### ISSUE THREAD

**Issue by JakenVeina** [nunit/nunit3-vs-adapter#338]
`vstest.console.exe [AssemblyName] /ListTests /UseVsixExtensions`

produces

> Information: NUnit Adapter 3.8.0.0: Test discovery starting
> 
> Warning: Exception System.ArgumentException, Exception thrown discovering tests
> in CommonUtilitiesTests.dll
> 
> Warning: Path cannot be the empty string or all whitespace.
> 
> Information: NUnit Adapter 3.8.0.0: Test discovery complete

I traced the exception to NUnitTestAdapter.cs, line 217.

```C#
var workDir = Settings.WorkDirectory;
if (workDir == null)
    workDir = Path.GetDirectoryName(assemblyName);
else if (!Path.IsPathRooted(workDir))
    workDir = Path.Combine(Path.GetDirectoryName(assemblyName), workDir);
if (!Directory.Exists(workDir))
    Directory.CreateDirectory(workDir);
package.Settings[PackageSettings.WorkDirectory] = workDir;
```

In this case, Settings.WorkDirectory returns null, which takes us into the first if statement, where Path.GetDirectoryName(assemblyName); is called for assemblyName "MyTestAssembly.dll", and returns an empty string, which then throws an exception when passed to Directory.CreateDirectory(workDir);.

Since PackageSettings.cs line 57 specifies that the WorkDirectory setting should be a full path, I implemented a fix in PR #339 that ensures workDir is always a full path by the time the Directory.Exists() check occurs.

**Comment by CharliePoole** [comment]
I don't understand why/how you have a value of "MyTestAssembly.dll" for assemblyName. I've only ever seen - and the code is written assuming - a complete rooted path passed to the adapter.

**Comment by JakenVeina** [comment]
I'd guess that value ultimately comes from the [AssemblyName] command line argument to vstest.console.exe. In this case, I'm running the executable directly from the directory containing the assembly.

**Comment by CharliePoole** [comment]
Fair enough. The code was originally written with the IDE in mind, which always passes in full paths.

**Comment by OsirisTerje** [comment]
PR merged, so closing the issue
