### ISSUE TITLE
Exception converting test method

### ISSUE THREAD

**Issue by grokky1** [nunit/nunit3-vs-adapter#354]
Using latest of everything. VS2017 15.2 (26430.15), NUnit 3.7.1, adapter 3.8.0-alpha1. Targeting .NET Core.

I get the following exception when trying to run tests:

```
------ Run test started ------
NUnit Adapter 3.8.0.0: Test execution started
Running selected tests in c:\foo\bar\bin\Debug\netcoreapp1.1\baz.Tests.dll
Exception System.ArgumentException, Exception thrown executing tests in c:\foo\bar\bin\Debug\netcoreapp1.1\baz.Tests.dll
Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
NUnit Adapter 3.8.0.0: Test execution complete
========== Run test finished: 0 run (0:00:03.4390416) ==========
```

So I use the [verbosity trick](https://github.com/nunit/nunit-vs-adapter/wiki/Tips-And-Tricks#setting-the-verbosity-level) and then try again, and get this:

````
------ Discover test started ------
NUnit Adapter 3.8.0.0: Test discovery starting
Exception System.ArgumentException, Exception converting foo.bar.BazTests.a_test_method
Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
NUnit Adapter 3.8.0.0: Test discovery complete
========== Discover test finished: 159 found (0:00:05.1380007) ==========
````

But that `a_test_method` is a regular test method that is defined and used in the regular way:
````
[Test]
public async Task a_test_method()
{
  // stuff
}
````

When I remove it, everything works. There are other tests in that fixture and they work fine.

I've had this problem many times before, and each time I manage to fix it by doing one or more of:
- rebuild solution
- terminate the vstest.*.exe processes
- restart VS
- restart windows

But nothing works for me now. How can I get to the bottom of this?

(Also, even after commenting out the offending test, a few days later, I'll gt the same problem for some other test, which I then comment out to get everything to work, etc. And sometimes after a few days of work, I uncomment a test and it works!)

**Comment by jnm2** [comment]
Can you share a repro .csproj?

**Comment by grokky1** [comment]
@jnm2 Yeah, here's the test project's csproj, but I suspect it's not out of the ordinary:

````xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.0</Version>
    <DebugType Condition="'$(TargetFramework)' != '' AND '$(TargetFramework)' != 'netcoreapp1.1'">Full</DebugType>
    <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.7.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0-alpha1" />
    <PackageReference Include="NSubstitute" Version="2.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Foo\Foo.csproj" />
    <ProjectReference Include="..\..\src\Bar\Bar.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
````

I seem to have all the problems of VS2017 reported by others in the issues - not discovering tests,  needing to terminate vstest.console.exe, etc. Maybe everything is related somehow. I'm quite certain by now it's the fault of VS itself.

**Comment by grokky1** [comment]
Since I upgraded to the stable version released a few days ago, I haven't had this problem again!

I don't get it though, the beta and the stable release have the same release notes. Were there any changes?

**Comment by jnm2** [comment]
That's interesting! @OsirisTerje might know.

**Comment by OsirisTerje** [comment]
@grokky1 @jnm2   Not sure what you mean by beta, there is only the alpha,  info on that is *only* here https://github.com/nunit/nunit3-vs-adapter/releases/tag/3.8-alpha1  .  Is that the one you mean?
There was no beta, just dropped a few rc's, but they didn't contain any notes.  
So the only released one is the stable 3.8.0.  And yes, there was a lot of changes in the last few hours to get it as stable as we could. 
If that one is working for this issue, that's good.

**Comment by grokky1** [comment]
@OsirisTerje Wait wait? You mean I was using an *alpha* all this time... No wonder it was so buggy! 😆 

Just kidding... Whatever you put into the stable is great, because not only is this problem gone (I hope), but I no longer need to terminate the vs runner processes `vstest.console.exe` etc. Good work, and thanks!

**Comment by OsirisTerje** [comment]
Seems it was fixed as a side effect, so i'll label it as Done :-)
