### ISSUE TITLE
ConfigurationManager doesn't find config file with "dotnet test"

### ISSUE THREAD

**Issue by gboucher90** [nunit/nunit3-vs-adapter#356]
NUnit: 3.7.1
NUnit3TestAdapter 3.8 Alpha 1
dotnet: .NET Core 2.0.0 Preview 2
OS: Win 7

Hello,
When run with "dotnet test" and NUnit, the actual entry point is the "testhost":
.nuget/packages/microsoft.testplatform.testhost/15.0.0/lib/netstandard1.5/testhost.dll

Then the System.Configuration.ConfigurationManager is looking at the wrong place and with wrong name as it's using `exeAssembly = Assembly.GetEntryAssembly();`
https://github.com/dotnet/corefx/blob/a8dce7c1c905e994c9519e0f26b0497832942a10/src/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs

I'm not sure where this should be fixed (I also posted an issue on corefx https://github.com/dotnet/corefx/issues/22101)

Thank you

**Comment by JamesIrish** [comment]
Likewise having the same issue but with an xUnit test project.   We are unit testing a NetStandard project that uses System.Configuration.ConfigurationManager for backward compatibility with a tonne of microservices that still target 462.  Running our xUnit tests via `dotnet test` results in nulls for all of our config.
Thanks

**Comment by PYasonau** [comment]
@gboucher90  just add https://www.nuget.org/packages/System.Configuration.ConfigurationManager/ to your project as nuget package

**Comment by jnm2** [comment]
This is an upstream issue with the .NET Core framework and Microsoft has decided not to fix.

https://github.com/dotnet/corefx/issues/22101#issuecomment-374415132:

> Closing. As stated, the recommendation here is to explicitly construct a `Configuration` object via `OpenMappedExeConfiguration()`. One can copy into `testhost.dll.config` as mentioned if in a pinch.

There's nothing I can think of that NUnit can do, so I'm closing the issue. Sorry about that.

**Comment by jnm2** [comment]
@jamescrowley Sorry, seems no one has.

**Comment by jnm2** [comment]
ℹ The .NET Core team is reinvestigating this issue for .NET Core 3.0: https://github.com/dotnet/corefx/issues/32095

**Comment by 0xced** [comment]
@Daniel-Khodabakhsh has provided a nice workaround in https://github.com/dotnet/runtime/issues/22720#issuecomment-621273186. You can copy the configuration file where it is expected by the configuration system:

```csharp
#if NETCOREAPP
using System.Configuration;
using System.IO;
using System.Reflection;
#endif

...

// In your global setup:
#if NETCOREAPP
    string configFile = $"{Assembly.GetExecutingAssembly().Location}.config";
    string outputConfigFile = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None).FilePath;
    File.Copy(configFile, outputConfigFile, true);
#endif
```

Also, there's an open pull request at https://github.com/dotnet/runtime/pull/35478 addressing this issue by using AppContext data.
