### ISSUE TITLE
Not all generic test fixtures can be found if unqualified type names match

### ISSUE THREAD

**Issue by chwarr** [nunit/nunit3-vs-adapter#357]
When using a [generic test fixture](https://github.com/nunit/docs/wiki/TestFixture-Attribute#generic-test-fixtures) if two of the types have the same unqualified name (e.g., Product.A.RedWidget and Product.B.RedWidget), only one of the tests will be found an executed.

In the following test, I expect two passed tests and two failed tests (total of four). Instead I get two failed tests and one passed test (total of three).

If I run the same test with nunit3-console (version 3.6.1), I see all four of the tests as expected.

    namespace Product
    {
        public interface IWidget
        {
            bool IsOK { get; }
        }
    
        namespace A
        {
            public class GoodWidget : IWidget
            {
                public bool IsOK => true;
            }
    
            public class BadWidget : IWidget
            {
                public bool IsOK => false;
            }
    
            public class RedWidget : IWidget
            {
                public bool IsOK => true;
            }
        }
    
        namespace B
        {
            public class RedWidget : IWidget
            {
                public bool IsOK => false;
            }
        }
    }
    
    namespace nunit_type_params
    {
        using Product;
        using Product.A;
    
        using NUnit.Framework;
    
        [TestFixture(typeof(GoodWidget))]
        [TestFixture(typeof(BadWidget))]
        [TestFixture(typeof(Product.A.RedWidget))]
        [TestFixture(typeof(Product.B.RedWidget))]
        public class TakesTypeParam<T> where T : IWidget, new()
        {
            [Test]
            public void IsGood()
            {
                var t = new T();
                Assert.That(t.IsOK);
            }
        }
    }

![Visual Studio Test Explorer only showing three tests instead of four](https://user-images.githubusercontent.com/10605667/28146702-9ef174fc-6730-11e7-97aa-82f68d5b1443.png)

* NUnit version 3.7.1
* NUnit3TestAdapater version 3.8.0-alpha1
* Targeting .NET Framework 4.6.1
* Visual Studio version details:
> Microsoft Visual Studio Enterprise 2015
> Version 14.0.25431.01 Update 3
> Microsoft .NET Framework
> Version 4.7.02046
>
> Installed Version: Enterprise
>
> Architecture and Modeling Tools   00322-90200-03147-AA547
> Microsoft Architecture and Modeling Tools
>
> UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.
>
> Visual Basic 2015   00322-90200-03147-AA547
> Microsoft Visual Basic 2015
>
> Visual C# 2015   00322-90200-03147-AA547
> Microsoft Visual C# 2015
>
> Visual C++ 2015   00322-90200-03147-AA547
> Microsoft Visual C++ 2015
>
> Visual F# 2015   00322-90200-03147-AA547
> Microsoft Visual F# 2015
>
> Windows Phone SDK 8.0 - ENU   00322-90200-03147-AA547
> Windows Phone SDK 8.0 - ENU
>
> .NET Portability Analyzer   1.1.10808.0
> Evaluates portability of assemblies across .NET platforms.
>
> ASP.NET and Web Tools 2015.1   14.1.21111.0
> ASP.NET and Web Tools 2015.1
>
> ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
> For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563
>
> ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
> For additional information, visit http://www.asp.net/
>
> Azure App Service Tools v2.9.5   14.0.20810.0
> Azure App Service Tools v2.9.5
>
> CodeMaid   10.4.53
> CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.
>
> Common Azure Tools   1.8
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
>
> Debugging Tools for Windows   10.0.10586.0
> Integrates the Windows Debugger functionality (http://go.microsoft.com/fwlink/?linkid=223405) in Visual Studio.
>
> JavaScript Language Service   2.0
> JavaScript Language Service
>
> JavaScript Project System   2.0
> JavaScript Project System
>
> JetBrains ReSharper Ultimate 2015.2   Build 103.0.20150818.200216
> JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.
>
> Microsoft .NET Core Tools (Preview 2)   14.1.21111.0
> Microsoft .NET Core Tools (Preview 2)
>
> Microsoft Azure Mobile Services Tools   1.4
> Microsoft Azure Mobile Services Tools
>
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40923.2
>
> NuGet Package Manager   3.5.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
>
> PreEmptive Analytics Visualizer   1.2
> Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
>
> SQL Server Data Tools   14.0.60923.0
> Microsoft SQL Server Data Tools
>
> TypeScript   1.8.36.0
> TypeScript tools for Visual Studio
>
> Visual Studio Tools for Universal Windows Apps   14.0.25527.01
> The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft > Windows 10 Software Development Kit.
>
> Windows Driver Kit   10.0.10586.0
> Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)

**Comment by OsirisTerje** [comment]
Hi!  This is not a bug, but the way that Test Explorer in Visual Studio resolves names.  If they are deemed equal, which is the case for the RedWidget, the results are listed under that one:  
![image](https://user-images.githubusercontent.com/203432/28156939-062f4552-67b5-11e7-8bd7-2002ae99ec8a.png)

Since one redwidget fails and one passes, the combined result is said to fail.

**Comment by chwarr** [comment]
Thanks for the explanation! I'll file feedback for Visual Studio about this.
