### ISSUE TITLE
Option to set Number of Worker Threads

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#36]
It has been reported that debugging tests is difficult when tests are marked as Parallelizable. We should either have an option to set the number of workers as you do in the console, or possibly run with one worker if debugging.

**Comment by CharliePoole** [comment]
How should one-time settings in general be specified for the adapter?

**Comment by rprouse** [comment]
I doubt they would be one time settings, just easy to set settings. In this case however, I think running single threaded if you are debugging might be the best answer. Not sure if we can determine if we are debugging or just running though.

We might also be able to add a menu item under the Test menu for NUnit specific toggle settings. You can do it with other extensions, so it might be possible with the adapter.

**Comment by CharliePoole** [comment]
Yes, that's what I meant as well. To add a menu item, you must create an actual VS extension, which I believe can be packaged in the same vsix.

**Comment by OsirisTerje** [comment]
We have had very few possible options to set to justify making an Tools/Options extension for NUnit adapter, but we did discuss this earlier.  I added the registry as a backing store for what we have ( see https://github.com/nunit/nunit-vs-adapter/wiki/Tips-And-Tricks) .  So we could create such an extension.  as part of the adapter vsix.  But this extension would not be there for those projects which use the nuget adapter.  In those cases these options should be present in a runsettings file.  That is also the way other options comes in, although we don't currently use any.  The user friendliness of setting stuff in the runsettings file is poorer of course.

**Comment by CharliePoole** [comment]
Is there any common naming convention for settings in the runsettings file
that apply to an adapter?

**Comment by CharliePoole** [comment]
Until we develop some standard way - maybe an extension - for settings, I think Rob's idea of disabling parallelism when running under debug makes sense and should be relatively easy.

**Comment by CharliePoole** [comment]
@rprouse Do you have some specific reported scenario? I'm testing using the Test Window context menu to debug one or more tests. Are there other use cases?
