### ISSUE TITLE
NET Core VS2017 running tests not found

### ISSUE THREAD

**Issue by OnamChilwan** [nunit/nunit3-vs-adapter#363]
I have some trouble running tests via VS 2017. I have followed these blog posts http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/ and http://www.alteridem.net/2016/10/20/nunit-visual-studio-adapter/ but still nothing is appearing in test explorer.

When I do build however, I get the following from the output window:

> An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Could not load file or assembly 'System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

Setup:
Visual Studio 2017 Version 15.2

Packages:
```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.6.1" />
    <PackageReference Include="NUnit.Runners" Version="3.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.7.0" />
```

Committed a stripped down version of the problem [here](https://github.com/OnamChilwan/NUnit-Net-Core)

**Comment by hoangchu** [comment]
Similar issue here. No test found. No Errors.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.7.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
  </ItemGroup>

</Project>
```

```
using NUnit.Framework;

namespace ClassLibrary1
{
    [TestFixture]
    public class Tests
    {
        [Test]
        public void This_is_a_test()
        {
            Assert.Fail("This is a failing test");
        }
    }
}
```

**Comment by rprouse** [comment]
@hoangchu you need to reference `<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />`

**Comment by rprouse** [comment]
@OnamChilwan you need to reference the 3.8.0 version of the adapter. The 3.7 version doesn't support .NET Core.

**Comment by hoangchu** [comment]
@rprouse that works, yay! Thank you.

**Comment by nadvolod** [comment]
I'm getting the same exception:
[1/28/18 12:12:23 PM Error] An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Could not load file or assembly 'nunit.engine, Version=3.7.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. 

My .csproj
```
    <Reference Include="nunit.framework, Version=3.8.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL">
      <HintPath>..\packages\NUnit.3.8.1\lib\net45\nunit.framework.dll</HintPath>
    </Reference>
```
NUnit version 3.8.1
NUnit.ConsoleRunner 3.8.0
I also tried both with 3.9.0, but downgraded to see if solutions above work. They didn't.

Also, my target framework is .NET 4.6.1
Visual Studio version 15.5.5

**Comment by rprouse** [comment]
@nadvolod your issue is different because you are not targeting .NET Core and judging by your reference, you are still using the old .NET CSPROJ format. Other people have had the same issue as you because of a corrupted cached copy of the adapter. Deleting that cache fixed it. The issue you want to look at is #261 

See this comment for the fix, https://github.com/nunit/nunit3-vs-adapter/issues/261#issuecomment-259970442.

**Comment by nadvolod** [comment]
@rprouse you're absolutely right. That fix worked for me.
