### ISSUE TITLE
An exception occurred while invoking executor: Could not load file or assembly System.Runtime.InteropServices.RuntimeInformation

### ISSUE THREAD

**Issue by gyorgynadaban** [nunit/nunit3-vs-adapter#365]
Target framework: netcoreapp1.0
NUnit 3.7.1
NUnit3TestAdapter 3.8.0

New test library project with 2 simple test classes, attempting to run "dotnet test" from command line yields exception:

```
PS C:\gitroot\azure\aui> dotnet test .\src\Logic.Test\Logic.Test.csproj
Build started, please wait...
Build completed.

Test run for C:\gitroot\azure\aui\src\Logic.Test\bin\Debug\netcoreapp1.0\Logic.Test.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
An exception occurred while invoking executor 'executor://nunit3testexecutor/': Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

**Comment by OsirisTerje** [comment]
@gyorgynadaban I am testing this using https://github.com/rprouse/NUnitPlatformTests  , and can't repro.  Can you check using the same repo, you should see 50 passed tests, 2 skipped and 2 failed.

**Comment by rprouse** [comment]
@gyorgynadaban is your project multi-targetted? Can you post a copy of your CSPROJ file?

NUnit does depend on `System.Runtime.InteropServices.RuntimeInformation`. If you look at the adapter in NuGet, https://www.nuget.org/packages/NUnit3TestAdapter/ we depend on [Microsoft.DotNet.InternalAbstractions](https://www.nuget.org/packages/Microsoft.DotNet.InternalAbstractions/) which pulls in the  `System.Runtime.InteropServices.RuntimeInformation`.

![image](https://user-images.githubusercontent.com/493828/28475536-aa8db424-6e1a-11e7-99bb-f415a863922c.png)

You've also added a reference to `Microsoft.NET.Test.Sdk`?

I tried to reproduce and cannot, I created a new project with the following CSPROJ,

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.7.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
```

From the command line in the project directory, I run `dotnet test`,

```
C:\src\Spikes\CoreTests\CoreTests [master +1 ~1 -1 !]
λ dotnet test
Build started, please wait...
Build completed.

Test run for C:\src\Spikes\CoreTests\CoreTests\bin\Debug\netcoreapp1.1\CoreTests.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in C:\src\Spikes\CoreTests\CoreTests\bin\Debug\netcoreapp1.1\CoreTests.dll
NUnit3TestExecutor converted 1 of 1 NUnit test cases
NUnit Adapter 3.8.0.0: Test execution complete

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 0.9971 Seconds
```

Also check out, http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/

**Comment by rprouse** [comment]
My mistake, I switched the above from `netcoreapp1.1` to `netcoreapp1.0` and get the error you mentioned.

I'm not sure why this is working in the test solution, we will need to look into it.

Workaround for now is to switch to `netcoreapp1.1` for now.

**Comment by rprouse** [comment]
It looks like targeting `netcoreapp1.0` causes a reference to `System.Runtime.InteropServices.RuntimeInformation` version 4.0.0 to get pulled in. A second workaround is to add System.Runtime.InteropServices.RuntimeInformation` version 4.3.0 as a dependency.

We could add this as a NuGet dependency to fix.

**Comment by halex2005** [comment]
@rprouse, can you review and approve #418?
