### ISSUE TITLE
Publish prerelease NuGet/VS-gallery packages

### ISSUE THREAD

**Issue by JeroMiya** [nunit/nunit3-vs-adapter#37]
The latest available NuGet packages (either the global extension install or the solution specific NuGet package) are for the older version. Please publish the 3.0-ctp-3 version as a prerelease NuGet package/extension. The only workaround currently is to build the CTP ourselves and install the vsix.

**Comment by OsirisTerje** [comment]
Do you mean these http://www.nuget.org/packages/NUnit3TestAdapter/3.0.2-ctp-3 and https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d ?

**Comment by JeroMiya** [comment]
Odd, those were not showing up when searching for "nunit" in VS. Thanks!
