### ISSUE TITLE
Exception System.InvalidOperationException

### ISSUE THREAD

**Issue by noobwu** [nunit/nunit3-vs-adapter#370]
Test Method 
         [Test]
        public  void Services_Test()
        {
        }
NUnit Adapter 3.8.0.0: Test discovery starting
Assembly contains no NUnit 3.0 tests: 
Exception System.InvalidOperationException, Exception converting NoobTests.OrmLite.Tests.Tests.NoobOrmLiteService_Tests.Services_Test
对象的当前状态使该操作无效。
NUnit Adapter 3.8.0.0: Test discovery complete
![qq 20170728172147](https://user-images.githubusercontent.com/4328356/28711179-4e1004f0-73b9-11e7-9152-60d2e1b7a989.png)
![qq 20170728172316](https://user-images.githubusercontent.com/4328356/28711304-c508210a-73b9-11e7-813b-936e4b98f34e.png)

**Comment by OsirisTerje** [comment]
Need a bit more info to comment. See template first. 
And can you provide a repro please?

**Comment by Maritims** [comment]
After upgrading to from VS2015 Update 3 to VS2017 I have recently begun experiencing this issue. I am working on a reproduction, but I'm not having any luck with reproducing the issue in a new project.

**Comment by Myrddraal** [comment]
Thank you @Maritims, I was experiencing the same issue with the new project system, and it was solved by adding the package you suggested. 

NB - I encountered this first when running tests on VSTS (we use the Resharper test runner locally, which never had this problem, although I could reproduce it locally by using the Visual Studio test runner).

**Comment by Maritims** [comment]
You're welcome @Myrddraal! I can confirm that the resharper test runner succeeded on our end aswell where the nunit test runner did not.
