### ISSUE TITLE
netcoreapp + CultureInfo.CurrentCulture = bad time

### ISSUE THREAD

**Issue by andersnm** [nunit/nunit3-vs-adapter#372]
Using latest NUnit and NUnit3TestAdapter, in a test project targeting netcoreapp1.0 (have also tried netcoreapp1.1 and a couple earlier versions of NUnit as well as the adapter alpha)

Put this line of code in a test:
```c#
CultureInfo.CurrentCulture = new CultureInfo("ar-SA");
```

... and you will have a bad time.  VS prints errors to the Tests output as below, and does not show any results in the Test Explorer.

```
NUnit3TestExecutor converted 564 of 564 NUnit test cases
Error processing test-case event for dotless.Test.Plugins.RtlPluginFixture.BorderRadiusIsReversed
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input)
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetBasicResult(XmlNode resultNode)
   at NUnit.VisualStudio.TestAdapter.TestConverter.MakeTestResultFromLegacyXmlNode(XmlNode resultNode)
   at NUnit.VisualStudio.TestAdapter.TestConverter.GetVSTestResults(XmlNode resultNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(XmlNode resultNode)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
```

Not sure if problem in NUnit or VS, but somebody are formatting XML dates using the incorrect culture.

These tests run fine on net45, although setting the culture works slightly differently on this target: `Thread.CurrentThread.CurrentCulture = new CultureInfo("ar-SA");`

**Comment by rprouse** [comment]
That call stack is ours, but we need to confirm at which end the parse is failing. The framework should be writing the DateTime out as invariant culture to the XML and the adapter should be parsing it as invariant culture. The `System.DateTimeOffset.Parse(String input)` in the callstack makes me believe it is on the adapter side, but we still need to confirm...

**Comment by Dispersia** [comment]
I just ended up needing this as well.

**Comment by OsirisTerje** [comment]
@Dispersia Did you have the same crash as @andersnm ?   And , did your PR #380 fix the crash?

**Comment by Dispersia** [comment]
@OsirisTerje Yes, it was the same crash (tested with his culture as well) and yes it did fix it and reports correctly the duration of the test
