### ISSUE TITLE
Test attachments are not appearing in the VS Test Explorer

### ISSUE THREAD

**Issue by kdubau** [nunit/nunit3-vs-adapter#373]
Test attachments are not appearing in the VS Test Explorer.

When I use the API `TestContext.AddTestAttachement` I'm expecting to see these attachments appear in the VS Test Explorer like this:

![image](https://user-images.githubusercontent.com/2809202/28883081-3c586372-777b-11e7-822d-8fbd6d27df74.png)

But unfortunately the attachments are not shown.

* NUnit 3.7.1 and NUnit3TestAdapter 3.8
* Visual Studio 2017 15.2 26430.16
* Repro: in a new Class Library project add the NUnit and NUnit3TestAdapter packages. Then add this code and run the test from the test explorer.
```csharp
using NUnit.Framework;
using System.IO;

namespace ClassLibrary1
{
    [TestFixture]
    public class Class1
    {
        [Test]
        public void Method1()
        {
            TestContext.AddTestAttachment(Path.GetTempFileName());
        }
    }
}
```

Running it using the console shows the attachment is in the TestResult.xml:
```xml
    <test-suite type="TestSuite" id="0-1003" name="ClassLibrary1" fullname="ClassLibrary1" runstate="Runnable" testcasecount="1" result="Passed" start-time="2017-08-02 16:11:28Z" end-time="2017-08-02 16:11:28Z" duration="0.025336" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
      <test-suite type="TestFixture" id="0-1000" name="Class1" fullname="ClassLibrary1.Class1" classname="ClassLibrary1.Class1" runstate="Runnable" testcasecount="1" result="Passed" start-time="2017-08-02 16:11:28Z" end-time="2017-08-02 16:11:28Z" duration="0.020426" total="1" passed="1" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
        <test-case id="0-1001" name="Method1" fullname="ClassLibrary1.Class1.Method1" methodname="Method1" classname="ClassLibrary1.Class1" runstate="Runnable" seed="2053457288" result="Passed" start-time="2017-08-02 16:11:28Z" end-time="2017-08-02 16:11:28Z" duration="0.007199" asserts="0">
          <attachments>
            <attachment>
              <filePath>C:\Users\kywhi\AppData\Local\Temp\tmp598C.tmp</filePath>
            </attachment>
          </attachments>
        </test-case>
      </test-suite>
    </test-suite>
```

* .NET Framework 4.6.1

**Comment by ChrisMaddock** [comment]
Hmm, no repro on VS 2015. I don't have 2017 here to test it.

Just for the avoidance of any doubt - have you spotted you need to click the 'output' label to view the attachments?

On VS2015, the test initially displays as this:

![image](https://user-images.githubusercontent.com/4837132/28883993-308805d4-77a8-11e7-9c4d-e25ab723b008.png)

And once you follow the 'output' link:

![image](https://user-images.githubusercontent.com/4837132/28884014-3da6f180-77a8-11e7-94ce-d3276c4fd969.png)

**Comment by kdubau** [comment]
🤦‍♂️  ...how embarrassing. You are right, need to click output and then it can be seen in the resulting view.

**Comment by ChrisMaddock** [comment]
😄 No problem!
