### ISSUE TITLE
Is .NET core 2.0 preview already supported?

### ISSUE THREAD

**Issue by FransBouma** [nunit/nunit3-vs-adapter#374]
I couldn't find information whether this is already supported or not, but nunit tests build against nunit 3.7.1 with NUnit3TestAdapter 3.8.0 aren't seen by 'dotnet test' of .net core 2.0.0-preview2-006497. Also not in VS2017 15.3 preview 7's test runner. I normally use R#'s testrunner but the latest build also doesn't see them. 

Now this might not be supported yet, so I'm just asking if this is already supported, and if not, are there plans to support it before RTM or after? 

The reason I ask is that I'm porting a large project to .netstandard 2.0 (multi-targeted projects with 2 outputs, one for 4.5.2 and one for netstandard2.0) and want to run my tests on both .netcore 2.0 (using the netstandard2.0 build) and net 4.5.2, and have a hard time getting my 4000+ tests to work on netcore 2.0 as they're not seen by any runner (which is a tad problematic ;)) My tests are in multi-targeting csproj files, like the one below:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;net452</TargetFrameworks>
    <AssemblyName>Unittests.TestLibrary.SqlServerTests.SelfServicing</AssemblyName>
    <RootNamespace>Unittests.TestLibrary.SqlServerTests.SelfServicing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.7.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Adapter\DITestClasses\DITestClasses.csproj" />
    <ProjectReference Include="..\SelfServicingAdventureWorksDAL\AdventureWorks.Dal.SelfServicing.csproj" />
    <ProjectReference Include="..\SelfServicingDAL\UnitTests.Dal.SelfServicing.csproj" />
    <ProjectReference Include="..\SelfServicingIH1DAL\InheritanceOne.Dal.SelfServicing.csproj" />
    <ProjectReference Include="..\SelfServicingNWDAL\Northwind.SelfServicing.csproj" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.0'">
    <Reference Include="..\..\..\..\RuntimeLibraries\NetStandard2.0\SD.LLBLGen.Pro.DQE.SqlServer.dll" />
	<Reference Include="..\..\..\..\RuntimeLibraries\NetStandard2.0\SD.LLBLGen.Pro.ORMSupportClasses.dll" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net452'">
    <Reference Include="..\..\..\..\RuntimeLibraries\SD.LLBLGen.Pro.DQE.SqlServer.dll" />
		<Reference Include="..\..\..\..\RuntimeLibraries\SD.LLBLGen.Pro.ORMSupportClasses.dll" />
		<PackageReference Include="SD.Tools.OrmProfiler.Interceptor.NET45" Version="1.5.20150715" />
	  <Reference Include="System.Transactions" />
	</ItemGroup>
</Project>
```

Thanks for any info you could give me :)

**Comment by OsirisTerje** [comment]
This should work.  Have you checked the post http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/ ?

@rprouse - any inputs?

**Comment by FransBouma** [comment]
I found out that referencing the Microsoft.net.test.sdk package, v15.5 something, the tests are picked up by vs testrunner, but only the netcore20 tests :) The build for net4.5.2 (the other target in the multitarget project) are still not showing up. 

Perhaps this multi-targeting system isn't yet supported, not sure?

**Comment by rprouse** [comment]
@FransBouma yes `Microsoft.Net.Test.SDK` is now needed even though it isn't mentioned in many places. Also, multi-targeted tests not working are a known bug/limitation in Visual Studio, not the adapter. I don't know when it will be fixed.

It sounds like you got this working, so I am going to close as an answered question. Let us know if that is a mistake.

**Comment by FransBouma** [comment]
@rprouse Thanks for the info :) As there's nothing you can do and I have all the info I need the issue can stay closed. the limitation inside vs is indeed unfortunate. I'll ping my contacts inside MS regarding this, perhaps that speeds things up a bit. Thanks!

**Comment by sm-g** [comment]
My project is
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net461</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0-preview-20170810-02" />
    <PackageReference Include="NUnit" Version="3.7.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
  </ItemGroup>
```

but also tests dissapeared from VS test runner after upgrade to VS 15.3 / Core 2.0

**Comment by rprouse** [comment]
@sm-g I created a project with 15.3 and Core 2.0 today and it worked fine. Is there any reason you are using a preview of the `Microsoft.NET.Test.Sdk`?

**Comment by sm-g** [comment]
I tried 15.3 and prerelease version and both not showing tests.

By the way, before migration, with VS 15.0, same NUnit and NUnit3TestAdapter (as VS extension, not as nuget), and Core 1.1 I also have no tests in VS Test explorer, but only on one of my working machines.

**Comment by rprouse** [comment]
@sm-g do you have Lightweight Solution Load enabled? I am not sure if it still does, but it used to break unit testing.

**Comment by sm-g** [comment]
@rprouse  Lightweight disabled

**Comment by ElanHasson** [comment]
I'm encountering the same issue... could this be part of the reason why?

![image](https://user-images.githubusercontent.com/234704/29740405-c1be9b66-8a23-11e7-903f-589bb7fc7e31.png)
