### ISSUE TITLE
DefaultTestNamePattern doesn't work with Live Unit Testing

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#375]
NUnit 3.7.1
NUnit3TestAdapter 3.8.0
Visual Studio 2017  (15.2.26430.12)
Targeting .net framework 4.5.2
Given a test like:
![image](https://user-images.githubusercontent.com/203432/29239868-015515e6-7f59-11e7-87f2-d16499ab258b.png)

If I add a default test name pattern to a runsettings file, like
![image](https://user-images.githubusercontent.com/203432/29239865-ec298260-7f58-11e7-96ca-6973042c9e4d.png)
which results in the test being displayed like this in the test explorer:
![image](https://user-images.githubusercontent.com/203432/29239877-46ca0d16-7f59-11e7-8620-63f3b7e29ea9.png)
If I then enable Live Unit Testing, then the test name is repeated twice
![image](https://user-images.githubusercontent.com/203432/29239881-5834124a-7f59-11e7-9182-de1a9f8ca1d6.png)

If I remove the runsettings again, but instead uses the TestName property like
![image](https://user-images.githubusercontent.com/203432/29239887-72870cce-7f59-11e7-939c-7a63df6fca88.png)
it works as it should.

It seems the LUT doesn't get the default test name pattern for its run.   The settings are being loaded for both discovery and execution, so I can't see the adapter is doing anything wrong here, is there something in NUnit itself that might cause this?  @CharliePoole @rprouse ?

**Comment by CharliePoole** [comment]
Looks like a bug in LUT.

**Comment by OsirisTerje** [comment]
@codito,  comment ?

**Comment by ManishJayaswal** [comment]
LUT at this time does not use settings from the runsettings file much ( except for finding the adapters). Additionally the integration of LUT with the test explorer window needs more polish ( which is the reason you see both when LUT is on). We have both in our backlog and intend to address them holistically.

**Comment by OsirisTerje** [comment]
Thanks Manish for the explanation!   
Then I'll close this here.  
Hope you have this fixed on your side soon :-)
