### ISSUE TITLE
No tests found in .Net Standard test library

### ISSUE THREAD

**Issue by nepdev** [nunit/nunit3-vs-adapter#379]
NUnit version 3.7.1, VS-Adapter version 3.8.0, VS Community 2017 version 15.3.0
(.Net Standard 2.0 SDK not installed) 

Steps to Reproduce:
Create class library in Visual Studio - Visual C#  >  .Net Standard  > Class Library (.Net Standard)
This results in a class library targeting .Net Standard 1.4 by default. 

Create a class with some test code, such as 
<pre>
using NUnit.Framework;
namespace Test3NetStd
{
    [TestFixture]
    public class Class1
    {
        [Test]
        public void TestMeNow()
        {
            Assert.That(1 == 1);
        }
    }
}
</pre>

From the menu, select Test > > Run > All Tests

The result is invariably:
[Warning] Exception NUnit.Engine.NUnitEngineException, Exception thrown discovering tests in C:\Users\Admin\source\repos\Test3NetStd\Test3NetStd\bin\Debug\netstandard1.4\Test3NetStd.dll
[Warning] An exception occurred in the driver while loading tests.

Changing the project properties to target .Net Standard 1.3 or .Net Standard 1.6 does not change this behavior at all. 

Counter-check: creating a .Net Windows Forms project in the same instance of Visual Studio and creating a test class has everything running fine. 

It seems NUnit cannot handle .Net Standard libraries?

**Comment by OsirisTerje** [comment]
Your Software Under Test can be .net standard, but the tests themselves have to be in .net core, which *is* a target.

**Comment by nepdev** [comment]
I have tried this but NUnit does not even attempt to find any tests in .Net Core projects.
Tried to add a .Net Core class library with the TestFixture code into the same path as the .Net Standard libraries (src folder in the solution), tried to put it into a separate Test folder, both to no avail.

Output shows that NUnit tries to find tests in the .Net Standard libraries and finds none. Does not try to find tests in the .Net Core library. To check, I added an ASP.Net Core project to the solution. Does not try to find tests in there either. Seems that .Net Core is entirely being disregarded.

Same happens if I make my tests contained in a .Net 4.6 framework class library. 
Any idea to make tests for .Net Standard?

**Comment by rprouse** [comment]
@nepdev I've put up a new page and FAQ for .NET Standard/Core. Please take a look at that and see if that helps you figure out what is wrong. If you figure it out, let us know what fixed it. If not, also let us know so we can work with you.

**Comment by rprouse** [comment]
Sorry, forgot the link to the FAQ, https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard

**Comment by nepdev** [comment]
Adding the Microsoft.NET.Test.Sdk package fixed it.
Tests created in a .Net Core class library are then able to test code in .NetStandard class libraries.
The FAQ is very helpful - thanks for the support.

**Comment by rprouse** [comment]
Glad you got it working. That is a common error as it is a new requirement of Visual Studio 2017.

**Comment by Latency** [comment]
Might I suggest adding `Microsoft.NET.Test.Sdk` as a dependency to the next build & release pkg?
