### ISSUE TITLE
Invalid current directory

### ISSUE THREAD

**Issue by mkudlinski** [nunit/nunit3-vs-adapter#38]
NUnit3 Test Adapter, v. 3.0.2.0 

When running tests by using Test Adapter, following method
System.IO.Directory.GetCurrentDirectory()

returns path to IDE dir:
"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE"

instead of directory where tests DLL are placed. Therefore it may be difficult to load some test resources (marked as "Copy to output directory") with using relative path.

Problem doesn't occur when using console runner.

**Comment by CharliePoole** [comment]
Unlike NUnit 2.x, 3.0 never changes the current directory and makes no guarantees of its value. Depending on your purpose, you must use TestContext.WorkDirectory or TestDirectory.

**Comment by rprouse** [comment]
@mkudlinski, if `GetCurrentDirectory` is in the code being tested, then I would highly recommend that you change that code. There are many things in Windows that can change the current directory even after your program has been running. This often causes hard to track down errors.

If you are loading resources that are relative to your assemblies, it is better to base your location off of the executing assembly. A couple of examples are,

```C#
Type type = typeof( MyClass );
FileInfo path = new FileInfo( type.Assembly.Location );
return path.DirectoryName;
```

or

```C#
return Path.GetDirectoryName( Assembly.GetExecutingAssembly().Location ) + Path.DirectorySeparatorChar;
```

**Comment by CharliePoole** [comment]
Or TestContext.TestDirectory should do it for you it it's the directory of the test assembly that you want.

**Comment by mkudlinski** [comment]
@rprouse, @CharliePoole  thanks for your answers :) 

I'm aware that I can also get the path by using Assembly (that was my workaround for above issue). I only didn't know about the difference between NUnit Adapter 2 / 3 (first comment from @CharliePoole )

thanks again
