### ISSUE TITLE
Hierarchy of TestCase[(...)] items are not separately displayed in VS Test Explorer for int[].

### ISSUE THREAD

**Issue by mukaofssn** [nunit/nunit3-vs-adapter#382]
Versions:
NUnit 3.8.1, NUnit3TestAdapter 3.8.0, 
Visual Studio 2015 - 14.0.25431.01 Update 3
.Net framework 4.7.02046

The hierarchy of TestCase[(...)] items is not separately displayed in the VS Test Explorer for a int[] type.

Code sample as follows:

```
        // Displays hierarchy as expected in Test Explorer. 3 out of 3 test cases were executed.
        [TestCase(1, 2, ExpectedResult = 3)]
        [TestCase(4, 5, ExpectedResult = 9)]
        [TestCase(27, 30, ExpectedResult = 57)]
        public int SumTests(int a, int b)
        {
            var sut = new Calculator();

            return sut.Sum(a, b);
        }

        // Doesn't display in hierarchy as expected in Test Explorer, shows as 1 test case only. But post test 
        // run, the output window counts as 3 tests.
        [TestCase(new[] { 1, 2, 4, 5, 7, 29, 30 })]
        [TestCase(new[] { 1, 2, 4, 5, 7, 28, 30 })]
        [TestCase(new[] { 1, 2, 4, 5, 7, 27, 30 })]
        public void SumValueSet(int[] arr)
        {
            var sut = new Calculator();

            var result = sut.SumValueSet(arr);

            Assert.That(result, Is.GreaterThan(10));
        }

```

![vstestexplorer](https://user-images.githubusercontent.com/28928475/29998727-734e009a-902a-11e7-94b4-695740a52900.png)

Output window:
```
------ Run test started ------
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in C:\Users\karthik\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1.Tests\bin\Debug\ConsoleApplication1.Tests.dll
NUnit3TestExecutor converted 6 of 6 NUnit test cases
NUnit Adapter 3.8.0.0: Test execution complete
========== Run test finished: 4 run (0:00:01.0271396) ==========
```

**Comment by mukaofssn** [comment]
![vstestexplorer](https://user-images.githubusercontent.com/28928475/29998725-5699eab8-902a-11e7-9b1e-318618e5b6f4.png)

**Comment by CharliePoole** [comment]
This is a well-known limitation of the Test Explorer (or from their point of view, of NUnit) 😸 It shows up in a number of situations and your case is one of the clearest examples.

Basically, Test Explorer likes to equate a test with a method group, while NUnit equates it with a method plus a set of arguments. We make some adjustments so that _most_ tests show up independently, as defined by NUnit, but others do not. At a certain point, we stopped making adjustments, because each individual data type has to be handled separately.

@OsirisTerje I would make this `wontfix` but it's your call, of course.

**Comment by OsirisTerje** [comment]
Adding to what @CharliePoole says: 
The test results are coming out fine,  the tests groups them by the test, e.g. as shown here #357 
What appears in the test explorer are based on the naming pattern we have, which is configurable.
To see the effect, try to add TestName as shown here:
[TestCase(new[] { 1, 2, 4, 5, 7, 29, 30 }, TestName = "{i}-{m}.{a}")]
[TestCase(new[] { 1, 2, 4, 5, 7, 28, 30 }, TestName = "{i}-{m}.{a}")]
[TestCase(new[] { 1, 2, 4, 5, 7, 27, 30 }, TestName = "{i}-{m}.{a}")]

These settings can be added to a runsettings file, so you don't have to add them to every test, see this blogpost for details http://hermit.no/how-to-change-visual-studio-test-explorer-testnaming-using-nunit/  

We could add more to the test name patterns to resolve these too, but there seems to be many variations.  We're also talking with the Product Group in MS about this, so something may change there too.   Closing this for now, and if we need we connect this up to a general change later.

**Comment by jnm2** [comment]
Follow https://github.com/nunit/nunit/issues/1382 for an automatic fix for this.
