### ISSUE TITLE
.NET Framework 4.6.2 test project using new .NET Standard 2.0 csproj format problem

### ISSUE THREAD

**Issue by vullnetyy** [nunit/nunit3-vs-adapter#383]
I have a .NET Framework 4.6.2 test project where  myproject.csproj file is in the new csproj format. Resharper successfully discovers and runs all the tests. The NUnit3TestAdapter however, does not. Here are the errors I see in the Tests output of VS2017:

````
[2017-09-06 10:27:27 Warning] Exception System.InvalidOperationException, Exception converting X2TransferGUI.Tests.ReducerStateTest.ReducersCannotContainState
[2017-09-06 10:27:27 Warning] Operation is not valid due to the current state of the object.
[2017-09-06 10:27:27 Warning] Exception System.InvalidOperationException, Exception converting X2TransferGUI.Tests.SubsetsTest.SubsetsUsedByViewModelsMatchStoreProps
[2017-09-06 10:27:27 Warning] Operation is not valid due to the current state of the object.
````

NUnit 3.8.1 and NUnit3TestAdapter 3.8.0 installed as a Visual Studio 2017 Extension
Visual Studio Enterprise 2017 version 15.3.3
.NET Framework 4.6.2

**Comment by OsirisTerje** [comment]
Can you upload a repro project?

**Comment by vullnetyy** [comment]
Here you go sir: [NUnitBugDemonstration.zip](https://github.com/nunit/nunit3-vs-adapter/files/1284504/NUnitBugDemonstration.zip)

NUnit 3.8.1.
NUnit3TestAdapter 3.8.0 is the one I have on my Visual Studio Enterprise 2017 version 15.3.3.

The original post mistakenly said 3.8.1 for the test adapter.

**Comment by vullnetyy** [comment]
My apologies. I just discovered your release notes and tried adding 
````
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
<PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
````

and this makes my package references look like this:
````
<ItemGroup>
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
  <PackageReference Include="NUnit" Version="3.8.1" />
  <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
</ItemGroup>
````

Using this successfully discovered and ran all my tests.

I propose that the exception messages shown in this case should point to the solution (your release notes.)

**Comment by ChrisMaddock** [comment]
Could we make the Microsoft.NET.Test.Sdk package a NuGet dependency of the TestAdapter package?

**Comment by vullnetyy** [comment]
That could be an elegant way to deal with this but the author may have objections to hard-coding "loosely required" dependencies like that

**Comment by rprouse** [comment]
> Could we make the Microsoft.NET.Test.Sdk package a NuGet dependency of the TestAdapter package?

I have been considering doing so myself. It is a hard requirement for any tests using the new `CSPROJ` format. See nunit/nunit-console#291

**Comment by OsirisTerje** [comment]
We have only one nuspec, and that one is afaik not target specific.  
We could however add a targets file to achieve it.

**Comment by ChrisMaddock** [comment]
Unfortunately, I don't think there's a way to detect 'uses new csproj'. I could be wrong however!

**Comment by OsirisTerje** [comment]
Also considering older VS versions,  perhaps it is not a good idea to attempt adding that dependency.  It could be wiser to add it to the NUnitTemplate project instead. 
Or, add our own AssemblyResolve event handler, as indicated in comments in https://github.com/nunit/nunit-console/issues/291

**Comment by OsirisTerje** [comment]
I'm closing this, as there doesn't seem to be anything we can do to help the users here, except ensuring the templates and documentation are up to date.
