### ISSUE TITLE
Force NUnit Console to run AnyCPU tests as x64

### ISSUE THREAD

**Issue by jgrossrieder** [nunit/nunit3-vs-adapter#384]
Hi,

I recently came across the following issues:
All our solution(Unit Test and library) is compiled in AnyCPU. We have some external library that have a specific version for x86 or x64, so we do 2 setups, one x86 with the global lib + the 32 bit library, and one x64 with the 64 bits libraries.

We have decided to make the unit tests with the x64 version of  libraries(so we copy those one), but once someone let the "Prefer 32-bit" of the build settings of an executable that was referenced by a referenced project of a test unit.

Then we got BadImageException( 0x8007000B ), globally saying that we were trying to use x64 libs in a x86 app. 

I did the following UnitTest just to confirm

```
        [Test]
        public void TestProcess()
        {
            Assert.AreEqual(Environment.Is64BitProcess, true);
        }
```

And it was failing on the build machine. In visual studio, if I set the `Test -> Test Settings -> Default Processor Architecture` to x64, it was working again(and the UnitTest was working too).
But when running myself the nunit3-console, I cannot specify this and the parameters fails.

So I tried to create a `test.runsettings` file with the following content:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>  
  <!-- Configurations that affect the Test Framework -->  
  <RunConfiguration>  
    <!-- [x86] | x64    
      - You can also change it from menu Test, Test Settings, Default Processor Architecture -->  
    <TargetPlatform>x64</TargetPlatform>  
  </RunConfiguration>  
</RunSettings>  
```

But after having selected it in Visual studio and reopening the solution on another computer, this is not persisted(and the Unit Tests still fails), so I guess it's not the way to go?
Is there a way to "force" the x64 behavior? even if there was a `Prefer 32-bit` in one of the reference project?

* NUnit versions: 3.7.0
* Visual Studio : 2017 Pro 15.3.3
* .Net Platform: .Net 4.6

**Comment by CharliePoole** [comment]
You reported this as an NUnit3Adapter problem, but in your description you are talking about using the NUnit console runner. Can you please clarify?

**Comment by jgrossrieder** [comment]
@CharliePoole I'm affraid I'm mistaken, it was for the NUnit console runner, is it possible to move it to there or do I've to close and open another one to the correct place?

**Comment by CharliePoole** [comment]
Moving this... please add info about your nunit3-console command-line.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-console #286](https://github.com/nunit/nunit-console/issues/286) via [**ZenHub**](https://www.zenhub.com/)
