### ISSUE TITLE
Can't specify bitness on command line

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#389]
@damageboy commented on [Sun Sep 17 2017](https://github.com/nunit/dotnet-test-nunit/issues/123)

## Steps to reproduce
Run dotnet test on a assembly with nunit:
```
dotnet test -- TargetPlatform=x64
```

## Expected  behavior
Be able to specify bitness (x64 / x86)

## Actual behavior
Always runs on x86 in Windows by default

## Environment data
`dotnet --info` output:

```
C:\projects\junk.git\tests\Junk.Tests>dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

---

@rprouse commented on [Sun Sep 17 2017](https://github.com/nunit/dotnet-test-nunit/issues/123#issuecomment-330050052)

1. You are using .NET Core 2.0, this repository is for the old `dotnet test` command line for the project.json format. The repo you want is the NUnit3TestAdapter.
2. I believe you are using the command line for the old xproj format, there is no TargetPlatform command line option for `dotnet test` or for the underlying `vstest.console.exe`. The VSTest command line option is `/Platform:x64`.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore2x
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-vstest

I created the following test,

```c#
[Test]
public void IsRunning64Bit()
{
    unsafe
    {
        Assert.That(sizeof(IntPtr), Is.EqualTo(8));
    }
}
```

And I run it with the command line, `dotnet test` and it passes, so it is running `x64` by default. **Are you sure you don't have `Prefer 32-bit` set?**

To switch the bitness that the process runs as, you have to use `dotnet vstest`. `dotnet test` used to pass extra command line options on to `vstest`, but now that I have 2.0 installed, it doesn't seem to be working.

If I switch to `dotnet vstest .\bin\Debug\netcoreapp2.0\NetCore20Tests.dll /platform:x86`, the test correctly failed for me once, but now every time I run it, it passes 😕 

The command line is correct, if I switch `/platform:x86` to `/platform:bad`, it gives the warning message `Invalid platform type:bad. Valid platform types are x86, x64 and Arm.` I can even run it as Arm and it passes which it shouldn't.

---

@rprouse commented on [Sun Sep 17 2017](https://github.com/nunit/dotnet-test-nunit/issues/123#issuecomment-330051555)

I am going to move this to the NUnit vs adapter repo where it belongs. Please follow it there...

**Comment by rprouse** [comment]
I think this might be a tooling or user error. I would like to test this using MSTest and xUnit to confirm.

**Comment by damageboy** [comment]
I was indeed trying this for .NET Core 2.x

**Comment by CharliePoole** [comment]
@damageboy The test adapter doesn't create a 32 or 64 bit process in which to run. It's invoked in a process created for it by its host.

**Comment by rprouse** [comment]
@damageboy as @CharliePoole says, the NUnit adapter is just a plugin that is loaded into the VSTest process. It is up to VSTest to start executing in x86 or x64. I am leaving this open and with a confirm label because I want to figure out if this is a VSTest bug or just an improper command line. No matter which way you run your tests, `dotnet test`, `dotnet vstest` or `vstest.console.exe`, it is ultimately a VSTest process and our adapter is just running in whatever bitness the adapter is running as.

**Comment by damageboy** [comment]
Ok, thanks for clarifying that.
I will create a minimal repro..

**Comment by rprouse** [comment]
I would also be interested in seeing if you see the same behavior if you use MSTest or xUnit 😄

**Comment by damageboy** [comment]
Will do


    Shechter.

**Comment by OsirisTerje** [comment]
@damageboy   Did you manage to create a minimal repro?

**Comment by damageboy** [comment]
I think I actually found a proper way to do it, the MS docs were conflicting, I will double check and report here, possibly closing the issue...

**Comment by OsirisTerje** [comment]
Closing this for now.

**Comment by asgerhallas** [comment]
> I think I actually found a proper way to do it, the MS docs were conflicting, I will double check and report here, possibly closing the issue...

@damageboy did you find a proper way to do it? :)

**Comment by kasobol-msft** [comment]
> > I think I actually found a proper way to do it, the MS docs were conflicting, I will double check and report here, possibly closing the issue...
> 
> @damageboy did you find a proper way to do it? :)

I found this issue by looking for a way to make net461 tests run 64-bits (they run 32 by default...). It seems that something like `dotnet test --runtime win-x64 --framework net461` does the job.
