### ISSUE TITLE
Improve performance of discovery

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#392]
It has been found that discovery of test cases are slowed down by the processing of traits.

**Comment by navin22** [comment]
With PR #406 I am seeing the below performance improvements for 10K empty nUnit tests in a project.

For Discovery: 67.5% perf improvement in console and 55.9% perf improvement in IDE.
Framework   /Adapter | VS CLI (vstest.console.exe) | VS IDE (VS2017 Latest)
-- | -- | --
3.8.1   / 3.8.0 | 5.24s | 8.4s
3.9.0-dev-04564 / 3.9.0-dev-00575 | 1.7s | 3.7s

For Execution: 26.7% perf improvement in console and 22.35% perf improvement in IDE.
Framework /Adapter | VS   CLI (vstest.console.exe) | VS   IDE (VS2017 Latest)
-- | -- | --
3.8.1 / 3.8.0 | 15.65s | 21.25s
3.9.0-dev-04564   / 3.9.0-dev-00575 | 11.47s | 16.5s

The above testing is done in following machine configuration:
OSName       : Microsoft Windows 10 Enterprise
OSVersion    : 10.0.15063
MachineType  : x64-based PC
Processor    : Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
LogicalCores : 8
RAMSize      : 15.9589996337891GB
