### ISSUE TITLE
Could not find test executor with URI 'executor://nunit3testexecutor/'.

### ISSUE THREAD

**Issue by softreigns** [nunit/nunit3-vs-adapter#399]
------ Discover test started ------
NUnit Adapter 3.8.0.0: Test discovery starting
NUnit Adapter 3.8.0.0: Test discovery complete
========== Discover test finished: 38 found (0:00:02.5451455) ==========
------ Run test started ------
Could not find test executor with URI 'executor://nunit3testexecutor/'.  Make sure that the test executor is installed and supports .net runtime version 4.0.30319.42000.
========== Run test finished: 0 run (0:00:01.861503) ==========

When reporting a bug, please provide the following information to speed up triage:

* NUnit (3.2.0.0) and NUnit3TestAdapter versions (3.8.0)
       also tried with NUnit 3.8 too, same error.
* Visual Studio edition (visual studio 2015) and full version number (see Help About)
- Microsoft Visual Studio Professional 2015
- Version 14.0.25431.01 Update 3
- Microsoft .NET Framework
- Version 4.6.00081

* What .net platform and version is being targeted
.net 4.5

**Comment by OsirisTerje** [comment]
Does this happen only with your particular solution, or does it happen also for any solution/project you have?

**Comment by softreigns** [comment]
Appreciate your reply!.

This is happening in all solutions/projects.
including all test project within same solution.
test project in other solution.
We have projects targeting 4.5 and 4.5.2

This has been working until a month or so back. And yesterday more people in my team are seeing the same issue. 

We have tried: 
uninstalling latest .net 4.7 version.
uninstalling everything and installing it back.
Changing Nunit test adaptor (I had 3.2 and changed it to 3.8 latest)

Note: the test run fine from the nunit3-console exe, but from within VS, we see this error.

**Comment by OsirisTerje** [comment]
1) Can you clone and test this repo:  https://github.com/OsirisTerje/Demo  (clone address https://github.com/OsirisTerje/Demo.git), and check if you see the error on this sln.
2) Are you using the vsix adapter or the nuget adapter in the solution(s)?  If you're using the vsix adapter, and 1) doesn't work, then please uninstall it and try again.  Remember to restart VS when you do such things. 

We have no known errors with respect to this, but it can be that you do something we haven't foreseen, so interested to see what it can be.

**Comment by softreigns** [comment]
I will try the demo. 

I have tried both adaptors (installing from extension and adding from nuget). always restart VS.

**Comment by softreigns** [comment]
------ Discover test started ------
NUnit Adapter 3.8.0.0: Test discovery starting
NUnit Adapter 3.8.0.0: Test discovery complete
========== Discover test finished: 2 found (0:00:00.270027) ==========
------ Run test started ------


Same result.

**Comment by OsirisTerje** [comment]
Ok,  can you ensure you have uninstalled the vsix. 
Then if you step back to earlier versions of the adapter, 3.7.0, 3.6.0, 3.5.1  (restart between each ofc), does the demo work with any of these version?

**Comment by softreigns** [comment]
so i tried those, still getting the error. I even removed all other extensions from visual studio (powertools, codemaid, sonarlint etc).

I setup Visual studio on another machine (fresh) and install adaptor 3.8 with the same solution/project (ours). And the test run fine. 

So it has to be something on my machine that's causing the issue. I do .net, java, angular development on my machine and have softwares/tools installed for all of them along with other build/analysis tools. Can any of those cause a problem in test run. I saw one post about resharper causing the similor error(i am not using resharper).

I am curious to know how the nunit test framework/engine works and look for testexecutor. Understanding that can help identify what can be an issue. I will try to research on this, but if you can share any knowledge or guide, I will really appreciate. Thanks

**Comment by OsirisTerje** [comment]
It is the vstest.executionengine.exe and vstest.discoveryengine.exe that invokes the adapter.  I am not 100% sure about the search mechanism, there is a TE.Processhost.exe involved too.  All of these should be found in a subfolder under the place where devenv.exe exist (a bit different on different versions).  

On my machine I find these (for VS 2015) under :  C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow 

If you locate these two exe, there is a corresponding config file for each.  Inside them there is a trace setting, and if not, you can add the section:
`
 <system.diagnostics>
    <switches>
      <add name="TpTraceLevel" value="4" />
    </switches>
  </system.diagnostics>
`
The default level is 0, and iirc, set it to 4.  
You will then find trace information in the %temp% folder 
(Some details can be found here:  https://blogs.msdn.microsoft.com/aseemb/2012/03/01/how-to-enable-ute-logs/  )

These can give you some indication on what it hits.  
Also, can it be you have installed some earlier versions of the adapter, either vsix or nuget ?  Walking through the nuget caches and cleaning those out can also be useful.  
The nuget caches to clean out are at 
`
%LocalAppData%\NuGet\Cache
%UserProfile%\.nuget\packages
`
The vsix have its own caches, and in addition the vstest system also have its caches.  If you don't find the issue from the logs and info above, I'll search out those locations for you too.  It has to be something around this.
When this is cleared out, I'll add this information to some documentation.   I've had a ton of similar stuff, you are not the first one and not the only one, be sure :-)

**Comment by softreigns** [comment]
wow, it worked. well i was able to find the problem and fix, but its really weird thing. 

So content of  vstest.executionengine.x86.exe.config on my machine, was showing content of my project config file. I can't imagine how would that happen. I never knew of TestWindow folder, never opened it. Can visual studio or test adapter overwrite this ? 
I replaced it with the one from the other fresh machine I setup, which was running fine. 

And now the test are running fine. 
Thanks a lot for prompt responses and great help. :)

**Comment by OsirisTerje** [comment]
Good to hear!  Thanks!  

I'll include this information in some docs at a later time.

**Comment by sveroa** [comment]
I got the problem. I deleted all files in these folders. Did rebuild and my test could be ran in the test explorer again.
%LocalAppData%\NuGet\Cache
%UserProfile%\.nuget\packages
[SOLUTION FOLDER]\Packags
