### ISSUE TITLE
Null Reference Exceptions with Version 3.0 of the Test Adapter

### ISSUE THREAD

**Issue by forestmarie** [nunit/nunit3-vs-adapter#40]
Hi, 

After successfully getting NUnit 2.6.4 and its adapter stable both locally and on our build server for a new project we are about to start, I decided to branch the project to tinker with NUnit 3.0 and its corresponding adapter.  

While it's close to working for me, I'm having a rather odd issue - at least in my opinion. 

Here's the log I get when I do a Rebuild on the project: 

------ Discover test started ------
NUnit Adapter 3.0.2.0 discovering tests is started
NUnit failed to load C:\Applications\CraftTraxNG\release-next-prototype\CraftTraxNG\CraftTraxNG.Core\bin\Debug\CraftTraxNG.Core.dll
NUnit failed to load C:\Applications\CraftTraxNG\release-next-prototype\CraftTraxNG\CraftTraxNG.TestCore\bin\Debug\CraftTraxNG.TestCore.dll
NUnit failed to load C:\Applications\CraftTraxNG\release-next-prototype\CraftTraxNG\CraftTraxNG.Web\bin\CraftTraxNG.Web.dll
NUnit Adapter 3.0.2.0 discovering test is finished
========== Discover test finished: 54 found (0:00:01.1000115) ==========

This is accurate - the discovery is working as intended - 54 tests across two projects.  Why the load failures is beyond me and likely part of the problem.

Continuing on, if I go to Test > Run All Tests, I'll get this (consistently every time): 

------ Run test started ------
NUnit Adapter 3.0.2.0 executing tests is started
Running all tests in C:\Applications\CraftTraxNG\release-next-prototype\CraftTraxNG\CraftTraxNG.IntegrationTests\bin\Debug\CraftTraxNG.IntegrationTests.dll
Loading tests from C:\Applications\CraftTraxNG\release-next-prototype\CraftTraxNG\CraftTraxNG.IntegrationTests\bin\Debug\CraftTraxNG.IntegrationTests.dll
Running all tests in C:\Applications\CraftTraxNG\release-next-prototype\CraftTraxNG\CraftTraxNG.UnitTests\bin\Debug\CraftTraxNG.UnitTests.dll
Exception System.NullReferenceException, Exception thrown executing tests
NUnit Adapter 3.0.2.0 executing tests is finished
========== Run test finished: 3 run (0:00:00.9840349) ==========

My tests in the project named CraftTraxNG.UnitTests will not be run - same exact result if I go to Test > Debug All Tests

The part that's weird - at least to me - is that if I select the tests in the unit test project, right click them and choose "Run Selected Tests" they'll run with no issues.  The same for the tests in the integration test project.

However, if I select at least 1 test from each of the unit testing projects, I get this: 

------ Run test started ------
NUnit Adapter 3.0.2.0 executing tests is started
Running selected tests in C:\Applications\CraftTraxNG\release-next-prototype\CraftTraxNG\CraftTraxNG.UnitTests\bin\Debug\CraftTraxNG.UnitTests.dll
Loading tests from C:\Applications\CraftTraxNG\release-next-prototype\CraftTraxNG\CraftTraxNG.UnitTests\bin\Debug\CraftTraxNG.UnitTests.dll
Running selected tests in C:\Applications\CraftTraxNG\release-next-prototype\CraftTraxNG\CraftTraxNG.IntegrationTests\bin\Debug\CraftTraxNG.IntegrationTests.dll

An exception occurred while invoking executor 'executor://nunit3testexecutor/': Object reference not set to an instance of an object.

========== Run test finished: 1 run (0:00:01.1071813) ==========

In these cases, the tests in the integration project seem to get 'lose out'. 

On the build server however, the integration test project actually 'wins' and the all of the tests in the unit test project are skipped.  The build result there is simply: 

 1 test run completed - 100% pass rate
 srv-*****@****-ALM-PROD 2015-07-12 15:43:39_Any CPU_Debug, 1 of 1 test(s) passed
 3 binaries instrumented - 0% of all code blocks covered (Coverage Results)
Other Errors and Warnings
 1 error(s), 0 warning(s)
 Exception System.NullReferenceException, Exception thrown executing tests 
See http://go.microsoft.com/fwlink/?LinkId=254169

Just seems to be weird to be going across projects.

FYI - The integration test project only has 3 tests right now and 2 of them are marked Ignore so that's why it's only 1 test running - I have verified the test on the build server that runs is from the integration test project. 

FYI - This is the same behavior as above when I posted what happens when I go to Test > Run All Tests  in that all the tests in the unit tests project are not executed.

For what it's worth, locally I'm running Visual Studio 2013 Update 4.  The build server is running TFS Build 2013 Update 4.

In the unit tests project, here's the packages.config: 

packages>
  package id="FakeItEasy" version="1.25.2" targetFramework="net45" />
  package id="FluentAssertions" version="3.3.0" targetFramework="net45" />
  package id="Microsoft.AspNet.WebApi.Client" version="5.0.0" targetFramework="net45" />
  package id="Microsoft.AspNet.WebApi.Core" version="5.0.0" targetFramework="net45" />
  package id="Moq" version="4.2.1502.0911" targetFramework="net45" />
  package id="Newtonsoft.Json" version="4.5.11" targetFramework="net45" />
  package id="Ninject" version="3.2.2.0" targetFramework="net45" />
  package id="NUnit" version="3.0.0-beta-2" targetFramework="net45" />
/packages>

And the integration test project: 

packages
  package id="EntityFramework" version="6.1.3" targetFramework="net45" />
  package id="Microsoft.CodeAnalysis.Analyzers" version="1.0.0-rc2" targetFramework="net45" />
  package id="Microsoft.CodeAnalysis.Common" version="1.0.0-rc2" targetFramework="net45" />
  package id="Microsoft.CodeAnalysis.CSharp" version="1.0.0-rc2" targetFramework="net45" />
  package id="Ninject" version="3.2.2.0" targetFramework="net45" />
  package id="NUnit" version="3.0.0-beta-2" targetFramework="net45" />
  package id="NUnit3TestAdapter" version="3.0.2-ctp-3" targetFramework="net45" />
/packages>

Also note that the integration test project has 3 .dlls:  nunitcore.engine, nunit.framework and NUnit3.TestAdapter and the unit test project has nunit.framework

As far as code changes, the only thing I changed after doing the branch was using [OneTimeSetup] as the other attribute is now obsolete.  

So any ideas here?  

Additionally, what is the process for using a modified version of the adapter?  A few days ago I was playing with the stable branch and I added the adapter project to my project locally and used that as a project reference instead of from nuget but the discovery engine was still using the version I got from nuget.  After building the adapter, what is the specific location I need to put the .dll to make Visual Studio's test runner use that copy - the reason I did that was because I wanted to add very verbose logging to try to understand better what's going on.  

Anyway - if I'm not clear on something here, please ask.  

Executive summary: Working flawlessly with 2.6.4 and the Version 2 adapter on the build server, but having hiccups with NUnit3's test adapter, which fortunately appear to be localized as well for me.  

Here's the log from my branch using all of the 2.6.4 bits for comparison after doing Test > Run All Tests 

------ Discover test started ------
NUnit VS Adapter 2.0.0.0 discovering tests is started
NUnit VS Adapter 2.0.0.0 discovering test is finished
========== Discover test finished: 52 found (0:00:00.4876589) ==========
------ Run test started ------
NUnit VS Adapter 2.0.0.0 executing tests is started
Loading tests from C:\Applications\CraftTraxNG\CraftTraxNG\CraftTraxNG.IntegrationTests\bin\Debug\CraftTraxNG.IntegrationTests.dll
Run started: C:\Applications\CraftTraxNG\CraftTraxNG\CraftTraxNG.IntegrationTests\bin\Debug\CraftTraxNG.IntegrationTests.dll
Loading tests from C:\Applications\CraftTraxNG\CraftTraxNG\CraftTraxNG.UnitTests\bin\Debug\CraftTraxNG.UnitTests.dll
Run started: C:\Applications\CraftTraxNG\CraftTraxNG\CraftTraxNG.UnitTests\bin\Debug\CraftTraxNG.UnitTests.dll
NUnit VS Adapter 2.0.0.0 executing tests is finished
========== Run test finished: 52 run (0:00:05.8894356) ==========

Clean as a whistle! 

Also - everything works beautifully in both branches with NCrunch as well.  Seems to be an adapter only issue to me.

I am sure if I need to do more to use NUnit 3 or if this is just a beta issue, but thanks for reading.

**Comment by OsirisTerje** [comment]
It seems you're hitting Issue-33 https://github.com/nunit/nunit3-vs-adapter/issues/33  .  That was merged in to master earlier, but after the release.  
I have built a 3.0.4 pre-release version, you can download the vsix and nuget package from here, https://bintray.com/nunit/NUnitAdapter/NUnitAdapter/NUnitAdapter3.0.4pre/view

If you build your own, the best way is to build them properly and use them from a local source, either the vsix, or, if you use the nuget package, just feed them from a local directory. See https://github.com/nunit/nunit-vs-adapter/wiki/How-to-build-and-package-a-release for details. 

The master source is updated equally now.

**Comment by forestmarie** [comment]
Thanks for the immediate feedback.  Sorry I missed the dupe. 

I'll download the nuget package tomorrow morning and add it to our internal feed.

**Comment by forestmarie** [comment]
Would have responded early but God sent me on a different plan - my adoption came through so I'm a proud daddy now! 

Anyway, I'll be brief - I'm getting the same behavior using the nuget package you gave me - I put it on my local feed - just a folder on my C drive with nuget packages.

Here's what I get on build: 

------ Discover test started ------
NUnit Adapter 3.0.2.0 discovering tests is started
NUnit failed to load C:\Applications\CraftTraxNG\CraftTraxNG\CraftTraxNG.Core\bin\Debug\CraftTraxNG.Core.dll
NUnit failed to load C:\Applications\CraftTraxNG\CraftTraxNG\CraftTraxNG.TestCore\bin\Debug\CraftTraxNG.TestCore.dll
NUnit failed to load C:\Applications\CraftTraxNG\CraftTraxNG\CraftTraxNG.Web\bin\CraftTraxNG.Web.dll
NUnit Adapter 3.0.2.0 discovering test is finished
========== Discover test finished: 52 found (0:00:00.7804234) ==========

But on Tests > run All:  

------ Run test started ------
NUnit Adapter 3.0.2.0 executing tests is started
Running all tests in C:\Applications\CraftTraxNG\CraftTraxNG\CraftTraxNG.IntegrationTests\bin\Debug\CraftTraxNG.IntegrationTests.dll
Loading tests from C:\Applications\CraftTraxNG\CraftTraxNG\CraftTraxNG.IntegrationTests\bin\Debug\CraftTraxNG.IntegrationTests.dll
Running all tests in C:\Applications\CraftTraxNG\CraftTraxNG\CraftTraxNG.UnitTests\bin\Debug\CraftTraxNG.UnitTests.dll


Exception System.NullReferenceException, Exception thrown executing tests <-- Offender


NUnit Adapter 3.0.2.0 executing tests is finished
========== Run test finished: 2 run (0:00:05.1438212) ==========

Packages on one unit testing project (integration tests): 

package id="EntityFramework" version="6.1.3" targetFramework="net451" />
package id="Ninject" version="3.2.2.0" targetFramework="net451" />
package id="NUnit" version="3.0.0-beta-3" targetFramework="net451" />
package id="NUnit3TestAdapter" version="3.0.4-ctp-4" targetFramework="net451" />

Packages on the other testing project (pure unit tests): 

package id="FakeItEasy" version="1.25.2" targetFramework="net45" />
package id="FluentAssertions" version="3.3.0" targetFramework="net45" />
package id="Microsoft.AspNet.WebApi.Client" version="5.0.0" targetFramework="net45" />
package id="Microsoft.AspNet.WebApi.Core" version="5.0.0" targetFramework="net45" />
package id="Moq" version="4.2.1502.0911" targetFramework="net45" />
package id="Newtonsoft.Json" version="4.5.11" targetFramework="net45" />
package id="Ninject" version="3.2.2.0" targetFramework="net45" />
package id="NUnit" version="3.0.0-beta-3" targetFramework="net451" />

I've checked out the reference paths to make sure they're pointing properly: 

C:\Applications\CraftTraxNG\CraftTraxNG\packages\NUnit3TestAdapter.3.0.4-ctp-4\lib\NUnit3.TestAdapter.dll

etc.  

Cleaned, rebuilt and restarted Studio 

Any ideas? Not sure when I'll get back to this but I will.

Thanks again for helping!

**Comment by OsirisTerje** [comment]
Congratulations with the child !!  

I think I need to set up some repro for this, or add some more logging to the adapter.  There is a verbosity flag that can be set, but not sure if it gives the needed info (you can try, see [Tips and Tricks](https://github.com/nunit/nunit-vs-adapter/wiki/Tips-And-Tricks)  ).  

I'm going on vacation now, so will be a bit on and off, but will try to look more into this.

**Comment by forestmarie** [comment]
OK. Enjoy your vacation!  I'll look into that maybe tomorrow or this
weekend.

Have fun.

**Comment by CharliePoole** [comment]
@forestmarie @OsirisTerje What's the status of this issue? Is it still present in CTP-6?

**Comment by jessehouwing** [comment]
We're seeing it on CTP8

**Comment by jessehouwing** [comment]
We can repro this on a VS2013 update 3 when there is one project which does reference NUnit.Framework, but doesn't contain any tests. On Visual Studio 2013 update 5 we do not see te error, but on 2013 update 3 we do see it.

That one project contains generic re-usable methods that are used by other test projects.

**Comment by CharliePoole** [comment]
Any update on this? I see a hint in the last comment about referencing framework, but not having tests. But I'd like to know if it's still an active bug using the latest releases.

**Comment by CharliePoole** [comment]
I'm closing this for lack of further information. We can re-open if any new reports come to light.
