### ISSUE TITLE
Change format of Fully qualified Name

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#404]
The FQN is now in a format given by NUnit, which includes NUnit specific information, and is passed on to VS.  VS require it to be in standard format.

**Comment by CharliePoole** [comment]
This has, of course, been true for years. VS has unstated, undocumented assumptions about the test name, which the MS dev have consistently refused to clarify for us. That's the main thing that led me, as the original author of the extension, to give up on it.

Do we now know with any precision what those assumptions are? Is it documented? Will future changes be documented?

I think this issue should say what the changes will be and it should remain only a discussion item until the format is agreed upon with Microsoft. I realize there have been private discussions but I'd like to see it spelled out as well as agreed to here in public.

**Comment by OsirisTerje** [comment]
We're currently output'ing a non-standard - fqn.   The change here just puts it back to a normal standard fqn.

**Comment by CharliePoole** [comment]
I'm asking for a definition of the format of a "standard fqn" for a TestCase. I'm asking that it be reviewed here, by our team and by somebody from the VS team. Otherwise, we just continue to do what we have done for years: make a guess of what Microsoft wants and try it, then change it when it no longer works.

**Comment by peterwald** [comment]
@CharliePoole You make some good points. 

I'm going to have some conversations internally to make sure we communicate clearly about what the FQN needs to be. I'll respond back soon with more information.

**Comment by peterwald** [comment]
The FullyQualifiedName should follow the pattern of CLR fully qualified names and reference the method that implements the test. Optionally, the FullyQualifiedName can include angle brackets for generic parameters, and parentheses for method parameters.

Here are some examples:

```
Namespace.Class.Method
Namespace.Class.Method()
Namespace.Class.Method(x: 0, y: 10)
Namespace.Class+Inner.Method(str: "Hello")
Namespace.Class<T>.Method<V>(val: "x")
```

**Comment by CharliePoole** [comment]
Comments on what NUnit provides...

* In each case, Method may be replaced by the user. However, the adapter actually has the class and method name and could construct from those.

* We never use empty parentheses

* Parameter names are not available, so we would use `Method(0, 10)` rather than `Method(x: 0, y: 10)`

* When angle brackets are used, the __actual__ type is provided rather than the type parameter name.

* Classes may also take arguments in parentheses.

@peterwald are any of these points issues for you? We might be able to overcome some of them in the adapter using other info that's in the NUnit XML.

**Comment by peterwald** [comment]
> In each case, Method may be replaced by the user. However, the adapter actually has the class and method name and could construct from those.

The `DisplayName` will still be used when showing these TestCases to the end user, but it would be best if the `FullyQualifiedName` could be constructed from the class and method name.

> We never use empty parentheses

Great

> Parameter names are not available, so we would use Method(0, 10) rather than Method(x: 0, y: 10)

No problem. We don't need the parameter names.

> When angle brackets are used, the actual type is provided rather than the type parameter name.

Good point, that's what we would expect as well. It was a poor choice of an example on my part. It should be something more like `Namespace.Class<String>.Method`

> Classes may also take arguments in parentheses.

No problem.

**Comment by CharliePoole** [comment]
Cool then! I think it would behoove us to initially dump the constructed FQN along with NUnit's test name, to make sure there are no surprises.

We can get the raw class name and method name from the XML provided by NUnit. Those don't have arguments, so we might have to construct the argument parts from our own test name. We would lose the method arguments in that case, if the user had set the display name to something else, but we wouldn't be losing anything that isn't already lost when the user does that.

**Comment by frankshearar** [comment]
How would parameterized TestFixtures fit into the FQN scheme?

**Comment by CharliePoole** [comment]
@frankshearar See the fifth bullet in my comment above and @peterwald 's response.

Of course we have to rely on correct interpretation by Test Explorer.

**Comment by peterwald** [comment]
For what it's worth, the Test Explorer doesn't have to fully interpret the `FullyQualifiedName`. We just need to have a predictable pattern so that we can identify groups of tests and can effectively "normalize" the identifiers.

**Comment by frankshearar** [comment]
You'd treat fixture parameters as type parameters? In other words
````
namespace Full.Namespace
{
    [TestFixture(1, 2)]
    public class MyFixture(int a, int b)
    {
        [TestCase(3, 4)]
        public void MyTest(int c, d) {}
    }
}
````

would have a test like "Full.Namespace.TestFixture<1,2>.MyTest(3,4)" ? Works for me.

**Comment by peterwald** [comment]
@frankshearar That's my understanding, yes. But I'd defer to @CharliePoole

**Comment by CharliePoole** [comment]
@frankshearar The example you gave would be given the name "Full.Namespace.TestFixture(1,2).MyTest(3.4) by NUnit. We don't use angle brackets except for Type parameters.

Note that we still don't know for sure that we can satisfy all the requirements for the FQN in the adapter. We only have access to what the framework provides. Beyond that, we would need to make a feature request for a framework change, which would be nice to avoid if possible.

**Comment by CharliePoole** [comment]
@frankshearar  and @peterwald 

Modifying the example to use a generic class...

```C#
namespace Full.Namespace
{
    [TestFixture(1, 2)]
    public class MyFixture<T,U>(T a, U b)
    {
        [TestCase(3, 4)]
        public void MyTest(int c, d) {}
    }
}
```

Would (IIRC) give us "Full.Namespace.TestFixture<System.Int32,System.Int32>(1,2).MyTest(3,4)"

**Comment by frankshearar** [comment]
Well, that would work for me - I was specifically asking about whether the "(1,2)" on the "class name" part of the FQN would work.

**Comment by CharliePoole** [comment]
@frankshearar Just to be clear, the FQN is not directly exposed to you as a user. What you see is whatever the Microsoft guys do with the FQN we give them.
