### ISSUE TITLE
Exception NUnit.Engine.NUnitEngineException

### ISSUE THREAD

**Issue by noobwu** [nunit/nunit3-vs-adapter#408]
Exception NUnit.Engine.NUnitEngineException, Exception thrown discovering tests in bin\Debug\netstandard2.0\NoobCore.Data.EntityFrameworkCore.Tests.dll

* NUnit and NUnit3TestAdapter versions
  NUnit version is 3.8.1 
 NUnit3TestAdapter version is 3.8.0.0
* Visual Studio edition and full version number (see Help About)
  Visual Studio version is 15.3.5
* A short repro, preferably attached or pointing to a git repo or gist
https://github.com/noobwu/NoobCore
* What .net platform and version is being targeted
  netstandard2.0

**Comment by OsirisTerje** [comment]
Thanks!  Can you upload the repro source too, there is only dll's and pdb's in the repo.  (Remove anything not essential to the issue, if this is from some production code, remove all internals in the methods for the software under test.  We only need the skeletons and the tests, as long as the fail is still present.

**Comment by noobwu** [comment]
https://github.com/noobwu/NoobCore/tree/master/NoobCore.NUnitTests

**Comment by noobwu** [comment]
use netstandard2.0 appears Exception NUnit. Engine. NUnitEngineException

**Comment by noobwu** [comment]
use netcoreapp2.0 appears Exception NUnit. Engine. NUnitEngineException

**Comment by OsirisTerje** [comment]
1.  Test projects, whatever framework, can not themselves be .net standard.  Make them .net core.  They need to target a platform.  See @rprouse blogpost http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/  

2. If you switch to .net core, you need to reference the Microsoft.net.test sdk and the nunit3testadapter.  I suppose you're trying to use the vsix adapter, but .net core is **only** supported using the nuget adapter.

A valid csproj file could look like this:
`
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="NUnit" Version="3.8.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
  </ItemGroup>

</Project>
`

**Comment by noobwu** [comment]
Thank you very much. @OsirisTerje
