### ISSUE TITLE
Strange nunit_random_seed.tmp file stays in build output directory

### ISSUE THREAD

**Issue by jozefizso** [nunit/nunit3-vs-adapter#410]
When reporting a bug, please provide the following information to speed up triage:

* NUnit3TestAdapter 3.8.0.0 (disabled)
* Visual Studio 2015.3 Enterprise
* Create any .NET project (eg. class library project, you don't have to reference NUnit library)
* .NET 4.5

Create any .NET project, build it and run Clean. The build output directory will contain strange 
nunit_random_seed.tmp file.

Expected behavior: The nunit_random_seed.tmp is cleaned up.

**Comment by OsirisTerje** [comment]
This is handled by the build system in VS.   We could add a target file to hook into the clean process though.   This would only work using the nuget adapter though.

**Comment by CharliePoole** [comment]
IMO, this is not our job. However, I'm surprised at the statement that this happens for any .NET project, whether it uses NUnit or not. It's possible we need to add some further condition for when it is saved: e.g. when the assembly is runnable by NUnit and contains test cases.

**Comment by jozefizso** [comment]
The files was created even for default Class Library project type, even without addin nunit to referenced assemblies.

**Comment by ChrisMaddock** [comment]
Is there a reason this file has to be created in the build dir, or could it instead be written to %TEMP%?

**Comment by OsirisTerje** [comment]
@jozefizso Did you have one test project with the NUnit3Testadapter nuget package and another class lib project, and you saw the temp file in the latter?  Or using the vsix (which you write was disabled)?

**Comment by OsirisTerje** [comment]
@CharliePoole Agree it should only be output for the test projects.   About not our job, we *do* create that file, so it's a bit boy scout rule here.

**Comment by CharliePoole** [comment]
@ChrisMaddock That would be possible although the user could mess us up by changing the temp directory.

@OsirisTerje If we could delete it when it was no longer needed, I would favor that. But of course we can't know if it will be needed for another execution. As it is, it's clearly named as a temp file and does no harm in subsequent builds or runs. Personally, I think time is better spent figuring out how to do without the file in the first place.

**Comment by jnm2** [comment]
This was fixed (https://github.com/nunit/nunit3-vs-adapter/issues/298)- is this a regression?

**Comment by OsirisTerje** [comment]
Hmm... Could look like.  I thought @jozefizso referred to test projects, but I see he writes "any project", which should not do that.  Can you confirm @jozefizso ?

**Comment by jozefizso** [comment]
It happens for any project type.

**Comment by OsirisTerje** [comment]
@jozefizso When you write "(disabled)" do you then mean the vsix adapter?  Do you have a nuget adapter too?

**Comment by jozefizso** [comment]
I have the NUnit Adapter extension installed in Visual Studio 2015, but it is disabled.

I don't use the test adapter nuget package.

I created new project from default Class Library template and haven't added any nuget packages to it. I've build the solution, I cleaned it and the nunit_random_seed.tmp file was in build output directory.

**Comment by OsirisTerje** [comment]
@jozefizso  
1.  Can you rebuild the project, and then copy what you see in the Output/Tests window?
2.  Then clean the project, and copy what you see in Output/Build and Output/Tests window?
