### ISSUE TITLE
NUnit on Visual Studio 2017 (Enterprise): Test Runner doesn't list tests when NUnit is deployed as a Solution NuGet package?

### ISSUE THREAD

**Issue by MikeTheGreat** [nunit/nunit3-vs-adapter#411]
This is a report based on a [StackOverflow question about this](https://stackoverflow.com/questions/46883228/nunit-on-visual-studio-2017-enterprise-test-runner-only-works-as-extension-n).

 _**NUnit and NUnit3TestAdapter versions**_ 
NUnit: v3.8.1
NUnit.ConsoleRunner: v3.7.0 
NUnit3TestAdapter: v3.8.0

_**Visual Studio edition and full version number (see Help About)**_
(I canNOT get NUnit3 Test Runner to detect the NUnit tests on this computer)

> Microsoft Visual Studio Enterprise 2017 
> Version 15.2 (26430.16) Release
> VisualStudio.15.Release/15.2.0+26430.16
> Microsoft .NET Framework
> Version 4.7.02046
> 
> Installed Version: Enterprise
> 
> Visual Basic 2017   00369-60000-00001-AA102
> Microsoft Visual Basic 2017
> 
> Visual C# 2017   00369-60000-00001-AA102
> Microsoft Visual C# 2017
> 
> Application Insights Tools for Visual Studio Package   8.6.00404.2
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2017   15.0.30503.0
> ASP.NET and Web Tools 2017
> 
> ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
> For additional information, visit https://www.asp.net/
> 
> Azure App Service Tools v3.0.0   15.0.30209.0
> Azure App Service Tools v3.0.0
> 
> Common Azure Tools   1.9
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> KofePackagePackage Extension   1.0
> KofePackagePackage Visual Studio Extension Detailed Info
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> NuGet Package Manager   4.2.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> SQL Server Data Tools   15.1.61702.140
> Microsoft SQL Server Data Tools
> 
> TypeScript   2.2.2.0
> TypeScript tools for Visual Studio
> 

**_A short repro, preferably attached or pointing to a git repo or gist_**

1. Open the attached project   [NUnitTest_Clean.zip](https://github.com/nunit/nunit3-vs-adapter/files/1417326/NUnitTest_Clean.zip)
2. Open Test > Windows > Test Explorer
3. Select Build > Rebuild Solution
4. Tests are not visible in the Test Explorer window (but they should be)

(If I install the NUnit3 Test Adapter as an extension the tests **do** show up in step 4)

Note: this works great on my personal computer (the tests appear in the Test Explorer window in step 4 on my personal laptop).  I've included the 'VS Edition, etc' info at the bottom of this report

_**What .net platform and version is being targeted**_

.Net Framework 4.5.2 (Console Application)

I've set the Test > Test Settings > Default Processor Architecture to "x64"

The Properties > Build tab lists "Platform Target" as "Any CPU"

_**If TFS/VSTS issue, what version, hosted, on-premises, and what build task you see this in**_

This is being run in Visual Studio 2017 directly, and doesn't use TFS/VSTS.

_**My personal laptop's info**_
(NUnit3 Test Runner DOES detect the NUnit tests on this computer, without any problems)

> Microsoft Visual Studio Community 2017 
> Version 15.1 (26403.7) Release
> VisualStudio.15.Release/15.1.0+26403.7
> Microsoft .NET Framework
> Version 4.7.02053
> 
> Installed Version: Community
> 
> Visual Basic 2017   00369-60000-00001-AA361
> Microsoft Visual Basic 2017
> 
> Visual C# 2017   00369-60000-00001-AA361
> Microsoft Visual C# 2017
> 
> ASP.NET and Web Tools 2017   15.0.30320.0
> ASP.NET and Web Tools 2017
> 
> ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
> For additional information, visit https://www.asp.net/
> 
> Azure App Service Tools v3.0.0   15.0.30209.0
> Azure App Service Tools v3.0.0
> 
> Common Azure Tools   1.9
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> KofePackagePackage Extension   1.0
> KofePackagePackage Visual Studio Extension Detailed Info
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> NuGet Package Manager   4.1.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> SQL Server Data Tools   15.1.61702.140
> Microsoft SQL Server Data Tools
> 
> TypeScript   2.1.5.0
> TypeScript tools for Visual Studio

**Comment by OsirisTerje** [comment]
Thanks!  I just downloaded your repro, and started it up, and it comes up with 9 tests, 8 passing, one failing. 
![image](https://user-images.githubusercontent.com/203432/32046437-57f5ec34-ba43-11e7-8436-71a4fd3b93b6.png)

So we need to find out what is special with the computer that won't show the tests.

Some observations:  
-  The project is an AnyCPU, so it should work fine with both x86 and x64 setting. 
-  The project includes the NUnit.ConsoleRunner.  That is not needed to run in VS, but it does no harm either (in case you just want it downloaded for console use).
- The project does not need any adapter extension installed into VS, and the best is to avoid doing it. The adapter is included with the project, as it should be.  (If you have it installed, please uninstall it)


First:
Do a Rebuild:
Check the Output/Tests window.  Do you see the same as shown below:
![image](https://user-images.githubusercontent.com/203432/32046418-48df2ca6-ba43-11e7-8ac6-bbf05bcab69a.png)

a) In case nothing is shown here: 
Drop down to a **Visual Studio 2017 command line**, and check that vstest.console is in the path (just try that command:
You should see a long help list being displayed, starting with:
![image](https://user-images.githubusercontent.com/203432/32046672-fde3ee0c-ba43-11e7-8e86-cd33e58c5fa0.png)

Go down to the bin/Debug folder, 
Check that it looks like this:
![image](https://user-images.githubusercontent.com/203432/32046756-36fe4ec6-ba44-11e7-9bba-2b80ef61e96e.png)

Then run the command
vstest.console nunittest.exe

And the result should be like this:
![image](https://user-images.githubusercontent.com/203432/32046820-5df309f4-ba44-11e7-8c8e-b933e481d99e.png)

**Comment by MikeTheGreat** [comment]
First - THANK YOU for your incredible help!  This is amazing, and I really appreciate it!  Thank you!!

I got to step "a", and when the Tests > Test Settings > Processor Architecture is set to "X64", then the Output/Tests window produced this:

```
------ Discover test started ------
Test run will use DLL(s) built for framework Framework45 and platform X64. Following DLL(s) will not be part of run: 
NUnitTest.exe is built for Framework Framework45 and Platform X86.
 Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
NUnit Adapter 3.8.0.0: Test discovery starting
Error: Unable to get runner for this assembly. Check installation, including any extensions.
NUnitEngineException: Cannot run tests in process - a 32 bit process is required.
Exception NUnit.Engine.NUnitEngineException, Exception thrown discovering tests in \\employee.cascadia.edu\empfiles\HomeDir\mpanitz\Desktop\NUnitTest_Clean\NUnitTest\bin\Debug\NUnitTest.exe
Cannot run tests in process - a 32 bit process is required.
NUnit Adapter 3.8.0.0: Test discovery complete
========== Discover test finished: 0 found (0:00:25.7373009) ==========
```
It looks like the VM I'm running on is actually x86, not x64.

When I switch Tests > Test Settings > Processor Architecture is set to "x86" I get this:

```
------ Discover test started ------
NUnit Adapter 3.8.0.0: Test discovery starting
NUnit Adapter 3.8.0.0: Test discovery complete
========== Discover test finished: 9 found (0:00:01.4560534) ==========

```
I checked the list of VS Extensions again just in case the IT department installed the NUnit Test Adapter Extension last night, but I couldn't find it listed.


(I **swear** I tried both x86 and X64 before contacting anyone.  This is both frustrating and unsettling - it seems to work now, but I'm not sure what changed that suddenly made it work)

**Comment by MikeTheGreat** [comment]
If this happens again I'll follow your instructions again and see if I can't get more data / a better repro.

In the meantime - would it be ok if I submitted a PR to the NUnit Test Adapter wiki mentioning both the Output / Tests window and the Architecture thing?  The Output/Tests window would be particularly good to let people know about, since it's a great source of troubleshooting info.

**Comment by MikeTheGreat** [comment]
I just got off the phone with the IT people and they said that the VM is actually X64.

Is it possible that they installed the x86 version of Visual Studio onto an X64 VM?

(I looked through the Help > About output and it didn't seem to say)

**Comment by rprouse** [comment]
@MikeTheGreat Visual Studio only has an x86 version, so that is not the issue. The error you see about not being able to run x86 in process used to happen in very old versions of the NUnit Engine, but has been fixed for a couple of years. Is it possible that an older version of NUnit or the Adapter is installed on the build machine?

**Comment by OsirisTerje** [comment]
@MikeTheGreat   Superb if you contribute a PR on the docs!  :-) 

About a possible older version being installed:  If you can check the build log on the build machine you should see the same output as the command line above.  There the version is stated.

**Comment by MikeTheGreat** [comment]
Ran the tests on the command line and it looks current. 

Specifically, the tests produced this output:

```
Microsoft (R) Test Execution Command Line Tool Version 15.0.26228.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Information: NUnit Adapter 3.8.0.0: Test execution started

Information: Running all tests in C:\TEMP\NUnitTest\bin\Debug\NUnitTest.exe

Information: NUnit3TestExecutor converted 9 of 9 NUnit test cases

Information: NUnit Adapter 3.8.0.0: Test execution complete

Passed   EmptyCollectionTests
Passed   EmptyStringTests
Passed   ExactTypeTests
Passed   InstanceOfTests
Passed   IsFalse
Passed   IsNaN
Passed   IsNotNull
Failed   IsNull
Error Message:
     Expected: null
  But was:  <System.Object>

Stack Trace:
   at NUnitTest.AssertSyntaxTests.IsNull() in \\employee.cascadia.edu\empfiles\HomeDir\mpanitz\Desktop\NUnitTest_Clean\NUnitTest\Program.cs:line 45

Passed   IsTrue

Total tests: 9. Passed: 8. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 2.0009 Seconds

```
(aside: the failing test is fine - I took some tests from one of the NUnit samples, and I made that one test fail just to make sure that it could)

If this happens again I'll get another copy of the output and see what it says.

Thank you both for all your help with this!

**Comment by OsirisTerje** [comment]
I understood you will be sending this to several students over time.  It would be nice to hear back if any of them get any issues.  Even if it is a usability issue, it should be looked at and either documentation or experience improved :-)

**Comment by MikeTheGreat** [comment]
Hello!

Ok, it's happening again :)

The attached file:
[PCE_03_VS_2017_Adapter_NUnit_3_0_Exception_Handling.zip](https://github.com/nunit/nunit3-vs-adapter/files/1424868/PCE_03_VS_2017_Adapter_NUnit_3_0_Exception_Handling.zip)
works great on my machine, and on the school's computer the tests are visible.

When I run vstest.console NUnitTest.exe, I get the following output:
```
C:\Users\mpanitz\Downloads\PCE_03_VS_2017_Adapter_NUnit_3_0_Exception_Handling\PCE_03_VS_2017_Adapter_NUnit_3_0_Exception_Handling\bin\Debug>vstest.console NUnitTest.exe
Microsoft (R) Test Execution Command Line Tool Version 15.0.26228.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Warning: No test is available in NUnitTest.exe. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.


Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true

```
Under Tools > NuGet Package Manager > Manage NuGet Packages for Solution I'm seeing NUnit (v3.8.1), NUnit Console Runner (not needed for the in-Visual-Studio adapter, I know :) ; v3.7.0), and NUnit3TestAdapter (v3.8.0) all listed under the 'Installed' tab.

The test's processor architecture is still x86.

--------------------------------------------

So it looks like the test adapter isn't finding the tests on this computer.  It's working fine on my computer (I even tried re-downloading the .ZIP attached to this comment, extracting it, opening it in VS 2017, and it compiles, finds the tests, runs them, and these tests all pass).

I assume there's something goofy about the school computer - any advice or thoughts on what to try next would be greatly appreciated! 

Thank you again for all your help with this!!

**Comment by OsirisTerje** [comment]
You are still seeing the adapter dlls in the output bin folder, right?  The bin folders are equal on yours and the school computer?

From the output above it seems the adapter is not even being found.

If you enable tracing on the vstest.discovery engine, it is possible to see what it is doing, and where it goes wrong.  Both Visual studio and the vstest.console calls on first the vstest.discoveryengine.exe to discover tests, then it calls vstest.executionengine.exe to run them.  Both these executables are found in a subfolder under your Visual Studio installation .  On my machine they are:

`D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow`

This blog post explains how to enable those trace logs: https://blogs.msdn.microsoft.com/aseemb/2012/03/01/how-to-enable-ute-logs/

Set the trace level of both discovery and execution to the value 4. 

The logs comes out in your %temp% folder.

**Comment by MikeTheGreat** [comment]
Actually, the bin/debug directories are not quite identical.  There's 1 file on my (working) computer that is not on the (nonworking) school computer: nunit_random_seed.tmp

Looks like I'm not allowed to modify the file in the VS install directory.  I can see the contents of the .config file, I can find the TpTraceLevel entry, but only administrators can modify the file.  The IT department keeps this pretty locked down (which is probably good, though sometimes inconvenient :) ).

I can ask them to modify this file (that might take a couple of days).  I don't suppose that the program looks anywhere in my user directories for a backup/supplemental .config file, does it?

**Comment by OsirisTerje** [comment]
The seed file comes as a result of the test run, so you can ignore that difference.  The important thing is that all dll's should be present. 

You're sure you cannot modify the config files by running from en elevated command prompt?  (Run as admin), or is that also blocked ?   
And no, the config exist only there.

**Comment by MikeTheGreat** [comment]
That's blocked, sadly.  I even just tried it again for good measure and it's not running as admin (whenever I try to modify anything in that directory it says 'Access Denied')

Let me ask them for a workaround.  Specifically, the computer I"m using is a VM, so I wonder how hard it would be for IT to copy the VM image, grant me Admin privs in that one VM image, and then let me mess around it with fewer restrictions.
I'll ask them tomorrow (Monday), and update when I get a response.

**Comment by MikeTheGreat** [comment]
Ok, I got admin access on a dedicated VM.

I've attached the .log file:
[vstest.console.TpTrace.log](https://github.com/nunit/nunit3-vs-adapter/files/1436068/vstest.console.TpTrace.log)

I took a look through it and this looks like useful feedback:

```
V, 5140, 1, 2017/11/01, 16:47:47.097, 39707963456, vstest.console, TestExtensionResolver:Resolving assembly 'NUnit3.TestAdapter'.
V, 5140, 1, 2017/11/01, 16:47:47.097, 39707964104, vstest.console, TestExtensionResolver: Failed to load the assembly 'NUnit3.TestAdapter'
I, 5140, 1, 2017/11/01, 16:47:47.097, 39707964153, vstest.console, AssemblyResolver: NUnit3.TestAdapter: Resolving assembly.
I, 5140, 1, 2017/11/01, 16:47:47.378, 39708658143, vstest.console, AssemblyResolver: NUnit3.TestAdapter: Failed to load assembly. Reason:System.IO.FileLoadException: Could not load file or assembly 'file:///D:\Users\mpanitz\PCE_03_VS_2017_Adapter_NUnit_3_0_Exception_Handling\PCE_03_VS_2017_Adapter_NUnit_3_0_Exception_Handling\bin\Debug\NUnit3.TestAdapter.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///D:\Users\mpanitz\PCE_03_VS_2017_Adapter_NUnit_3_0_Exception_Handling\PCE_03_VS_2017_Adapter_NUnit_3_0_Exception_Handling\bin\Debug\NUnit3.TestAdapter.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.VisualStudio.TestPlatform.Common.Utilities.AssemblyResolver.OnResolve(Object senderAppDomain, ResolveEventArgs args)
```
Specifically, the bit about

> An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

The location that I'm running the project from is a network drive - 
`\\netdrive.cascadia.edu\drivestorage\etc\myusername\Desktop\Lesson03\bin\debug`

The IT department is doing this thing where the Desktop is actually on a network drive so that students and employees can log into any physical (or virtual) computer on campus and the Desktop will follow the user around.  It makes sense, but it's easy to forget about.

**Comment by MikeTheGreat** [comment]
Just as an addendum - I tried to run the code from %temp% (which was d:\users\Me\AppData\Local\Temp) and it gave the same sort of error, and from c:\Lesson03 and it again gave the same sort of error.

It looks like the problem is that it can't run from a network drive, and the VM only has network drives attached to it.

I'll go Google this after dinner, but would it be ok for me to ask you if you happen to have any overall advice on using .Net's CAS to allow .Net to run from network locations?
(General feedback like "It's bad to do", or "It's tricky/easy/etc" would be wonderful - I can do the Googling myself, but figured that if you already knew that this does/doesn't work well (or if there's a better way to do this) that would be great!)

**Comment by CharliePoole** [comment]
Historically (i.e. since way back in NUnit 2.x), we have told people this isn't supported. I'm pretty sure we could make it supported if we payed a __lot__ of attention to security demands, but realistically I don't see it happening.

**Comment by MikeTheGreat** [comment]
Just so I"m clear: running NUnit from within a project that's stored on a network drive is not supported, yes?

That's totally fine - I'll work with IT and see about the possibility of getting the VM to think that it's disk is a local disk.

Thank you all again very, very much for your help - I greatly appreciate it!!!

(I think I've got some time on Friday to put together a Markdown file for troubleshooting the install - I can put in all the stuff that @OsirisTerje walked me through, and hopefully that will be a generally-useful block of text for the Wiki)

THANK YOU!!!

**Comment by rprouse** [comment]
A virtual disk on a VM will work fine, it's done all the time, what you will probably have trouble with is network drives.

**Comment by CharliePoole** [comment]
Indeed...  my comment was about network drives, ie shares in windows terminology.

**Comment by MikeTheGreat** [comment]
I'm really sorry to bug y'all again - 
I wrote up the above information into an .MD file with the intention of adding it to the NUnit/docs wiki.

I'm having a bunch of trouble figuring out how to send it to you.  

- I can't edit the wiki directly (which is reasonable).  
- The https://github.com/nunit/docs page has a 'Clone This Wiki Locally' option, but when I do that I can't push my changes back to nunit/docs (I think this is reasonable - I shouldn't be able to unilaterally change your docs :) )
- I can't find any instructions on how to submit a pull request specifically to the wiki.
The wiki appears to be stored in a repo that's separate from the main nunit/docs, so forking the 'nunit/docs' repo doesn't bring any of the wiki files with it.  There _is_ a 'New Pull Request' on nunit/docs, but that repo doesn't include the wiki pages.  As far as I can tell, there's no web page on GitHub for the wiki repo itself, so I can't ask for a pull request.

I, uh, could just send you the file (e.g., by attaching it to this issue), but that seems really hacky :)

**Comment by CharliePoole** [comment]
Generally, the way this works is somebody is made a contributor and then has the ability to simply edit the wiki. This works for editing existing pages but not for creating new pages or changing the right-hand menus. That's because the wiki has a directory structure that is ignored when you edit online.

When you clone a wiki, you don't clone the main (docs) repo, but wiki.git under it. However, there's still no PR process so this is only useful after you have write access.

If you already created the md file, you can either send it by email to somebody or paste it into the create page form once you have write access.

Since this is the vs adapter, it's really up to @OsirisTerje how he wants to handle it. I'm just laying out the options.

**Comment by MikeTheGreat** [comment]
That makes sense - thanks for explaining that!
If it's all right with y'all (and specifically @OsirisTerje, since it's your show) I'd love to just attach a .ZIP with the .MD and .PNGs to this issue.

**Comment by MikeTheGreat** [comment]
I had one other thought - 
I turned on the detailed trace on my computer (where the NuGet package works fine) and looked for what the discovery engine did when it went looking for NUnit3TestAdapter.  On my computer it says that it loads just fine from "C:\dir1\dir2\etc\".  On the problematic school computer it wouldn't run via either the c:\ drive d:\ drive or e:\drives - each time I got that error about how .Net couldn't open the remote .DLL at  "file:///D:\Users\mpanitz\PCE_03_VS_2017_\etc\etc".

#### I wonder - does the presence of **file:///** at the start indicate that the discovery engine is trying to open a local file using a URL?  And maybe an API call that's specific to loading remote code?

I was wondering if it might be good to talk to whomever makes the discoveryengine - would y'all know where I could open an issue / talk with someone about this hypothesis?

Regardless - have a good weekend!

**Comment by OsirisTerje** [comment]
@MikeTheGreat Just attach it, and I'll get it in.   Thanks for the effort :-)

And, I'll point someone from the Microsoft product group to this issue to comment on your findings.

**Comment by MikeTheGreat** [comment]
Sure thing - thank you all for your amazing help!!

The files in here go into the docs.wiki/adapter directory.  There's a couple of new images, a new 'Troubleshooting.md' file, and the sidebar is updated to (hopefully) point to the new MD file.

[adapter.zip](https://github.com/nunit/nunit3-vs-adapter/files/1443337/adapter.zip)

I mostly took what you wrote above and adjusted it slightly, so it should be pretty familiar / wasn't too much work for me :)

Thank you for reaching out to the MS people!
