### ISSUE TITLE
NUnit Adapter 3.9.0.0: Test discovery starting but process doesn't end

### ISSUE THREAD

**Issue by ashok8734** [nunit/nunit3-vs-adapter#413]
NUnit Adapter 3.9.0.0: Test discovery starting but process doesn't end. My project is a simple class library (test project using selenium and C#). There is no error in Output window. Test discovery process starts but it never completes.

Microsoft Visual Studio Professional 2015 Version 14.0.25431.01 Update 3

Nunit framework version : 3.8.1
Nunit 3 Adpater version : 3.9.0.0

Installed from NUGET Package Manager

Target Framework : .NET Framework 4.5
Platform : Any CPU

**Comment by ashok8734** [comment]
I tried all solutions which are given in this forum but no success. Please let me know if you want more details.

**Comment by rprouse** [comment]
We will need more details. This is working for most people. Can you provide a minimum reproducible solution?

**Comment by ashok8734** [comment]
Previously we used Nunit Framework 3.0.1, its working fine and yesterday I updated to  Nunit framework version : 3.8.1 also the Nunit Adapter to 3.9.0.0 and then this problem started. I tried to go back to Nunit Framework 3.0.1 but no success. Please let me know if you need more info. Thanks.

**Comment by OsirisTerje** [comment]
As @rprouse  said:  Can you please upload a repro project?
Make it as small as you can, it should compile "as is".
That is, given:    This repro on any project you have

If it *only* appears on this special project, please disable tests until you get the one (or few) method(s) that breaks 

Diagnosing:
Verify the same happens when you tun using vstest.console
Set verbosity to 5 in the runsettings file, check if there are any new warnings 
Set tpTrace to 4 for vstest.discovery engine, and upload the vstest log.

**Comment by ashok8734** [comment]
Hi, 
Please find the log file
[devenv.TpTrace.log](https://github.com/nunit/nunit3-vs-adapter/files/1456306/devenv.TpTrace.log)
Please let me know if you need more details

**Comment by ashok8734** [comment]
Also When I tried VStest.console it is not showing any tests. Ch
![vstestconsole](https://user-images.githubusercontent.com/33411104/32589003-2ebd72e2-c538-11e7-9a85-06ac08189161.jpg)
eck screenshot

**Comment by ashok8734** [comment]
Please tell me where to upload my project without making public

**Comment by OsirisTerje** [comment]
Don't upload your production code. Create a new small fake project which just reproduces the error, and upload that, preferably to a git repo, or if it is small, just as an attachment here.    From the screenshot above and tracelog it doesnt look like you have any adapter that your project can find.

**Comment by ashok8734** [comment]
I removed all Test script files (to create a fake project to upload) and added one by one to the project ( checking whether it shows newly added test method) and now test explorer is showing all tests.
