### ISSUE TITLE
Can not run a single test

### ISSUE THREAD

**Issue by msalzig** [nunit/nunit3-vs-adapter#414]
* NUnit and NUnit3TestAdapter versions 3.9.0.0
* Visual Studio professional 2017 Preview (2)
* What .net platform and version is being targeted 4.5.1

Working steps:
- set cursor in a test method
- start test by Ctrl+R, T
- all test of the TestFixture are performed

- expected behaviour: only the marked test should be performed

**Comment by OsirisTerje** [comment]
1.  Can you check your keyboard settings:
![image](https://user-images.githubusercontent.com/203432/32593800-a3eb3694-c529-11e7-84b4-08d58824b8f4.png)
2. You write you're using 2017 preview (2), but which version ? 2017 is now on 15.4, do you mean preview for 15.5 ?  

3.  This doesn't look like an adapter bug, more like something in VS.

**Comment by rprouse** [comment]
Another thing to check, is the Test Explorer Window open? If not, tests are not discovered. Also, check your output window, switch it to Test and check the test discovery output.

**Comment by OsirisTerje** [comment]
No further response, so assumes it is working for @msalzig
