### ISSUE TITLE
Test Explorer won't start IIS Express

### ISSUE THREAD

**Issue by martinRocks** [nunit/nunit3-vs-adapter#415]
I'm using Visual Studio 2017 Professional 15.4.3 with resharper installed.  When I run the Selenium UI tests using the resharper's runner, IIS Express starts.  However, when I run the test with the VS Test Explorer, IIS Express doesn't start.  I have NUnit3TestAdapter 3.9 installed to make the NUnit show up in the test explorer.

I'm starting IIS as a new process in the base class.

I have created a small demo project of exactly what I'm doing.
NUnit: 3.8.1
NUnit3TestAdapter:3.9.0
.net platform 4.7
[NunitDemo.zip](https://github.com/nunit/nunit3-vs-adapter/files/1459529/NunitDemo.zip)

**Comment by CharliePoole** [comment]
Issue title confused me, making me think you were using the NUnit Explore API to examine tests, hence the title edit.

Two suggestions:
1. Debug your OneTimeSetUp method to make sure everything works as expected.
2. See if a brief wait for the process to actually start solves the problem.

**Comment by martinRocks** [comment]
Sorry about the confusion. 

I have used the StartIisExpress method in a number of different projects without any problems.  And when I run the test with resharper, IIS starts.  However, when I run it with Visual Studio's test explorer, the process doesn't start.  

I tried adding a Thread.Sleep(5000); before and after the _iisProcessExpress.Start(); without any luck.

Thank you for the suggestions.

**Comment by CharliePoole** [comment]
I'd be curious to know if it works when running under nunit3-console.exe. That would help narrow down the problem quite a bit: if it does work, it's an adapter problem, if not possibly an nunit problem. FYI, the fact that it runs with R# would give us more info, if we actually understood how R# runs NUnit. 😄

**Comment by martinRocks** [comment]
I completely understand about R#.  It does a ton of things I wish I understand better :)

I just tried the console runner (NUnit.ConsoleRunner.3.7.0) and it acted just like VS's test explorer.  I.E. the IIS Express process didn't start.  

Also, I just upgraded NUnit to version 3.9.0

Does that mean that this is a problem with NUnit?

**Comment by CharliePoole** [comment]
Most likely it is. I'm moving this to the NUnit repo.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit #2557](https://github.com/nunit/nunit/issues/2557) via [**ZenHub**](https://www.zenhub.com/)
