### ISSUE TITLE
NUnitEngineException when running NetCoreApp1.0 test project from vstest.console.exe

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#417]
@gyorgynadaban commented on [Fri Aug 18 2017](https://github.com/nunit/dotnet-test-nunit/issues/121)

Hi,

I ran into an issue trying to use Visual Studio Team Services for running our unit tests.
The test runs fine when:
- Executed via "dotnet test"
- From within Visual Studio

However, Visual Studio Team Services invokes vstest.console.exe, which fails with **NUnitEngineException**.

Sample project file:
``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RuntimeFrameworkVersion>1.0.4</RuntimeFrameworkVersion>
    <PackageTargetFallback>$(PackageTargetFallback);dnxcore50;portable-net451+win8</PackageTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <ApplicationIcon />
    <OutputTypeEx>library</OutputTypeEx>
    <StartupObject />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.7.1" />
    <PackageReference Include="NUnit.Console" Version="3.7.0" />
    <PackageReference Include="nunit3testadapter" Version="3.8.0" />
    <PackageReference Include="System.Runtime" Version="4.3.0" />
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
  </ItemGroup>

</Project>
```

Sample test class:

``` csharp
using System;
using NUnit.Framework;

namespace TestProj
{
    [TestFixture]
    public class MyTests
    {
        [Test]
        public void DummyTest()
        {
            Assert.IsTrue(true);
        }
    }
}
```

Command line (from Powershell):
``` powershell
$vsTest = "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe";
iex "& `"$vsTest`" .\bin\Debug\netcoreapp1.0\TestProj.dll /logger:trx /TestAdapterPath:$($env:USERPROFILE)\.nuget\packages /UseVsixExtensions:true /logger:trx"
```

---

@rprouse commented on [Sat Aug 19 2017](https://github.com/nunit/dotnet-test-nunit/issues/121#issuecomment-323524659)

Try removing NUnit.Console from your dependencies. The console can't run .NET Core tests.

Does the powershell command line work locally for you adjusting the `/TestAdapterPath` to point to your packages directory?

Another possibility is that another project in your solution has a reference to an older version of the NUnitAdapter and the test task is using that. Or if it is your own build host, the `$($env:USERPROFILE)\.nuget\packages` has an old copy. You can specify the path to the adapter in the advanced options for the test task.

---

@gyorgynadaban commented on [Sat Aug 19 2017](https://github.com/nunit/dotnet-test-nunit/issues/121#issuecomment-323530577)

The sample project here reproduces the issue. Have you tried running the sample and did you get different results?

The Powershell command works in terms of it executes the vstest.console.exe and the TestAdapterPath is correct on both my dev box and VSTS.

My solution has a single test project, and there's no chance using an older adapter as I started with NUnit3 from scratch, only adding the latest package. Besides, the VSTS cleans the work environment before each execution. I **did** specify the path to the adapter which is the **$($env:userprofile)\.nuget\packages** part.

---

@rprouse commented on [Mon Aug 21 2017](https://github.com/nunit/dotnet-test-nunit/issues/121#issuecomment-323897900)

@gyorgynadaban no I didn't get a chance to test. NUnit gets dozens of issues and comments per day and all of us are volunteers and do our best to keep up in our spare time, but it can be hard to help diagnose everyone's problems and keep the projects moving forward.

The sample project in this repository shouldn't work, it uses the old `project.json` format which isn't supported by the new CLI tools or our new test adapter.

What errors are you seeing when you run your tests? This is working for most people, so we need to figure out what you have done differently.

---

@gyorgynadaban commented on [Tue Aug 22 2017](https://github.com/nunit/dotnet-test-nunit/issues/121#issuecomment-324004245)

Rob, I appreciate that volunteers don't have a lot of time on their hands, and thank you for your contribution.

It is precisely why I added this sample **csproj** created with Visual Studio 2017.

I cannot tell from your brisk questions what you mean by "what errors am I getting" as I explained it already: none when running from within Visual Studio or when running **dotnet test**, but when executed via **vstest.console.exe** I only get a single 
NUnitEngineException.

Please, just try running the sample, there's nothing more telling than actually seeing for yourself.

As for this working for most people, it's using 1.0 .NET Core, is that unusual?

---

@rprouse commented on [Sat Nov 18 2017](https://github.com/nunit/dotnet-test-nunit/issues/121#issuecomment-345461977)

I am moving this issue to the adapter repository. It belongs there because your code doesn't use this adapter, but it.

**Comment by OsirisTerje** [comment]
Updating the NUnit3TestAdapter tes project from 3.8.1 to 3.9.0 give exactly this error, so there is some regression here.  
![image](https://user-images.githubusercontent.com/203432/33796528-3a30ec14-dcf6-11e7-80fb-e06aae3b129b.png)
I have uploaded the branch https://github.com/nunit/nunit3-vs-adapter/tree/Issue417-NUnitEngineException which shows the error.

**Comment by rprouse** [comment]
The engine is copied into the bin folder along with the adapter in this props file in the NuGet package, https://github.com/nunit/nunit3-vs-adapter/blob/master/nuget/netcoreapp1.0/NUnit3TestAdapter.props

The `PerformShadowCopy` in the error is suspicious. Can you check that temp directory and see if the engine was shadow copied along with the adapter? If could be a change in VS, not the adapter?
