### ISSUE TITLE
No tests discovered in .NET Core project with NUnit >=3.8.1

### ISSUE THREAD

**Issue by Maritims** [nunit/nunit3-vs-adapter#420]
Attempted to write a test today using NUnit 3.8.1 for a .NET Core project. No tests discovered when I built the solution and attempted to run all tests from the unit test explorer in VS2017 15.4.4. I updated to the latest versions of both NUnit and the NUnit3TestAdapter but did not experience any improvement. Still no tests discovered.

The target framework is .NET Standard 1.6.

I made a minimal repo which reproduces the issue. It contains one fresh .NET Standard library project which references the latest versions of NUnit and the adapter, the single test in there is not discovered.

Link to repo: [https://github.com/Maritims/UnableToDiscoverTests](url)

Output from the Tests pane in VS2017 (diagnostic mode):

> [23.11.2017 15:10:45 Diagnostic] About to Enqueue operation 'RunAllOperation', hashcode:63464671 
> [23.11.2017 15:10:45 Diagnostic] Enqueue operation 'RunAllOperation', hashcode:63464671 
> [23.11.2017 15:10:45 Diagnostic] Operation left in the the queue: 1
> [23.11.2017 15:10:45 Diagnostic] 	'RunAllOperation', hashcode:63464671
> [23.11.2017 15:10:45 Diagnostic] 
> 
> [23.11.2017 15:10:45 Diagnostic] Processing Queue .....
> [23.11.2017 15:10:45 Diagnostic] Operation Dequeue : 'RunAllOperation'
> [23.11.2017 15:10:45 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetStarted, operationInProgress=False
> [23.11.2017 15:10:45 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetStarted, InProgress=False
> [23.11.2017 15:10:45 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionStarting, operationInProgress=True
> [23.11.2017 15:10:45 Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionStarting, InProgress=False
> [23.11.2017 15:10:45 Diagnostic] We programmatically start the build in TestWindowHost.UpdateContainer... 
> [23.11.2017 15:10:45 Diagnostic] After we await the build that programmatically started in TestWindowHost.UpdateContainer... 
> [23.11.2017 15:10:45 Diagnostic] TestContainer update (build) complete : 255 ms
> [23.11.2017 15:10:45 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
> [23.11.2017 15:10:45 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False
> [23.11.2017 15:10:45 Diagnostic] test container discoverer executor://vsprojectoutputcontainerdiscoverer/v1, discovered 1 containers
> [23.11.2017 15:10:45 Diagnostic] Containers from 'Microsoft.VisualStudio.TestWindow.VsAdapters.VsProjectOutputContainerDiscoverer' :
> [23.11.2017 15:10:45 Diagnostic] 	C:\Users\martin\source\repos\UnableToDiscoverTests\UnableToDiscoverTests\bin\Debug\netstandard1.6\UnableToDiscoverTests.dll:executor://vsprojectoutputcontainerdiscoverer/v1
> [23.11.2017 15:10:45 Diagnostic] test container discoverer executor://testexplorerservicecontainerdiscoverer/v1, discovered 0 containers
> [23.11.2017 15:10:45 Diagnostic] No containers found from 'Microsoft.VisualStudio.TestWindow.Extensibility.TestExplorerServiceContainerDiscoverer' :
> [23.11.2017 15:10:45 Diagnostic] test container discoverer executor://cpsprojectoutputtestcontainerdiscoverer/v2, discovered 0 containers
> [23.11.2017 15:10:45 Diagnostic] No containers found from 'Microsoft.VisualStudio.TestWindow.Extensions.CPSTestContainerDiscoverer' :
> [23.11.2017 15:10:45 Diagnostic] test container discoverer executor://powershelltestexecutor/v1, discovered 0 containers
> [23.11.2017 15:10:45 Diagnostic] No containers found from 'PowerShellTools.TestAdapter.PowerShellTestContainerDiscoverer' :
> [23.11.2017 15:10:45 Diagnostic] test container discoverer executor://nodejstestexecutor/v1, discovered 0 containers
> [23.11.2017 15:10:45 Diagnostic] No containers found from 'Microsoft.NodejsTools.TestAdapter.TestContainerDiscoverer' :
> [23.11.2017 15:10:45 Diagnostic] test container discoverer executor://orderedtestadapter/v1, discovered 0 containers
> [23.11.2017 15:10:45 Diagnostic] No containers found from 'Microsoft.VisualStudio.MSTest.TestWindow.OrderedTestContainerDiscoverer' :
> [23.11.2017 15:10:45 Diagnostic] test container discoverer executor://generictestadapter/v1, discovered 0 containers
> [23.11.2017 15:10:45 Diagnostic] No containers found from 'Microsoft.VisualStudio.MSTest.TestWindow.GenericTestContainerDiscoverer' :
> [23.11.2017 15:10:45 Diagnostic] test container discoverer executor://webtestadapter/v1, discovered 0 containers
> [23.11.2017 15:10:45 Diagnostic] No containers found from 'Microsoft.VisualStudio.MSTest.TestWindow.WebTestContainerDiscoverer' :
> [23.11.2017 15:10:45 Diagnostic] DiscoveryOperation<RunAllOperation> FinishedChangedCotainers, changed container count is 0
> [23.11.2017 15:10:45 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionFinished, operationInProgress=False
> [23.11.2017 15:10:45 Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionFinished, InProgress=False
> 

Output from `dotnet test`:

> PS C:\Users\martin\source\repos\UnableToDiscoverTests\UnableToDiscoverTests> dotnet test .\UnableToDiscoverTests.csproj
> Build started, please wait...
> Build completed.
> 
> Test run for C:\Users\martin\source\repos\UnableToDiscoverTests\UnableToDiscoverTests\bin\Debug\netstandard1.6\UnableToDiscoverTests.dll(.NETStandard,Version=v1.6)
> Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Starting test execution, please wait...
> No test is available in C:\Users\martin\source\repos\UnableToDiscoverTests\UnableToDiscoverTests\bin\Debug\netstandard1.6\UnableToDiscoverTests.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are approp
> riate and try again.

**Comment by OsirisTerje** [comment]
You are using .netstandard, your test project must be either .net4* or .netcore.
