### ISSUE TITLE
Expand and reorganize Demo solution

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit3-vs-adapter#424]
We use the NUnit 3 Test Demo for exploratory testing,, particularly for seeing how things appear in the VS IDE. This would be facilitated if the demo were available for some other languages besides C# and with the solution moved to the top level of the project. Currently, it is nested under the adapter solution and doesn't get as much visibility as it should. As a further step, we might move it to its own repository but this issue does not envision doing that right away.

**Comment by CharliePoole** [comment]
@OsirisTerje Started work on this and discovered that the demo project now requires VS2017 since it includes .NET Core demo code as well. This seems to me to defeat the entire purpose of having the demo code in a separate project, one which could be opened in various versions of VS for test purposes. My inclination is to create separate solutions for VS2017 and earlier versions. What do you think?

**Comment by OsirisTerje** [comment]
Makes sense to me

**Comment by CharliePoole** [comment]
I created a new project repo. See nunit/nunit3-vs-adapter-demo#1. Once that's merged, I'll use this issue to remove the test demo code from this repository.
