### ISSUE TITLE
Access to the Mono.Cecil.dll is denied

### ISSUE THREAD

**Issue by AnyCPU** [nunit/nunit3-vs-adapter#428]
Hello,
I have recently started struggling with this problem:
> One or more errors occurred. (One or more errors occurred. (Access to the path '..\packages\NUnit3TestAdapter.3.9.0\build\net35\Mono.Cecil.dll' is denied.)) (Access to the path '..\packages\NUnit3TestAdapter.3.9.0\build\net35\Mono.Cecil.dll' is denied.)

I use self-hosted Visual Studio build agent on Windows Server 2012R2 version 6.3 build 9600.
Either vstest.console.exe or NUnit hangs up silently and that is all. After waiting for a one hour the VSO terminates a build task. 
I tried different settings of the Visual Studio Test Task, but it did not help.

* NUnit and NUnit3TestAdapter versions: *3.9.0.0*
* Visual Studio edition and full version number: *Microsoft Visual Studio Community 2015, Version 14.0.25431.01 Update 3, Microsoft .NET Framework, Version 4.7.02053*
* What .net platform and version is being targeted: *.NET Framework 4.6.2*
* If TFS/VSTS issue, what version, hosted, on-premises, and what build task you see this in: *Visual Studio Test v. 2,  VSTest v.14, The build Agent version 2.126.0* .

**Comment by rprouse** [comment]
Sorry, this is the first report of this. At what point do you see the error? You mention that it hangs during the test task, but is the error output during the NuGet restore or during the test task?

Is your project set to clean the entire workspace?

It sounds like you have a hung test process. Any chance of rebooting the test agent machine?

**Comment by AnyCPU** [comment]
@rprouse 
The build agent cleans the work dir every time. I make changes and push them, then a build task starts. It hangs up at the testing stage. After waiting for some minutes I cancel the build task and queue new one, then I see that error message.

I can do on the build machine whatever I want to.
I tried different settings. It did not help.

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?
Make it as small as you can, it should compile "as is".

**Comment by AnyCPU** [comment]
Hello @OsirisTerje 
I have found the cause. The cause is connected to Windows rights management for UrlReservations, exception handling and threading.
Due to some circumstances some threads had become dead locked. That is why Mono.Cecil and the other dlls were not unloaded.

I think this issue can be closed.

Thanks)

**Comment by OsirisTerje** [comment]
Superb!  Thanks for the information!
