### ISSUE TITLE
OneTimeSetup and Setup not always run until changed

### ISSUE THREAD

**Issue by brinkdinges** [nunit/nunit3-vs-adapter#430]
Right now all tests in one or two of my classes are suddenly failing. When I set a break point in my OneTimeSetup and run a test in debug mode, the break point isn't hit. In my OneTimeSetup (and I've changed it to Setup but that didn't change anything) I set a boolean in a static class to true. Nowhere in my solution do I set it to false, only its initial value is false.

Only when I edit the setup method (remove the semicolon and add it again), the method gets picked up and all of the tests in the class will run for a while. All is fine for a few minutes or hours and then I have to edit the method again. I have an identical setup method in about five classes but only or or two fail at the same time. 

The result is the same with or without NCrunch turned on. It happened in VS2015 as well as now in 2017. I tried to recreate the issue in a new project but couldn't reproduce it. 

It seems unrelated, but the coverage dots of NCrunch also don't properly appear when the Setup method isn't called. They should all be red in the image below. They appear again after editing the method.

![setupscreenshot](https://user-images.githubusercontent.com/15387410/34069195-532d889e-e24b-11e7-964c-2b57e73fdd69.png)

NUnit 3.9.0 with NUnit3TestAdapter 3.9.0
Visual Studio 2017 Community 15.5.2 
Resharper 2017.2.2. 
NCrunch 3.12.0.15 
.Net framework 4.5.2

**Comment by OsirisTerje** [comment]
Are there any messages in the Output/Test window?
Can you enable verbosity=5, and then see if there is any messages in Output/Test?
You enable Verbosity by adding a runconfig file, enable that in Tests/Test Settings/Select test settings file, see https://github.com/nunit/docs/wiki/Tips-And-Tricks  , or download an item template here: https://visualstudiogallery.msdn.microsoft.com/1cc3863b-f15f-4107-bb05-3586fd65540b

**Comment by brinkdinges** [comment]
Thanks for the help :) There are indeed useful comments in there:

[16-12-2017 19:32:24 Warning] SetUp failed for test fixture CADBooster.Drew.Test.Register.DrawingRegisterDocumentTest
[16-12-2017 19:32:25 Warning] SetUp failed for test fixture CADBooster.Drew.Test.Register.DrawingRegisterTest
[16-12-2017 19:32:25 Warning] System.TypeInitializationException : The type initializer for 'CADBooster.Drew.Test.Register.DrawingRegisterTest' threw an exception.
  ----> System.Exception : Unable to attach to SOLIDWORKS

The exception text is from my code and the stacktrace shows it is only thrown because the setup isn't run.

Both setups are identical to this. The only difference is the method name. There are a few more identical once in my solution and the failing once vary from time to time.
[OneTimeSetUp]
public static void Setup()
{
   SwHelpers.IsTest = true;
}

I then removed the semicolon and added it again. NCrunch runs the tests automatically and all 31 failing tests pass again. I then run all tests again using Visual Studio Test> Run > All tests and they fail again.

So the Setup methods only set a value in a static class to true. I tried adding a static constructor and set the default explicitly to false, that didn't change the outcome.

**Comment by CharliePoole** [comment]
While a failure in OneTimeSetUp __may__ indicate that the setup method threw an exception, that's not necessarily the case. The OneTimeSetUp phase of running a test class includes locating the constructor and constructing the class as well. If the class could not be constructed, then you would get the same error.

To get more info, I suggest running under the console runner and examining the XML result for the fixture that is failing. It should include a stack trace.

Note also that we can't help you much here WRT running under NCrunch, which executes tests diffrently from how the console and vs adapter run them.

**Comment by OsirisTerje** [comment]
Is it possible for you to create a small repro project for this behaviour?    You can upload it to a github repo or just attach it.

**Comment by brinkdinges** [comment]
Before posting this issue I tried to recreate the issue in a new project. I wasn't able to recreate the error. 

I do understand that you can't help me if NCrunch causes the issue, I just added the info for completeness. I'm not considering it a suspect because the VS test runner also fails many tests. I just checked if running Ncrunch on a single core was the reason for failing, but the results were identical. 

I ran the tests using the console runner and it pointed towards an error in the constructor and towards a line halfway the class. Since these test classes don't have a constructor, I found a property object that called a method to get its initial value. Apparently that property was initialized sometimes before the Setup or OneTimeSetup was being called. I moved the assignment to the Setup and didn't see an error again. 

Thanks a lot for showing me how to debug this issue, I might be able to do it myself next time :)
