### ISSUE TITLE
No netstandard package

### ISSUE THREAD

**Issue by noelmcgrath** [nunit/nunit3-vs-adapter#432]
NUnit 3.9.0 NUnit3TestAdapter 3.9.0
Visual Studio Professional 2017 v 15.5.2

Steps:
Create a .NET Standard class library
   Default Target Framework will be .NET Standard 2.0
Install NUnit3TestAdapter via Manage NuGet Packages

The following message appears:
![image](https://user-images.githubusercontent.com/671790/34482640-360df492-efb1-11e7-8a3f-46feb6e27cb7.png)

Clean and Rebuild Solution so that tests from the project appear in TestExplorer

Expected:
Tests appear

Actual:
No tests appear.

More info
If I do same steps with a Class Library(.NET Framework), the tests appear.
I believe it is due to the fact that there is no netstandard  option available in package.

Can a netstandard package be made available as I believe a lot of people would use the package in this way?
thanks

**Comment by rprouse** [comment]
You need to change your test project to .NET Core 2.0. See our FAQ, https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard

Visual Studio and VSTest require that the tests target a specific platform. .NET Standard is like a Portable library in that it does not target any specific platform, but can run on any supported platform. Microsoft decided that your tests should be compiled to target a platform so they know which platform to run your tests under and you get the behavior you expect for the platform you are targeting. You can however target multiple platforms in your tests and compile and run each from the command line. It still only runs one platform from Visual Studio, but I would hope that is being worked on. 

It is similar to a console application, it cannot be .NET Standard, it must target a platform, .NET Core or .NET Framework.

This limitation is the same for all test adapters including xUnit and MSTest2. It is not an NUnit issue.

**Comment by noelmcgrath** [comment]
thanks rprouse
