### ISSUE TITLE
Question on dotnet test color selection for printing test output

### ISSUE THREAD

**Issue by Suremaker** [nunit/nunit3-vs-adapter#435]
Hello,

Given test:
```c#
[TestFixture]
public class Class1
{
    [Test]
    public void Test_with_progress()
    {
        TestContext.Progress.WriteLine("progress");
    }

    [Test]
    public void Test_with_output()
    {
        TestContext.Out.WriteLine("output");
    }

    [Test]
    public void Test_with_assert_ignore()
    {
        Assert.Ignore("ignored");
    }

    [Test]
    public void Test_with_assert_inconclusive()
    {
        Assert.Inconclusive("inconclusive");
    }
}
```

when tests are run with `dotnet test` command, a following output it printed:
![image](https://user-images.githubusercontent.com/1894621/34850041-5413a9ba-f71c-11e7-99e1-63e683a61a24.png)

What is a bit confusing here is that:
* progress messages are printed with yellow color indicating warnings (even thought they are not really warnings),
* test ignore reason (and inconclusive test reason) message is printed with red color indicating error.

Would it be possible to make nunit adapter to report messages to dotnet test in a way that their color will properly reflect the severity of the message?

**Comment by rprouse** [comment]
I am pretty sure that we don't have any control over this in the adapter although I would like to try similar code in xUnit and/or MSTest to see how `dotnet test` handles those frameworks.

**Comment by jnm2** [comment]
This is a benefit that will fall out of `dotnet nunit`.

**Comment by OsirisTerje** [comment]
I'll close this for now, as we don't have any control over this in the adapter.
