### ISSUE TITLE
Why is netcoreapp1.0 targeted rather than netstandard1.x/2.x?

### ISSUE THREAD

**Issue by phatcher** [nunit/nunit3-vs-adapter#439]
NUnit3 targets net20->net45 and netstandard1.3/1,6 whereas NUnit3TestAdapter targets net35 and netcoreapp1.0

AFAIK the idea is that dll's should target netstandard and applications should target netcore since you need an actual framework to run.

The issue I have is if I write a library and target netstandard2.0 and do the same for my test assembly, I get a warning 

```
C:\Devel\OpenSource\NCheck\code\NCheck.Test\NCheck.Test.csproj : warning NU1701: Package 'NUnit3TestAdapter 3.9.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

I can suppress this, but it adds friction.

Oddly enough Microsoft.NET.Test.Sdk targets net45 and netcoreapp1.0 but I don't get a warning from that

**Comment by rprouse** [comment]
@phatcher it was the .NET Team's decision that they require test assemblies target a specific platform when using `dotnet test`, the VS adapter or `VSTest`. The alternative is that you would need to pass in a command line option for which platform to run. You will find that all .NET Test frameworks work the same. Your test assembly must target .NET Core or .NET Framework.

For more info, see our FAQ at https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard

> Visual Studio and VSTest require that the tests target a specific platform. .NET Standard is like a Portable library in that it does not target any specific platform, but can run on any supported platform. Microsoft decided that your tests should be compiled to target a platform so they know which platform to run your tests under and you get the behavior you expect for the platform you are targeting. You can however target multiple platforms in your tests and compile and run each from the command line. It still only runs one platform from Visual Studio, but I would hope that is being worked on. I haven't tested 15.3 yet.

> It is similar to a console application, it cannot be .NET Standard, it must target a platform, .NET Core or .NET Framework.

> This limitation is the same for all test adapters including xUnit and MSTest2.
