### ISSUE TITLE
Does nunit support code coverage with .net standard projects in VS2017?

### ISSUE THREAD

**Issue by berndu** [nunit/nunit3-vs-adapter#440]
Tried with Version 3.9.0.0 with Visual Studio 2017 15.5.4

The test project is a .net 4.6.1 project - the target project is a .net standard 2.0 project.
I ran the tests locally in visual studio.

I can only see the test project in the coverage results, what is quite suboptimal for checking the coverage of the tested code.

Maybe I am doing something wrong here? Is it still missing support or should it already work?

**Comment by OsirisTerje** [comment]
This is still missing in VIsual Studio.  We're trying to push them.

**Comment by berndu** [comment]
I managed to get it to work - so i will close this question.
The reason it has not worked in our setting was, that the .net standard project does not use full debug info (portable was the default).
If i switch to full we can see the coverage results correctly.

See here [https://developercommunity.visualstudio.com/content/problem/96117/test-analyze-code-coverage-not-including-net-stand.html](https://developercommunity.visualstudio.com/content/problem/96117/test-analyze-code-coverage-not-including-net-stand.html)

**Comment by OsirisTerje** [comment]
Cool, thanks!
