### ISSUE TITLE
NUNIT 3.x (NUnit 2.0) - Max Number of Tests. 

### ISSUE THREAD

**Issue by BruceGombrelli** [nunit/nunit3-vs-adapter#448]
We have used multiple versions of VS and are currently on 2015. We have always had issues with the Test Adapters loading one of our biggest test projects.  I finally went in and started excluding files and finally got it to load (I'm currently testing version 3.9 using the 3.0 test adapter and VS Test Runner).

I don't have an exact number of tests (yet) but when I can currently load with about 124,000 tests but as the number increases it will reach a point that it simply will not load (no error message).  In the older days I would get "out of memory". (I followed some threads on that, and that's why I switched to 3.9 to see if that would help.

Is there a quantity of tests limitation or is it just a memory limitation and when that is reached, that's it.  

I'm not seeing any error, just no loading.

**Comment by CharliePoole** [comment]
There's no explicit limit, so it's probably a memory issue. Questions...

1. You put (NUnit 2.0) in your description. What do you mean by that?

2. Have you tried running your tests in the nunit 3 console runner? That would tell us if the issue is with NUnit itself or just with the adapter.

**Comment by BruceGombrelli** [comment]
I will get back you on this when I do some more investigation this week. Thanks!!  Tests do succeed when executed when run on the cmd line, but it's takes 2x time to load it (tests take 30 min, total time is reported as 1 hour 30 min (approx)) - I just can't load them in the VS Test Runner.  I ran into the same problem when using 2.0 adapter except you would see an outofmemory error (same thing when using 3.6.1 - but no outofmemory error with 3.9)

**Comment by CharliePoole** [comment]
If your tests take extremely long to load, you should look for any user code that is executed in order to discover the tests. That would include any methods invoked from `TestCaseSource`. Currently, test discovery (aka loading) is serial, which makes things even worse.

In the console runner, we have done some work to allow loading to proceed in parallel across multiple assemblies, but I'm not sure that has been released yet. Under the adapter, each assembly is loaded and executed in sequence and due to constraints of the Test Explorer design, the discovery actually happens twice. 😢

**Comment by OsirisTerje** [comment]
1) If you have the tests over multiple assemblies, you **can** enable VSTest (TestExplorer) parallell testing by enabling it in Test explorer by
![image](https://user-images.githubusercontent.com/203432/35932686-9ba4fba4-0c38-11e8-9e6e-8a24b4887770.png)
This setting is stored with the solution.

or by using a runsettings file and setting MaxCPU Count there, e.g. to 0, or anything different from 1.  You can download a template for such a runsettings file from https://marketplace.visualstudio.com/items?itemName=OsirisTerje.Runsettings-19151 

2). If you want to find out which tests are taking too long, you can use the dumps, which give you xml dump files for all interaction between the adapter and nunit, see https://github.com/nunit/docs/wiki/Tips-And-Tricks

**Comment by BruceGombrelli** [comment]
Assembly contains no NUnit 3.0 tests: c:\Users\bgombrelli\Perforce\bgombrelli_SHP-DEV-19-PC_NUNIT_2.0_to_3.0_Update_-_Edit_Definitions_Solution_4452\DataModels\Edits\Source\bin\Debug\Shp.DataModels.Edits.dll
Exception NUnit.Engine.NUnitEngineException, Exception thrown discovering tests in c:\Users\bgombrelli\Perforce\bgombrelli_SHP-DEV-19-PC_NUNIT_2.0_to_3.0_Update_-_Edit_Definitions_Solution_4452\DataModels\Edits\Test\bin\Debug\Shp.DataModels.EditsTests.dll
An exception occurred in the driver while exploring tests.
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, IMessageLogger messageLogger, ITestCaseDiscoverySink discoverySink)
Innerexception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore(String filter)
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)

**Comment by BruceGombrelli** [comment]
Trying to find a different way to repro, It is definitely tied to the amount of tests that are included that use the testcasesource technique.  The issues is just a few tests using it do not create a problem. We are also closed tied to our database tables with these tests so it's hard to come up with a good "externally" available version.  We have a total of 160K tests in the edits area if I reduce the total amount of tests (by not including textfixtures, it will load at VERY approximately 110K tests depending on if they contain testecasesource or not.

**Comment by BruceGombrelli** [comment]
I tried to set the verbosity to 5 in testsettings and I'm not getting any more detail then before, I was hoping for more debug info..So maybe that's a good place to continue, to get more debug info.

**Comment by BruceGombrelli** [comment]
InternalTrace: Initializing at level Debug
13:44:07.640 Debug [13] DefaultTestAssemblyBuilder: Loading c:\Users\bgombrelli\Perforce\bgombrelli_SHP-DEV-19-PC_NUNIT_2.0_to_3.0_Update_-_Edit_Definitions_Solution_4452\DataModels\Edits\Test\bin\Debug\Shp.DataModels.EditsTests.dll in AppDomain domain-bc64625a-Shp.DataModels.EditsTests.dll
13:44:07.649 Debug [13] DefaultTestAssemblyBuilder: Examining assembly for test fixtures
13:44:07.778 Debug [13] DefaultTestAssemblyBuilder: Found 1424 classes to examine
13:44:45.975 Debug [13] DefaultTestAssemblyBuilder: Found 657 fixtures with 386704 test cases

**Comment by BruceGombrelli** [comment]
Slightly different stack:

Slightly different stack:

Exception thrown discovering tests in c:\Users\bgombrelli\Perforce\bgombrelli_SHP-DEV-19-PC_NUNIT_2.0_to_3.0_Update_-_Edit_Definitions_Solution_4452\DataModels\Edits\Test\bin\Debug\Shp.DataModels.EditsTests.dll
NUnit.Engine.NUnitEngineException: An exception occurred in the driver while exploring tests. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore(String filter)
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   --- End of inner exception stack trace ---
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, IMessageLogger messageLogger, ITestCaseDiscoverySink discoverySink)
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, IMessageLogger messageLogger, ITestCaseDiscoverySink discoverySink)

**Comment by BruceGombrelli** [comment]
Possibly related? https://github.com/nunit/nunit/issues/2706

**Comment by smm1369** [comment]
a
