### ISSUE TITLE
Category excludation as in console runner

### ISSUE THREAD

**Issue by wanted156** [nunit/nunit3-vs-adapter#455]
I've noticed that in the Nunit 3 VS adapter there is no way to exclude tests containing a specific category like in the console runner (cat != category). I've tried sorting the tests using traits and selecting only the categories i want to run, but if a test consists of two different categories and you "exclude" one and the other one not, then it will still be run, which is something the console runner does not do. I've also noticed that Description [insertDescriptionHere] shows up in some cases, without specifying the attribute.
![image](https://user-images.githubusercontent.com/19693647/36432720-2aa76608-165b-11e8-9abd-5776458c8423.png)

Are those 2 scenarios meant to be like that?

**Comment by OsirisTerje** [comment]
Have you tried to do    -Trait:"Whatever" ?    Notice the dash/hyphen in the start ?

**Comment by wanted156** [comment]
To be completely honest, i didn't even realise there is a search bar on top. I tried it and it worked just as I wanted it to. Is there any documentation regarding the arguments? I've noticed that i couldn't use -Trait:"Category1,Category2", only -Trait:"Category1" -Trait:"Category2" worked.

Also, is there any idea why the Description is there as a trait? Thnaks :)

**Comment by OsirisTerje** [comment]
@wanted156  Take a look midway down in this post: https://blogs.msdn.microsoft.com/devops/2012/11/09/how-to-manage-unit-tests-in-visual-studio-2012-update-1-part-1using-traits-in-the-unit-test-explorer/ , (Sections "Control test runs based on other filter terms", or "Using Traits to control test running" and downwards).
