### ISSUE TITLE
VSTS free minutes used up

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit3-vs-adapter#456]
This month I've pushed too many times to branches that build, as witnessed by the failure on master! 😲

> Your account has no free minutes remaining. Add a hosted pipeline to run more builds or releases. See https://nunit.visualstudio.com//_admin/_buildQueue?_a=resourceLimits for more information.

Is this something the .NET Foundation can do for us?

**Comment by rprouse** [comment]
Yes, although I'm not sure it is available yet. @jongalloway, is this something that you can help with?

**Comment by rprouse** [comment]
We now have unlimited build minutes. Next step, get build definitions working for the other projects 😄
