### ISSUE TITLE
Digitally sign VSIX extension

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit3-vs-adapter#459]
One of the things I was looking forward to once we joined the .NET Foundation was Authenticode signing.

![](https://user-images.githubusercontent.com/8040367/36597373-e8960170-1876-11e8-95eb-63f84671efcd.png)

Is that something we're interested in? What does it take to get that set up?

**Comment by rprouse** [comment]
We'd thought about signing the MSI installer, but not the VSIX. We could though. We're still waiting on the license agreements to sign though 😦 I'll send another email to Jon about that...

**Comment by rprouse** [comment]
Talked to Jon, this is definitely something we can do. Same with signing our NuGet packages. I would prefer to get everything building for release in CI, possibly VSTS and store secrets like this in key vault where they will be secure.

**Comment by OsirisTerje** [comment]
Closing since VSIX is being deprecated, and 4.X version does not deliver this anymore.
