### ISSUE TITLE
NUnit failed to load binary for unknown reason

### ISSUE THREAD

**Issue by TannerStevenson** [nunit/nunit3-vs-adapter#465]
I am using NUnit 3.7 and NUnit Test Adapter 3.9 in visual studio 2015 to run SpecFlow functional tests. Yesterday the test adapter successfully loaded all of my functional tests and today I get an error saying "NUnit failed to load [Path to dll]".

I don't know if this is related, but the dependency copying functionality of NUnit was making functional testing very difficult (I must explicitly find and load binaries that are installed by other applications in their respective ProgramFiles bin folders), so I made a batch script to remove all binaries in the bin/Debug folder except for the test project and test dependency binaries. I configured this batch script to run at the end of the test projects build, and ever since I built and ran the batch, the test binary will no longer load, whether or not I run the batch file after building.

**Comment by CharliePoole** [comment]
Can you clarify what you mean by the "dependency copying functionality of NUnit?"

NUnit doesn't copy anything at runtime. Some files are copied when you install using the nuget package. In general, NUnit relies on the environment and/or the user to make necessary dependencies available.

**Comment by TannerStevenson** [comment]
Does NUnit try to determine all binary dependencies and sub-dependencies (binaries referenced by the binaries referenced by the project) and copy all dependencies to the bin/debug folder of the visual studio project? If not, that functionality must come from SpecFlow.

Either way, I reverted my changes and verified that the assembly gets loaded just fine. Whatever I changed to make it so the binary cannot be loaded by the NUnit test adapter is not obvious to me, so I was wondering what would make this error message appear? Other binaries without tests give a message saying that no tests were found.

**Comment by CharliePoole** [comment]
No, NUnit does no analysis of dependencies. The engine (which is used by the VS adapter as well as the NUnit console runner) examines the top level of dependencies looking for a reference to a known framework such as NUnit itself. It then loads the test assembly, relying on the runtime to pull in any references. The references must be found in the application base, any private probing path or the GAC in order for this to succeed. The logic of the original (and present) NUnit developers was that NUnit is a tool used by developers who can be relied upon to make all the necessary dependencies available at runtime.

One way this sort of problem sometimes comes up is when folks have relied on Visual Studio to copy dependencies and then switch to an environment where VS is not present. It doesn't sound like that's the case for you, however.

Unfortunately, I'm not familiar with how SpecFlow works.

**Comment by TannerStevenson** [comment]
It seems that running the batch file and removing extraneous binaries is the source of error. Do you know what exactly the test runner looks for when loading a binary that contains NUnit tests?

**Comment by rprouse** [comment]
The NUnit console runner only requires the `nunit.framework.dll` in your bin directory with your tests, but you must also ensure that all assemblies that your tests reference and all assemblies that those reference are also in the probing path. It is no different than running a .NET program, all references must be loadable.

**Comment by CharliePoole** [comment]
When you say "runner" I'm taking that to mean the NUnit engine's runner, which is what is used if you are running the console or VS adapter. 

It looks to see that the binary has a reference to `nunit.framework`. Period. It then tries to load the framework and locate an entrypoint in it. It uses .NET `Load`, so the normal rules of finding .NET assemblies are followed.

Once the framework is located, it will attempt to load your test assembly. Once again, it will use .NET `Load` to do so. Any dependencies will be located by .NET, following the normal rules. If they are not present, the load fails.

**Comment by TannerStevenson** [comment]
I see, so even during test discovery, all dependencies must be found by the .NET loader?

**Comment by rprouse** [comment]
> I see, so even during test discovery, all dependencies must be found by the .NET loader?

Yes, test discovery loads all dependencies. NUnit has features like `[TestCaseSource]` that create tests dynamically based on data. NUnit must run that code to discover the tests. That causes references to be loaded.

I am going to close this issue. If you need more help, just post. We will see it.
