### ISSUE TITLE
Release Readiness Review for version 3.10

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#472]
The latest pre-release package can be found at : https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter  

Latest VSIX: https://ci.appveyor.com/project/CharliePoole/nunit3-vs-adapter/build/artifacts.

Add this to your nuget.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="NUnit prerelease" value="https://www.myget.org/F/nunit/api/v3/index.json" />
    </packageSources>
</configuration>
```

Latest version is : NUnit3TestAdapter 3.10.0-dev-00820
Install directly in PM console:  
` Install-Package NUnit3TestAdapter -Version 3.10.0-dev-00820 -Source https://www.myget.org/F/nunit/api/v3/index.json`

Verify it is working on (add an OK and sign in each cell).  Rudimentary check, no crash, no suspicious warnings in output, discover and execution works. 

|   Target   |    VSIX    |    Nuget  .net FW 4.6  |  Nuget .net core 2 |
| ---------  |  --------  |  ----------  |  ---- |
| Visual Studio 2017 | ✔ jnm2 | ✔ jnm2 | ✔ jnm2 |  
| VSTest.Console      | ✔ jnm2 | ✔ jnm2 | ✔ jnm2 |
|  TFS 2017              |    |    |    |
| VSTS                     |  N/A |   |     |

Confirm the following issues are working  (Add Ok and sign) 

| Issue/feature |   VS 2017  - VSIX |  VSTest.Console - VSIX  | VS 2017 - Nuget |  VSTest.Console - Nuget |
| ----- | --- |  ---- | ---- | ---- | 
|  #47 | n/a |   | n/a | ✔ jnm2 | 
|  #296  | ✔ jnm2 | ✔ jnm2 | ✔ jnm2, users | ✔ jnm2, users |  
|  #310  | ✔ jnm2 | n/a | ✔ jnm2 | n/a |  
|  #365  |   |   |   | ✔ [halex2005](https://github.com/nunit/nunit3-vs-adapter/pull/418#issuecomment-346114092) |  
|  #419  |   |   | ✔ jnm2 | ✔ jnm2 |  
|  #444 |   |     | ✔ @osiristerje | ✔ @osiristerje |   
|  #452  | n/a |   | n/a | ✔ jnm2 |  
|  #460  |   |   | ✔ jnm2 | ✔ jnm2 |  
|  Categories showing and run by works|   |   | ✔ jnm2 | ✔ jnm2 | 
|  Can debug and jump to source | ✔ jnm2 | n/a | ✔ jnm2 | n/a | 
|  Can filter on categories  |  |   | ✔ jnm2 | ✔ jnm2 | 

All issues should be checked on at least one column.  If checked by reporter, copy from issue with reporter. 

(Update directly in this item.)

**Comment by jnm2** [comment]
Edited to add current VSIX link and use triple-backtick fences for the code block (some of the elements were missing).

**Comment by jnm2** [comment]
Tested against ApiContractGenerator and Castle.Windsor so far.

**Comment by jnm2** [comment]
@OsirisTerje It seems like there is overlap between VSTest.Console and TFS/VSTS, since the Visual Studio Test build step is just a wrapper around a VSTest.Console call.

**Comment by OsirisTerje** [comment]
Yep it is, but the wrapper and UI is a "thing" in itself, so - just to be sure we don't miss anything, and also many people don't know that is what is happening under the hood.

**Comment by jnm2** [comment]
@OsirisTerje I've got at least one checkmark in every issue row and no warnings signs.
