### ISSUE TITLE
Skip surfacing certain properties as UI groupings

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit3-vs-adapter#474]
`Description` is something that people are not likely to want to group by and it introduces a lot of noise:

<img src="https://user-images.githubusercontent.com/8040367/36951103-6d498ed4-1fcd-11e8-864c-ca5e0f75cc78.png" width="300" />

Likewise, per-value `Timeout` and per-value `Repeat` don't seem that useful as things to group by.

Having them as hidden traits seems fine. That way you can still search for `Trait:"Repeat"` in Test Explorer.

**Comment by jnm2** [comment]
Updated image.

**Comment by rprouse** [comment]
Good idea, that is confusing. We should do a scan of the framework to make sure we get all of the properties users won't want to see in the UI.

**Comment by CharliePoole** [comment]
I haven't looked at the code, but here's what I think happened. We used to suppress internal attributes from appearing as traits. They were marked as beginning with an underscore. For example, once upon a time, the descrition property was _DESCRIPTION. As time went on, we added attributes for our own use that didn't use this convention and some of the old internal attributes got "normal" names. I don't think it was intentional, but just happened.

**Comment by jnm2** [comment]
That makes sense! I wondered when this ever came into play.

https://github.com/nunit/nunit3-vs-adapter/blob/3b9e3953fd4d3996858fc677744799939ed0afe6/src/NUnitTestAdapter/CategoryList.cs#L90-L91

**Comment by OsirisTerje** [comment]
This then needs to be fixed in the framework, right?

**Comment by CharliePoole** [comment]
Not necessarily. You could have a list of properties to bypass in the adapter **or** you could rename the properties in the framework.

**Comment by jnm2** [comment]
I just finished telling @sharwell how to determine whether an `ITest` is being run with a single-threaded apartment. Renaming the framework properties is something I would hope to avoid unless we first provide a strongly-typed API for it.

**Comment by rprouse** [comment]
Last time we changed names we broke other runners, so we probably don't want to do that. A list in the adaptor is a hacky solution, but it is backwards compatibile and won't break anything.

**Comment by CharliePoole** [comment]
I agree and for another reason as well. Properties don't exist for the adapter to use for grouping. That's a usage that has been retrofitted to match what the Test Explorer team wanted when they first came up with Traits and wanted to showcase it for a Build conference. It's logical to make any adaptations in the adapter.

**Comment by dzmitry-lahoda** [comment]
Issue with Description it my real biggest pain. It slows down test explorer UI to miserable. Any plan for fixing this? If this and donation page will be fixed I will donate again:)

**Comment by OsirisTerje** [comment]
Discovery has been removed by the Test Explorer in 15.7.

**Comment by OsirisTerje** [comment]
Sorry, misspelled, corrected.
