### ISSUE TITLE
Digital signature. c#

### ISSUE THREAD

**Issue by kuatkh** [nunit/nunit3-vs-adapter#475]
hi, everyone. 
i have some question. 
if i try to add a digital signature to a doc file a second time, should i change hash code?

**Comment by CharliePoole** [comment]
This issue doesn't seem to have anything to do with the test adapter.

**Comment by kuatkh** [comment]
why you close this issue?

**Comment by CharliePoole** [comment]
See comment. This is a general question about digital signing. If it really has some relation to the nunit3-vs-adapter, please edit the question so we understand.

**Comment by kuatkh** [comment]
CharliePoole, i change question

**Comment by CharliePoole** [comment]
I still don't see why you are asking this here. What is the connection to the adapter?

**Comment by kuatkh** [comment]
oh sorry. could you delete this issue?

**Comment by CharliePoole** [comment]
If it's a question about asp.net programming, use some asp.net forum. This is the issue repository for our VA adapter.

**Comment by CharliePoole** [comment]
Issues are only closed, there is no delete available.

**Comment by kuatkh** [comment]
okay. thank you
