### ISSUE TITLE
VS shows error message when updating to 3.10.0.0

### ISSUE THREAD

**Issue by JohanLarsson** [nunit/nunit3-vs-adapter#482]
I got the notification about the update and selected it.
Closed Visual Studio and then got:
![image](https://user-images.githubusercontent.com/1640096/37166961-d30bdfa2-2300-11e8-86bb-023f7e1b2bf8.png)

When restarting Visual Studio it reports the latest version as installed.
Running tests using the VS testrunner works, did not work before.

Visual Studio Enterprise 2017, 15.6.0
Windows 10.

**Comment by jnm2** [comment]
Hey, I had a thought. Did you install any prerelease of 3.10?

**Comment by JohanLarsson** [comment]
Nope, no prerelease.

**Comment by JohanLarsson** [comment]
I updated on my other computer now, worked fine. Maybe my VS is broken somehow on computer 1.

**Comment by rprouse** [comment]
Visual Studio can automatically update extensions. Maybe it was already updated?

**Comment by JohanLarsson** [comment]
Don't know, you can close the issue if you want but maybe best to wait a couple of days and see if other people run into the same.

**Comment by rprouse** [comment]
Thanks. I've applied the confirm label. We'll leave it open for a few days then close.
