### ISSUE TITLE
NUnit TestResult level messages are logged at Run level instead of TestResult level

### ISSUE THREAD

**Issue by abhishkk** [nunit/nunit3-vs-adapter#486]
**Environement Info**
* NUnit: 3.8.1
* NUnit3TestAdapter: 3.8.0
* Visual Studio edition: VS enterprise 2017 15.6.1
* .net platform: v4.5.2
* Repro: [NUnitTestProject.zip](https://github.com/nunit/nunit3-vs-adapter/files/1806503/NUnitTestProject.zip). Run it from command line: `vstest.console.exe NUnitTestProject.dll /logger:trx`

**Issue**
Nunit sends Console.Error.WriteLine() content as a run level message  to testPlatform which is captured in trx file in Runinfo of ResultSummary

For example, TestResultSummary of a Nunit test:

```
  <ResultSummary outcome="Failed">
    <Counters total="2" executed="2" passed="1" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>NUnit Adapter 3.8.0.0: Test execution startedRunning all tests in C:\Users\userName\Source\Repos\NUnitTestProject\NUnitTestProject\bin\Debug\NUnitTestProject.dllNUnit3TestExecutor converted 2 of 2 NUnit test casesNUnit Adapter 3.8.0.0: Test execution complete</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="userComputer" outcome="Warning" timestamp="2018-03-13T14:35:17.6470877+05:30">
        <Text>console error</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
```

**Expected Behavior**

Any logging either trace, debug, error etc at test result level should be logged or captured under TestResult tag not at RunLevel. With the current model there is no way to correlate log message with TestCase. 
For this NUnit should send TestResult level message embedded in TestResult.

**Comment by OsirisTerje** [comment]
Checking this with the 3.16.1 adapter, and it seems to work as it should now.
```
 <Results>
    <UnitTestResult executionId="f7c18e44-bccb-47ff-99ca-a16824e6a2e5" testId="875d8e89-15b9-8521-2071-6a7df95a661c" testName="TestMethod1()" computerName="DESKTOP-SIATMVB" duration="00:00:00.0080000" startTime="2020-02-01T20:04:29.0000000+01:00" endTime="2020-02-01T20:04:30.0000000+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="f7c18e44-bccb-47ff-99ca-a16824e6a2e5">
      <Output>
        <StdErr>console error</StdErr>
      </Output>
    </UnitTestResult>
    <UnitTestResult executionId="e61aea66-18de-41e1-afc8-f3b71e26639e" testId="4553a21c-2f99-fbb7-807c-a7f3126d1687" testName="TestMethod2()" computerName="DESKTOP-SIATMVB" duration="00:00:00.0000001" startTime="2020-02-01T20:04:30.0000000+01:00" endTime="2020-02-01T20:04:30.0000000+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="e61aea66-18de-41e1-afc8-f3b71e26639e" />
  </Results>
```

**Comment by OsirisTerje** [comment]
Seems this was fixed in 3.11

**Comment by arnonax-tr** [comment]
I'm getting this behavior now using NUnit 3.13.1 and NUnit3TestAdapter version 4.2.1. Could it be a regression?

**Comment by arnonax-tr** [comment]
I checked again with NUnit3TestAdapter 4.3.1 and it look like `Console.Error` is now written correctly and shown in the test level's "Standard Console Error" section. But messages written through `Test.Progress.WriteLine` are written only at the run level and not in the test level. Is this by design?

**Comment by OsirisTerje** [comment]
Not an easy answer to that, I am afraid.  There have been a lot of changes around the output, and some of it is also configurable  (ConsoleOut property in runsettings), and the VS testhost had also had its changes, so what is "by design" and what is "by accident" is a bit hard to say.

It needs however to be properly documented, and also checked for the different runners, and also taking into consideration their configurations.  Work to be done.....
