### ISSUE TITLE
Issue #461 Fix Causes Build Error (Somewhat Indirectly)

### ISSUE THREAD

**Issue by TheAjItator** [nunit/nunit3-vs-adapter#490]
In issue #461, where the .pdb file was added to the nuget package specifically, causes a build breakage on my company's build server.

My SCM engineer tells me that coverage tool runs coverage on the 3rd party .pdb files in the output. 
 This throws off the code metrics when they exist in the output directory.  Therefore they delete all .pdb files after installing packages.  Unfortunately the recent change to the NUnit3TestAdapter.props file now requires that the .pdb be copied.  The build cannot, so an error is raised.
This hasn't been an issue for other builds so I believe this hasn't been an issue with other libraries.

I see that NUnit has the .pdb files in the nuget package in a lib folder instead of a build folder and the NUnit.props file doesn't instruct the build to copy the .pdb file.  (Just to compare with a sister project.)

I've also seen suggestions that a nuget symbols package might be the suggested way to add debugging info.  [Stackoverflow.com item](https://stackoverflow.com/a/29414133).
The MS article on symbols packages is: [Creating symbol packages](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages)

For reference, NUnit v3.10.1 and NUnit3TestAdapter v3.10.0

Any chance that the nuget package could be updated to not have the .pdb directly or require it be copied to the build output?

Thanks!

**Comment by rprouse** [comment]
@jnm2 can you take a look at this?

**Comment by jnm2** [comment]
@TheAjItator Is the build error due to the fact that the source PDB file has been deleted and cannot be copied? Or is the problem that your tool is not deleting the PDB and it is actually showing up in build output and messing up your code coverage tool?

**Comment by TheAjItator** [comment]
@jnm2 The  error is because the files are deleted and cannot be copied.

**Comment by jnm2** [comment]
Great! It seems like we have a simple workaround, if @OsirisTerje thinks https://github.com/nunit/nunit3-vs-adapter/pull/492 is something we want to take.
