### ISSUE TITLE
TestContext.AddTestAttachment does not work on Linux environment with specified dotnet logger

### ISSUE THREAD

**Issue by Kira-Lappo** [nunit/nunit3-vs-adapter#494]
# Summary

Test Attachments are not added to trx file after test run is done on linux environment.

# Repro steps
1. Create Nunit tests project with the only test, which adds some existing file to attachments.
1. Build project and start test execution with command:
    ```dotnet vstest "/path/to/project.dll" /logger:"trx" /ResultsDirectory:./test-results /Diag:./diag/diag.main.log ```
1. Wait until test execution is finished. Take a look at terminal messages, it says that 1 of 1 tests passed.
1. Check created trx file

**Expected result** : the trx file contains section with a test attachment with correct file path;
**Actual result** : the trx file contains stderr section for the executed test:
```
 <StdErr>Failed to attach files from: Attachments&#xD;
Error Details: System.InvalidOperationException:System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_LocalPath()
   at Microsoft.TestPlatform.Extensions.TrxLogger.Utility.Converter.ToResultFiles(AttachmentSet attachmentSet, Guid testResultExecutionId, TestRun testRun, String trxFileDirectory)
   at Microsoft.TestPlatform.Extensions.TrxLogger.Utility.Converter.UpdateTestResultAttachments(TestResult rockSteadyTestResult, TestResult testResult, TestRun testRun, String trxFileDirectory, Boolean addAttachments)</StdErr>
```

# Analysis
I digged into adapter code, checked mstest logic and test execution logs(./diag/diag.main.log).
The reason of the problem is that adapter sends straigh file path to mstest's executor, without **file://** URI schema. 
So, for example, path ```/absolute/path/to/attachment.txt``` is a correct absolute path on linux environment, but mstest consider it as a relative path when it deserializes the data which was recieved from adapter. The path is deserialized without errors, but [calling property **.LocalPath**](https://github.com/Microsoft/vstest/blob/4128f5dc8243221413af2f4dcf68dbcc75cc75dd/src/Microsoft.TestPlatform.Extensions.TrxLogger/Utility/Converter.cs#L510)(line 510) on relative uri causes exception from the repro steps.

I modified adapter code locally and [added "file://" in the beginning of the file path](https://github.com/nunit/nunit3-vs-adapter/blob/87da66782f022bd5de9f80ffc05532a981593d49/src/NUnitTestAdapter/TestConverter.cs#L254)  right before attachment item creation. After that I built adapter dll and made my test project use that modified dll. Attachments were added to trx file without any error.

# Other details
|                                  |                               |
|-----------------------| ------------------------------: |
|NUnit Version           |3.10.1                      |
|NUnit3TestAdapter   |3.10.0                      |
|dotnet sdk                |2.1.301                     |
|vstest.console.exe   | 15.7.0                      |
|OS                             | Ubuntu 18.04 LTS |

Last Updated : 2018/07/04

**Comment by Kira-Lappo** [comment]
I updated the description as I looked into the problem a bit dipper than before.
I got the reason of the problem (more-less), but I'm not sure where it should be fixed.
My opinion is to add **file://** schema right before attachment DTO for vstest.console.

I didn't check mstest code carefully and don't know how exactly mstest converts execution message from json to object.

**Comment by arybkin** [comment]
We have same problem on our side. Do you have any updates for this issue?

**Comment by Kira-Lappo** [comment]
@rprouse how can I contribute to the project? I checked a lot of docs about code rules, guidelines here, but did find any about pull request procedure. I created feature branch with my variant of fix, but I have no rights to push it and, as a consequence, to create a pullrequest.

**Comment by Kira-Lappo** [comment]
Checked on 3.11.0-ci-00893-pr-527 package, the bug is fixed, closing the issue
