### ISSUE TITLE
No tests run when nested classes in partial generic.

### ISSUE THREAD

**Issue by JohanLarsson** [nunit/nunit3-vs-adapter#498]
```cs
using NUnit.Framework;

[TestFixture(typeof(int))]
[TestFixture(typeof(double))]
public partial class Foo<T>
{
    public class Bar
    {
        [Test]
        public void BarTest()
        {
        }
    }
}

public partial class Foo<T>
{
    public class Baz
    {
        [Test]
        public void BazTest()
        {
        }
    }
}
```

The VS runner does not run any test from what I can see.

Visual Studio Enterprise 2017 v15.6.4
NUnit 3 Test Adapter v3.10.0.0
NUnit v3.9.0
net461

**Comment by rprouse** [comment]
Have you attempted to run this using the console? If so, does it work? This will help us determine if the bug is in Visual Studio only, or actually in the framework.

**Comment by rprouse** [comment]
Also, do the tests show up in the Test Explorer window?

**Comment by JohanLarsson** [comment]
I did not run it with console.
Does the code in the issue not reproduce the issue?

**Comment by rprouse** [comment]
The code may reproduce the issue, but I deal with between 20 or 30 issues a day across the various NUnit projects, all in my spare time, so reproducing all issues takes time and we can use all the help we can get 😄

**Comment by JohanLarsson** [comment]
Visual Studio runner:
![animation](https://user-images.githubusercontent.com/1640096/38150551-bfa91aa4-345f-11e8-8a5b-49111b907511.gif)

Console runner:
```
Microsoft Windows [Version 10.0.16299.309]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Johan\Downloads\NUnit.Console-3.8.0>nunit3-console.exe C:\Git\Kasta\WpfApp1\WpfApp1.Tests\bin\Debug\WpfApp1.Tests.dll
NUnit Console Runner 3.8.0
Copyright (c) 2018 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.16299.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\Git\Kasta\WpfApp1\WpfApp1.Tests\bin\Debug\WpfApp1.Tests.dll


Run Settings
    DisposeRunners: True
    WorkDirectory: C:\Users\Johan\Downloads\NUnit.Console-3.8.0
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 4

Test Run Summary
  Overall result: Passed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2018-03-30 19:36:13Z
    End time: 2018-03-30 19:36:15Z
    Duration: 1.523 seconds

Results (nunit3) saved as TestResult.xml
```

I never use the console runner so not sure I did it right.

**Comment by rprouse** [comment]
Your run looks good. Can you share the test project?

**Comment by JohanLarsson** [comment]
https://github.com/JohanLarsson/NUnitRepro

**Comment by OsirisTerje** [comment]
I can reproduce the issue.  I wonder if this might be a variation around 1)  Issue #218 (No tests found to run when TestFixture is a nested class) which was fixed late 2016 for version 3.7, but did not check generics.

I also see that the new source based discovery (SBD) fi/nds the tests, but won't run them as reported.  If I turn off SBD, then the adapter doesn't find the tests either. 

Running it from R# unit tests, they are found and executed, so this must be related to the adapter itself.

**Comment by JohanLarsson** [comment]
R# is shaky, runs them sometimes.

**Comment by OsirisTerje** [comment]
@JohanLarsson Interesting, there might be something further down here.  When I enable discoverydump, I see that the GenericFixture and the two internal classes are found, but not any test methods.
`  <test-suite type='GenericFixture' id='0-1002' name='Foo&lt;T&gt;' fullname='Partial.Foo&lt;T&gt;' runstate='Runnable' testcasecount='0'>
            <test-suite type='TestFixture' id='0-1001' name='Foo&lt;Double&gt;' fullname='Partial.Foo&lt;Double&gt;' classname='Partial.Foo`1' runstate='Runnable' testcasecount='0' />
            <test-suite type='TestFixture' id='0-1000' name='Foo&lt;Int32&gt;' fullname='Partial.Foo&lt;Int32&gt;' classname='Partial.Foo`1' runstate='Runnable' testcasecount='0' />
         </test-suite>`

@rprouse This means we don't get anything up from NUnit/Engine itself.  Further, the non-partial generic class is not coming up at all.

**Comment by OsirisTerje** [comment]
If I add the TestFixture attribute to the inner class, it **is** discovered, but not reported, because the fixture is skipped.
` [TestFixture(typeof(int))]
    [TestFixture(typeof(double))]
    public partial class Foo<T>
    {
        [TestFixture]
        public class Bar
        {
            [Test]
            public void BarTest()
            {
            }
        }
    }`

Gives the following output:
`
 <test-suite type='GenericFixture' id='0-1006' name='Foo&lt;T&gt;+Bar' fullname='Partial.Foo&lt;T&gt;+Bar' runstate='Runnable' testcasecount='0'>
            <test-suite type='TestFixture' id='0-1005' name='Foo&lt;T&gt;+Bar' fullname='Partial.Foo&lt;T&gt;+Bar' classname='Partial.Foo`1+Bar' runstate='NotRunnable' testcasecount='0'>
               <properties>
                  <property name='_SKIPREASON' value='Fixture type contains generic parameters. You must either provide Type arguments or specify constructor arguments that allow NUnit to deduce the Type arguments.' />
                  <property name='_SKIPREASON' value='Fixture type contains generic parameters. You must either provide Type arguments or specify constructor arguments that allow NUnit to deduce the Type arguments.' />
               </properties>
            </test-suite>
         </test-suite>
`

**Comment by jnm2** [comment]
It looks like the framework is not using the `[TestFixture(typeof(x))]` attributes on the containing class to satisfy the generic parameter in the nested class. (Nested types inherit all type parameters from containing types.)

**Comment by rprouse** [comment]
The fact that the run from NUnit console resulted in no tests run leads me to believe that it is an NUnit issue. This issue should be in the nunit repo, moving.

**Comment by rprouse** [comment]
This issue was moved to nunit/nunit#2789
