### ISSUE TITLE
Nuget version install script doesn't work withVS 2015

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#50]
Same as https://github.com/nunit/nunit-vs-adapter/issues/78

**Comment by CharliePoole** [comment]
@OsirisTerje This may be working now that the bug in nuget has been fixed. Can you check?

**Comment by CharliePoole** [comment]
@OsirisTerje Have you done anything on this?

**Comment by CharliePoole** [comment]
I have verified that this is no longer a problem.
