### ISSUE TITLE
Adapter using huge amount of RAM and possibly crashing

### ISSUE THREAD

**Issue by wanted156** [nunit/nunit3-vs-adapter#501]
Hi!

We are using the NUnit 3 visual studio adapter to run tests in our testbench. The testbench has around 80.000 tests, and when the test discovery is happening, the RAM usage spikes up (takes around 4GB+), and sometimes the discovery (or VS) crashes before it loads up the tests. We realise it's a huge amount of tests, is there anything we can do to avoid the crashing and usage spikes?

VS version: 14.0.25431.01 Update 3
Nunit framework: 3.8.1.0 / v4.0.30319 Runtime 
Nunit adapter: 3.9.0
Targeted version is .NET 4.0

**Comment by OsirisTerje** [comment]
@wanted156 If you move up to VS 2017 15.6  source based discovery is on by default, and then the adapter skips its own discovery phase.  This *might* help, but it do run an exploration when running the tests, so it might crash there instead.  You just have to try.

**Comment by OsirisTerje** [comment]
@wanted156  Any results ?

**Comment by wanted156** [comment]
@OsirisTerje We cannot test it at the moment because we are waiting for the VS 2017 licence. I've observed that the issue is not present or is present in a mild form in VS 2015 Update 3 (14.0.25431.01 Update 3), but the biggest problems are having users without the Update 3 installed (users using 14.0.23107.0 D14REL). We will try to upgrade some more entities to Update 3 and see if that helps or not. Will keep you updated!

**Comment by OsirisTerje** [comment]
I can't see what we can do more here, so closing this for now.
