### ISSUE TITLE
When using Run all in Test Explorer it never finishes

### ISSUE THREAD

**Issue by appel1** [nunit/nunit3-vs-adapter#51]
Using the NUnit test runner extension and a .NET 4.5.2 class library project with a single class with a single test method. The Cancel button never switches back to a Run all button. 

> ------ Run test started ------
> NUnit Adapter 3.0.2.0 executing tests is started
> Running all tests in <path>\ClassLibrary1.dll
> Loading tests from <path>\ClassLibrary1.dll
> NUnit Adapter 3.0.2.0 executing tests is finished

When in this state and I press cancel it looks like it finishes correctly and the Tests output shows

> ========== Run test finished: 1 run (0:02:04,7120631) ==========

If I instead use the Run passed test or Run failed tests options everything looks to work as expected. When using those options it is also a lot quicker to load tests. 

> ------ Run test started ------
> NUnit Adapter 3.0.2.0 executing tests is started
> Running selected tests in <path>\ClassLibrary1.dll
> Loading tests from <path>\ClassLibrary1.dll
> NUnit Adapter 3.0.2.0 executing tests is finished
> ========== Run test finished: 1 run (0:00:00,8790505) ==========

Run selected tests also seem to work properly.

**Comment by OsirisTerje** [comment]
Closing, can't see this as an issue any more.
