### ISSUE TITLE
DumpXmlTestResults does not output a file

### ISSUE THREAD

**Issue by wanted156** [nunit/nunit3-vs-adapter#511]
I've set up the needed config following the example and keys on https://github.com/nunit/docs/wiki/Tips-And-Tricks. The config does get applied and recognized by the adapter (tried playing around with the timeout key), it's also selected via Test -> Test Settings -> Select Test Settings File, there is also a check symbol on the left side of the config. Using the config posted below, the TestResults file does not get dumped, even if I set a fixed path instead of relative. 

```
<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>
    <!-- Path relative to solution directory -->
    <ResultsDirectory>.\TestResults</ResultsDirectory>

    <!-- [x86] | x64  
      - You can also change it from menu Test, Test Settings, Default Processor Architecture -->
    <TargetPlatform>x86</TargetPlatform>

    <!-- Framework35 | [Framework40] | Framework45 -->
    <TargetFrameworkVersion>Framework40</TargetFrameworkVersion>

  </RunConfiguration>


  <!-- Adapter Specific sections -->
  <NUnit>
    <DumpXmlTestResults>True</DumpXmlTestResults>
    <DumpXmlTestDiscovery>True</DumpXmlTestDiscovery>
    <PrivateBinPath>extras;more.extras</PrivateBinPath>
    <DefaultTimeout>500000</DefaultTimeout>
    <WorkDirectory>binaries</WorkDirectory>
    <InternalTraceLevel>Info</InternalTraceLevel>
    <UseVsKeepEngineRunning>True</UseVsKeepEngineRunning>
  </NUnit>
</RunSettings>
```

VS version: 14.0.25431.01 Update 3
Nunit framework: 3.8.1.0 / v4.0.30319 Runtime
Nunit adapter: 3.9.0
Targeted version is .NET 4.0

**Comment by OsirisTerje** [comment]
Take a look under the bin folder, there is a Dump folder there :-)
