### ISSUE TITLE
DisableAppDomain does not have the desired behavior

### ISSUE THREAD

**Issue by joaompneves** [nunit/nunit3-vs-adapter#513]
Setup information:
* NUnit 3.10.1 and NUnit3TestAdapter 3.10.0
* Visual Studio 15.7.3
* .NET 4.6.2

Using a settings file with the  DisableAppDomain = true does not have the desired effect. An app domain is created (and tests fail). This was working as expected in previous Visual Studio versions (at least with 15.4 was).

**Comment by rprouse** [comment]
Are you saying that using NUnit3TestAdapter 3.10.0, it was working in VS 15.4, but not in 15.7.3? If so, it is likely Visual Studio, not the adapter, but we will confirm.

If you turn off "Discover tests in real time from source files" in the Visual Studio settings, does it start working again?

![image](https://user-images.githubusercontent.com/493828/41040558-c3b1e30c-696a-11e8-9661-39aa20ffe4d3.png)

**Comment by joaompneves** [comment]
Not sure about adapter 3.10 and VS. Before I had VS 15.4 and adapter 3.07.
Do you think this might be VS problem? Is VS the appdomain creator? Or is there any other component involved?

**Comment by OsirisTerje** [comment]
If you turn off the setting and then don't see any tests, that means the adapter is not running at all.  With source discovery on, it is VS that finds the testcases, with it off - it is the adapter (and engine/framework) that finds the tests.

**Comment by plemasantos** [comment]
I have also bumped into this regression.

Setting DisableAppDomain to true in a .runsettings file is not having the desired effect when executing tests.

VisualStudio 15.9.3
NUnit 3.11.0 / NUnitTestAdapter 3.12.0
.NET 4.6.2

As @joaompneves mentioned, an AppDomain is created and tests fail.

**Comment by joaompneves** [comment]
Any news on this?

**Comment by OsirisTerje** [comment]
@joaompneves  I just tried it, and it works on my machine.  Also checked the adapter code and the DisableAppDomain is correctly converted to an engine property DomainUsage=None.

So it seems you are doing something else, and we then need a repro from you.

**Comment by plemasantos** [comment]
@OsirisTerje which VisualStudio version are you using?

**Comment by OsirisTerje** [comment]
15.9.7,  with adapter 3.13.0

**Comment by OsirisTerje** [comment]
@plemasantos Does it work for you after upgrading?

**Comment by plemasantos** [comment]
Just tested Adapter 3.13.0 against VisualStudio 15.9.8 and I got the same problem.

If I run the tests using NUnit-Console with --domain:None, everything works as expected. If I try to do the same with the .runsettings file in VisualStudio, it seems like the AppDomain is being created.

**Comment by OsirisTerje** [comment]
What is "as expected" ?  What are you seeing as being different?  
Do you have any repro for this?

Looking at my own "repro", I can't see anything going wrong, all tests are coming up as they should.
