### ISSUE TITLE
Dynamic TestCaseSource from reflection are not listed as sub-tests of the test method

### ISSUE THREAD

**Issue by dstj** [nunit/nunit3-vs-adapter#515]
Using VS 2017 Community 15.7.3, .NET Core 2.1.300, NUnit 3.10.1 and NUnitTestAdapter 3.10.0.

Using the following test, no (sub)tests appear in the Test Explorer, I only see `HasAuthorizeAttributes` as "never ran".

```
public static IEnumerable<TestCaseData> AllControllerMethods {
	get {
		var masterType = typeof(MyController);
		var types = masterType.Assembly.GetTypes()
			.Where(x => x.Namespace == masterType.Namespace);

		foreach (var type in types) {
			var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);
			foreach (var method in methods) {
				yield return new TestCaseData(method) { TestName = $"{type.FullName}.{method.Name}" };
			}
		}
	}
}

[TestCaseSource(nameof(AllControllerMethods))]
public void HasAuthorizeAttributes(MethodInfo methodInfo)
{
	var authorizeAttribute = methodInfo.GetCustomAttributes(typeof(AuthorizeAttribute), false);
	var allowAnonymousAttribute = methodInfo.GetCustomAttributes(typeof(AllowAnonymousAttribute), false);

	if (!authorizeAttribute.Any() && !allowAnonymousAttribute.Any())
		Assert.Fail($"Method '{methodInfo.DeclaringType.FullName}.{methodInfo.Name}' does not have either one of the 'Authorize' or 'AllowAnonymous' attributes");
}
```

Adding a "logger" shows me that something is executed and that a method is found, but still, no test run.

```
using (var stream = new StreamWriter(@"C:\temp\test.log")) {
	stream.Write($"{type.FullName}.{method.Name}");
}
```

Any ideas/help to understand what I'm doing wrong is appreciated.

#### Workaround
This workaround works, but it not as clear in the test output:
```
public static IEnumerable<MethodInfo> AllControllerMethods {
	get {
		var masterType = typeof(MyController);
		var types = masterType.Assembly.GetTypes()
			.Where(x => x.Namespace == masterType.Namespace);

		foreach (var type in types) {
			var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);
			foreach (var method in methods) {
				using (var stream = new StreamWriter(@"C:\temp\test.log")) {
					stream.Write($"{type.FullName}.{method.Name}");
				}
				yield return method;
			}
		}
	}
}

[Test]
public void HasAuthorizeAttributes()
{
	var methods = AllControllerMethods.ToList();

	methods.ForEach(method => {
		var authorizeAttribute = method.GetCustomAttributes(typeof(AuthorizeAttribute), false);
		var allowAnonymousAttribute = method.GetCustomAttributes(typeof(AllowAnonymousAttribute), false);

		if (!authorizeAttribute.Any() && !allowAnonymousAttribute.Any())
			Assert.Fail($"Method '{method.DeclaringType.FullName}.{method.Name}' does not have either one of the 'Authorize' or 'AllowAnonymous' attributes");
	});
}
```

**Comment by OsirisTerje** [comment]
The repro above is a bit short of a working repro, so I added what I believe is something like what you're doing, see https://github.com/OsirisTerje/Issue515 

When I run this code, it works as it should  (all is in one assembly just for ease, so ignore that it also detects the test method itself.
![bilde](https://user-images.githubusercontent.com/203432/41179698-e7019b6a-6b6b-11e8-8d19-5079113d1a8b.png)

**Comment by dstj** [comment]
Thanks. I checked out your repo and the .NET 4.6.1 version does indeed work, but the .NET Core 2 does not run.

Here the result:
![image](https://user-images.githubusercontent.com/467692/41180252-a2aa453c-6b3b-11e8-8f6b-c7d971ef88a9.png)

**Comment by dstj** [comment]
Thanks! I checked out your repo and ran it. With just a few tests, I understand what I was not seeing: The dynamic tests are not reported as sub-test under the test name (like they are with simple test cases (see image)). They are reported under the Controller's name (the testee).

![image](https://user-images.githubusercontent.com/467692/41180828-9b8dddf2-6b3d-11e8-91b4-c98c90b6e1ce.png)

Also, when right-clicking --> Run selected tests on the `HasAuthorizeAttributes` test, the sub-test are not ran, only when doing "Run All" did I get them to run.

You're saying that this is a bug from VS itself, not the adapter?

**Comment by withkittens** [comment]
Please look at my referenced issue in nunit/nunit. May be somehow related?

**Comment by Igneous01** [comment]
I am having a similar issue. I am using a dynamic TestCaseSource that is provided by an external class via public static property. If I pass the correct type in the 1st argument to TestCaseSource the test is never recognized. If I change the type in the 1st argument to typeof(string), the test is recognized via test explorer.

`
    [XmlMapper()]
    sealed class SampleClass
    {
        public string FirstName;
        public string LastName;
        public int Age;
        public double Money;
        public List<string> References;
    }

    public class TestDataSource
    {
        public static object[] SampleClassProperties = typeof(SampleClass).GetProperties();
    }

    [TestFixture]
    public class TestClass
    {
        private SampleClass instance;
        private XmlMapper<SampleClass> mapper;
        private string xml = @"
<SampleClass>
<FirstName>John</FirstName>
<LastName>Doe</LastName
<Age>John</Age>
<Money>Doe</Money>
<References>Jane Doe</References>
<References>Edward Smith</References>
<References>Will Smith</References>
</SampleClass>";

        [SetUp]
        public void SetupBeforeEachTest()
        {
            this.instance = new SampleClass()
            {
                FirstName = "John",
                LastName = "Doe",
                Age = 30,
                Money = 87000.413,
                References = new List<string>() { "Jane Doe", "Edward Smith", "Will Smith" }
            };

            this.mapper = new XmlMapper<SampleClass>();
        }

        [Test]
        [TestCaseSource(typeof(TestDataSource), nameof(TestDataSource.SampleClassProperties))]
        public void XmlPropertyExists(string property)
        {
            XmlDocument xmlDocument = mapper.MapToXmlDocument(instance);
            Assert.That(xmlDocument.SelectSingleNode($"//{property}"), Is.Not.Null, $"{property} does not exist in xml");
        }`

![image](https://user-images.githubusercontent.com/5571589/56398447-97608b00-6216-11e9-9267-604c3b7b0819.png)

![image](https://user-images.githubusercontent.com/5571589/56398460-a7786a80-6216-11e9-8480-4cef5472af71.png)

**Comment by mikkelbu** [comment]
@Igneous01 There are some problems with the code. You are extracting all the properties of `SampleClass`, but the `SampleClass` class does not have any properties only fields, hence no test cases are generated. So either extract the fields or change `SampleClass` to have properties instead.
```
sealed class SampleClass
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int Age { get; set; }
    public double Money { get; set; }
    public List<string> References { get; set; }
}
```

Also the test assumes that strings (the name of a property) are input so you must change the code to supply this and not a `PropertyInfo` as it is the case now.
```csharp
public static object[] SampleClassProperties = typeof(SampleClass).GetProperties().Select(p => p.Name).ToArray();
```

Ps. The example with `[TestCaseSource(typeof(string), nameof(TestDataSource.SampleClassProperties))]` will fail unless the `string` class have a static field/property with the name `SampleClassProperties` which is not the case.

**Comment by Igneous01** [comment]
@mikkelbu ahhh yes you are right, it makes sense now why it was not finding any test cases. It was a little bizarre that it found test cases when using typeof(string) which threw me off from this slip up.

That fixed the issues for me - thanks for your help!

**Comment by johnmwright** [comment]
This issue appears to have the same underlying cause as #622 and is resolved by PR https://github.com/nunit/nunit3-vs-adapter/pull/668

**Comment by OsirisTerje** [comment]
The test repo contains two projects, with different project formats, and they crash now, so running only the NetCore2 alone show that when upgraded with NUNit 3.12 and Adapter 3.16.0-dev it now works
![image](https://user-images.githubusercontent.com/203432/68073327-28e8b200-fd8f-11e9-9427-7acff8cda76f.png)
