### ISSUE TITLE
ArgumentException when whitespace sent to logger

### ISSUE THREAD

**Issue by slide** [nunit/nunit3-vs-adapter#516]
This is related to https://github.com/nunit/nunit3-vs-adapter/issues/220. The previous fix was to send a single space when there was no text in the message, but TestSessionMessageLogger checks for IsNullOrWhitespace and throws an ArgumentException if the message is null or only whitespace, (https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.Common/Logging/TestSessionMessageLogger.cs#L65) which means sending the single space causes an argument exception.

These are the versions we are referencing:

```xml
<PackageReference Include="NUnit.ConsoleRunner" Version="3.7.0" />
<PackageReference Include="NUnitLite" Version="3.9.0" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
<PackageReference Include="NUnit3TestAdapter" Version="3.9.0" />
<PackageReference Include="Mono.Cecil" Version="0.10.0-beta6" />
```

We use nunit to run unit tests for IronPython. Cloning https://github.com/IronLanguages/ironpython2 and running `make.ps1` then `make.ps1 test-test_macurl2path` will show the issue. I worked around this in a local build of the adapter by implementing my own IsNullOrWhiteSpace (since the adapter is being built with a framework prior to IsNullOrWhiteSpace) and didn't send the message if it is null or only whitespace. 

This is the output we see from tests:

```
.\make.ps1 test-test_macurl2path
WARNING: No tests available for 'test_macurl2path' trying to run single test 'net45.test_macurl2path'
dotnet test C:\Users\USER\Code\_ipy\ironpython2/Src/IronPythonTest/IronPythonTest.csproj -f net45 -o C:\Users\USER\Code\_ipy\ironpython2/bin/Release/net45 -c Release --no-build -l trx;LogFileName=single-net45-Release-result.trx -s C:\Users\USER\Code\_ipy\ironpython2\Src\IronPythonTest\runsettings.xml --filter="Name=net45.test_macurl2path"
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 160.02 ms for C:\Users\USER\Code\_ipy\ironpython2\Src\DLR\Src\Microsoft.Scripting\Microsoft.Scripting.csproj.
  Restore completed in 156.32 ms for C:\Users\USER\Code\_ipy\ironpython2\Src\DLR\Src\Microsoft.Scripting.Metadata\Microsoft.Scripting.Metadata.csproj.
  Restore completed in 175.2 ms for C:\Users\USER\Code\_ipy\ironpython2\Src\DLR\Src\Microsoft.Dynamic\Microsoft.Dynamic.csproj.
  Restore completed in 160.26 ms for C:\Users\USER\Code\_ipy\ironpython2\Src\DLR\Tests\ClrAssembly\ClrAssembly.csproj.
  Restore completed in 48.03 ms for C:\Users\USER\Code\_ipy\ironpython2\Src\IronPython\IronPython.csproj.
  Restore completed in 118 ms for C:\Users\USER\Code\_ipy\ironpython2\Src\IronPythonTest\IronPythonTest.csproj.
Test run for C:\Users\USER\Code\_ipy\ironpython2\bin\Release\net45\IronPythonTest.dll(.NETFramework,Version=v4.5)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
test_macurl2path
.
.
Error processing test-output event for
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Common.Logging.TestSessionMessageLogger.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
----------------------------------------------------------------------
Error processing test-output event for
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Common.Logging.TestSessionMessageLogger.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
Ran 2 tests in 0.159s
Error processing test-output event for
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Common.Logging.TestSessionMessageLogger.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
Error processing test-output event for
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Common.Logging.TestSessionMessageLogger.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
OK
Error processing test-output event for
System.ArgumentException: The parameter cannot be null or empty.
Parameter name: message
   at Microsoft.VisualStudio.TestPlatform.Common.Logging.TestSessionMessageLogger.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report)
WARNING: Overwriting results file: C:\Users\USER\Code\_ipy\ironpython2\Src\IronPythonTest\TestResults\single-net45-Release-result.trx
Results File: C:\Users\USER\Code\_ipy\ironpython2\Src\IronPythonTest\TestResults\single-net45-Release-result.trx

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 22.1010 Seconds
```

We see this on both net45 and netcoreapp2.0

/cc @slozier

**Comment by OsirisTerje** [comment]
@CharliePoole When you did the change on #220 , was there any particular reason  not to just skip sending anything if it IsNullOrWhiteSpace ?

**Comment by slide** [comment]
Sorry, for some reason I didn't get an email when the question was asked about a PR. My apologies!

**Comment by OsirisTerje** [comment]
No problem :-)

And thanks for raising the issue :-)

**Comment by CharliePoole** [comment]
@OsirisTerje Neither did I (get an email). Strange.

Anyway, I didn't ignore whitespace lines because the assumption is that the user wanted to send them.

**Comment by OsirisTerje** [comment]
@CharliePoole @slide Strange with the emails.  I do get the notifications all the time, is there some new approvals needed due to the GDPR checks stopping them (just guessing) ?

**Comment by CharliePoole** [comment]
I normally do too, but this is the first I've seen from this project for a while.

**Comment by OsirisTerje** [comment]
Hmm....  That may explain why I get very little response lately.

**Comment by CharliePoole** [comment]
Very odd. Neither @slide nor I are team members, but you @mentioned us so we should get it.

**Comment by OsirisTerje** [comment]
@CharliePoole But do you get emails from the mentions today?

**Comment by CharliePoole** [comment]
That seems like a feasible explanation

**Comment by slide** [comment]
@CharliePoole I agree, I think I need to raise an issue with the VSTest project because sending whitespace only should be allowed, it is useful. Thanks for fixing this up!

**Comment by kswoll** [comment]
I noticed I had `Console.WriteLine();` in my code, which was causing this error.  I'm on 3.13.1 for NUnit and 3.17.0 for NUnit3TestAdapter.  Removing that line allowed my tests to pass.  However, reading over this thread, was this not supposed to be fixed?

**Comment by mikkelbu** [comment]
@kswoll Can you include a minimal test showing the problem, as I cannot make it fail. E.g. the following works on my machine
```csharp
        [Test]
        public void TestConsoleWriteLine()
        {
            Console.WriteLine();
            Console.WriteLine("a");
            Console.WriteLine((string)null);
            Console.WriteLine("b");
            Console.WriteLine(" ");
        }
```

**Comment by kswoll** [comment]
Thanks @mikkelbu, it seems to be related to threading.  Here's a minimal example:

```
[Test]
public async Task ThreadingTest()
{
    await Task.Run(() => Console.WriteLine());
    Assert.Pass();
}
```

Produces the following exception in the Output Window when Tests is selected:

```
System.ArgumentException: The parameter cannot be null or empty. (Parameter 'message')
   at Microsoft.VisualStudio.TestPlatform.Common.Logging.TestSessionMessageLogger.SendMessage(TestMessageLevel testMessageLevel, String message)
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(INUnitTestEventTestCase resultNode) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 162
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 92
```

Moving the `Console.WriteLine();` outside of the thread doesn't present the problem.  Let me know if I should open a new ticket. 👍

**Comment by OsirisTerje** [comment]
Thanks @kswoll !  Can you try this with the 4.0 beta ?

**Comment by moh-hassan** [comment]
I confirm that @mthjones  point the root problem that I also face.
The solution is to write any value in the test case :
```
Console.WriteLine(0);
```
The next code is working with '\t'
```
 public class Tests {

        [TestCase( null )]
        [TestCase( "" )]
        [TestCase( " " )]
        [TestCase( "\t" )]
        [TestCase( "\r" )]
        [TestCase( "\n" )]
        [TestCase( "\r\n" )]
        public void Test1( string output ) {
           Console.Write( 0 );   //this line help to pass test
            Console.Write( output );
            Assert.Pass();
        }
```
pass Both the "\t" and " " test cases that produce the error:

**Comment by OsirisTerje** [comment]
@mthjones @moh-hassan  Please try the attached alpha version,  4.1.0-alpha02
[NUnit3TestAdapter.4.1.0-alpha02.zip](https://github.com/nunit/nunit3-vs-adapter/files/7480930/NUnit3TestAdapter.4.1.0-alpha02.zip)

**Comment by moh-hassan** [comment]
@OsirisTerje 
I tests the project using your fix `NUnit3TestAdapter.4.1.0-alpha02.nupkg` and it resolved the issue.
So, I can say It's fine. :+1:

**Comment by OsirisTerje** [comment]
@moh-hassan  Thanks!   

It'll go into the 4.1 release, which I believe will go out within a week.
