### ISSUE TITLE
N unit Adapter issue with .NET frame work

### ISSUE THREAD

**Issue by kumarbrandmuscle** [nunit/nunit3-vs-adapter#517]
Hi Team,
Just,I am following n unit blog to develop the N unit framework.Below is the link I am following to create the same.  [](https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard#why-cant-my-tests-target-net-standard).
Please find the below snapshots to give more info on the same.
![image](https://user-images.githubusercontent.com/40033740/41451769-405e5386-708c-11e8-9245-22ee9a6a4368.png)
when I am using .net standard library to create a project and after that adding n unit test adapter, It was throwing me the unrecognized error.
Then I created the framework with class library(.NET Framework) and below is the snapshot and nunit adapter does not throw any error.

![image](https://user-images.githubusercontent.com/40033740/41451878-c87c31b6-708c-11e8-8f2a-2d174ff70181.png)

Please,suggest me as I am following the correct process inorder to create N unit framework.
In case,If you have any video/snapshot to create a n UNIT FRAMEWORK.Please share with me.

**Comment by OsirisTerje** [comment]
Seems you're trying to create a .net standard project for your unit test, correct?   That doesn't work, a test project must either be .net core or .net framework.

**Comment by jnm2** [comment]
See also https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard.
