### ISSUE TITLE
Having ApartmentAttribute on both classes and methods causes test runner to hang

### ISSUE THREAD

**Issue by appel1** [nunit/nunit3-vs-adapter#52]
A .NET 4.5 test project with just these two classes trigger the issue if you use "Run All". 

```csharp
    [TestFixture]
    [Apartment(ApartmentState.STA)]
    public class ApartmentFixture
    {
        [Test]
        public void ApartmentOnClass()
        { }
    }

    [TestFixture]
    public class ApartmentFixture3
    {
        [Test]
        [Apartment(ApartmentState.STA)]
        public void ApartmentOnMethod()
        { }
    }
```

From what I can tell it hangs on ```thread.Join(timeout)``` in WorkItem.RunTestOnOwnThread(int, apartment). 

It does not hang if you use any of the other methods to run tests like Run Selected Tests or Run Passed Tests. 

Using Visual Studio 2015 and NUnit3 Test Adapter 3.0.4.0.

**Comment by CharliePoole** [comment]
I'd be interested to know what happens if you run this under nunit-console.
It will help us figure out whether we have to fix NUnit or the adapter. You
may find different results running with --workers:0 versus without.

**Comment by appel1** [comment]
I can't reproduce it with nunit-console.
