### ISSUE TITLE
System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by OmicronPersei** [nunit/nunit3-vs-adapter#528]
A good number of NUnit tests are failing using the NUnit Test Adapter (3.10.0.0), NUnit (3.11), VS 2017 community edition (15.7.4).

Many tests fail with this message:
> Message: OneTimeSetUp: System.UnauthorizedAccessException : Access to the path 'C:\WINDOWS\system32\TestAttachmentsTests.tmp' is denied.

**Comment by jnm2** [comment]
I'm hitting this as well, but only through Test Explorer. ReSharper and the console runner are fine.

**Comment by OsirisTerje** [comment]
Not hitting this.  @jnm2 / @OmicronPersei  Can you upload a small repro ?

**Comment by OmicronPersei** [comment]
A screenshot?

**Comment by OsirisTerje** [comment]
A small repro sln that show the same behavior.

**Comment by OmicronPersei** [comment]
I'm not sure I can, the errors that are occurring are from the current head of the NUnit solution itself.

**Comment by OmicronPersei** [comment]
Well a lot of the tests that are failing were the NUnit solution tests themselves.  Let me see if I can reproduce similar behavior in a smaller solution.

**Comment by OsirisTerje** [comment]
@OmicronPersei What exactly do you mean by "NUnit solution tests themselves"?

**Comment by OmicronPersei** [comment]
The NUnit framework code base's tests.

**Comment by jnm2** [comment]
Huh, I know I've seen this but it's not happening to me anymore with a fresh clone of the NUnit repo and 15.7.5. I wonder if there was an upstream bug with VSTest.

**Comment by OsirisTerje** [comment]
Closing this for now

**Comment by OsirisTerje** [comment]
Closing this for now
