### ISSUE TITLE
Coverage VSTS messed up with nunit.framework.dll

### ISSUE THREAD

**Issue by SahinOzdemir** [nunit/nunit3-vs-adapter#531]
Hi we're using NUnit 3.10.1 with the NUnit3TestAdapter 3.10.0 and in SonarQube I get correct coverage data, but when I download the coverage report from VSTS (based on the low score on the build output), I see the following:
![image](https://user-images.githubusercontent.com/7938059/42768518-0896e9de-8920-11e8-91c5-637d7576f44e.png)

It seems that external assemblies like nunit.framework.dll aree impacting our coverage results. Is there any way to opt them out. When running coverage locally I don't see these external assemblies.

Any help is welcome!

**Comment by jnm2** [comment]
Here's the docs on how to exclude them: https://msdn.microsoft.com/library/jj159530.aspx#Anchor_0

@OsirisTerje, it's expected that folks would manually exclude our assemblies, right?

**Comment by OsirisTerje** [comment]
Currently they need to exclude them the way you show yes, but this is a bug in the code coverage analysis from MS, they should not include anything which is not in the solution, and they do - if there is a corresponding pdb file.  We have not got any ETA for the fix, but it is on their backlog.

**Comment by SahinOzdemir** [comment]
Thanks for your quick responses. I'll try to include a runsettings file!

**Comment by SahinOzdemir** [comment]
Adding the runsettings and opting out nunit.framework did the trick.
Thanks again!
