### ISSUE TITLE
NUnit Framework freezes when we abort main thread

### ISSUE THREAD

**Issue by MichailQA** [nunit/nunit3-vs-adapter#532]
Hi, 
I observed the following strange behavior:
NUnit Framework freezes when we abort main thread in OneTimeSetUp method.

When we abort main thread in test or in SetUp method - behavior is expected (test fails with message "Test cancelled by user"), but when it happens in OneTimeSetUp method - NUnit Framework freezes.

* NUnit (3.7.1) and NUnit3TestAdapter (3.10.0) versions 
* Visual Studio edition and full version number (see Help About) => 2017, Version 15.6.6
* A short repro, preferably attached or pointing to a git repo or gist

```cs
 [TestFixture]
    class Test1
    {
        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            Thread mainThread = Thread.CurrentThread;
            Task paralelThread = Task.Factory.StartNew(() =>
            {
                mainThread.Abort();
            });

            Thread.Sleep(2000);
        }

        [Test]
        public void Test_1() { }

        [Test]
        public void Test_2() { }

        [Test]
        public void Test_3() { }
    }
```

**Comment by MichailQA** [comment]
Also if we catch this type of exception (ThreadAbortException) in OneTimeSetUp its doesn't help, and NUnit freezes

**Comment by OsirisTerje** [comment]
This also crashes in 3.10.1.

**Comment by OsirisTerje** [comment]
Issue moved to [nunit/nunit #2947](https://github.com/nunit/nunit/issues/2947) via [**ZenHub**](https://www.zenhub.com/)
