### ISSUE TITLE
Missing null check before runner dispose

### ISSUE THREAD

**Issue by MaceWindu** [nunit/nunit3-vs-adapter#540]
Adapter Version: "3.10.0.21"
nunit.engine: 3.7.0.0

https://github.com/nunit/nunit3-vs-adapter/blob/master/src/NUnitTestAdapter/NUnit3TestExecutor.cs#L314

Just hit NRE on this line trying to debug my tests. Looks like it failed with exception somewhere in GetRunnerFor as it cannot return null.

**Comment by MaceWindu** [comment]
Aha, it is really exception, output log:
```
Exception thrown: 'System.IO.FileNotFoundException' in nunit.engine.dll
Exception thrown: 'System.NullReferenceException' in NUnit3.TestAdapter.dll
Object reference not set to an instance of an object.

```

**Comment by MaceWindu** [comment]
Original exception is:
```
FileNotFoundException: 'Could not load file or assembly 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' 
```
which I suspect not actual for recent adapter version, but missing null check is still here

**Comment by rprouse** [comment]
1. Are you using the NuGet version of the adapter?
2. Are yours tests .NET Core or desktop?

**Comment by MaceWindu** [comment]
1. yep, nuget
2. tests I was running targeted net45 in multi-target project

Also:
- it was failing only when I debug test, not when I just run them
- taking into account that I didn't seen this issue before, it could be somehow caused by me running and debugging tests in two different projects in parallel. Second project use adapter as VSIX extension

**Comment by MaceWindu** [comment]
Different solutions. Will see if I can do something about repro, but my original issue was just about missing null check in code :-)

**Comment by OsirisTerje** [comment]
@MaceWindu Can you copy in the line where you saw this?  The linenumber points just to an #ifdef (probably some changes done afterwards)
