### ISSUE TITLE
TestCategory Attribute is ignored when running test via dotnet cli when placed on class

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit3-vs-adapter#542]
@dos-ise commented on [Fri Aug 31 2018](https://github.com/nunit/nunit/issues/2998)

I am having an issue when running my dotnet core test on an linux machine. 
The category only works when the testCategoryAttribute is placed on an individual test.
When the testCategoryAttribute  is placed on the testclass the tests are executed although they should be execluted via the filter.

Is this a known problem or am I doing something wrong?

---

@ChrisMaddock commented on [Sat Sep 01 2018](https://github.com/nunit/nunit/issues/2998#issuecomment-417850736)

Can you share details of exactly which filter your passing to dotnet test? I'm also going to move this over to the test adapter repository, as the guys there will be more able to help.

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?
Make it as small as you can, it should compile "as is".
Let include a cmd file for the use of the dotnet cli, so we see the parameters you use.

**Comment by dos-ise** [comment]
Done :)
https://github.com/dos-ise/nunit-TestCategoryDemo

It seems like the category works when using the WSL ubuntu. We ran our test on an arm plattform.
Maybe this only appears on arm devices. I will check this now..

**Comment by OsirisTerje** [comment]
@dos-ise  I'll close this for now.  I assume it works.  If not, please reopen.
