### ISSUE TITLE
Setting [TestCaseSource] to [Explicit] makes other tests in fixture explicit.

### ISSUE THREAD

**Issue by JohanLarsson** [nunit/nunit3-vs-adapter#545]
```cs
public class FooTests
{
    private static readonly TestCaseData[] Values =
    {
        new TestCaseData(1),
        new TestCaseData(2),
    };

    [Explicit("Don't run this")]
    [TestCaseSource(nameof(Values))]
    public void Test1(object value)
    {
    }

    [Test]
    public void Test2()
    {
        Assert.Pass();
    }
}
```

```xml
<TargetFramework>net461</TargetFramework>
```

Using the R# runner:
![image](https://user-images.githubusercontent.com/1640096/45301903-2fc0bf80-b512-11e8-8440-84250b60243f.png)

- NUnit 3.10.1
- NUnit 3 Test Adapter 3.10.0.0
- VS 15.8.3
- Resharper 2018.2.1

**Comment by jnm2** [comment]
@JohanLarsson Thanks for filing!

@OsirisTerje This could end up being a ReSharper or NUnit framework bug, but my gut said we should start here.

**Comment by OsirisTerje** [comment]
Trying the code above, and it seems to work in VS.
![image](https://user-images.githubusercontent.com/203432/45318029-0583f780-b53c-11e8-8acf-49bbe5ebaabc.png)

So seems the adapter is doing this correct

**Comment by jnm2** [comment]
That points to this being a ReSharper bug then since it differs from Test Explorer. @JohanLarsson Do you want to file for ReSharper?

/cc @estrizhok

**Comment by JohanLarsson** [comment]
https://youtrack.jetbrains.com/issue/RSRP-471450

**Comment by OsirisTerje** [comment]
Resolved with https://github.com/nunit/nunit3-vs-adapter/pull/763

**Comment by OsirisTerje** [comment]
@JohanLarsson Alpha.1 released now: https://www.nuget.org/packages/NUnit3TestAdapter/4.0.0-alpha.1
