### ISSUE TITLE
Cannot find any tests for standard class library

### ISSUE THREAD

**Issue by Baxtex** [nunit/nunit3-vs-adapter#546]
* NUnit and NUnit3TestAdapter versions
NUnit Version=3.10.1
NUnit3TestAdapter Version=3.10.0
Microsoft.NET.Test.Sdk Version=15.8.0

* Visual Studio edition
Visual Studio 17 Community 15.8.4

* A short repro, preferably attached or pointing to a git repo or gist
* What .net platform and version is being targeted

My solution contains two projects:
_Class Library (.Net Standard 2) //My code
Class Library(.Net Core 2) //My tests_

When trying to run a super simple test the output says the following:
`No test is available in C:\Users\user\Documents\vs_projects\XXX.CustomStringParsing\XXX.CustomStringParsing\XXX.CustomStringParsing.csproj C:\Users\user\Documents\vs_projects\XXX.CustomStringParsing\XXX.Test\XXX.Test.csproj. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
`
I have googled a lot and seen a lot of references to targeting the correct framework but I believe I am already doing this. My test class lib is targeting .net core 2 and I got the newest versions of the NUnit. The tests do show up in the test explorer view inside vs but when I run them, the output is that it cannot find any tests.

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?
Make it as small as you can, it should compile "as is".
The reason it shows up in Test Explorer is that 15.8 is using source based discovery, so it is Test Explorer itself that finds the tests.  

It seems you're missing something.  You can look through http://hermit.no/how-to-resolve-cases-of-visual-studio-no-tests-appearing/ , the flowchart there should take you through all the normal cases.
