### ISSUE TITLE
Exception System.Reflection.TargetInvocationException after NUnit 3.0.0-beta-5 upgrade

### ISSUE THREAD

**Issue by GibbOne** [nunit/nunit3-vs-adapter#56]
After NUnit 3.0.0-beta-5 installation, the adapter can't run the tests (neither single neither all).

From output window I receive this message

```
NUnit Adapter 3.0.2.0 executing tests is started
Running selected tests in myProjectFolderAndAssy.Tests.dll
Loading tests from myProjectFolderAndAssy\Bin\Release\Loccioni.Aulos.Tests.dll
Exception System.Reflection.TargetInvocationException, Exception thrown executing tests in myProjectFolderAndAssy\Loccioni.Aulos.Tests.dll
NUnit Adapter 3.0.2.0 executing tests is finished
```

Any suggestions?

**Comment by CharliePoole** [comment]
We have not yet released a version of the NUnit 3 Adapter to work with Beta 5. You may have better luck, however, if you use the adapter CTP 4 rather than 2. At the very least, I would hope for a more complete exception message!

**Comment by GibbOne** [comment]
Thanks! 
I'll we wait for the new release of the adapter.

Just for the sake of correctness, I'm using CTP 4, but the output window message shows always "3.0.2.0" instead of "3.0.4.0".

Also in discovering:

```NUnit Adapter 3.0.2.0 discovering tests is started```

**Comment by CharliePoole** [comment]
Hmmm... the message must be hard-coded. That should be fixed as well.

**Comment by OsirisTerje** [comment]
The Version number comes from the assemblyinfo.cs, which wasn't updated for the 3.0.4 Version.

**Comment by alexschwantes** [comment]
Am also having the same issue, is there any way around this issue other than waiting for an updated TestAdapter? 
As a workaround, at least I can use the nunit3 console RC1 to run the tests on the build server as it has some great fixes included in it. :)

**Comment by CharliePoole** [comment]
No, I'm afraid I don't know of any way around the problem. It's possible that one could be found, but what's actually needed is to replace the engine component used by the adapter and update the API calls. This is probably less than a day's work, and I'll try to get to it on the weekend, once we get out RC2 of NUnit.

**Comment by alexschwantes** [comment]
Ok thanks for the reply. Will look forward to it :)

**Comment by CharliePoole** [comment]
@GibbOne Did the RC2 resolve your issue?

**Comment by GibbOne** [comment]
I get this:
```
------ Run test started ------
NUnit Adapter 3.0.5.0 executing tests is started
Running selected tests in myProjectFolderAndAssy.Tests.dll
Loading tests from myProjectFolderAndAssy.Tests.dll
Exception System.Reflection.TargetInvocationException, Exception thrown executing tests in myProjectFolderAndAssy.Tests.dll
NUnit Adapter 3.0.5.0 executing tests is finished
========== Run test finished: 0 run (0:00:01,001) ==========
```

Now the version is right, but the exception seems to be the same.

**Comment by appel1** [comment]
I believe this was fixed in 3.0.6.0. If not the error message should be better.

**Comment by GibbOne** [comment]
I dont know why but after restarting VS2015 it works!

**Comment by GibbOne** [comment]
I understood why. @appel1 you are right.
With automatic update I got the new version.

```
------ Run test started ------
NUnit Adapter 3.0.6.0 executing tests is started
```

Thanks!

**Comment by rprouse** [comment]
Even with automatic updates, Visual Studio needs to restart to apply the update.
