### ISSUE TITLE
NUnit3TestAdapter 3.11.1 TestCategory from VSTest no longer working (No tests selected)

### ISSUE THREAD

**Issue by cwood-panopto** [nunit/nunit3-vs-adapter#568]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions

NUnit 3.9.0
NUnit3TestAdapter 3.11.1

* Visual Studio edition and full version number (see Help About)

N/A

* A short repro, preferably attached or pointing to a git repo or gist

TestCategory=blah is no longer working after the release 2 hours ago. prior versions of test adapter worked. We pinned back to 3.10 and now it is working again.

> 2018-11-21T23:29:36.1959470Z Executing the powershell script: c:\buildagent\tasks\VSTest\1.0.32\VSTest.ps1
> 2018-11-21T23:29:40.0552479Z ##[debug]Calling Invoke-VSTest for all test assemblies
> 2018-11-21T23:29:40.1802455Z Working folder: F:\2
> 2018-11-21T23:29:40.1802455Z Executing C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe "F:\2\b\SeleniumWebTests.dll"  /TestCaseFilter:"(TestCategory=ProdSmoke)" /Settings:"F:\2\TestResults\Localx64_2018-11-21_11-29-40-PM.runsettings" /logger:trx /TestAdapterPath:"F:\2\s"
> 2018-11-21T23:29:40.8364829Z Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
> 2018-11-21T23:29:40.8364829Z Copyright (c) Microsoft Corporation.  All rights reserved.
> 2018-11-21T23:29:41.3677227Z Starting test execution, please wait...
> 2018-11-21T23:29:41.4927203Z Warning: Using Isolation mode to run tests as required by effective Platform:X64 and .Net Framework:Framework45 settings for test run. Use the /inIsolation parameter to suppress this warning.
> 2018-11-21T23:29:43.3208102Z Information: NUnit Adapter 3.11.1.0: Test execution started
> 2018-11-21T23:29:43.3520596Z Information: Running all tests in F:\2\b\SeleniumWebTests.dll
> 2018-11-21T23:29:44.6176603Z Information:    NUnit3TestExecutor converted 226 of 226 NUnit test cases
> 2018-11-21T23:29:44.6332850Z Information:    Skipping assembly - no matching test cases found
> 2018-11-21T23:29:44.6645344Z Information: NUnit Adapter 3.11.1.0: Test execution complete
> 2018-11-21T23:29:44.6957838Z Warning: No test is available in F:\2\b\SeleniumWebTests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
> 2018-11-21T23:29:44.8676555Z Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true
> 2018-11-21T23:29:44.9770284Z ##[warning]No results found to publish.

Simplest repro is likely:
`vstest.console.exe SomeTest.dll /TestCaseFilter:"(TestCategory=SomeNUnitCategory)" /logger:trx /TestAdapterPath:"PathToNUnitAdapter3.11.1"`
Note no tests selected for some build dll that actually has tests

* What .net platform and version is being targeted

Framework 4.5.2

* If TFS/VSTS issue, what version, hosted, on-premises, and what build task you see this in

on-prem TFS 2015
Task is Visual Studio Test

**Comment by OsirisTerje** [comment]
Thanks for reporting!    QuickFixes for Hotfixes is not good.    The attempt was to ensure #506 remained fixed, but the PR #507 obviously doesn't work.
The default now is to use the MsTest format, which obviously doesnt work for some reason.  I need to investigate further.   I'll release a 3.11.2 which sets the default format to the older NUNit format.  

The workaround now is as you say either to go back to 3.10, or even 3.11.0,  or you can add the following section to a runsettings file, and enable that in the tests-

`<NUnit>
    <VsTestCategoryType>NUnit</VsTestCategoryType>
  </NUnit>`

**Comment by OsirisTerje** [comment]
@cwood-panopto Please try version 3.11.2,  it has reverted default back to NUnit format.  It works on the projects I have tested here.  Awesome if you could test it too.

**Comment by cwood-panopto** [comment]
3.11.2 appears to have fixed the issue on our end.
