### ISSUE TITLE
NUnit3TestDiscoverer Could not load file or assembly 'nunit.engine

### ISSUE THREAD

**Issue by Sedemicra** [nunit/nunit3-vs-adapter#573]
### Problematic combination:
- NUnit 3.11.0
- NUnit3TestAdapter 3.11.0 / 3.11.1 / 3.11.2
- Visual Studio Enterprise 2017 Version 15.9.2 (issue reproduces also on v 15.8.5)
- Targeting .NET Framework 4.6.1

### Working combination:
Test discovery and execution works normally.
- NUnit 3.11.0
- NUnit.Engine 3.8.0
- NUnit3TestAdapter 3.10.0

### Issue
After updating either NUnit.Engine to 3.9.0 or NUnit3TestAdapter to any of the 3.11.* versions, attempting to run tests from VS results in the following:

>[23-Nov-18 14:29:25 Informational] ------ Discover test started ------
[23-Nov-18 14:29:25 Error] An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Could not load file or assembly 'nunit.engine, Version=3.7.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.
[23-Nov-18 14:29:25 Warning] No test is available in C:\Users\Raagmaa\source\repos\TestLib\TestLib\TestLib\bin\TPMaster\TestLib.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[23-Nov-18 14:29:25 Informational] ========== Discover test finished: 0 found (0:00:00.6817703) ==========
[23-Nov-18 14:29:31 Informational] ------ Run test started ------
[23-Nov-18 14:29:32 Error] An exception occurred while invoking executor 'executor://nunit3testexecutor/': Could not load file or assembly 'nunit.engine, Version=3.7.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.
[23-Nov-18 14:29:32 Informational] ========== Run test finished: 0 run (0:00:00.4088265) ==========

No idea why it would start looking for nunit.engine, Version=3.7.0.0. Haven't used that version for a while now and can't find any reference to it form our solution either.
The issue seems to appear with specific combinations of NUnit NuGets and Visual Studio version (see Problematic combination section) which makes it hard to pinpoint but since it doesn't stop running through console runner I would assume the issue is adapter related.
**Note:** Issue doesn't reproduce with Visual Studio version 15.7.6

**Comment by OsirisTerje** [comment]
Are you installing the engine separately?  The correct engine version comes with the adapter, so updating that may cause the system to not work.  Can you check again with ONLY installing NUnit and NUnit3TestAdapter ?

If you still have the error:
Can you please upload a repro project?
Make it as small as you can, it should compile "as is".

**Comment by jnm2** [comment]
I'm going to try the https://github.com/nunit/nunit3-vs-adapter/pull/541 fix which worked to isolate the user project's version of Mono.Cecil from the version the adapter uses.

**Comment by jnm2** [comment]
Currently it's looking like there's no way to hook AssemblyResolve before VSTest encounters System.IO.FileNotFoundException while trying to load the adapter DLL:

> 'Could not load file or assembly 'nunit.engine.api, Version=3.0.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The system cannot find the file specified.'

https://github.com/Fody/Costura does IL rewriting at build time to use a module initializer (the best C# can do is a type initializer). I'm pretty sure by now that these are our options:

- Stop directly referencing any NUnit engine DLLs from the adapter; use reflection for everything

- Or, ship a separate entry point assembly which does not reference any NUnit engine DLLs which hooks AssemblyResolve and then loads our main adapter logic assembly which does reference NUnit engine DLLs.

- Or, use something like https://github.com/Fody/Costura to rewrite the IL after building the adapter assembly to insert a module initializer, in hopes that a module initializer can hook AssemblyResolve before the TypeLoadException happens.

**Comment by jnm2** [comment]
Out of time for the day.

**Comment by jnm2** [comment]
Another thing that *might* work is making sure that the only public type in the adapter assembly is an entry point which has no type reference which would cause the runtime to try to load NUnit engine DLLs.

**Comment by OsirisTerje** [comment]
Thanks so far, @jnm2 !    
The two first options sounds most promising.

**Comment by Sedemicra** [comment]
Tried it out:
Installed the NUnit3TestAdapter version 3.12.0-dev-00991 
And also the latest NUnit.Engine
Worked like a charm.

**Comment by OsirisTerje** [comment]
Thanks @Sedemicra !  
That was fast! 
We'll try to get this version out as soon as possible :-)

**Comment by OsirisTerje** [comment]
@jnm2 I'll close this as this is solved.  Should we raise another issue for your work above ?

**Comment by Sedemicra** [comment]
@OsirisTerje Is there any rough ETA on the  NUnit3TestAdapter 3.12? The dev package solved my problem locally, but I can't use it in my CI flow which needs a NuGet coming through the proper channels.

**Comment by OsirisTerje** [comment]
It will be out this week.

**Comment by OsirisTerje** [comment]
@Sedemicra  The release pre-release is out now.   I would like some feedback on #215 , but will in any case release it tomorrow.  The pre-release is at https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.12.0-dev-01009 .  No (known) changes wrt to this issue though.

**Comment by Sedemicra** [comment]
Thank you!

**Comment by jnm2** [comment]
@OsirisTerje 

> @jnm2 I'll close this as this is solved. Should we raise another issue for your work above ?

Definitely, since the problem still exists for user test projects that depend on an engine version that doesn't exactly match the adapter's. https://github.com/nunit/nunit3-vs-adapter/issues/583

**Comment by Userjland00** [comment]
Not sure if it's relevant here but I came across this when I was having issues with NUnit.Engine and wanted to leave a comment that what I was trying to do, I was able to do with NUnit.Engine.Api instead, so that is how I solved my issue - basically switching NuGet packages from Engine to Engine.Api etc.
