### ISSUE TITLE
Should the VSIX ever support VS 2019?

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit3-vs-adapter#576]
It would be good to document this clearly before folks start asking.

**Comment by rprouse** [comment]
@OsirisTerje if my memory serves me correctly from our meetings with the Visual Studio teams at the beginning of the year, VS 2019 is dropping support for VSIX based test adapters in favor of NuGet based test adapters. Can you confirm my recollection? If not, I'll reach out to Kendra.

This is in addition to the new requirement that the test adapter be added as a NuGet package to any project that contains tests unless you change your settings.

We should document both of these very clearly, probably in the README and in the documentation. We should also probably make an announcement on the mailing list and for any of us that blog regularly, maybe get the word out that way.

**Comment by OsirisTerje** [comment]
If you look at what we say on the VS marketplace, it is clearly stated there, I think. 
It will be deprecated:
"NOTE: - EARLY WARNING: Please observe that VSIX test adapters will be deprecated in the upcoming Visual Studio 2019. Please add the nuget adapter package to your solutions instead. See further information here and here"

**Comment by OsirisTerje** [comment]
Yep, agree.

**Comment by OsirisTerje** [comment]
I do however note that the Preview 2 still seems to be supporting VSIX adapters though....  Checking it out.
