### ISSUE TITLE
Fix licenseUrl in nuspec, will be deprecated

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#580]
![image](https://user-images.githubusercontent.com/203432/50222216-e2b57a80-0397-11e9-8fe7-92135296d62d.png)

**Comment by mikkelbu** [comment]
@OsirisTerje I can supply a PR for this if you like - it is a simple change similar to nunit/nunit.analyzers#127.

**Comment by OsirisTerje** [comment]
@mikkelbu Please do.  Last time I tried it failed though......
