### ISSUE TITLE
NUnit Adapter 3.12.0.0: Test discovery starting

### ISSUE THREAD

**Issue by VrushaliHaldankar** [nunit/nunit3-vs-adapter#584]
When reporting a bug, please provide the following information to speed up triage:

* NUnit : v3.11 and NUnit3TestAdapter versions :v3.12.0
* Visual Studio edition  : 2015and full version number (see Help About)

* What .net platform and version is being targeted  : .NET4.5 FRAMEWORK
===========================================================

In Test Explorer could not view class files. it happen sudden  everything was going perfect
===============================================
------ Discover test started ------
NUnit Adapter 3.12.0.0: Test discovery starting
========== Discover test finished: 0 found (0:07:16.2822061) ==========
------ Discover test started ------
NUnit Adapter 3.12.0.0: Test discovery starting
========== Discover test finished: 0 found (0:13:35.4652106) ==========
------ Discover test started ------
NUnit Adapter 3.12.0.0: Test discovery starting

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?
Make it as small as you can, it should compile "as is".
