### ISSUE TITLE
Debug.WriteLine messages don't appear in Output window like they did in NUnit 2.x

### ISSUE THREAD

**Issue by uxmal** [nunit/nunit3-vs-adapter#595]
NUnit: 3.11.0
 NUnit3TestAdapter: 3.12.0.0:
Visual Studio Professional 2017 version 15.9.4
.NET Framework 4.7

I have over 8000 unit tests, which were written using NUnit 2.x. Many of these unit tests, when reporting failure, emit useful diagnostic output to the Output window in Visual Studio by simply using the following code:
```C#
    Debug.Print("Test failed: {0}", someArg);
```
This has been working fine with NUnit 2.x + associated NUnit adapter for Visual Studio.

Expected:
With NUnit3, diagnostic output with `Debug.Write`, `Debug.WriteLine`, and `Debug.Print` to appear in the Output window as before _with no changes in the test code_.

Actual:
Output diagnostics fail to appear in the Output window!

Is this regression deliberate? If so, what was the reasoning behind it?

**Comment by OsirisTerje** [comment]
Have you tried running it under Debug?
![image](https://user-images.githubusercontent.com/203432/52782150-a9735100-304e-11e9-96dc-b9e938b14ae1.png)

**Comment by uxmal** [comment]
I suppose I can do this, but if I run this on a large batch of tests and one or more start failing, the VS debugger will capture the assertion failures and stop, which will be a pain. Our workflow has been that we spew diagnostics on failures using `Debug.Write/Print` and collect the output in the `Debug` window for diagnostics.

I suppose a workaround is to change my 8000 unit tests to use `Console.WriteLine` instead. Really not looking forward to that. What I don't understand is why this change was made in Nunit 3.0, since the Nunit 2.x test adapter is perfectly capable of emitting output to the `Output` window.

**Comment by OsirisTerje** [comment]
I don't really see how this could have worked any different in NUnit2.  Whether the Debug statement runs or not should be dependent upon whether the DEBUG symbol is defined, and that would be in your own code. 

@CharliePoole   I see some comments in the NUnit2 repo for the eventlistener that indicates it might have tracked debug output too.  But would that work in release mode?

**Comment by CharliePoole** [comment]
NUnit2 tracked both debug and trace. Also the console, when run with in debug mode under VS used to write to the output window. That's many years ago, of course.
