### ISSUE TITLE
url of the repo to https

### ISSUE THREAD

**Issue by 304NotModified** [nunit/nunit3-vs-adapter#599]
Please change the url of the repo to https :)

It should be http**s**://nuget.org, **not** https://**www**.nuget.org

![image](https://user-images.githubusercontent.com/5808377/52538139-41331f80-2d6f-11e9-93e6-82ce3a880029.png)

related: https://github.com/nunit/nunit/issues/3161

**Comment by OsirisTerje** [comment]
@304NotModified Not sure why this is needed.  Both should work, right?

**Comment by 304NotModified** [comment]
> @304NotModified https is good, but not sure why with or without www is an issue. Both should work, right?

Nope, not in this case:

![image](https://user-images.githubusercontent.com/5808377/52791594-98840900-3069-11e9-9ad5-600691e8ec1f.png)

The ceritifcate is only valid for the naked domain:

![image](https://user-images.githubusercontent.com/5808377/52791651-b3ef1400-3069-11e9-89e3-e93bea23dd61.png)


See also https://github.com/nunit/nunit/issues/3161#issuecomment-462123605

**Comment by 304NotModified** [comment]
> And, anyway your PR #598 fixes this.

No it doesn't, I can't PR the repo url :(

**Comment by OsirisTerje** [comment]
Ahh, thanks!  Now I see what you mean.  

@rprouse  - 1) Can you fix the url   2)  Why does our certificate not accept both forms (normally that can be set within the certificate) ?

**Comment by rprouse** [comment]
@OsirisTerje I have made the change and I've also made you an admin for this repo.

The SSL certificate is created and provided by GitHub which hosts the site. It is a limitation that only the one custom domain that we add is given a certificate.

**Comment by OsirisTerje** [comment]
Thanks @rprouse !
