### ISSUE TITLE
TestOutputXml setting ignored on netcore2.1, works on net461

### ISSUE THREAD

**Issue by zynori** [nunit/nunit3-vs-adapter#600]
**Environment:**
NUnit 3.11.0
NUnit3TestAdapter 3.12.0
Windows10
Visual Studio Pro 2017 15.9.5
net461 
dotnet 2.1.503

**Problem statement:**

Repro can be found here: https://github.com/zynori/nunitBugRepro

Project setup and settings below, the test result xml is not generated for netcoreapp2.1 while it is net461.

```xml
   <PropertyGroup> 
      <TargetFramework>netcoreapp2.1</TargetFramework> 
      <IsTestProject>true</IsTestProject>  
      <IsPackable>false</IsPackable>  
   </PropertyGroup>
```

.runsettings
```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
    <RunConfiguration>
        <TargetPlatform>x64</TargetPlatform>
    </RunConfiguration>
    <NUnit>
        <TestOutputXml>TestResults</TestOutputXml>
    </NUnit>
</RunSettings>
```

It creates the TestResults folder, but into bin\Debug\netcoreapp2.1\ and without any xml file.
On the other hand:

```xml
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
```

With this framework, it works perfectly. Creates the TestResult folder into the root folder with the xml file. 

**Questions:** 
Am I missing something?
Why is there a discrepancy between frameworks?
As a workaround, any tips how to get nunit xml?

**Comment by daniel-v** [comment]
I too observed this.

**Comment by OsirisTerje** [comment]
@daniel-v  @zynori  You are absolutely right.  It doesn't currently generate that output for .net core.  
Great you made an issue for it, as it should support .net core in the end, but there was some issues there using the NUnit service for this.  I hope it is nothing too serious, and I'll see how soon I get that part out too.

**Comment by daniel-v** [comment]
I need my lovely Jenkins test reports (using NUnit plugin), so as a temporary workaround, I started using `NunitXml.TestLogger` package. If and when this enhancement lands, I'll return to using only NUnit. 

Is there anything else on top of what @zynori did that can help you?

**Comment by OsirisTerje** [comment]
@daniel-v  IIRC the issue is in the NUnit Engine.  I am talking with the other guys there how we can fix that.  Not sure exactly what is in the engine that stops it, but I'll be back as soon as I know with more info.

**Comment by OsirisTerje** [comment]
@daniel-v @zynori  I got a fix in, but late here and no good test project, so I'll drop an alpha package here, if one of you guys can check it, it would be awesome.  
[NUnit3TestAdapter.3.13.0-d01.zip](https://github.com/nunit/nunit3-vs-adapter/files/2861722/NUnit3TestAdapter.3.13.0-d01.zip)

It **may** just works.... but....

**Comment by zynori** [comment]
@OsirisTerje thank you, it works perfectly, at first glance! 
Although, still creates the TestResult folder into the bin/debug/.... folder, so give a path, if you don't want it there.

**Comment by OsirisTerje** [comment]
@zynori Thanks!   
And yes, when using relative paths, the only starting point we have is the folder where the assembly is running, so any path given must be relative to that.

**Comment by OsirisTerje** [comment]
This fix will then go into the 3.13 release. 
A pre-release should be on Myget as soon as the PR goes goes through (that is, in a couple of hours)

**Comment by daniel-v** [comment]
> And yes, when using relative paths, the only starting point we have is the folder where the assembly is running, so any path given must be relative to that.

In that case, would it make sense to unify that part too between frameworks? Does it make sense to open another issue for it?

**Comment by OsirisTerje** [comment]
@daniel-v Now I lost you ;-)  There should be no difference in the relative path handling between the frameworks.  I might have missed something though...

**Comment by daniel-v** [comment]
In my experience, when I have `<TargetFramework>net461</TargetFramework>`, the TestResults folder indicated in the `.runsettings` file is created at the project root of the test project.
For `netcoreapp2.1`, it is created in `$(OutputPath)`.

@zynori can you confirm?

**Comment by zynori** [comment]
> In my experience, when I have `<TargetFramework>net461</TargetFramework>`, the TestResults folder indicated in the `.runsettings` file is created at the project root of the test project.
> For `netcoreapp2.1`, it is created in `$(OutputPath)`.
> 
> @zynori can you confirm?

Yes, @daniel-v that's correct.

**Comment by OsirisTerje** [comment]
Thanks !   And ok, this is another issue.  And this is not controlled by the adapter either, the TestResults folder is handled by VSTest.

**Comment by OsirisTerje** [comment]
Pre-release package available here: https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.13.0-dev-01048
