### ISSUE TITLE
Request to change working directory from Windows/System32 to another directory

### ISSUE THREAD

**Issue by vpenades** [nunit/nunit3-vs-adapter#609]
Hi

This is not yet another "why the working directory points to Windows/System32" , I've read the previous issues about the issue and I understand the reasons behind why the working directory does not point to where the test is located.

My concern is that, pointing the working directory to Windows/System32 _by default_ is dangerous, since a naive test can inadvertently write files to that directory, or any third party application, expecting to output to the working directory, writes files to it.

Which is exactly what just happened to me. I was pointing my tests to use TestDirectory and WorkDirectory as NUnit requires.... but by using a third party assembly which happens to write log files into the current working directory, I've just found that my Windows/System32 directory is full of trash.

Could it be possible to change this behaviour by default, so, the current working directory points to a safer **sink** directory?  for example, the Temp Files directory?

**Comment by OsirisTerje** [comment]
@CharliePoole Fair request.
@vpenades  Anything under \windows is good, but "any other directory considered harmful," any other that comes to mind?

**Comment by vpenades** [comment]
@OsirisTerje It comes to mind pretty much most SpecialFolders:
- Program Files (x86)
- ProgramsData
- Users (but not AppData\Local\Temp, which is inside the current user's path)

I can't imagine a reason why a test might require to run pointing to these directories. While doing so inadvertently might cause serious harm to the computer.

So I believe these directories need to be opted out by default, and maybe allow to manually opt them in, but under the full knowledge of the developer.

**Comment by OsirisTerje** [comment]
@vpenades Cool if you could check out the alpha:  https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.14.0-dev-01112
