### ISSUE TITLE
It is not possible to run an explicit test from Test Explorer

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit3-vs-adapter#612]
Visual Studio 2019 (I think 2017 as well), NUnit3TestAdapter 3.12.0.

If you right-click a test marked `[Explicit]` and click Run, the run ends immediately without running the test.

**Comment by OsirisTerje** [comment]
@jnm2  If we create small simulator for Visual Studio,  which calls the adapter interface with the appropriate parameters, - could we then create an integration test that show this thing failing?  Because this must be a regression, I "know" (I hope) that this worked earlier.

**Comment by bahusoid** [comment]
Same behavior in Visual Studio 2017 and NUnit3TestAdapter 3.10.0 - can't run Explicit tests nor from Test Explorer no from right-click.

**Comment by chm-tm** [comment]
This seems related to [these](https://github.com/nunit/nunit3-vs-adapter/issues/47) [issues](https://github.com/nunit/nunit3-vs-adapter/issues/473).

**Comment by DmitriiGaidukov** [comment]
The same problem with NUnit3TestAdapter 3.13.0.0 and Visual Studio15.9.6.

**Comment by OsirisTerje** [comment]
Resolved with https://github.com/nunit/nunit3-vs-adapter/pull/763

**Comment by OsirisTerje** [comment]
@jnm2 Alpha.1 released now: https://www.nuget.org/packages/NUnit3TestAdapter/4.0.0-alpha.1
