### ISSUE TITLE
Description from TestContext.AddTestAttachment does not displays in TEst Output window

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit3-vs-adapter#618]
@CMALD commented on [Wed Mar 06 2019](https://github.com/nunit/docs/issues/301)

![description](https://user-images.githubusercontent.com/46340089/53882724-c97bac00-401f-11e9-85af-c278a62aa3a2.PNG)
My code is: 

      var v = @"C:\Screenshots\1.Jpeg";
      TestContext.AddTestAttachment(v , "Description Test Attachment");

and as the screenshot, I see only the picture name and not the description

Thanks.

---

@OsirisTerje commented on [Wed Mar 06 2019](https://github.com/nunit/docs/issues/301#issuecomment-470126927)

Which tool do you use ?  

---

@CMALD commented on [Thu Mar 07 2019](https://github.com/nunit/docs/issues/301#issuecomment-470401393)

Visual Studio Community 2015
.NET Framework 4.7.1
Nunit3 +Selenium WebDriver

---

@CharliePoole commented on [Thu Mar 07 2019](https://github.com/nunit/docs/issues/301#issuecomment-470403958)

We need to know what tool you use to execute the tests. For example, nunit console runner, nunit is test adapter, some 3rd party runner. Usually, it's up to the runner to decide what to display.

---

@CMALD commented on [Thu Mar 07 2019](https://github.com/nunit/docs/issues/301#issuecomment-470405073)

![nunit test runner](https://user-images.githubusercontent.com/46340089/53936951-42c4de80-40b4-11e9-8786-54f8a35ee501.PNG)
See attached screenshot

---

@CMALD commented on [Thu Mar 07 2019](https://github.com/nunit/docs/issues/301#issuecomment-470406262)

This is perhaps called "VS Test Adapter"?

---

@CharliePoole commented on [Thu Mar 07 2019](https://github.com/nunit/docs/issues/301#issuecomment-470422961)

If you are able to run nunit3 tests in Test Explorer, then you have almost certainly installed the NUnit 3 VS adapter somewhere. It would help to know which version.

---

@CharliePoole commented on [Thu Mar 07 2019](https://github.com/nunit/docs/issues/301#issuecomment-470425276)

I'm on my phone right now, but as soon as I get onto my computer I'll transfer this to the correct project... unless someone else does it first!

---

@CMALD commented on [Thu Mar 07 2019](https://github.com/nunit/docs/issues/301#issuecomment-470426283)

I has NuGet Package : NUnit3TestAdapter v3.13.0

**Comment by OsirisTerje** [comment]
Reported to developer community here:  https://developercommunity.visualstudio.com/content/problem/1069478/test-attachment-descriptions-missing.html

Please vote up

**Comment by OsirisTerje** [comment]
Microsoft has decided not to fix this issue, since so few voted it up.
