### ISSUE TITLE
TestContext.Progress output.

### ISSUE THREAD

**Issue by vpenades** [nunit/nunit3-vs-adapter#621]
In my tests I am using `TestContext.WriteLine` for writing test outcome to the output panel, and `TestContext.Progress.WriteLine` for writing test progress to the console, so I can see the progress for very heavy tests.

The problem is that `TestContext.Progress` is also writing to the default output, so in the output panel, I have test data and test progress mixed.

Is there a way to prevent Progress to write to the output window, and let it write only to the console?

I think Out and Progress are expected to be used for different purposes. I consider "Out" to be a place to write test outcomes, while Progress is meant to allow monitoring the running process, and both outputs should not be mixed.

**Comment by OsirisTerje** [comment]
@vpenades Included in version 3.14, released today, Aug 8th 2019
