### ISSUE TITLE
Run all tests not refreshing failed tests

### ISSUE THREAD

**Issue by LuciLiu** [nunit/nunit3-vs-adapter#625]
Environment:
- NUnit Adapter 3.13.0.0
- Microsoft Visual Studio Professional 2015 Version 14.0.25420.01 Update 3
- .NET 4.5.2

Hi
I have a problem when I do "Run all the tests": I had 305 failed tests. I corrected 2, but when I do "Run all the tests",  I still have 305 failed tests. However, when I do Run failed tests, I have 303.

Why aren´t failed tests refreshed after correct them? I would like to have tests up to date when I do "Run all the tests". This happens when I use Visual Studio Adapter and when I compile in TFS CI.

I tried cleaning the solution and rebuilding, deleting bin and obj folder, deleting c:\temp files... It seems like test are being cached somewhere, but I dont know where 

Thanks in advance.

**Comment by OsirisTerje** [comment]
Sorry, I missed this one.  I am not sure what you see.  Do you have a possibility to create a small repro for this?   
If I try thi s on a test project with failed tests, I get the same number for both.  So there must be something with those tests you have, and a repro could shed some light on that.
