### ISSUE TITLE
The test pass even if there is a failure in [OneTimeTearDown]

### ISSUE THREAD

**Issue by goyzhang** [nunit/nunit3-vs-adapter#627]
Hi,
I'm using Nunit3 v3.11 with the adapter v3.13.
VS2017 15.9.11.
I want to test my Dispose methods with [OnetimeTearDown], but the test explorer always gives me PASS even if there is a failure inside Cleanup.
```
        [OneTimeTearDown]
        public void Cleanup()
        {
            Assert.Fail(); //The test explorer still gives me GREEN PASS
        }
```

**Comment by OsirisTerje** [comment]
@rprouse @jnm2 @ChrisMaddock   Can you comment on the general behavior of OneTimeTearDown ?

It is correct behavior in the adapter, the Tests are finished, and the OneTimeTearDown do not affect those Tests. 

But, if you want to test your dispose methods,  could you use separate tests for that?

**Comment by goyzhang** [comment]
@OsirisTerje 
Hi, I see [here](https://stackoverflow.com/questions/48598822/nunit-fail-test-when-onetimeteardown-fails) indicates that the ReSharper consider this as a failure.
My test procedure is like:

1. Setup and connect to a device
2. Run a bunch of function tests which will change the status on the device
3. The `dispose` methods shall be tested based on what we already have on the device.

The dispose method must be run at last. I can use `Order` attribute but then I have to add `Order` to all my test methods in order to make sure the `dispose` run at last. So...hopefully, the failure in teardown can be considerred as some sort of failure, or is there any other better way?

**Comment by OsirisTerje** [comment]
@goyzhang Interesting.  I just checked with MSTest and the result is exactly the same.  Afaik resharper also uses the adapter in the background, but the runner might have some functionality for handling this case.  It doesn't seem that the TestExplorer have the same.  I'll check with the Product Group.

**Comment by ChrisMaddock** [comment]
> @rprouse @jnm2 @ChrisMaddock Can you comment on the general behavior of OneTimeTearDown ?

The code above should cause the entire suite to Error, I believe. ("Error" rather than "Fail" - as FailureAssertions aren't permitted in TearDown's)

**Comment by OsirisTerje** [comment]
The adapter code handling this is sending only messages to TE, so we then need to send test results too.  I am not sure if the TE accepts it though.  Will check.

**Comment by rprouse** [comment]
Chris is correct, any asserts or exceptions in a teardown are considered an Error and should fail all the tests in the fixture. While I can see use cases for performing tests/asserts in a tear down or one time tear down, it has always been NUnit's policy to flag those as errors.

I expect that the adapter is just dealing with the individual tests, then ignoring the error on teardown?

**Comment by OsirisTerje** [comment]
OneTimeTearDown yes, the TearDown is per test case and is fine, any errors there are part of the test.  
Yep, it only sends the messages, but we can also send a result.  The question, which I have asked the PG about, is if the Test Explorer will honor it, since TE haven't had any concept of a test fixture.   MSTest behaves the same way.
