### ISSUE TITLE
Assert.Multiple produces new tests in the report if inner assertions fail

### ISSUE THREAD

**Issue by nvborisenko** [nunit/nunit3-vs-adapter#630]
* NUnit 3.12, NUnit3TestAdapter 3.13
* Visual Studio 2019 (16.1.1)

```csharp
[Test]
        public void Test1()
        {
            Assert.Multiple(() =>
            {
                Assert.AreEqual(2, 3, "Real part");
                Assert.AreEqual(4, 5, "Imaginary part");
            });
        }
```

When we execute this test we gets 2 test results instead one.
![image](https://user-images.githubusercontent.com/22616990/60503854-2c790900-9cc9-11e9-961c-2e99ee743776.png)

NUnit3TestAdapter lies about tests count.

**Comment by OsirisTerje** [comment]
Not sure what you mean here.  The Assert.Multiple works this way, it continues with the other asserts, so that you see all the results.

**Comment by nvborisenko** [comment]
Right. But my project contains only 1 test. When I executed test, I got 2 tests... It is confusing. And 2 tests fail, but I have only 1...

**Comment by OsirisTerje** [comment]
Ahh, got it.

**Comment by OsirisTerje** [comment]
Just to be precise:
Visual Studio Test Explorer itself reports this correctly. 
It is the command line vstest.console that reports this wrongly.  That counter is from vstest.console, and not from the adapter. 
The error also comes only when both tests are failing, if both are passing or just one is passing it reports correctly.
