### ISSUE TITLE
Tested Marked as failed console but pass in visual studio

### ISSUE THREAD

**Issue by dsielert** [nunit/nunit3-vs-adapter#633]
latest nunit3 adapter and nunit3 console runner tests are marked as passed in VS 2019 but when ran from console several are in reality failing but don't seem to be reported as such in Visual studio

**Comment by OsirisTerje** [comment]
Which tests are you referring to?
Can you elaborate on this?

**Comment by dsielert** [comment]
Our tests.. they are clearly failing in nunit-console but this adapter marks them as passed

**Comment by OsirisTerje** [comment]
Can you upload a small repro ?
