### ISSUE TITLE
Follow up on: NUnit & TestCaseSource, test cases are not recognized

### ISSUE THREAD

**Issue by yahorsi** [nunit/nunit3-vs-adapter#634]
Hi Guys!

Here is the issue I have created from VS.

https://developercommunity.visualstudio.com/content/problem/620120/nunit-testcasesource-test-cases-are-not-recognized.html

Following up the answer Peter Waldschmidt [MSFT] gave:
I still do not understand why in some cases we see test cases being recognized by VS and why in some not. Could someone please review Peter's answer?

Thanks

**Comment by OsirisTerje** [comment]
The behavior described by @Peter Waldschmidt [MSFT] is correct, and by design. Also note that with Real Time Test Discovery (aka Source based discovery) in VS turned on (default), you will only see a single test case. It is first when you run the tests that we know the total number, and NUnit has chosen to report that as underlying test results.

About some times seeing it, and sometimes not, can this be related you you using Real Time discovery or not ?   I cloned down your repo, and it worked as it should for me.  
Can you point to how I can repro your case ?

**Comment by yahorsi** [comment]
> About some times seeing it, and sometimes not,

By that I, mainly, meant that for some test cases we see them as test cases in VS and for some we don't.

**Comment by OsirisTerje** [comment]
It sounds weird.  Is there not any pattern to the behavior ?

When you say "test cases" , I assume you mean tests, right?   The individual test cases are shown as results,  but what you don't see is the test itself at all, right?

**Comment by yahorsi** [comment]
> It sounds weird. Is there not any pattern to the behavior ?


Exactly ) That is what this issue is about. I would understand when it always does not show test cases, but, we see them sometimes, and sometimes does not. It seems it depends on test case data. Like, for simple cases, e.g. string, we see them with no problem. I pushed update to the github repo with 2 tests, where in 1 case we see test cases and in another we don't. Here is the screenshot

![NUnitTestCase](https://user-images.githubusercontent.com/9819679/60893681-a711cd80-a261-11e9-99e1-f2fa10c4fdae.jpg)



BTW, in my case I see test cases right after build, not after tests execution. And nothing changes after tests execution.

>Also note that with Real Time Test Discovery


Where could I check is it enabled or not? Anyway I have not changed it since I have installed VS so it should be default that is ON,

**Comment by mikkelbu** [comment]
> Exactly ) That is what this issue is about. I would understand when it always does not show test cases, but, we see them sometimes, and sometimes does not. It seems it depends on test case data. Like, for simple cases, e.g. string, we see them with no problem. 

And it is not consistently a problem for test case data that does not have a string representation that gives rise to unique test names?

> Where could I check is it enabled or not? Anyway I have not changed it since I have installed VS so it should be default that is ON,

It can be found under "Tools => Options" and the element "Test".

**Comment by OsirisTerje** [comment]
@yahorsi The thing is that the string based defines names for the tests, whereas the non-string based keeps the same name.  That way they will be grouped together.  But, you can add your own test names by returning TestCaseData instead of object, and add naming to that construction.  I did that for a couple of your cases:
![image](https://user-images.githubusercontent.com/203432/60917128-82811a00-a290-11e9-9ed1-6adc1c5bb8b1.png)

**Comment by yahorsi** [comment]
> And it is not consistently a problem for test case data that does not have a string representation that gives rise to unique test names?

Sorry, don't get it, why can't you have a string representation in my case?

**Comment by OsirisTerje** [comment]
I think the reason back then was that there are too many variations of how that could turn out. Using the SetName seemed like a better solution for users.

**Comment by yahorsi** [comment]
> I think the reason back then was that there are too many variations of how that could turn out. Using the SetName seemed like a better solution for users.

When you know it exists )

**Comment by OsirisTerje** [comment]
You can also derive your own class from TestCaseData and do everything (SetName) in that class, that will reduce the "clutter" in the GetEnumerator method.

**Comment by OsirisTerje** [comment]
> > I think the reason back then was that there are too many variations of how that could turn out. Using the SetName seemed like a better solution for users.
> 
> When you know it exists )

Yeah, that is the thing.  We need to get the documentation better :-)

**Comment by OsirisTerje** [comment]
@mikkelbu Perhaps we could add some more examples in https://github.com/nunit/docs/wiki/TestCaseSource-Attribute , or enhance the existing example code there using TestCaseData.  It could make it easier to understand.

**Comment by mikkelbu** [comment]
@OsirisTerje I like the sound of this. The documentation could need some more TLC in some areas.

**Comment by yahorsi** [comment]
Sorry guys, but I need to bring this back :)

2 points:
1. Even if we cannot infer test case name (astill don't get why we can't), we could show some dummy names, like "Case1", "Case2", etc...

2. SetName is a bit different thing, it let's to set the name of the test and not test case, so, your test cases won't be groupped in the VS tests explorer

**Comment by OsirisTerje** [comment]
@yahorsi  Not sure what you mean, take a look at the repro code I modified at https://github.com/OsirisTerje/Issue634, and see if that doesn't solve your issue.
