### ISSUE TITLE
VS 2019 16.2 Test Explorer - no longer showing Categories

### ISSUE THREAD

**Issue by MPasadu** [nunit/nunit3-vs-adapter#639]
I am not sure if the issue is on this side or the VS 2019 team. 

With the latest VS 2019 16.2 version the test explorer window got updated. Before you could change the "Group By" to use NUnit3's categories or the author attribute. This functionality is now missing. 

The exact use case is: We have multiple integration tests that are marked with the category "long-running". Finding them was easy with just grouping by category. This is no longer possible.

Best Regards

**Comment by OsirisTerje** [comment]
@MPasadu 
You're saying this *IS* working with 16.1, but not with 16.2 ?  

(I am on vacation on low bandwidth, and my laptop doesn't have VS2019 16.1 nor 16.2 installed. )

**Comment by kendrahavens** [comment]
This Trait grouping was moved to be a column. With the multi-tiered and customizable hierarchy in Visual Studio 2019 Update 16.2 we thought continuing to include traits as a grouping created unneeded visual complexity. We are definitely listening to feedback on this design!https://developercommunity.visualstudio.com/content/problem/458772/test-explorer-doesnt-categorize-based-on-testcateg.html

For now, you can right click on the column in the Test Explorer and select Columns. Check the Trait column and it will appear in the Test Explorer. You can now filter this column by what traits you are interested in.
![image](https://user-images.githubusercontent.com/8293542/61893288-93ea3900-aec2-11e9-99ce-1cdc2a90393b.png)

![image](https://user-images.githubusercontent.com/8293542/61893174-48378f80-aec2-11e9-990f-f719cba06af3.png)

**Comment by OsirisTerje** [comment]
Thanks for the good explanation @kendrahavens!
