### ISSUE TITLE
NUnit3TestAdapter 3.14.0 includes NUnit3.TestAdapter.dll versioned 3.13

### ISSUE THREAD

**Issue by flcdrg** [nunit/nunit3-vs-adapter#645]
The NUnit3TestAdapter NuGet package contains the NUnit3.TestAdapter.dll assembly

Confusingly, this assembly has the file/product version 3.13.0.0

NUnit3.TestAdapter, Version=3.13.0.0, Culture=neutral, PublicKeyToken=4cb40d35494691ac

I just upgraded from 3.13 to 3.14 and couldn't understand why Visual Studio kept using the "old" version! Turns out it probably wasn't - just displaying the version number from the assembly that didn't line up with the package version.

**Comment by OsirisTerje** [comment]
@flcdrg  Thanks!   Will fix in 3.15 :-)
