### ISSUE TITLE
NUnit3TestAdapter 3.15 OneTimeSetUp not working anymore

### ISSUE THREAD

**Issue by SmartLibertyFBO** [nunit/nunit3-vs-adapter#649]
Visual Studio 2017 v15.9.14
<package id="NUnit" version="3.12.0" targetFramework="net471" />
<package id="NUnit3TestAdapter" version="3.15.0" targetFramework="net471" />

The first time I run a test, OneTimeSetUp is called, then every other runs fails. I had no problems with 3.14. I made a new project to reproduced it with minimal code and I can run multiple time my test and it always succeed with 3.14, but as soon as I upgrade to 3.15, it is never called anymore.. If I restart VS, it work only once and all following try fails. Can be reproduced with nuget package or VS extension.

```
using NUnit.Framework;

namespace NunitAdapter315Bug
{
    [SetUpFixture]
    public class ProjectSetup
    {
        public static bool oneTimePassed = false;

        [OneTimeSetUp]
        public void OneSetup()
        {
            oneTimePassed = true;
        }
    }
}
```

```
using NUnit.Framework;

namespace NunitAdapter315Bug
{
    [TestFixture]
    public class TestNunitAdpaterTest
    {
        bool setupPassed = false;
       
        [SetUp]
        public void Setup()
        {
            setupPassed = true;
        }

        [Test]
        public void TestIt()
        {
            Assert.IsTrue(ProjectSetup.oneTimePassed);
            Assert.IsTrue(setupPassed);
        }
    }
}

```

**Comment by mikkelbu** [comment]
I'm quite sure that this is the same problem as in nunit/nunit#3356 (see the comments for more info), but I've not had time to look into how to fix it.

**Comment by ggeurts** [comment]
I have also had to revert to version 3.14 because tests in .NET Core started failing due to not running of SetUpFixture with OneTimeSetup method.

**Comment by OsirisTerje** [comment]
Thanks @jhbell !

Will try to get out a fix within this week, probably using a feature flag to enable/disable the pre-filtering.

**Comment by ViceIce** [comment]
@jhbell Your solution only works for the vsix, we don't use that. We have to downgrade the `NUnit3TestAdapter` package reference to `3.14.0`

**Comment by OsirisTerje** [comment]
@ViceIce Downgrading a nuget package is much more simple than the vsix, since all you have to do is either  :  1) Use the Tools/Manage nugetpackages in Visual Studio and select the 3.14 version 2) If you have a SDK based project, just edit the csproj file directly. :-)   

However, the fix is on its way now, a PR is up, waiting for a quick review.  Hopefully we can get it out tomorrow, Aug 30.

**Comment by OsirisTerje** [comment]
@SmartLibertyFBO @ggeurts @ViceIce  There is now a beta version of the fix in https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.15.1-dev-01134  .  Would appreciate if you checked it.

**Comment by ViceIce** [comment]
I can test it earliest on monday

**Comment by OsirisTerje** [comment]
@SmartLibertyFBO 3.15.1 hotfix released now.

**Comment by SmartLibertyFBO** [comment]
It seems to work with my test solution, thanks

**Comment by ViceIce** [comment]
Works here
