### ISSUE TITLE
Unable to individually run some tests in VS2015

### ISSUE THREAD

**Issue by ninevoltbatterie** [nunit/nunit3-vs-adapter#653]
The Visual Studio Test Explorer window seems to populate correctly with my tests, but some of them won't run when individually selected.  In one test class, for example, I have 24 tests, and if I select the class in Test Explorer (with the view where the tests are organized by class), only 8 tests are run, with the message "NUnit3TestExecutor converted 8 of 8 NUnit test cases", as if the others didn't exist.  If I click "Run All" in Test Explorer, it runs almost all the tests (leaves 1 out of ~3,000 not run), but if I use a search filter to restrict the tests to the class I'm trying to run, and _then_ click "Run All", still not all 24 tests are run.  If I simply retry the class tests, the same 8 tests will run again and again, but at some point after my experimentation (eg. trying different NUnit3TestAdapter versions, cleaning, rebuilding, restarting VS, rebooting, upgrading and un-upgrading other packages), the tests which were runnable did change.

This sounds similar to issue #131, but that ticket is resolved.  The description of that ticket matches the behavior I'm seeing, but the behavior described is different- I can run _all_ tests, but I can't always run individual tests.  The description there was that individual tests could be run but not all tests.

Coworkers working on the same code base have now experienced the same problem.  I can't think of anything I had changed when this started happening, but it seems to be system-wide; I see the same behavior in other working copies of my code, as well as after reverting my working copy to a weeks-old version.  When I first observed this, I was using NUnit 3.6.1 and NUnit3TestAdapter 3.7, but during my experimentation, I have upgraded.

I somewhat suspect that Typemock Isolator (now v8.8) might be involved in this, because each of the tests which don't run are tests which use it.  But there are also many tests which use it that _are_ running.

I am now using NUnit 3.12.0 and NUnit3TestAdapter 3.15.0.
Visual Studio 2015, Version 14.0.25431.01 Update 3
Target framework is .NET 4.6.1.

**Comment by ninevoltbatterie** [comment]
Update: I have created some minimal tests to reproduce this.  They do not use Typemock, so that's out.

I can't get multiple lines of code to format nicely here, but here they are:
----- begin example ----
using NUnit.Framework;

namespace ExampleTests
{
  [TestFixture]
  class AAATests
  {
    // These tests can each be run individually
    [TestCase(TestName = "{m}")] // select this and they all run
    [TestCase(TestName = "{m}(")]
    [TestCase(TestName = "{m}(a")]
    public void GoodTest()
    {
    }

    // These tests don't run.
    [TestCase(TestName = "BadTes")]
    [TestCase(TestName = "{m} a")]
    [TestCase(TestName = "{m} a(")]
    [TestCase(TestName = "{m}a(")]
    [TestCase(TestName = "{m}-")]
    [TestCase(TestName = "{m} (")]
    //[TestCase(TestName = "BadTest")]
    // comment this last one in and all of these will run if
    // selected together. Also, if you ONLY select this one,
    // all of them will run.
    public void BadTest()
    {
    }
  }
}
------ end example ------

Here's a summary of what I deduce from those examples:
* If you use "TestName", you must also use “{m}” in it OR the exact name of the method itself.
* If you have characters after the “{m}”, a "(" must immediately follow "{m}".
* For a given test method, you can break any of the above as long as one of the other test cases follows them, and they are selected together.

I assume that my earlier observation that the tests which were runnable changed at some point is misleading, and that it was the result of selecting different groups of tests, which affects whether or not a given test is run.  I hope this is helpful, I would love to get some advice as to how I can pin this down.

**Comment by OsirisTerje** [comment]
@ninevoltbatterie Can you try either adapter 3.14 or the beta of 3.15.1 at https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.15.1-dev-01134  

Also see the comments on #650

**Comment by OsirisTerje** [comment]
@ninevoltbatterie    I assume that what you see in the Test Explorer is this:
![image](https://user-images.githubusercontent.com/203432/64014089-91ae7680-cb21-11e9-89f0-36e3e38d1d66.png)
Group (1) are the "real tests" so to speak.  Group (2) are "ghost tests", which appears due to the way Real Time discovery in Visual Studio Test works.  There is work in progress to fix this in Visual Studio.  
If you turn off Real Time Discovery, it will llook like this:
![image](https://user-images.githubusercontent.com/203432/64014160-cd494080-cb21-11e9-9722-209fefcd20f8.png)

To turn it off, go to Tools/Options:
![image](https://user-images.githubusercontent.com/203432/64014205-de924d00-cb21-11e9-89d5-bd4e2915719c.png)

**Comment by ninevoltbatterie** [comment]
@OsirisTerje , First things first: With 3.15.1-dev-01134 and 3.15.1, the problem I was having seems to be fixed.  :+1: 

However, your first image is not how my tests were depicted in the Test Explorer.  They were showing up just as the should, they just weren't running when selected.

Also, I don't have a "Test" menu on my Tools/Options dialog like you show (maybe because of VS2015?), so I wasn't able to experiment with that setting.  After "SQL Server Tools" comes "Text Templating" in mine.

It's still a mystery to me why this behavior started; I hadn't recently changed my NUnit3TestAdapter version.  But I am happy that it seems to be working again.

**Comment by OsirisTerje** [comment]
If you're using the vsix extension, then it is automatically updated, so not always easy to notice it is being updated.  
You stated that you have adapter 3.15.0, and that was released Aug 23rd :-)

And yes, with VS2015, you don't have Real Time Discovery, so then I assume it is just the PreFilter in 3.15.0 messing up the names.

**Comment by ninevoltbatterie** [comment]
That all makes sense now.  Thank you for the resolution.
