### ISSUE TITLE
How to run parameterized NUnit tests on .NET Core?

### ISSUE THREAD

**Issue by OlegYanushkevich** [nunit/nunit3-vs-adapter#655]
I'm trying to run my NUnit test based on .NET Core and getting something like nunit/nunit-console#487. And I'm trying to use ```dotnet test```. And I have one small question: how i can run parameterized tests vial ```dotnet test```? See [that](https://github.com/dotnet/cli/issues/12493#issuecomment-528720829) for see discussion about that.

**Comment by mikkelbu** [comment]
@OlegYanushkevich I've transfered this issue to the "nunit3-vs-adapter" project, as `dotnet test` calls the adapter.
As far as I know we don't use FQN yet, but @OsirisTerje will know for sure. Perhaps it is possible to send another kind of filter via `dotnet test`?

**Comment by OlegYanushkevich** [comment]
@mikkelbu I used FQN for running NUnit tests via ```dotnet test```. And I should somehow rerun failed tests. But now I don't have any idea how I can do that. Unfortunately, even possibility like ```--testlist``` in NUnit ```dotnet test``` isn't supporting.

**Comment by OsirisTerje** [comment]
@OlegYanushkevich Can you check https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.16.0-dev-01202 ?

Instructions for use is here:  http://blog.prokrams.com/2019/12/16/nunit3-filter-dotnet/

**Comment by OlegYanushkevich** [comment]
@OsirisTerje , shure. 
But, unfortenately, I'm not seeing any changes. I use simple project for testing(see picture below)
![image](https://user-images.githubusercontent.com/28996736/71028846-249a0d80-211f-11ea-9bc7-6beb613313c4.png)
And trying to run one test with specific argument triggers test with other parameters. You can get more details in log files from visual studio, that ware attached below.
[logs.host.19-12-17_22-36-24_63102_29.txt](https://github.com/nunit/nunit3-vs-adapter/files/3975167/logs.host.19-12-17_22-36-24_63102_29.txt)
[logs.host.19-12-17_22-23-01_13404_17.txt](https://github.com/nunit/nunit3-vs-adapter/files/3975168/logs.host.19-12-17_22-23-01_13404_17.txt)
During trying to run test with specific filter with helping -- Nunit.Where parameter, I'v got next error:
![image](https://user-images.githubusercontent.com/28996736/71029206-f10bb300-211f-11ea-8c06-f0d1646f6efd.png)
But, as you can see, executing without parameters successfully completed.

**Comment by OsirisTerje** [comment]
Thanks @OlegYanushkevich !  I'll close this as resolved using the NUnit test filter language :-)
