### ISSUE TITLE
TestContext.Progress not visible in test output

### ISSUE THREAD

**Issue by cocowalla** [nunit/nunit3-vs-adapter#661]
I'm trying to use `TestContext.Progress.WriteLine("my message")` in tests (using Xamarin.UITest, if it matters), but `TestContext.Progress` output doesn't appear when running tests in Visual Studio or Rider.

In Visual Studio, I tried running tests using both the ReSharper test runner and Visual Studio's built-in one, but got the same result - no output in the test output window.

If I run tests from the command line (`dotnet test`), then `TestContext.Progress` appears as it is generated, as expected.

Note that `TestContext.Out` and `TestContext.Error` work in all cases as expected.

csproj snippet:

```xml
<TargetFramework>netcoreapp2.1</TargetFramework>
...
<PackageReference Include="nunit" Version="3.12.0" />
<PackageReference Include="NUnit3TestAdapter" Version="3.15.1" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.1" />
<PackageReference Include="Xamarin.UITest" Version="3.0.3" />
```

**Comment by OsirisTerje** [comment]
If  you look in the Output window , don't you see this:
![image](https://user-images.githubusercontent.com/203432/65842200-11e71800-e32a-11e9-836e-bdff4eb2c95f.png)

**Comment by cocowalla** [comment]
Ach, you're right, it is displayed there in VS. Annoyingly, I'm sure I've made this mistake before!

It really isn't displayed in Rider though - it seems there's some [secret-squirrel](https://rider-support.jetbrains.com/hc/en-us/articles/115000233004-How-to-enable-Unit-Tests-runner-s-logging-) way to enable it, but you need to start Rider in "internal mode" to make the setting available.

**Comment by OsirisTerje** [comment]
Thanks for the comment on Rider.  I'll see if we can reach out to them about it.
