### ISSUE TITLE
Exception in OneTimeSetUp has no stack trace

### ISSUE THREAD

**Issue by provegard** [nunit/nunit3-vs-adapter#671]
When an exception is thrown in code called from a `OneTimeSetUp` method, I get:

> Exception doesn't have a stacktrace

Code to demonstrate the problem: 

    public class Tests
    {
        [OneTimeSetUp]
        public void Setup()
        {
            throw new Exception("oops");
        }

        [Test]
        public void Test1()
        {
            Assert.Pass();
        }
    }

Versions:

* .NET Core 3.0
* NUnit 3.12.0
* NUnit3TestAdapter 3.15.1
* Microsoft.NET.Test.SDK 16.3.0

**Comment by OsirisTerje** [comment]
Thanks :-)   But, closed ?

**Comment by CharliePoole** [comment]
User closed... I meant to reopen.

**Comment by Brondahl** [comment]
FYI, you can sort-of bypass this issue, by wrapping all of your `OneTimeSetUp` methods in:
```
try
{
  //... do setup
}
catch(Exception e)
{
  throw new Exception(e.ToString(), e);
}
```
Kinda sucks, but it's better than what you get at the moment.

**Comment by bronumski** [comment]
I am also hitting this issue with the Test Explorer (or more specifically with ReSharper). I write a number of behavioral tests where the arrange and act happen in the one time setup and the logical assertions are the individual tests. If an exception is thrown during the arrange or the act it is a pain to debug. Work around suggestion accepted.

**Comment by radiy** [comment]
> Because TestExplorer (and I believe Resharper as well) never reports errors on the fixture, we report the message **as if** the exception was thrown for the test case itself - otherwise, you would never see it. We do not report the stack trace simply because that would be a lot of repetition and you can generally find where the exception was thrown pretty easily, if not by inspection, then in the debugger.

Please reconsider, this is HUGE waste of time. Think about CI scenario, sometimes setup is pretty complex and when it went wrong all you get is NullReferenceException.

**Comment by bronumski** [comment]
I wan't 100% sure so I checked and Rider and ReSharper do report errors on the fixture:

![image](https://user-images.githubusercontent.com/3909845/106286362-69d1af80-61fa-11eb-8c9e-6f5879beb2db.png)

**Comment by CharliePoole** [comment]
@radiy I only posted a __description__ of how TestExplorer works and how the adapter tries to compensate for it. It's not possible to "reconsider" that - it's just a fact. Are you using TestExplorer in your CI? That seems unlikely. You may want to post info about what you are using, what doesn't work for you and what you would like changed.

To be clear, I haven't worked on the adapter for years myself, so I'm only making suggestions.

@bronumski I have no idea how they do that, but apparently they have figured out a way. As commercial companies, they're probably not going to tell us. :disappointed: It's possible they get the info directly from NUnit and not through the adapter.

Still, that's good information. It shows that any of these runners - test explorer included - could access and display the info you want to see. That was kind of my point. Although I don't work on the adapter any longer, I do remember how frustrating it was that it tends to be blamed for limitations in the code that calls it.

IMO, if you simply accept the fact that Test Explorer does not know about fixture-level failures and will never report them directly, you are a step ahead. Then you can start to imagine workarounds, where the adapter displays the info you need "on the side" i.e. in a fake test or in the output window or as some visible text output elsewhere in the interface.

**Comment by radiy** [comment]
> @radiy I only posted a **description** of how TestExplorer works and how the adapter tries to compensate for it. It's not possible to "reconsider" that - it's just a fact. Are you using TestExplorer in your CI? That seems unlikely. You may want to post info about what you are using, what doesn't work for you and what you would like changed.

Looks like I was a little rushed.
I will try to describe my issue.
Of course I`m not using Test Excelorer in CI, I run tests with dotnet test and collect test results from trx-files.
Development environment and test environment are different, so sometimes unexpected errors occur,
finding root case when you have only exception message in many cases impossible
and at the same time it`s trivial to find root case if you have a complete exception text.
For me, the main problem is that exceptions in the OneTimeSetUp method are neither recorded in trx-file, nor in standard output.

Do you think it`s possible to log exception only once, on the first test method.

**Comment by CharliePoole** [comment]
Sounds possible! I believe the adapter knows when it's running under vstest vs test explorer. @OsirisTerje will have to give the final answer, since he does the work. :smile:

**Comment by OsirisTerje** [comment]
@radiy @CharliePoole We do get the stack trace so it should be possible to get this out somehow.  If we focus on dotnet test and vstest commandline scenarios it might be even easier.

**Comment by svengeance** [comment]
@OsirisTerje I recently worked in the adapter quite a bit for a personal project. Is this an issue you'd like a contribution for?

**Comment by OsirisTerje** [comment]
@svengeance Absolutely!  Feel free to add a PR :-)

**Comment by svengeance** [comment]
@OsirisTerje To be sure - what's the intended solution here? Log the stacktrace on the first test method, log it to the Test Output window, log the full stacktrace on all tests, etc?

For giggles I'm investigating manipulating the text on the Fixture itself, but I don't have high hopes for that..

**Comment by jamers99** [comment]
Nice, any progress on this? I'm sure the people over at [this issue](https://github.com/nunit/nunit/issues/2466) would appreciate this.

**Comment by OsirisTerje** [comment]
@jamers99  @provegard @svengeance 
[NUnit3TestAdapter.4.0.0-dev.751.zip](https://github.com/nunit/nunit3-vs-adapter/files/6564895/NUnit3TestAdapter.4.0.0-dev.751.zip)
Please check the enclosed adapter.  It will output the stack trace for the exceptions in the overall message part.  It will not come out per test.  It will be included in the trx file, and in Visual Studio Console Output window for testing.
