### ISSUE TITLE
VS Test Explorer fails to run tests with test cases mocked with NSubstitute

### ISSUE THREAD

**Issue by GRXoft** [nunit/nunit3-vs-adapter#672]
Consider this test (using NSubstitute):

    public interface IParameter { }

    public class TestExample
    {
        public static IEnumerable<IParameter> Parameters { get; } = new[]
        {
            Substitute.For<IParameter>()
        };

        [Test]
        [TestCaseSource(nameof(Parameters))]
        public void ThisTestIsNotRun(IParameter p)
        {
            Assert.IsNotNull(p);
        }
    }

I'd expect the test to be run and pass. This is the case when run with `dotnet test`:

> Test run for C:\Users\\********\source\repos\Sample.Tests\Sample.Tests\bin\Debug\netcoreapp3.0\Sample.Tests.dll(.NETCoreApp,Version=v3.0)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.
>
> Starting test execution, please wait...
>
> A total of 1 test files matched the specified pattern.
>
> Test Run Successful.
> Total tests: 1
>      Passed: 1
>  Total time: 1.5845 Seconds

However, when run in Visual Studio 2019 Test Explorer, even though the test is correctly recognized, it seems not to be run - it is grayed out in the VS Test Explorer, and the test menu shows icons:
> 1 total
> 0 passed
> 0 failed
> 1 not run

The tests output does not seem to report anything interesting - perhaps only that it did not discover any test cases to be converted in the first place:

> [2019-10-30 11:11:59.056 PM Informational] ---------- Discovery started ----------
> [2019-10-30 11:11:59.528 PM Informational] NUnit Adapter 3.15.1.0: Test discovery starting
> [2019-10-30 11:11:59.791 PM Informational] NUnit Adapter 3.15.1.0: Test discovery complete
> [2019-10-30 11:11:59.842 PM Informational] ========== Discovery finished: 1 tests found (0:00:00.7853148) ==========
> [2019-10-30 11:11:59.859 PM Informational] ---------- Run started ----------
> [2019-10-30 11:12:00.382 PM Informational] NUnit Adapter 3.15.1.0: Test execution started
> [2019-10-30 11:12:00.392 PM Informational] Running selected tests in C:\Users\\********\source\repos\Sample.Tests\Sample.Tests\bin\Debug\netcoreapp3.0\Sample.Tests.dll
> [2019-10-30 11:12:00.675 PM Informational]    NUnit3TestExecutor converted 0 of 0 NUnit test cases
> [2019-10-30 11:12:00.713 PM Informational] NUnit Adapter 3.15.1.0: Test execution complete
> [2019-10-30 11:12:00.908 PM Informational] ========== Run finished: 0 tests run (0:00:00.9240394) ==========

I am using this _csproj_:

    <Project Sdk="Microsoft.NET.Sdk">

      <PropertyGroup>
        <TargetFramework>netcoreapp3.0</TargetFramework>
        <IsPackable>false</IsPackable>
      </PropertyGroup>

      <ItemGroup>
        <PackageReference Include="NSubstitute" Version="4.2.1" />
        <PackageReference Include="NUnit" Version="3.12.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="3.15.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.3.0" />
      </ItemGroup>

    </Project>

from within _Microsoft Visual Studio Professional 2019 Version 16.3.7 (VisualStudio.16.Release/16.3.7+29424.173)_

**Comment by OsirisTerje** [comment]
@GRXoft This might be related to the #622   issue.   Can you check with  a) https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.16.0-dev-01202  and 2) NUNit version 3.12 ?

**Comment by GRXoft** [comment]
@OsirisTerje The problem seems to be gone when using version 3.16.0-dev-01202. The test is run and marked as passed in Test Explorer. The test output also indicates success:

> [2019-11-02 8:37:24.393 AM Informational] ---------- Discovery started ----------
> [2019-11-02 8:37:24.431 AM Informational] ========== Discovery skipped: All test containers are up to date ==========
> [2019-11-02 8:37:24.457 AM Informational] ---------- Run started ----------
> [2019-11-02 8:37:25.609 AM Informational] NUnit Adapter 3.16.0.0: Test execution started
> [2019-11-02 8:37:25.623 AM Informational] Running selected tests in C:\Users\********\source\repos\Sample.Tests\Sample.Tests\bin\Debug\netcoreapp3.0\Sample.Tests.dll
> [2019-11-02 8:37:26.409 AM Informational]    NUnit3TestExecutor converted 1 of 1 NUnit test cases
> [2019-11-02 8:37:26.537 AM Informational] NUnit Adapter 3.16.0.0: Test execution complete
> [2019-11-02 8:37:26.698 AM Informational] ========== Run finished: 1 tests run (0:00:02.222783) ==========

**Comment by OsirisTerje** [comment]
https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.16.0-dev-01202
