### ISSUE TITLE
When multiple test projects are in a solution, one is not run

### ISSUE THREAD

**Issue by johnjaylward** [nunit/nunit3-vs-adapter#674]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions
  * NUnit: 3.12.0
  * Nunit Adapter: 3.16.0-dev-01202
* Visual Studio edition and full version number (see Help About)
  * VS 2019 - 16.3.7
* A short repro, preferably attached or pointing to a git repo or gist
  * https://github.com/johnjaylward/nUnitExpressionTest
* What .net platform and version is being targeted
  * net46+
* If TFS/VSTS issue, what version, hosted, on-premises, and what build task you see this in
  * N/A

The example project shows that when the solution only includes a single test project, the tests run fine. However, when 2 or more tests projects are in the solution, only 1 of the Test project's tests will be run. even manually running does not appear to work.

**Comment by johnjaylward** [comment]
@OsirisTerje This is the 2nd issue not solved in the fix for #622

**Comment by OsirisTerje** [comment]
I can confirm this.  What seems strange is that the adapter gets the test results, and even stores them on disk, but for some reason it is not propagated or accepted to the Test Explorer

**Comment by johnjaylward** [comment]
Has there been any movement on this? This is holding back updating to VS2019 for my projects and is now an issue because one of my other dependencies now requires it (https://github.com/Fody/Fody/ as an example).

**Comment by OsirisTerje** [comment]
From what I can see, the tests are being run, but not displayed correctly.  I have sent a question to the MS PG.

**Comment by OsirisTerje** [comment]
Using adapter 3.16.1 and the latest preview version, 2019 16.5  Preview 2, it seems to work.
