### ISSUE TITLE
Documentation missing: How to make Test Adapter load addins

### ISSUE THREAD

**Issue by TFTomSun** [nunit/nunit3-vs-adapter#681]
I couldn't find any documentation, where an addin file needs to be placed to make the test adapter load it.

**Comment by OsirisTerje** [comment]
The test adapter don't load addins, but the engine does load extensions, which will probably do the same thing for you.  Please see here:  https://github.com/nunit/docs/wiki/Engine-Extensibility  .  If you want to extend nunit itself, please see https://github.com/nunit/docs/wiki/Framework-Extensibility  .   You can get better response rising your question on https://gitter.im/nunit/nunit

**Comment by TFTomSun** [comment]
@OsirisTerje 
where do i need to place the addins file to make the runner, that uses the adapter, load the addin? (e.g. ReSharper, Visual Studio Test Explorer)

**Comment by slluis** [comment]
I have the same question. Where is the .addins file supposed to be located? I haven't been able to make the adapter load add-ins.
