### ISSUE TITLE
Test discovery fails when using TestCaseSource in RIDER and VS2017 with Resharper Unit Tests

### ISSUE THREAD

**Issue by nesc58** [nunit/nunit3-vs-adapter#687]
Hi,
Since updating NUnit3TestAdapter to version 3.16.0 the test discovery fails when projects are using the TestCaseSource.

Versions:
* NUnit: 3.12.0
* NUnit3TestAdapter: 3.16.0
* VS2017: 15.9.18
* Resharper: 2019.3.1
* Rider: 2019.3.1
* .Core Version: 2.2.110
* Target Framework: netcoreapp2.2

Test project to reproduce the error: https://github.com/nesc58/nunit-test-project

Is this a bug in NUnit3TestAdapter or is there something wrong in Resharper 2019.3.1?

After downgrading the project to version 3.15.1 everything works fine.
On command line using `dotnet test` everything works fine.

kind regards,
nesc

Test discovery exception:
```
Unfortunately, it's impossible to discover unit tests in some of your projects. :(
Below you can find the error details for each project.

Exception:
Exception occured during exploration.
    System.ArgumentException: Cannot parse testId Tests.Tests.Test1 with displayName Test1(1, 1, 2)
       bei JetBrains.ReSharper.UnitTestProvider.nUnit.v30.DotNetCore.NUnitDotNetCoreTestElementMapper.ParseFqn(Test test)
       bei JetBrains.ReSharper.UnitTestProvider.nUnit.v30.DotNetCore.NUnitDotNetCoreTestElementMapper.Map(Test test, Boolean isDiscovery, Boolean& wasChanged)
       bei JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetVsTest.DotNetVsTestDiscovery.CreateElements(TestCase testCase)
       bei JetBrains.ReSharper.UnitTestFramework.DotNetCore.DotNetVsTest.DotNetVsTestDiscovery.TestsDiscovered(TestCase[] tests)
       bei Appccelerate.StateMachine.Machine.ActionHolders.ArgumentActionHolder`1.Execute(Object argument) in C:\projects\appccelerate\repos\statemachine\source\Appccelerate.StateMachine\Machine\ActionHolders\ArgumentActionHolder.cs:Zeile 50.
       bei Appccelerate.StateMachine.Machine.Transitions.Transition`2.PerformActions(ITransitionContext`2 context) in C:\projects\appccelerate\repos\statemachine\source\Appccelerate.StateMachine\Machine\Transitions\Transition.cs:Zeile 225.```

**Comment by administersoftware** [comment]
Having exactly the same issue, have reverted back to NUnit3TestAdapter 3.15.1

**Comment by OsirisTerje** [comment]
The issue seems to come from a mismatch between how the FullyQualifiedName is being defined in the 3.16 version compared to what Resharper UnitTestProvider expects.  That changed between 3.15.1 and 3.16.  The way it is in 3.15.1 is a bug, which was fixed by [PR 668](https://github.com/nunit/nunit3-vs-adapter/pull/668), and actually fixed a whole series of bugs in the adapter.  The error can be seen in the stack trace above where it says DisplayName doesnt match FQN.  See 668 for an explanation, and also code changes at https://github.com/nunit/nunit3-vs-adapter/commit/78300b4d6201448e2b92a3920fc060c0e5887d39#diff-b7a39ec0f3d5eb92159134f889fdddb3  .   

I'll contact Jetbrains about this issue.

**Comment by OsirisTerje** [comment]
I have created an issue at the jetbrains support system, https://youtrack.jetbrains.com/issue/RSRP-477651

**Comment by OsirisTerje** [comment]
Jetbrains says the fix will be in 2020.1 and 2019.3.2

**Comment by administersoftware** [comment]
> 
> 
> Jetbrains says the fix will be in 2020.1 and 2019.3.2

Thank you @OsirisTerje :)

**Comment by nesc58** [comment]
Thank you.
With the 3.16.1 release the issue is fixed for me. All tests were correctly discovered.
https://github.com/nunit/nunit3-vs-adapter/releases/tag/V3.16.1

**Comment by rlordcardano** [comment]
@nesc58 - I still see differences with combinatorial tests in a solution that multi-targets .NET Core 3.1 and .NET Framework 4.7, using ReSharper 2019.3.1. The .NET Framework 4.7 tests pick up the combinatorial tests correctly, whereas there appear to be less tests listed under .NET Core 3.1.

**Comment by OsirisTerje** [comment]
@rlordcardano Do you see the same with Test Explorer ?

**Comment by rlordcardano** [comment]
Yes - in the problematic project I see the following:

VS test explorer:
* .NET Framework 4.7: 2542 tests
* .NET Core 3.1: 2542 tests

ReSharper:
* .NET Framework 4.7: 2597 tests
* .NET Core 3.1: 2835 tests

**Comment by OsirisTerje** [comment]
The resharper bug although fixed is not out yet, afaik, it may affect some of this.  The difference between .net fw and -net core is very strange.  Are you able to pin this down better, and even create a small repro for it?

**Comment by rlordcardano** [comment]
I have a very small reproduction that shows that the VS test explorer gives a different no. than the ReSharper test runner, also in 3.16.1. Where can I best upload it?

**Comment by OsirisTerje** [comment]
@rlordcardano  1) add it to a gitrepo of your own 2) add it as a zip attachment here

**Comment by rlordcardano** [comment]
Apologies for the delay - see attached:

[NUnitTestSolution.zip](https://github.com/nunit/nunit3-vs-adapter/files/4112076/NUnitTestSolution.zip)

**Comment by rlordcardano** [comment]
Hi @OsirisTerje - should the issue be reopened?

**Comment by OsirisTerje** [comment]
Thanks for the code.  It shows the same however, just in two different ways.
![image](https://user-images.githubusercontent.com/203432/73391368-1a4f5f80-42d8-11ea-8d54-e319520610b2.png)

Resharper shows the similarly named tests as two seperate tests, whereas Test Explorer regards them as half the number of tests, but for each similarly named tests, it reports two results.  This is just the way the two test hosts, Test Explorer and Resharper, chooses to display the results.  The data from the adapter is exactly the same, and all results are reported.

**Comment by rlordcardano** [comment]
@OsirisTerje - thanks for clearing that up!
