### ISSUE TITLE
nUnit doesn't run on Visual Studio 2019

### ISSUE THREAD

**Issue by felipedelta0** [nunit/nunit3-vs-adapter#689]
Hi everyone, I need some help on running tests. I never figured out why this don't work on VS19.

I'm using nUnit 3.12.0 and nUnit3TestAdapter 3.16.0.

I'm studying tests and trying to make a simples test on a sum function, but every time I run the tests, don't matter what I do, the output comes as:
`========== Build: 0 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========`

I've made a .NET Core simples calculator, but it's kinda impossible to run.

Anyone had this problem too?

**Comment by OsirisTerje** [comment]
Suggest you upload a small repro, some screenshots would be nice too. :-)
