### ISSUE TITLE
Update from 3.15.0 to 3.16.0 adds additional items to PackageReference

### ISSUE THREAD

**Issue by jawn** [nunit/nunit3-vs-adapter#695]
## Steps to reproduce
- Open a C# test project that uses NUnit3TestAdapter 3.15.1
- Use Visual Studio > manage nuget packges to check for updates
- Update to 3.16.0

## Expected result
`<PackageReference Include="NUnit3TestAdapter" Version="3.15.1" />`
Is changed to
`<PackageReference Include="NUnit3TestAdapter" Version="3.16.0">`

## Actual result
`<PackageReference Include="NUnit3TestAdapter" Version="3.15.1" />`
Is changed to
```
<PackageReference Include="NUnit3TestAdapter" Version="3.16.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

Versions:
*  NUnit3TestAdapter: 3.16.0
* Visual Visual Studio Enterprise 2019, Version 16.4.2
* .NET Core 3.1

**Comment by OsirisTerje** [comment]
The settings are correct, but will only have meaning if you have another project referencing this one, which is normally not the case for test projects, but may happen.  
Normally you can delete these two lines, but they're not incorrect.
