### ISSUE TITLE
Test case names containing parentheses are grouped before execution but not after

### ISSUE THREAD

**Issue by DaRosenberg** [nunit/nunit3-vs-adapter#696]
NUnit 3.12.0
NUnit3TestAdapter 3.16.0
Microsoft Visual Studio Professional 2019 version 16.4.2
.NET Core 3.1

When creating test cases with explicit `TestName` properties, like this:

```cs
// ...
[TestCase("67DC-FFFB-4803-4D3D", mIntegrationTestProductId, "anything", StatusCodes.Status200OK, null, TestName = "Unlimited (correct)")]
[TestCase("67DC-FFFB-4803-4D3D", mIntegrationTestWrongProductId, "anything", StatusCodes.Status404NotFound, LicenseVerificationError.UnknownLicenseKey, TestName = "Unlimited (wrong product)")]
[TestCase("AB13-D3B4-1234-54A8", mIntegrationTestProductId, "anything", StatusCodes.Status404NotFound, LicenseVerificationError.UnknownLicenseKey, TestName = "Non-existent license key")]
public async Task VerifyTestAsync(string licenseKey, string productId, string domain, int expectedStatusCode, LicenseVerificationError? expectedError)
{
// ...
```

... and the `TestName` values contain parentheses, the tests get grouped in Test Explorer on the part *before* the parenthesized portion. This in itself, while a bit unexpected and arbitrary to me, does at least look like a deliberate feature, and I can understand the rationale.

However, after the tests are executed, this grouping is unwound and the executed tests are moved to a new, flat, ungrouped node in the tree view.

![image](https://user-images.githubusercontent.com/3889090/72146608-1bf2cb00-339d-11ea-9c63-85d21ff9d5ec.png)

I expect the grouping to be consistent before and after executing the tests. The current behavior must be a bug.

**Comment by OsirisTerje** [comment]
Thanks!   This is also a part of the current issues we have matching the TE real time discovery (I assume that is what gives the discovery results, not the adapters discovery), and the execution.

**Comment by OsirisTerje** [comment]
@DaRosenberg I am not able to repro this.  
I copied your code snippet into a project here:  https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/ParametrizedIssue/ParametrizedIssue , and it comes up just fine. I don't see the grouping you have above. 
Discovery:
![1](https://user-images.githubusercontent.com/203432/72204129-dacdea00-3474-11ea-9161-62d9d2d3332f.jpg)
Execution:
![2](https://user-images.githubusercontent.com/203432/72204132-e6211580-3474-11ea-931e-6a8284d0cba7.jpg)


I do however, sometimes see this:
![3](https://user-images.githubusercontent.com/203432/72204136-efaa7d80-3474-11ea-924d-f532857b146b.jpg)

And it seems to be a bug in VS related to caching.  Deleting the .vs folder fixes this.

**Comment by DaRosenberg** [comment]
@OsirisTerje That is bizarre - it repros for me 100%. I did delete the `.vs` folder multiple times while trying to come to grips with it.

Are you using the same versions as me of everything?

**Comment by OsirisTerje** [comment]
Yes,  exactly the same......   
I haven't touched the default grouping in TE though, it is on Project, NameSpace, Class

**Comment by DaRosenberg** [comment]
I have the same grouping. This is so weird.

**Comment by OsirisTerje** [comment]
@DaRosenberg  Did you ever figure this one out ?  Does it still happen?

**Comment by DaRosenberg** [comment]
@OsirisTerje The grouping still happens, yes:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/3889090/81058512-e08d8680-8ece-11ea-81b4-a5ab28c21239.png">

But the *ungrouping* after running the tests no longer happens - not sure which one is the intended behavior?

**Comment by Axemasta** [comment]
I am having this issue passing in the following test cases:
```csharp
static object[] TestCases =
{
    new object[] { "0.0.1", "1", "0.0.1(1)" },
    new object[] { "0.0.1", "120", "0.0.1(120)" },
    new object[] { "0.2.2", "15", "0.2.2(15)" },
    new object[] { "0.2.3", "16", "0.2.3(16)" },
    new object[] { "1.0.0", "25", "1.0.0(25)" }
};
```

When I pass in any string with parentheses it sorts the tests incorrectly in my IDE.

Expected sorting:
![Expectation image](https://user-images.githubusercontent.com/33064621/105490332-8460d180-5cac-11eb-93d0-c6df4f8dd9de.png)

Actual sorting:
![Reality image](https://user-images.githubusercontent.com/33064621/105490560-dc97d380-5cac-11eb-9645-50d686b3c7ea.png)

As you can see its not respecting the namespace sorting at all, I've hacked around this (as you can see in the expected image) by using `&lt;` & `&gt;` characters and replacing them inline in the test with parantheses which solves the problem in a hacky way  😖

**Comment by OsirisTerje** [comment]
@Axemasta This is happening in the Test Explorer, and not the adapter.  Have you looked at this issue https://github.com/Microsoft/vstest/issues/1425

**Comment by Axemasta** [comment]
@OsirisTerje thanks, i wasnt quite sure where the issue lied and this appeared in my searching. Thanks I'll checkout the issue 😁
