### ISSUE TITLE
Test adapter props files should not add assemblies to Content ItemGroup

### ISSUE THREAD

**Issue by bording** [nunit/nunit3-vs-adapter#697]
The two props files that get embedded in the test adapter package to copy the assemblies to the output directory add those items as `Content` items. 

https://github.com/nunit/nunit3-vs-adapter/blob/master/nuget/net35/NUnit3TestAdapter.props

https://github.com/nunit/nunit3-vs-adapter/blob/master/nuget/netcoreapp2.1/NUnit3TestAdapter.props

This has the unfortunate side effect of these files being included in any package that is built from a project that references the test adapter package. While it might be unusual to want to package a test project, I do build several source packages to ship the tests, so I'm hitting this problem.

They should be added as `None` items instead to avoid the problem. This will still get the files copied to the output directory, but `None` items aren't packaged by default.

**Comment by OsirisTerje** [comment]
Thanks!

**Comment by OsirisTerje** [comment]
@andreasohlund @bording  Beta released on Nuget, see https://www.nuget.org/packages/NUnit3TestAdapter/3.17.0-beta.1 . Please check that it works :-)
