### ISSUE TITLE
Test discovery does not appear to be correct when test cases contain arrays of tuples

### ISSUE THREAD

**Issue by paynecrl97** [nunit/nunit3-vs-adapter#710]
Take this test:
```
[TestCaseSource("MyTestCases")]
public void MyTest(string path, (string type, string name)[] expectedResults)
{
}

static object[] MyTestCases =
{
	// Folders
	new object[] { "pathA", new[] { (type: "TypeA", name: "A") } },
	new object[] { "pathB", new[] { (type: "TypeA", name: "A"), (type: "TypeB", name: "B") } },
};
```

This is how the Test Explorer in VS 2019 displays the test:

![image](https://user-images.githubusercontent.com/2872984/68610250-3c8ec980-04af-11ea-9e1f-92e057e2a467.png)

I'd expect there to be a line with the text `MyTest (2)`, and under that I'd expect to see the two test cases. In this state, the test runner fails if you try and run all the tests in the class: `An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Error: Missing '('. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.`

Now, change the test cases so that the arrays are now the same length:

```
[TestCaseSource("MyTestCases")]
public void MyTest(string path, (string type, string name)[] expectedResults)
{
}

static object[] MyTestCases =
{
	// Folders
	new object[] { "pathA", new[] { (type: "TypeA", name: "A") } },
	new object[] { "pathB", new[] { (type: "TypeB", name: "B") } },
};
```

This is better, but still not correct:
![image](https://user-images.githubusercontent.com/2872984/68610431-a27b5100-04af-11ea-9b06-8bfa3c98e193.png)

Note that the tests are nested as expected, but the name of the test is `MyTest]) (2)` - the test name is suffixed with `])`. It is now possible to run all the tests in the class (because the tuple arrays are all the same length).

**Comment by mikkelbu** [comment]
@paynecrl97 I've moved the issue to the adapter project. Most of the issues described have been solved by the last releases of the adapter. The only thing remaining as far as I can tell is that the name in the last case is still `MyTest]) (2)`.

**Comment by OsirisTerje** [comment]
![image](https://user-images.githubusercontent.com/203432/72755274-64df2680-3bca-11ea-9952-af90b528cb0d.png)

This is what I see when running the tests above.  What do you mean is wrong?

PS:  Have you deleted all old stuff? (meaning. deleted the .vs folder and done a Clean)
