### ISSUE TITLE
The master branch allows pushes

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit3-vs-adapter#713]
@OsirisTerje I clicked the wrong link in Team Explorer and pushed from my new `linux_ci` branch directly onto master: https://github.com/nunit/nunit3-vs-adapter/commit/9e78f779a492a344d5c6a8df1ccc1717f4161abc

**Comment by jnm2** [comment]
I didn't have a quick followup to fix CI, so I reverted: https://github.com/nunit/nunit3-vs-adapter/commit/68627dc12e53550ef0075745a72f05e28a25885f

**Comment by OsirisTerje** [comment]
You're an admin, so that's why.  Turned on protection also for admins now.

**Comment by jnm2** [comment]
Thanks. I don't see a settings tab for this repo which is something I would have expected an admin to have.

**Comment by OsirisTerje** [comment]
Weird, I see no difference between you and me there.

**Comment by ChrisMaddock** [comment]
Hey Terje - can I ask what you changed to sort this? The console has the same issue here, but I'm a little confused what I need to change to sort it - and don't want to prevent anyone from merging to master!

Thanks. 🙂 (Also, I'm looking at your email re: engine extensions up next!)

**Comment by OsirisTerje** [comment]
First:
![image](https://user-images.githubusercontent.com/203432/73615692-931d2700-460a-11ea-85c9-689aa7dc926b.png)
Then:
![image](https://user-images.githubusercontent.com/203432/73615699-a7f9ba80-460a-11ea-817a-3587cc6acb89.png)

**Comment by ChrisMaddock** [comment]
Great - thanks!
