### ISSUE TITLE
"Where" Test Selection Language not working as expected

### ISSUE THREAD

**Issue by alexschwantes** [nunit/nunit3-vs-adapter#72]
I'm having some issues with the NUnit.Console.3.0.0-rc using the "where" test selection language as defined here https://github.com/nunit/nunit/wiki/Test-Selection-Language

## This works:
Selecting only a category works: --where=cat==Dev

### Excluding a category
--where=cat!=Dev. When at least one test has the category Dev, The result is that it doesn't find any tests to run and just completes 'successfully'. I would have expected it to run all tests except those with the Dev category assigned.
--where=cat!=DevDoesntExist. In this case the category DevDoesntExist isn't assigned to any tests and Nunit proceeds to run all the tests.

### Selecting by test, name, class or method
I may be doing this wrong, I'm not sure. I have a namespace of Company which contains a test fixture Sample1 with a test method FilterTest().
I have tried all manner of combinations but all of the following fail with the below exception.
--where=test==Company.Sample1.FilterTest
--where=test==Company.Sample1.FilterTest()
--where=test==Company.Sample1.FilterTest()
--where=name==Sample1
--where=name==Sample1()
--where=class==Company.Sample1
--where=class=~Sample1
--where=method==FilterTest
--where=method=~FilterTest
--where=method=~/.*FilterTest.*/

I have also tried some of the regular expression matches such as 

> packages\NUnit.Console.3.0.0-rc\tools\nunit3-console.exe Company\Company.csproj /config:Australia --where=method==FilterTest
> 
> NUnit Console Runner 3.0.5783
> Copyright (C) 2015 Charlie Poole
> 
> Runtime Environment
>    OS Version: Microsoft Windows NT 6.3.9600.0
>   CLR Version: 4.0.30319.42000
> 
> Test Files
>     Company\Company.csproj
> 
> Test Filters
>     Where: method==FilterTest
> 
> no
> no
> 
> Errors and Failures
> 
> 1) Error : C:\Users\tmpalex\Source\Repos\rubrikk\Company\Company
> .csproj
> Exception has been thrown by the target of an invocation.
> 
> Server stack trace:
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
>  Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, B
> inder binder, Object[] parameters, CultureInfo culture)
>    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder bin
> der, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCra
> wlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binde
> r binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
>    at System.Activator.CreateInstance(String assemblyString, String typeName, Bo
> olean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, Cultur
> eInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlM
> ark& stackMark)
>    at System.Activator.CreateInstance(String assemblyName, String typeName, Bool
> ean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureI
> nfo culture, Object[] activationAttributes, Evidence securityInfo)
>    at System.AppDomain.CreateInstance(String assemblyName, String typeName, Bool
> ean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureI
> nfo culture, Object[] activationAttributes, Evidence securityAttributes)
>    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeN
> ame, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args,
>  CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes
> )
>    at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeN
> ame, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args,
>  CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes
> )
>    at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(ITestEventListener listener
> , String filter)
>    at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener
> , TestFilter filter)
>    at NUnit.Engine.Runners.AbstractTestRunner.Run(ITestEventListener listener, T
> estFilter filter)
>    at NUnit.Engine.Agents.RemoteTestAgent.Run(ITestEventListener listener, TestF
> ilter filter)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(
> IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMes
> sage msg)
> 
> Exception rethrown at [0]:
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage req
> Msg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgDa
> ta, Int32 type)
>    at NUnit.Engine.ITestEngineRunner.Run(ITestEventListener listener, TestFilter
>  filter)
>    at NUnit.Engine.Runners.ProcessRunner.RunTests(ITestEventListener listener, T
> estFilter filter)
> 
> Test Run Summary
>     Overall result: Failed
>    Tests run: 0, Passed: 0, Errors: 0, Failures: 0, Inconclusive: 0
>      Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
>   Start time: 2015-11-11 10:01:34Z
>     End time: 2015-11-11 10:01:34Z
>     Duration: 0.012 seconds
> 
> Results (nunit3) saved as TestResult.xml

**Comment by CharliePoole** [comment]
This is not an NUnit 3 Adapter issue. Let's talk about the problems and then you can refile any issues against the NUnit project.

If cat!=Dev is not running any tests, this may be a regression. We had a similar issue in the past.

The other problems you are having (test, name, method, class) don't seem to have anything to do with --where selection but with a mismatch between the console version and the framework version. In fact, this could also be the cause of your problem with cat.

As explained in the release of RC2, the original RC release should not be used. You need to upgrade all your tests to RC2 and use the RC2 console runner and engine. If any of the problems resurface, then you should file them against the NUnit issue list on github.
