### ISSUE TITLE
InvalidCastException: Unable to cast transparent proxy to type ICallbackEventHandler

### ISSUE THREAD

**Issue by logiclrd** [nunit/nunit3-vs-adapter#722]
I am encountering a strange problem running tests, and I'm not sure whether this is a bug in NUnit (or its test adapter) itself, because it's only happening on one workstation -- but I'm not sure what to check next.

I have two different machines, both with Visual Studio 2019 Preview fully-updated (version 16.5.0 Preview 2.0, with .NET Core 3.1.200-preview-014883 installed), and a solution with various test projects, including some newer .NET Core test projects targeting .NET Core 3.1. The exact same files work on one machine, but fail on another. I'm not aware of any odd configurations or customizations on either machine related to Visual Studio or NUnit or the testing framework. On the machine where they fail, I get the following error report in the Tests output:

```
NUnit Adapter 3.11.0.0: Test execution started
Running selected tests in (path to DLL file)
Exception NUnit.Engine.NUnitEngineException,    Exception thrown executing tests in (path to DLL file)
The NUnit 3 driver encountered an error while executing reflected code.
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(String testAssemblyPath, IDictionary`2 settings)
   at NUnit.Engine.Runners.DirectTestRunner.LoadDriver(IFrameworkDriver driver, String testFile, TestPackage subPackage)
   at NUnit.Engine.Runners.DirectTestRunner.LoadPackage()
   at NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, TestFilter filter) in D:\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 234
Innerexception: System.InvalidCastException: Unable to cast transparent proxy to type 'System.Web.UI.ICallbackEventHandler'.
   at NUnit.Framework.Api.FrameworkController.LoadTestsAction..ctor(FrameworkController controller, Object handler)
NUnit Adapter 3.11.0.0: Test execution complete
```

I have tried using the most recent adapter release as well and get identical output: It works on one system, and not on the other.

If this is a configuration issue, what should I be looking for on the machine where it isn't working?

**Comment by OsirisTerje** [comment]
Can you repro the issue with another smaller test projects?  Or does it just fail in your particular project?

Have you turned off all parallellism ?

**Comment by logiclrd** [comment]
I just tried to pare it down to a minimal reproduction and bumped into something really weird. I started by cloning my local repository into a temporary directory, and then repeatedly removing some features and then rerunning the tests. Every time I removed some features and reproduced the problem, I did a new git commit. Then, after 10 changes each with a commit to lock in that state of the repository, I finally removed a project and the tests passed -- so I reverted the changes back to the most recent commit, and the tests still passed. I proceeded to walk back up the chain of commits, repeatedly running `git checkout HEAD~`, and the tests succeeded each time, even back to the initial state I started with. But, I went back to my original repository, prior to any changes, reran the tests, and the problem persists. Clearly, then, whatever the exact cause is, it isn't contingent on the state of the files in the repository.

To summarize, the following describes the operations I did:

    # origrepo: Contains my projects in which two test projects refuse to run at all with the error decribed in the original post.
    git clone origrepo testrepo
    cd testrepo
    # Run tests in testrepo: problem still happening
    for (i=0; i < 10; i++)
    {
        rm -r ...
        # Update code to get it back into a building state
        # Rerun tests -- problem persists
        git commit -am "fail"
    }

    # Then, finally:
    rm -r ...
    # Update code to get it back into a building state
    # Rerun tests -- problem is gone! Tests run as pass.

    # So, now check sanity by reverting the changes and trying again
    git reset --hard
    # Rerun tests -- problem is _still_ gone (?)

    # Hmm, okay, try previous states
    for (i=0; i < 10; i++)
    {
        git checkout HEAD~
        # Rerun tests -- problem is _still_ gone (?!)
    }

    # Now the source code in testrepo is back to the same commit origrepo is on -- but the tests are running correctly in testrepo
    cd ../origrepo
    # Rerun the tests -- problem is still happening
        
I will diff my two working copies, which should at this point be identical. Something _must_ be different...

**Comment by logiclrd** [comment]
I am very confused by what I have observed. I diffed the two repositories and found the following differences:

* Files in `.git` -- this I ignored.
* `.vs/solutionname/config/applicationhost.config` -- I tried copying this from `origrepo` to `testrepo`, no effect.
* `.vs/solutionname/DesignTimeBuild/.dtbcache.v2` -- I tried copying this from `origrepo` to `testrepo`, no effect.
* `.vs/solutionname/v16/TestStore/0/000-0000.testlog` and `testlog.manifest` -- I tried copying this from `origrepo` to `testrepo`, and then when Visual Studio was launched in `testrepo`, it initially showed the most recent test run results from `origrepo`, i.e. with the .NET Core tests skipped because of the test discovery failure, but the actual test run worked just fine.
* `.dbmdl` and `.jfm` files in SQL Server database projects. I ignored these files.

I initially ignored this file:

* `.vs/solutionname/v16/.suo`

But, it was the last one left after I'd tried everything else, and when I copied it from `origrepo` to `testrepo`, `testrepo` started having the test failures. I find this exceedingly odd!

So then I removed the file from `origrepo` to make it regenerate it, but it was still exhibiting test failures.

So, finally, I copied the `.suo` file that `testrepo` had had back into `origrepo`, and lo and behold, the tests are working properly. Halfway through the test run, Visual Studio suddenly decided that my product license was invalid. "Check for an updated license" did not work, but after a restart, it _seems_ to be back on track?

This has been the most bizarre evening ever.

**Comment by OsirisTerje** [comment]
It does happen that VS gets out of track with its caches.  You might have gotten into that situation.  The files you refer to (outside .git folder) are cache files.  The best thing is to make sure you clean this out after each major change, or when things go bad.  Doing a 
```
git clean -xdf
```
should do the trick.  VS should be closed when this is being done.

**Comment by logiclrd** [comment]
Fair enough. I suppose there's really not much use for the .suo file in question, as I assume its format and usage by Visual Studio will be opaque to anybody not on the Visual Studio team at Microsoft :-P Thanks for your time :-)
