### ISSUE TITLE
NUnit Adapter Update 3.0.6.0 throws System.ArgumentException

### ISSUE THREAD

**Issue by drkthng** [nunit/nunit3-vs-adapter#73]
I use Microsoft Visual Studio Community Edition and have NUnit Adapter 3 installed via `Tools/Extensions and Updates` with automatic Updates.

Until today I had no problems executing my tests from within the studio.

Since this morning (CTP6 was automatically installed) I get this Result for every test I'm trying to run:

```
------ Run test started ------
NUnit Adapter 3.0.6.0 executing tests is started
Running selected tests in D:\[...].UITests.UITests.dll
Loading tests from D:\[...].UITests.UITests.dll
Exception System.ArgumentException, Exception thrown executing tests in D:\[...].UITests.UITests\bin\Debug\[...].UITests.UITests.dll
Invalid filter element: test
Parametername: xmlNode
NUnit Adapter 3.0.6.0 executing tests is finished
========== Run test finished: 0 run (0:00:00,9950569) ==========
```

**Comment by appel1** [comment]
You need to update NUnit3 to RC2.

**Comment by rprouse** [comment]
I believe it is because you need to upgrade NUnit in your tests to the
latest RC 2. The API changed in the betas.

**Comment by drkthng** [comment]
Ohhh thanks sooo much guys! This helped. 
Actually I just saw that there was a comment under "Features" in the Release notes regarding usage of RC2, I just didn't see it as a "call for action".
Great support! Thanks!
