### ISSUE TITLE
TRX report is missing test result for a test that timed out

### ISSUE THREAD

**Issue by provegard** [nunit/nunit3-vs-adapter#731]
* NUnit: 3.12.0
* NUnit3TestAdapter: 3.16.1
* .NET Core 3.1 (3.1.100)

I have a test that sometimes times out on the build server. This particular test exists in a base class, so there are multiple sub classes that run the test against different types of infrastructure.

When the test times out, the following happens:

* The test does not have a result in the TRX report.
* The console logger shows the test name but not the sub class name.

This means that I have no way of knowing which sub class (and thus infrastructure type) that the test failed in.

The following repo illustrates the problem: https://github.com/provegard/nunit-timeout-bug

Clone it and run `./test.sh`. Check the test report in the `TestResults` directory. There is a `UnitTest` element but no `UnitTestResult` element. If the timeout is removed and the test succeeds, both elements will be present.

**Comment by rprouse** [comment]
This could be related to #726 and fixed by the VSTest team?

**Comment by OsirisTerje** [comment]
@provegard Can you check if you have the same behavior with VS 16.6 ?  It is in Preview 5 now, and #726 should be fixed in Pv 2.

**Comment by provegard** [comment]
@OsirisTerje downloading the preview now...

**Comment by provegard** [comment]
Yes, it works with the new tooling. Both elements are present in the report now. Thank you!
