### ISSUE TITLE
Tests not running with dotnet test

### ISSUE THREAD

**Issue by souhailelk** [nunit/nunit3-vs-adapter#732]
* NUnit version : 3.11.0
* Nunit3TestAdapter version : 3.16.1
* .NET version : net48
* Microsoft.Net.Sdk version : 16.4.0

When running tests using the .NET cli command `dotnet test` there are some random tests (resp. test cases) that does not run.

(I have approximativly 7000 tests in my solution).

**Comment by OsirisTerje** [comment]
Can you provide some more information?

The best is if you can provide a repro project.

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".

**Comment by souhailelk** [comment]
I'm not able to replicate the problem into a dummy project because I don't have a lead about what may cause this issue, and in the other hand I can't provide you the original repository.
We are still blocked with this problem, I am available if there is any way to retrieve some usful information about the issue.
Thank you.

**Comment by OsirisTerje** [comment]
We must have something to work on.   You must provide some more information. 

Some tips:

1. Have you checked all log files for any exceptions?   

2. Do you see the tests that are missing in e.g. dump files?  https://github.com/nunit/docs/wiki/Tips-And-Tricks#DumpXmlTestDiscovery-and-DumpXmlTestResults 

3. If you open in Visual Studio proper, do you see all tests there?

4. If you turn up verbosity on runsettings, do you see anything there?

5. What kind of tests are these,  dynamic tests (TEstCase, TestCaseSource) or ordinary Test

and so on...
