### ISSUE TITLE
Visual Studio Test Explorer does not show all test cases

### ISSUE THREAD

**Issue by rjax** [nunit/nunit3-vs-adapter#733]
* NUnit 3.12.0
* NUnit3TestAdapter  3.16.1
* Visual Studio Enterprise 2017, 15.9.21
* repro: https://gist.github.com/rjax/f454faeda2e3f7a655bcee61d2153c61
* .Net Framework 4.7.1

Visual Studio Test Explorer does not list all of the tests when using a TestCaseSource in the form of:
```
 public static IEnumerable ByObject
    {
        get
        {
            yield return new TestCaseData(0m, new DataObject(0m, 0m)).Returns(0m);
            yield return new TestCaseData(0m, new DataObject(1m, 0m)).Returns(0m);
            yield return new TestCaseData(0m, new DataObject(1m, 1m)).Returns(0m);
        }
    }
```
Note that TestCaseData constructor takes two parameters, the first is a value type and is the same for each case. The second is a reference type and has different values. When the parameters are switched to value types or when an additional value type parameter with a unique value is added, the tests are displayed as expected.
```
    public static IEnumerable Explicit
    {
        get
        {
            yield return new TestCaseData(0m, 0m, 0m).Returns(0m);
            yield return new TestCaseData(0m, 1m, 0m).Returns(0m);
            yield return new TestCaseData(0m, 1m, 1m).Returns(0m);
        }
    }
```
or
```    
    public static IEnumerable ByExplicitObject
    {
        get
        {
            yield return new TestCaseData(1, 0m, new DataObject(0m, 0m)).Returns(0m);
            yield return new TestCaseData(2, 0m, new DataObject(1m, 0m)).Returns(0m);
            yield return new TestCaseData(3, 0m, new DataObject(1m, 1m)).Returns(0m);
        }
    }
```
My guess, based on the information in this post on the Microsoft Developer Community forum [NUnit & TestCaseSource, test cases are not recognized](https://developercommunity.visualstudio.com/content/problem/620120/nunit-testcasesource-test-cases-are-not-recognized.html), is that the adapter does not differentiate between the three cases in the first example and reports a single test only to the test explorer. The tests are performed, but they are not listed.

**Comment by rprouse** [comment]
We've also had problems with Visual Studio's real-time discovery parsing tests differently than NUnit does. Have you tried turning off real-time discovery?

![image](https://user-images.githubusercontent.com/493828/78369543-58485880-7593-11ea-8765-82f458f7e8eb.png)

**Comment by OsirisTerje** [comment]
@rjax The information we get from NUnit itself does not contain any parameter information from embedded objects.  That is the reason why it is not displayed. 

@rprouse 
The following attached file is the dump from NUnit.  
Not sure if it is feasible to handle such cases with more complex parameter structures.  


[E_TestCaseSource.dll.dump.txt](https://github.com/nunit/nunit3-vs-adapter/files/4467264/E_TestCaseSource.dll.dump.txt)

**Comment by mikkelbu** [comment]
@OsirisTerje I don't think we should do anything different in the framework, like reflecting after all the properties in the embedded objects (we e.g. don't know if all properties are relevant).

The concrete problem above can be solved in different manners depending on the complexity of `DataObject` and whether it is only used in the tests. One could:
* Add a `ToString` implemementation to `DataObject` that returns the fields as a string
* Using `SetName` on each TestCase (I often use this to give more telling names to the tests rather than a lot of different input)
* If `DataObject` is just used in the tests for wrapping some data, then one could also use `Tuples` or `ValueTuples` instead.

**Comment by OsirisTerje** [comment]
Agree, and one can also add an extra sequential number, like @rjax has done in ByExplicitObject.
