### ISSUE TITLE
TestCaseData: Missing Feature "Jump to File"

### ISSUE THREAD

**Issue by bernd5** [nunit/nunit3-vs-adapter#735]
In my project I have a test which runs my application with around 600 different input files checks the result ... 
I'm really happy that I can use your "TestCaseSource" for this purpose - this is a really great feature!

But there is one thing I really miss. For a "normal Test" you can make a double click in "Visual Studio Test Explorer" and it jumps to the file where the Test is defined. But for a "TestCaseSource-Test" I don't see a way to specify which file should be opened - so currently double clicks are ignored.

Is there a way to achieve that?

**Comment by OsirisTerje** [comment]
Not sure what you mean here.  If you click on the parent or one of the dynamic children, it will jump to the test itself.  
Do you see that is not working ?
If so, what versions are you running?

If you mean you want to jump to the testdata, that information is not really available for use.  What we get is the name of the assembly, class and method.  That is used to look up the location.

**Comment by bernd5** [comment]
If I click on a dynamic test node currently nothing happens which is by default not a bad idea. It is not clear what do in this case.

Now I'd like to specify where the testdata is located (like for non dynamic tests). But I don't see an option to do so.

My setup is a method tagged with `TestCaseSource` which refers to a function that produces `System.IO.FileInfo` objects wrapped into `TestCaseData` objects. The files itself belong to my solution.

````CSharp
[TestCaseSource(nameof(GetTestFiles))]
public void TestHeader(FileInfo file)
{
  //Exec Test for file
  ...
}

public static IEnumerable<TestCaseData> GetTestFiles
{
    get
    {
        var testFiles = Directory.GetFiles(/* ... */);
        foreach (var f in testFiles)
        {
            yield return new TestCaseData(new FileInfo(f))
                .SetName(Path.GetFileNameWithoutExtension(f).Replace(".", "_"))
                .SetDescription($"Description for: {f}")
                .SetCategory(GetCategory(f));

             /* How to setup Jump-File here??? */
        }
    }
}
````

**Comment by OsirisTerje** [comment]
I don't think there is any way the current method of **finding** the correct source code can find your testdata.   It is based on using the class and method name, and then using the MS Diasession to locate the file and line number. 
But, I assume you want to jump to the actual test file in your case, and tt could have been added manually to the TestData, but then it would have to be either a dynamic parameter based on some convention, which the adapter could use to extract it, or it had to be a proper property of that class.  The second option would be the best, but it would require a change to NUnit itself.  I see it could be useful, but it would have to cover more cases than just jumping into a file.
It's a good idea!

**Comment by OsirisTerje** [comment]
@bernd5  I have attached a dev version of the 3.17 adapter that handles this.   In [this repo](https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue735/TestCaseSourceJumpToGivenLocation) I have elaborated on your code above, and added in an extension method that adds two new properties.  The code for using it in the test is shown there, and goes like:
```
public static IEnumerable<TestCaseData> GetTestFiles
        {
            get
            {
                var testFiles = Directory.GetFiles(TestContext.CurrentContext.WorkDirectory,"*.txt");
                foreach (var f in testFiles)
                {
                    var td = new TestCaseData(new FileInfo(f))
                        .SetName(Path.GetFileNameWithoutExtension(f).Replace(".", "_"))
                        .SetDescription($"Description for: {f}")
                        .SetCategory("TextFiles")
                        .SetSourceLocationEx(f);   // This is setting the location
                    yield return td;
  
```
The result is as shown below:

![image](https://user-images.githubusercontent.com/203432/79687569-8642c380-8248-11ea-86c9-98c94f5322ae.png)

The extension method to set these properties is in the same project, and is as:
```
public static class NUnitTestCaseDataExtension
    {
        const string CodeFilePath = "_CodeFilePath";
        const string LineNumber = "_LineNumber";
        public static TestCaseData SetSourceLocationEx(this TestCaseData td,string path,int lineNumber=1)
        {
            td.Properties.Add(CodeFilePath, path);
            td.Properties.Add(LineNumber, lineNumber);
            return td;
        }
    }
```

You can verify this using the version of the adapter enclosed :
[NUnit3TestAdapter.3.17.0-a06.zip](https://github.com/nunit/nunit3-vs-adapter/files/4498930/NUnit3TestAdapter.3.17.0-a06.zip)

**Comment by bernd5** [comment]
Thank you so much, GREAT!!!!
It is exactly what I wanted :-).
