### ISSUE TITLE
An assembly specified in the application dependencies manifest was not found

### ISSUE THREAD

**Issue by eduherminio** [nunit/nunit3-vs-adapter#737]
When upgrading `NUnit3TestAdapter` package to `3.16.1` via Visual Studio in a `.NET Core 3.1` project, it **automatically** adds `PrivateAssets` and `IncludeAssets` like this:
```xml
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

That makes some tests invoked by `dotnet vstest` fail when run inside of a docker container based on [`mcr.microsoft.com/dotnet/core/sdk:3.1.201-bionic`](https://hub.docker.com/_/microsoft-dotnet-core-sdk/).

We've suffered 2 different errors so far, one of them being:

```
Testhost process exited with error: Error:
      An assembly specified in the application dependencies manifest (XXXXXXX.deps.json) was not found:
        package: 'Microsoft.Win32.Registry', version: '4.3.0'
        path: 'runtimes/unix/lib/netstandard1.3/Microsoft.Win32.Registry.dll'
```

The other one, whose logs I don't longer have access to, was also indicating some issue with a dll inside of `lib/netstandardXX`.

We are unable to reproduce this either via VisualStudio or with `dotnet vstest`, just inside of a docker container based on the sdk image.

Removing `PrivateAssets` and `IncludeAssets` was the solution to workaround this issue.

**Comment by OsirisTerje** [comment]
@jnm2 Can you comment on this, please?

**Comment by jnm2** [comment]
PrivateAssets and IncludeAssets are added if you use the .NET SDK to reference a NuGet package that has `developmentDependency="true"` in its .nuspec file.

A development dependency is one that is not used at runtime, only at build time. I suspect that it doesn't make sense for us to be marking the adapter package as such. Do you know of any reason in favor of keeping `developmentDependency="true"`?

**Comment by OsirisTerje** [comment]
Thanks @jnm2 !!  
Actually not.......  I think that was added way back in time, since the adapter is only used during development, but then again, it is only added to the test projects, so it sort of has no additional meaning then.   So we can then just set that to false.

**Comment by OsirisTerje** [comment]
@eduherminio  Beta released on Nuget, see https://www.nuget.org/packages/NUnit3TestAdapter/3.17.0-beta.1 . Please check that it works :-)

**Comment by eduherminio** [comment]
Looks good to me, thanks @OsirisTerje!
