### ISSUE TITLE
NUnit engine IDriverFactory extensions don't load using the adapter

### ISSUE THREAD

**Issue by Caiptain1** [nunit/nunit3-vs-adapter#745]
The currently used NUnit.engine version 3.10.0 in the NUnit3 VS Adapter has a bug with `DriverService` that it is initialized after the `ExtensionService` and the `IDriverFactory` extensions are not being loaded because of that. The latest version 3.11.1 has this fixed. The 3.10.0 version is a year old by this point and it would be nice to upgrade and include it in the next release.
Adapter version - 3.17-alpha

**Comment by aolszowka** [comment]
@OsirisTerje I have a branch where I performed this upgrade; but I am unclear on what exactly the testing procedures are for these changes, before I submit a pull request I'd like to make sure this is OK.

The reason I have this is I am trying to track on the slow running of tests on another issue, my first step was to upgrade the Engine to 3.11.1

**Comment by OsirisTerje** [comment]
Just raise a PR.  You can mark it as WIP, until you are sure it is ready to be merged.
