### ISSUE TITLE
ShadowCopyFiles doesn't work on .NET Framework

### ISSUE THREAD

**Issue by DavidSimner** [nunit/nunit3-vs-adapter#750]
**To reproduce:**
- In a blank directory, run:
- `dotnet new nunit --framework net461`
- `dotnet test -- NUnit.ShadowCopyFiles=true`

**Current behaviour:**
```
Test run for C:\Users\me\example\bin\Debug\net461\example.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 16.6.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Exception System.InvalidCastException,    Exception thrown executing tests in C:\Users\me\example\bin\Debug\net461\example.dll
Specified cast is not valid.
   at NUnit.Engine.TestPackage.GetSetting[T](String name, T defaultSetting)
   at NUnit.Engine.Services.DomainManager.CreateAppDomainSetup(TestPackage package)
   at NUnit.Engine.Services.DomainManager.CreateDomain(TestPackage package)
   at NUnit.Engine.Runners.TestDomainRunner.LoadPackage()
   at NUnit.Engine.Runners.DirectTestRunner.EnsurePackageIsLoaded()
   at NUnit.Engine.Runners.DirectTestRunner.Explore(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Explore(TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 235
No test is available in C:\Users\me\example\bin\Debug\net461\example.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

**Expected behaviour:**
- There is no `InvalidCastException` from the NUnit Engine, and `Test Run Successful` is shown.

**Notes:**
- `nunit` is version `3.12.0`
- `NUnit3TestAdapter` is version `3.15.1`
- `dotnet --info` shows:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Believed root cause**:
I believe that the root cause is that `NUnit3TestAdapter` is passing a `string` according to https://github.com/nunit/nunit3-vs-adapter/blob/f1e496a97459d634ac30d06a6d0a709e17d33a6a/src/NUnitTestAdapter/NUnitTestAdapter.cs#L180
whereas `nunit` is expecting a `bool` according to https://github.com/nunit/nunit-console/blob/d927e8a5eb490fcc230a5adf6a4d864a176c4ff7/src/NUnitEngine/nunit.engine.core/Services/DomainManager.cs#L128

**Possible fix**:
I believe the simplest fix may be to change 1 line in `NUnit3TestAdapter`
from:
`package.Settings[PackageSettings.ShadowCopyFiles] = "true";`
to:
`package.Settings[PackageSettings.ShadowCopyFiles] = true;`

There is another example in this file where a `true` is passed without quotes and making `PackageSettings.ShadowCopyFiles` consistent with it should fix the bug in my opinion: https://github.com/nunit/nunit3-vs-adapter/blob/f1e496a97459d634ac30d06a6d0a709e17d33a6a/src/NUnitTestAdapter/NUnitTestAdapter.cs#L230

**Comment by OsirisTerje** [comment]
Nice find!   Would you give us a PR for this ?

**Comment by DavidSimner** [comment]
> Nice find! Would you give us a PR for this ?

I've created #751 -- can you review it please :)
