### ISSUE TITLE
Allow same name for multiple Tests with "TestCaseData" via User defined "Test-ID"

### ISSUE THREAD

**Issue by bernd5** [nunit/nunit3-vs-adapter#756]
In my application I test several files which might have non unique names, just a unique path.

I would like to use the file name as test name, and the directory-path as category. 

But this results in a strange behaviour in case of duplicates like this:
![grafik](https://user-images.githubusercontent.com/26689688/83804687-cb16a280-a6ae-11ea-82f5-66c9c24ac8af.png)

To reproduce the issue I created / adjusted a simple Testproject:
[Test project](https://github.com/bernd5/NUnit-Nonunique-Test-Names)

It would be greate if I could specify a Test-ID (file path).

**Comment by OsirisTerje** [comment]
Duplicate identical issue here:  https://github.com/nunit/nunit/issues/3574 .

**Comment by OsirisTerje** [comment]
It seems you have a testcasesource, which give you access to TestData.  You can then set whatever you like.  Doesn't that solve your issue?

**Comment by bernd5** [comment]
Sorry for the duplicate.

I produce just "TestCaseData" like in your sample (which I adjusted again).
I don't know what "TestData" is.
The class "TestCaseData" does not seem to have an ID Property / Setter function.

I found this class which adds a prefix to the name (is it used for TestCaseSource, too):
[NUnitTestCaseBuilder.cs](https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Internal/Builders/NUnitTestCaseBuilder.cs#L103)

It would be fine, if you would include the category in the "FullName", too.

[Similar issue](https://github.com/nunit/nunit/issues/3015)

**Comment by bernd5** [comment]
I don't know if you got my issue.

Each test should just get it's own node in Visual Studios TestExplorer. I don't want them grouped together...

**Comment by OsirisTerje** [comment]
That is a behavior in the Test Explorer.  Anything with the same name will be grouped together, and the results shown as in your screenshot above.  That is by MS design.  
What you can do is to set the names to be different, and you can also set categories.  There are methods for that in the TestCaseData (sorry for shortening it above). 
Even if you could, setting the ID will not help.  The tree is organized by fullname for the hierarchy and display name for the nodes.

**Comment by bernd5** [comment]
The thing is that it works as expected, when I use multiple classes (which seem to be added to the FullName).
But if I have duplicates from a single class they are grouped together. Even if the nodes have different categories.
----
So what I want is:
Root
  - CategoryA
  -- TestA
 - CategoryB
 -- TestA
 -- TestB

and not

Root
  - CategoryA
  -- TestA / TestA
 - CategoryB
 -- TestB

**Comment by OsirisTerje** [comment]
This is the Test Explorer "at work" here.  The hierarchy is determined by the fullname, so that probably explains why you see them separate in that case.  When under a single class the fullname keeps them together, and even if you group on category, that is just a visible effect.    You can have a  look at this comment https://github.com/nunit/nunit3-vs-adapter/issues/640#issuecomment-633059425, it explains more in detail how it works.  I  doubt we can manage to change this from the adapter side.  The Id will not do it.

**Comment by bernd5** [comment]
The problem is that the test cases are not grouped by category. It takes actually the category of the last test case with the same name

**Comment by bernd5** [comment]
As a solution it would be okay if I could just use a another text for the class name.

**Comment by OsirisTerje** [comment]
@bernd5 Hi!  Did you find any way around this issue?   I can't see anything we can do from the adapter side, since we can't control the test explorer's display more than on a method level.
