### ISSUE TITLE
Feature Request: Adapter to support NonTestAssemblyAttribute

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit3-vs-adapter#758]
The NUnit Console/Framework have a feature which allows 'NonTestAssemblies' to be excluded from running. See the docs [here](https://github.com/nunit/docs/wiki/NonTestAssembly-Attribute).

The attribute is intended to be used to force-exclude assemblies from a test run, where they may have otherwise been included. Examples of this could be passing a solution file into the NUnit console, or using a wildcard to select test assemblies, and wanting to exclude a certain one.

In my case, we have a mock-assembly in the NUnit Console solution which is intended to have many failing tests. I want to be able to install the adapter into that solution, and then exclude that assembly, so the only tests that are running are those which are intended as actual tests.

It would be a pretty simple feature to add to the adapter, all that would be required is setting an extra TestPackage setting. We'd just need to consider if the adapter also wants to have this default-disabled, and configurable with a runsetting, or on by default. (The former would be consistent with the console's behaviour)

See the console's implementation below:

https://github.com/nunit/nunit-console/blob/226da1565619dbf1ea36a777ce9c239b84f1a7b5/src/NUnitConsole/nunit3-console/ConsoleRunner.cs#L414-L415

What do you think, @OsirisTerje? 🙂 I'm keen on this as it's one of the last blockers for using the adapter in the Console/Engine repo (I think), which would make for a nicer development experience.

**Comment by OsirisTerje** [comment]
This could also solve some annoying test assemblies in the adapter itself.  I am all for it!  

Not even sure if this needs to be runsettings at all.  If an assembly have been annotated this way, is there any reason why anyone would want to run it ?

**Comment by OsirisTerje** [comment]
For VS Test Explorer It works in the way that the assembly is not being tested, but the RTD will still find it.  So it works as intended, but we need to wait for when we get better control of the RTD to get the last part off it.  I'll raise the PR now.

**Comment by OsirisTerje** [comment]
@ChrisMaddock  Pull Request up, waiting for your review:  #758

**Comment by ChrisMaddock** [comment]
Wow - great, thanks Terje!

> Not even sure if this needs to be runsettings at all. If an assembly have been annotated this way, is there any reason why anyone would want to run it ?

I think the concern when it was originally implemented was that someone may add the attribute to an assembly, and then several years later, someone else may struggle to diagnose why the tests weren't running. Personally, I agree with your view - I think that issue could be easily tackled with the right debug messages. 🙂

**Comment by OsirisTerje** [comment]
Yeah, and Settings Verbose = 5 in the runsettings will dump the setting out.
