### ISSUE TITLE
How could I run nunit in CLI with macos

### ISSUE THREAD

**Issue by zhoujiazhi222** [nunit/nunit3-vs-adapter#762]
- The full command line being used
I use dotnet test but get nothing output
<img width="809" alt="Screen Shot 2020-06-19 at 10 08 11 PM" src="https://user-images.githubusercontent.com/20750357/85148440-bb888380-b282-11ea-8119-29a622badb68.png">
- Method of installation (e.g. NuGet, zip, msi)
I using nuget install a lot plugin
<img width="851" alt="Screen Shot 2020-06-19 at 11 14 45 PM" src="https://user-images.githubusercontent.com/20750357/85148426-b592a280-b282-11ea-83a0-21405f7de927.png">
- Version of the NUnit Engine/Console
Nunit （3.12.0） in Rider terminal

**Comment by OsirisTerje** [comment]
@zhoujiazhi222  Try to add the  ```-v n ``` option to the dotnet test command.

**Comment by zhoujiazhi222** [comment]
1.dotnet test -v d
[dotnet-detail.log](https://github.com/nunit/nunit3-vs-adapter/files/4808301/dotnet-detail.log)
2.dotnet test -v diag
[dotnet-diag.log](https://github.com/nunit/nunit3-vs-adapter/files/4808303/dotnet-diag.log)
3. It is my repo csproj , Automatically generated by Unity
[Assembly-CSharp-Editor.csproj.txt](https://github.com/nunit/nunit3-vs-adapter/files/4808306/Assembly-CSharp-Editor.csproj.txt)

**Comment by zhoujiazhi222** [comment]
I can using Rider run test success  but CLI failed
@OsirisTerje 
<img width="762" alt="Screen Shot 2020-06-20 at 10 21 11 PM" src="https://user-images.githubusercontent.com/20750357/85208534-e696d400-b363-11ea-85ee-1b11aa79fcef.png">

**Comment by OsirisTerje** [comment]
If you create a very small standard dotnet test project,  like:

```
dotnet new nunit
dotnet test
```

Does that work ?

**Comment by zhoujiazhi222** [comment]
It seems work
<img width="703" alt="Screen Shot 2020-06-21 at 2 13 18 AM" src="https://user-images.githubusercontent.com/20750357/85208665-cca9c100-b364-11ea-973e-b1e7f9a92b0c.png">

**Comment by OsirisTerje** [comment]
Ok, then your basic infrastructure works, so the fault is then in your project.  Can you create a new project in unity containing **only** a small nunit test, and try to run that one ?

**Comment by zhoujiazhi222** [comment]
unfortunately , it is failed , below is diag log and my new small unity project
[Assembly-CSharp-Editor.csproj.txt](https://github.com/nunit/nunit3-vs-adapter/files/4808382/Assembly-CSharp-Editor.csproj.txt)
[diag.log](https://github.com/nunit/nunit3-vs-adapter/files/4808377/diag.log)

**Comment by OsirisTerje** [comment]
I can't see that test is started at all in that log.  I am not familiar with Unity,  but from the test above it is obvious the error is in the project itself.  So something there is not correctly set up.  

Is this the smallest project you can make?   
From what I can see it has a ton of dependencies.  Try to make a new one, with nothing but a small single test.

**Comment by zhoujiazhi222** [comment]
Yes , this is the smallest project I can make , below is my project 
And I find I must open Unity Application then I can use Rider to run nunit test , If I close Unity Application then Rider can not run nunit test
[nunittest.zip](https://github.com/nunit/nunit3-vs-adapter/files/4808439/nunittest.zip)

**Comment by OsirisTerje** [comment]
As I said, I am not familiar with Unity, but:

The project doesnt build with ``` dotnet build ```
And, one of the errors is that it can't find nunit, so it seems nunit is not included there.  I see it is referring to it from some cache.  Not sure of the syntax for that one, but does the @1.0.0 indicates some version ?  Is this really using NUnit 3 ?
And, I don't see any reference to the NUnit3 test adapter, so that is for sure one thing that is missing.

If   ``` dotnet build ``` doesn't work, then  ``` dotnet test  ``` can not work either, since the latter depends on the first.

But, as I said, I am not familiar with Unity, and not sure how this is supposed to work.

**Comment by zhoujiazhi222** [comment]
ok, dotnet build is work in my computer , maybe unity do not support run standalone now , I will go to ask unity staff，Finally thank you for your help and patient.
