### ISSUE TITLE
Issue running nunit tests inside Visual Studio2019 with newer nunit engine

### ISSUE THREAD

**Issue by winstondz** [nunit/nunit3-vs-adapter#764]
NUnit : 3.12.0
NUnit3Test Adapter : 3.16.1
NUnit Engine : 3.11.1
NUnit Engine Api : 3.11.1
Visual Studio 2019 : 16.6.0

When trying to run tests, I hit the following error : 
An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Could not load file or assembly 'nunit.engine, Version=3.10.0.0, Culture=neutral' or one of its dependencies. The system cannot find the file specified.

---------- Starting test run ----------
An exception occurred while invoking executor 'executor://nunit3testexecutor/': Could not load file or assembly 'nunit.engine, Version=3.10.0.0, Culture=neutral' or one of its dependencies. The system cannot find the file specified.
========== Test run finished: 0 Tests run in 1.6 sec (0 Passed, 0 Failed, 0 Skipped) ==========

Is it looking for the older version of nunit engine(3.10). I am using 3.11.1?

**Comment by winstondz** [comment]
ok. Looking through the issues, I see that I need : Version 3.17.0-beta.2 - June 8, 2020, but this doesnt show up in nuget manager or on the nuget website. Can someone publish this out there?

**Comment by OsirisTerje** [comment]
Try now :-)
