### ISSUE TITLE
NRE at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(INUnitTestEventTestCase resultNode) When Referencing NUnit 3.11

### ISSUE THREAD

**Issue by aolszowka** [nunit/nunit3-vs-adapter#768]
As it says on the tin:

* Have a Project that References NUnit 3.11
* Reference the New NUnit3TestAdapter
* Encounter a stack trace similar to the following:

```text
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestFinished(INUnitTestEventTestCase resultNode) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 169
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 92
```

~~Repro Incoming~~

Repro here https://github.com/nunit/nunit3-vs-adapter.issues/pull/1

**Comment by OsirisTerje** [comment]
Thanks @aolszowka !  

@ChrisMaddock  Is this caused by the upgrade to the new engine ?

**Comment by ChrisMaddock** [comment]
@OsirisTerje I'd be surprised if it was, but it's not impossible.

Those events are created in the framework. It's quite possible that something changed there between v3.11 and latest. Probably worth having a look at what event is actually received from the framework, and how it differs between the two versions? I'd expect the adapter can just ignore any missing information, rather than stop supporting anything before 3.11.

**Comment by ChrisMaddock** [comment]
I was intrigued enough to have more of a dig. 🙂 

I suspect the issue is with the new `TestConverterForXml` - which is why it's just started showing in this version.

`public TestResultSet GetVsTestResults()` has a path that allows TestCaseResult to be null. [The line that's crashing](https://github.com/nunit/nunit3-vs-adapter/blob/master/src/NUnitTestAdapter/NUnitEventListener.cs#L169) in `NUnitEventListener` requires that property not to be null.

I haven't dug any deeper into why it would be null, or not. 🙂

**Comment by OsirisTerje** [comment]
@ChrisMaddock The TestConverterForXml is the old code ........The new code is running with TestConverter

**Comment by OsirisTerje** [comment]
There is a breaking change in the Xml structure received from 3.12 versus 3.11.  In 3.11 a TestSuite can have test cases, but in 3.12 that is not so.
![image](https://user-images.githubusercontent.com/203432/97104910-ad76c380-16b7-11eb-8ed4-341b26aed60e.png)

The xml received  in 3.11 is:
```xml
<test-suite type="Assembly" id="0-1005" name="NRENUnitEventListner_v2.dll" fullname="NRENUnitEventListner_v2.dll"                                                                                           runstate="Runnable" testcasecount="1">
  <test-suite type="TestSuite" id="0-1006" name="NRENUnitEventListner_v2" fullname="NRENUnitEventListner_v2" runstate="Runnable" testcasecount="1">
    <test-suite type="TestSuite" id="0-1007" name="TestNRE" fullname="NRENUnitEventListner_v2.TestNRE" runstate="Runnable" testcasecount="1">
      <test-suite type="TestSuite" id="0-1008" name="SimpleTest" fullname="NRENUnitEventListner_v2.TestNRE.SimpleTest" classname="NRENUnitEventListner_v2.TestNRE" runstate="Runnable" testcasecount="1">
        <test-case id="0-1001" name="SimpleTest()" fullname="NRENUnitEventListner_v2.TestNRE.SimpleTest()" methodname="SimpleTest" classname="NRENUnitEventListner_v2.TestNRE" runstate="Runnable" seed="192546702" />
      </test-suite>
    </test-suite>
  </test-suite>
</test-suite>
```

The structure from 3.12 is:
```xml
<test-suite type="Assembly" id="0-1013" name="NRENUnitEventListner_v2.dll" fullname="d:\repos\NUnit\nunit3-vs-adapter.issues\Issue768\NRENUnitEventListner_v2\bin\Debug\net472\NRENUnitEventListner_v2.dll" runstate="Runnable" testcasecount="1">
  <test-suite type="TestSuite" id="0-1014" name="NRENUnitEventListner_v2" fullname="NRENUnitEventListner_v2" runstate="Runnable" testcasecount="1">
    <test-suite type="TestFixture" id="0-1015" name="TestNRE" fullname="NRENUnitEventListner_v2.TestNRE" runstate="Runnable" testcasecount="1">
      <test-suite type="ParameterizedMethod" id="0-1016" name="SimpleTest" fullname="NRENUnitEventListner_v2.TestNRE.SimpleTest" classname="NRENUnitEventListner_v2.TestNRE" runstate="Runnable" testcasecount="1">
        <test-case id="0-1001" name="SimpleTest()" fullname="NRENUnitEventListner_v2.TestNRE.SimpleTest()" methodname="SimpleTest" classname="NRENUnitEventListner_v2.TestNRE" runstate="Runnable" seed="607480154" />
      </test-suite>
    </test-suite>
  </test-suite>
</test-suite>

```
The repro code to generate this is:
```cs
[TestFixture]
    public class TestNRE
    {
        [TestCase]
        public void SimpleTest()
        {
            Assert.True(true);
        }
    }
```

**How to fix**

You can change the DiscoveryMethod from Current (which is the default) to Legacy in your ```.runsettings``` file:

```xml
    <NUnit>
          <DiscoveryMethod>Legacy</DiscoveryMethod>
    </NUnit>
```
