### ISSUE TITLE
"Not a TestFixture, but TestSuite" error when using un-namespaced SetupFixture

### ISSUE THREAD

**Issue by VoidPtr74** [nunit/nunit3-vs-adapter#770]
Note: only occurs using the 4.0.0-alpha.1 release. 3.17 appears fine.

When using a SetupFixture outside of a namespace, the new DiscoveryConverter doesn't handle the case where a test suite appears inside of the setupfixture node when reading tests from the assembly.

* NUnit and NUnit3TestAdapter versions: NUnit - 3.12.0, NUnit3TestAdapter - 4.0.0-alpha.1
* Repro: https://github.com/nunit/nunit3-vs-adapter.issues/pull/2
* Repro steps: `dotnet test TestLib.sln`
* .net framework or core.

**Comment by OsirisTerje** [comment]
Thanks @VoidPtr74 !    Really appreciate you're reporting this !

**Comment by sloncho** [comment]
It happens even if the SetupFixture is inside a namespace.

**Comment by Bithellio** [comment]
Is there any workaround for this as of yet ?

**Comment by OsirisTerje** [comment]
Should be real soon now.....   just need some more spare time to spend.....

**Comment by OsirisTerje** [comment]
@Bithellio  @sloncho @VoidPtr74  The fix can be found in this package:  https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/4.0.0-dev-01527

Would be very good if you can confirm it.

**Comment by fabsenet** [comment]
had the same issue as @VoidPtr74 and the mentioned package by @OsirisTerje solved it, so even if I am not OP, I can confirm the solution is working! 👍  Thanks for your greak work!
