### ISSUE TITLE
An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by prithvivinayak1** [nunit/nunit3-vs-adapter#771]
Using MS Visual Studio Professional 2015
Visual c# 2015
Nunit version 3.12.0
Nunit3 version 3.16
.Net framework 4.5.2
I opened a solution and it works. Tests are discovered.
I made some changes  to a line of code and rebuild.
I got
An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Object reference not set to an instance of an object.
If i change default processor architecture(Test->Test settings ) from  x86 to x64 or  x64 to x86  it will work once. Same error occurs during the next rebuild

<img width="911" alt="Annotation 2020-07-20 151745" src="https://user-images.githubusercontent.com/68429564/87924746-ebeb5980-ca9c-11ea-9fa3-5dd8ddfaf7e3.png">

> -``

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".

Also, are you using the nuget package or the vsix adapter ?

**Comment by OsirisTerje** [comment]
I can confirm the VSIX is not working for VS2015.

**Comment by felipepessoto** [comment]
It is a known issue. Try to downgrade to https://github.com/nunit/nunit3-vs-adapter/releases/tag/V3.16.1

![image](https://user-images.githubusercontent.com/1336227/93516120-f6409d00-f8ff-11ea-8b44-955dcc2e22d2.png)

**Comment by rmboggs** [comment]
FYI - I'm still running into this issue with VS.NET 2015 and 2017.  Is there going to be a fix released for this soon?

**Comment by OsirisTerje** [comment]
@rmboggs We do not have any repro for this.  It can be related to other issues with VS2015.  Have you checked the 4.0.0-alpha release, and even better the latest dev package ? (See readme.md for link)

**Comment by rmboggs** [comment]
Just tried. Still won't run any tests.

Fyi - I tried on vs.net 2017 v15.6.4. And i can't seem to get version beyond 3.11.2 of the adapter to work properly.

**Comment by OsirisTerje** [comment]
@rmboggs Is this specific to your project or to your machine?   If project - then can you create a small repro ?  Are you using the vsix or the nuget ?

**Comment by shahnawazm786** [comment]
Hello Viewer,
I am getting the following error in visual studio 2013

------ Discover test started ------
An exception occurred while test discoverer 'NUnit3TestDiscoverer' was loading tests. Exception: Object reference not set to an instance of an object.
NUnit VS Adapter 2.3.0.0 discovering tests is started
Assembly contains no NUnit 2 tests:  F:\Applications\NUnit.Tests5\NUnit.Tests5\bin\Debug\NUnit.Tests5.dll
NUnit VS Adapter 2.3.0.0 discovering test is finished
========== Discover test finished: 0 found (0:00:00.3292366) ==========

My code is as follows

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using RestSharp;
using NUnit.Framework;
using Microsoft.VisualStudio.TestTools.UnitTesting;
namespace NUnit.Tests5
{
    [TestFixture]
    class StatusCodeTest
    {
        [TestMethod]
        public void TestCode()
        {
            RestClient clinet = new RestClient("http://api.zippopotam.us");// server name
            RestRequest request = new RestRequest("nl/3825", Method.GET);
            IRestResponse response = clinet.Execute(request);
            NUnit.Framework.Assert.That(response.StatusCode, Is.EqualTo(System.Net.HttpStatusCode.OK));

        }
    }
}

--
Thanks
Mohammad Shahnawaz

**Comment by OsirisTerje** [comment]
@shahnawazm786 You're using the NUnit 2 testadapter.  That will not work with NUnit 3.
