### ISSUE TITLE
dotnet test with --filter FullyQualifiedName!~IntegrationTests not working

### ISSUE THREAD

**Issue by satuday** [nunit/nunit3-vs-adapter#772]
When using dotnet test with `--filter FullyQualifiedName!~IntegrationTests`, for some reason, some test projects fail, my solution has 6 test projects and 2 will fail with this error, but the other test project ran fine. I can run all the test fine using VS19.

But if I use `dotnet test project/xxx.sln --filter FullyQualifiedName!~IntegrationTests`
2 of the test projects will fail with this message.
`An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Error: Invalid Condition 'FullyQualifiedName!~IntegrationTests'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.`

If I change the filter to `--filter FullyQualifiedName!~[any project name]`, the same projects fails.

If I change the filter to  `--filter FullyQualifiedName!=IntegrationTests`, all my tests run, of cause this is expected since I dont have a FullyQualifiedName = IntegrationTests

If I change the filter to `--filter FullyQualifiedName~IntegrationTests`, it also works as expected and only run the test project that contains the name IntegrationTests

If I change the filter to `--filter FullyQualifiedName~[any 1 of the project name that failed from the first filter]`, this works as expected and only that test project is ran and no error.

So it seem the issue happen when using `!~` 

I also tried commenting out all the tests in the failing project and still got the same error.  Any idea what this could be?

* NUnit and NUnit3TestAdapter versions
NUnit: 3.12
NUnit3TestAdapter: 3.17
* What .net platform and version is being targeted
.net core 2.2

**Comment by george-polevoy** [comment]
I have the same issue.
