### ISSUE TITLE
How to pass info output to TFS test output?

### ISSUE THREAD

**Issue by tomwaitforitmy** [nunit/nunit3-vs-adapter#776]
I was wondering what would be the supposed way to pass output containing any "good to know" information to a TFS release pipeline?

Stacktrace, Exceptions, Asserts are all shown in case of an error.
TestContext.AddTestAttachment is super sweet, but for files.

I have tried so far:
```
Debug.WriteLine
Console.WriteLine
TestContext.Out.WriteLine
TestContext.WriteLine 
```
last one -> shown in case of error like this:
![grafik](https://user-images.githubusercontent.com/25305424/88563478-50289300-d032-11ea-82e3-e1bed11010c1.png)

Any suggestions? Or is that feature not implemented by Microsoft TFS? Any documentation giving me background information for this topic would be appreciated. I don't know what this transfer of resources from NUnit to DevOps tools is called and supposed to work. Thanks a lot!

**Comment by OsirisTerje** [comment]
@tomwaitforitmy  Have you tried to use the latest 3.17 version of the adapter?  It outputs more from the console output that earlier version.  Nice if you could check if that could help with this.

**Comment by tomwaitforitmy** [comment]
@OsirisTerje I just checked. We are on NUnit 3.12, NUnit3TestAdapter 3.15.1 and TFS 2017. I will update to 3.17. It would help if you could tell me which output is supposed to appear: Debug.WriteLine, Console.WriteLine or both? Or how can I figure that out myself?

**Comment by OsirisTerje** [comment]
Console.Writeline should appear.  
You can look at the repro for the resolved issue at https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue343B/TestConsoleTests

**Comment by tomwaitforitmy** [comment]
@OsirisTerje Did you see my *edit* part? The output is in the attached .trx test results file but is not shown in TFS web api. Or maybe I am looking at the wrong place? Where is it supposed to appear?

**Comment by OsirisTerje** [comment]
Ahh, sorry.  If you got the output (in e.g. the trx, or really anywhere), you **can** get it displayed, but not necessarily by default.  You don't state where you want it.  It should appear in the build log with 3.17, is that good enough for you?  If you want it displayed otherwise, you need to add your own scripting.
