### ISSUE TITLE
Seemingly redundant dependency on Microsoft.DotNet.InternalAbstractions

### ISSUE THREAD

**Issue by Dmitry-Me** [nunit/nunit3-vs-adapter#785]
As of 3.17.0 there's a dependency on Microsoft.DotNet.InternalAbstractions package in .nuspec but it's unclear how it is useful - I cannot find any code in this codebase which would depend on Microsoft.DotNet.InternalAbstractions.

The problem is Microsoft.DotNet.InternalAbstractions is published in Nuget https://www.nuget.org/packages/Microsoft.DotNet.InternalAbstractions/ without mentioning any license. This causes a great deal of trouble when auditing the codebase which uses code from this codebase in a larger project - the dependency on Microsoft.DotNet.InternalAbstractions raises a lot of red flags because it is "unlicensed" and so this component raises a red flag too because it relies on an "unlicensed" component.

Since it looks like the dependency is redundant it'd be nice if it was removed and a new version of this component was published in Nuget.

**Comment by Dmitry-Me** [comment]
Here's a workaround for some scenarios. Add explicit reference to Microsoft.DotNet.InternalAbstractions and set its "exclude assets" to "all". This way Nuget will not put the dependency into build results.

**Comment by OsirisTerje** [comment]
@Dmitry-Me The package is used by the NUnit.Engine.  I see it is included in the nuspec,  Since the nunit.engine is added as an direct artifact, and not a package, the dependencies of that one is repeated here. 

@rprouse You added this back in 2017.  Comments?

I've sent a mail to the maintainers of the package (MS), and asked about this.

**Comment by jnm2** [comment]
Also see https://github.com/dotnet/sdk/issues/9889

**Comment by jnm2** [comment]
The source lives at https://github.com/dotnet/sdk/tree/master/src/Cli/Microsoft.DotNet.InternalAbstractions, so my first thought is that maybe https://github.com/dotnet/sdk/tree/master/src/Cli/Microsoft.DotNet.InternalAbstractions applies.

**Comment by rprouse** [comment]
It may no longer be needed by the engine. If I remember correctly, it was originally added in the early days of .NET Core to provide features that were missing. @ChrisMaddock have you tried removing the dependency lately? 

That said, why aren't you excluding your tests from your license audit? You don't ship your tests, they are just part of your build pipeline.

**Comment by Dmitry-Me** [comment]
@rprouse  Tests cannot be fully excluded, because copyright covers all types of use, not only distribution. It's fully possible to have a piece of software available for download somewhere which would require a commercial license to be used legally. This is why a piece of software in Nuget gallery having no license specified raises red flags regardless of whether this piece is distributed - having it "used" is enough to raise concerns.

**Comment by Dmitry-Me** [comment]
@OsirisTerje This https://github.com/nunit/nunit-console/blob/0d037ca9d569282c14b798ed6a69b8532fc88a4e/src/NUnitEngine/nunit.engine/Runners/MasterTestRunner.cs#L451 seems to be the only use of `InternalAbstractions` in the entire NUnit.Engine. If this line is reworked then the dependency goes away, doesn't it?

**Comment by Dmitry-Me** [comment]
@OsirisTerje It looks like the dependency in NUnit.Engine only makes sense for .Net Standard 1.6 but it's specified for .Net Core 2.1 in this codebase .nuspec Perhaps this exposes a much broader audience of users than absolutely required to the "no explicit license in Nuget" issue.

**Comment by Dmitry-Me** [comment]
@OsirisTerje Here's what I did. Created a .NET core console application, added NUnit3TestAdapter package into dependencies, and added the following piece of code inside. This does not list `InternalAbstractions`. I guess this does prove that there're no actual dependency and so the dependencies can be removed from .nuspec

        static void Main(string[] args)
        {
            dumpRefs("NUnit3.TestAdapter.dll");
            dumpRefs("nunit.engine.dll");
            dumpRefs("nunit.engine.api.dll");
            dumpRefs("nunit.engine.core.dll");
        }

        static void dumpRefs(string name)
        {
            var assembly = Assembly.LoadFrom(name);
            var deps = assembly.GetReferencedAssemblies();
            foreach (var dep in deps)
                Console.WriteLine(dep.FullName);
        }

**Comment by OsirisTerje** [comment]
@Dmitry-Me Nice !  Do you want to raise a PR ?

**Comment by Dmitry-Me** [comment]
@OsirisTerje I'm not sure I could sign the CLA. The change is basically removing this line from .nuspec https://github.com/nunit/nunit3-vs-adapter/blob/a8d20348242d11495fb9473fc04dea13a1a4b2a1/nuget/NUnit3TestAdapter.nuspec#L30 and that's all.

**Comment by OsirisTerje** [comment]
@Dmitry-Me No problem doing it, but PRs are the way we give people credit later.  You raised the issue, then you deserve the credit for fixing it.   
PS:  Just curious:  The CLA is a standard github thing, what is that prevents you from just signing that one?

**Comment by Dmitry-Me** [comment]
Thank you for taking care of this. Now there's a non-beta release https://github.com/nunit/nunit3-vs-adapter/releases/tag/V4.0.0 where the dependency is removed. It's also published in NuGet.
