### ISSUE TITLE
When using TRX logger, should warn about incompatible test adapter across .NET Framework and .NET Core and/or log where an adapter is located

### ISSUE THREAD

**Issue by mgroetan** [nunit/nunit3-vs-adapter#786]
We are running a suite of tests in an Azure DevOps release pipeline, with the "Visual Studio Test" task, for regression testing.
The pipeline uses a build artifact containing a number of NUnit test projects, using both .NET Framework and .NET Core, respectively.

Recently, we've encountered that the .NET Framework-based tests are not properly discovered, with the following warning:
"_No test is available in D:\a\r1\a\[...]\bin\Release\net461\[...]Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again._"

The problem started for one test project when **another** test project was re-targeted from .NET Framework to .NET Core. The other test project was also run in a different release pipeline task, as we need to run .NET Framework and .NET Core test projects in different runs, to avoid a runtime error concerning "netstandard".

* NUnit and NUnit3TestAdapter versions
  * NUnit: 3.12.0
  * NUnit3TestAdapter: 3.17.0
* Visual Studio edition and full version number (see Help About)
  * VS edition: 2019 Enterprise 16.7.0 (running in Azure DevOps)
* What .net platform and version is being targeted
  * .NET Framework 4.6.1 for some projects and .NET Core 3.1 for others
* If TFS/VSTS issue, what version, hosted, on-premises, and what build task you see this in
  * Azure DevOps hosted agent (Azure Pipelines), with VS2019
  * Build task: Visual Studio Test 2.170.1
* A short repro, preferably attached or pointing to a git repo or gist
  * https://github.com/mgroetan/NUnit3TestAdapterMismatchRepro

**The cause of the problem:**
When the default test adapter path is used, it will point to the root of the artifact directory. Thus, it will start traversing the sub-directories in alphabetical order, and stop whenever it locates the first occurrence of an "NUnit3TestAdapter.dll" file. This test adapter will then be used for the entire test run.
If the first project/sub-directory of the artifact is a .NET Core test project, any .NET Framework-based test projects will be unable to run.
The reason why it started failing for us, was that the re-targeted project happened to be the first project/sub-directory in the artifact.

**Solution:**
As the repro shows, running *with* a TRX logger *and* a custom test adapter path enables both .NET Framework and .NET Core test projects to run, without being afraid of getting a test adapter mismatch.

**What I would like from NUnit3TestAdapter:**
- [ ] Output to the log the path of the located test adapter (this would have helped in debugging the problem)
- [ ] Ideally, output a warning to the log whenever a .NET Core test adapter is attempted used for a .NET Framework test project
- [ ] Ideally, should skip non-compatible test adapters during the search phase

**Comment by mgroetan** [comment]
On a side note: The .NET Core test run was perfectly happy to use the .NET Framework version of the NUnit3TestAdapter, it seeems, probably due to some backward compatibility. Thus, the solution to specify a custom test adapter path for a .NET Core test run is strictly not needed, at least not currently. But I'd recommend it in any case, for readability/consistency.

**Comment by OsirisTerje** [comment]
First, it seems you're running with the vsix based adapter.  The preferred solution is to add the nuget adapter to the test projects, and then there will no issues whatsoever wrt to what framework is being used, and you would not need to set any paths either.   I would really recommend you to do that. 

Second, adding information about which of the variants of the adapter is being run, .net core or .net framework can be done, that is an easy one.   Further, we can add the location too, but I think it should not be on the default verbosity, since it is more of a debugging need.  We can add it a couple of levels up though.

**Comment by mgroetan** [comment]
Thank you for the response, @OsirisTerje. The added logging will come in handy for someone some day, I hope.

As for this, you are not quite right, I'm afraid:

> First, it seems you're running with the vsix based adapter. The preferred solution is to add the nuget adapter to the test projects, and then there will no issues whatsoever wrt to what framework is being used, and you would not need to set any paths either.

As the repro shows, I am using the NuGet package for the test adapter. Are anyone still using the VSIX these days ;-)?
The repro also demonstrates why a custom test adapter path is needed, under which circumstances. I'd be happy to be corrected, though, but I think the repro speaks for itself, as it duplicates the behaviour we're seeing in Azure DevOps.

**Comment by OsirisTerje** [comment]
Sorry, made some assumptions there,  I should have looked a bit closer, and run the repro first  ;-) 

What you do in the repro though is that you set the adapterpath, just like you were using a vsix adapter.  You should **not** set the adapterpath, then it will default to the use the location where the test assembly is located.

I added the loginfo, very useful (thanks!) in this case to show how it works:

It then comes out as:
![image](https://user-images.githubusercontent.com/203432/93382746-dc04b180-f862-11ea-98db-327c3fbb0f19.png)

As you can see the correct adapters are used in all cases.  The one that fails can't display anything, since it is not run. 

If I now remove the adaptersettings in your script:
```cmd
set RunMessage=Running .NET Core tests (without TRX logger)
set CmdToExec=%RunNetCoreTests% 
call :LogAndExecuteCommand "%RunMessage%" "%CmdToExec%"

set RunMessage=Running .NET Framework tests (without TRX logger)
set CmdToExec=%RunNetFrameworkTests% 
call :LogAndExecuteCommand "%RunMessage%" "%CmdToExec%"

set RunMessage=Running .NET Core tests (with TRX logger, simulating a default Azure DevOps test run)
set CmdToExec=%RunNetCoreTests%  /Logger:"trx"
call :LogAndExecuteCommand "%RunMessage%" "%CmdToExec%"

set RunMessage=Running .NET Framework tests (with TRX logger, simulating a default Azure DevOps test run)
set CmdToExec=%RunNetFrameworkTests%  /Logger:"trx"
call :LogAndExecuteCommand "%RunMessage%" "%CmdToExec%"

set RunMessage=Running .NET Core tests (with TRX logger, simulating a default Azure DevOps test run + using a custom test adapter path)
set CmdToExec=%RunNetCoreTests%  /Logger:"trx"
call :LogAndExecuteCommand "%RunMessage%" "%CmdToExec%"

set RunMessage=Running .NET Framework tests (with TRX logger, simulating a default Azure DevOps test run + using a custom test adapter path)
set CmdToExec=%RunNetFrameworkTests%  /Logger:"trx"
call :LogAndExecuteCommand "%RunMessage%" "%CmdToExec%"
```

Running it now runs all tests, and as you can see the adapters are loaded from the correct place:
![image](https://user-images.githubusercontent.com/203432/93382884-1c642f80-f863-11ea-9180-14ff74fe8343.png)

**Comment by mgroetan** [comment]
Thanks for the clarification about the test adapter path. We have also read the same documentation while we were investigating the issue, and took for granted that the "local" test adapter would be used.

**This is our live release pipeline's test task, where we have currently set a custom test adapter path:**
![bilde](https://user-images.githubusercontent.com/9464822/93387254-330d8500-f869-11ea-8ea3-8915fb542bdc.png)

**The log for this type of run:**
2020-09-16T16:26:06.1720182Z Task         : Visual Studio Test
[...]
2020-09-16T16:26:06.1721659Z Version      : 2.170.1
[...]
2020-09-16T16:26:07.9512134Z Test selector : Test assemblies
2020-09-16T16:26:07.9512656Z Test filter criteria : null
2020-09-16T16:26:07.9514454Z Search folder : D:\a\r1\a
2020-09-16T16:26:07.9808697Z Action when minimum tests threshold not met : donothing
2020-09-16T16:26:07.9809229Z Minimum tests expected to be run: 0
2020-09-16T16:26:07.9809996Z VisualStudio version selected for test execution : latest
2020-09-16T16:26:07.9811521Z Attempting to find vstest.console from a visual studio installation with version [16.0,17.0).
2020-09-16T16:26:08.1836883Z Run in parallel : false
2020-09-16T16:26:08.1837567Z Run in isolation : false
**2020-09-16T16:26:08.1838235Z Path to custom adapters : D:\a\r1\a\_OneComputePlatform\integration-tests\src\JobSchedulerIntegrationTests**
2020-09-16T16:26:08.1839576Z Other console options : null
[...]
2020-09-16T16:26:13.6533165Z [command]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@D:\a\_temp\bjhcde5m3cl.tmp"
2020-09-16T16:26:14.1421489Z Microsoft (R) Test Execution Command Line Tool Version 16.7.0
2020-09-16T16:26:14.1424950Z Copyright (c) Microsoft Corporation.  All rights reserved.
2020-09-16T16:26:14.2963604Z vstest.console.exe "D:\a\r1\a\_OneComputePlatform\integration-tests\src\JobSchedulerIntegrationTests\bin\Release\net461\JobSchedulerIntegrationTests.dll"
2020-09-16T16:26:14.2964436Z /Settings:"D:\a\_temp\2dy3auqko0a.tmp.runsettings"
2020-09-16T16:26:14.2964783Z /Logger:"trx"
**2020-09-16T16:26:14.2965079Z /TestAdapterPath:"D:\a\r1\a\_OneComputePlatform\integration-tests\src\JobSchedulerIntegrationTests"**
2020-09-16T16:26:18.0658062Z Starting test execution, please wait...
2020-09-16T16:26:23.5992359Z A total of 1 test files matched the specified pattern.
2020-09-16T16:26:23.8692945Z Blame: Attaching crash dump utility to process testhost.x86 (3552).
**2020-09-16T16:26:25.9417300Z NUnit Adapter 3.17.0.0: Test execution started**
**2020-09-16T16:26:26.1970955Z Running all tests in D:\a\r1\a\_OneComputePlatform\integration-tests\src\JobSchedulerIntegrationTests\bin\Release\net461\JobSchedulerIntegrationTests.dll**
**2020-09-16T16:26:28.5450976Z    NUnit3TestExecutor discovered 7 of 7 NUnit test cases**

**Then I proceed to remove the custom test adapter path, as in our original configuration, before we ran into the problems:**
![bilde](https://user-images.githubusercontent.com/9464822/93387832-1cb3f900-f86a-11ea-80d6-c14cfaf81d81.png)

**The log for this run:**
2020-09-16T20:20:40.5428616Z Task         : Visual Studio Test
[...]
2020-09-16T20:20:40.5430089Z Version      : 2.170.1
[...]
2020-09-16T20:20:42.3305261Z Test selector : Test assemblies
2020-09-16T20:20:42.3305775Z Test filter criteria : null
2020-09-16T20:20:42.3307484Z Search folder : D:\a\r1\a
2020-09-16T20:20:42.3507236Z Action when minimum tests threshold not met : donothing
2020-09-16T20:20:42.3507862Z Minimum tests expected to be run: 0
2020-09-16T20:20:42.3508701Z VisualStudio version selected for test execution : latest
2020-09-16T20:20:42.3510253Z Attempting to find vstest.console from a visual studio installation with version [16.0,17.0).
2020-09-16T20:20:43.0599519Z Run in parallel : false
2020-09-16T20:20:43.0605737Z Run in isolation : false
**2020-09-16T20:20:43.0606848Z Path to custom adapters : null**
2020-09-16T20:20:43.0613180Z Other console options : null
[...]
2020-09-16T20:20:50.0203325Z [command]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@D:\a\_temp\tozsjet11zs.tmp"
2020-09-16T20:20:50.9346519Z Microsoft (R) Test Execution Command Line Tool Version 16.7.0
2020-09-16T20:20:50.9347193Z Copyright (c) Microsoft Corporation.  All rights reserved.
2020-09-16T20:20:50.9966198Z vstest.console.exe "D:\a\r1\a\_OneComputePlatform\integration-tests\src\JobSchedulerIntegrationTests\bin\Release\net461\JobSchedulerIntegrationTests.dll"
2020-09-16T20:20:50.9968035Z /Settings:"D:\a\_temp\qjhdrr50cmk.tmp.runsettings"
2020-09-16T20:20:50.9984858Z /Logger:"trx"
**2020-09-16T20:20:50.9985278Z /TestAdapterPath:"D:\a\r1\a"**
2020-09-16T20:20:55.4007488Z Starting test execution, please wait...
2020-09-16T20:21:12.0067092Z A total of 1 test files matched the specified pattern.
2020-09-16T20:21:12.1124137Z Blame: Attaching crash dump utility to process testhost.x86 (2396).
**2020-09-16T20:21:17.0001863Z No test is available in D:\a\r1\a\_OneComputePlatform\integration-tests\src\JobSchedulerIntegrationTests\bin\Release\net461\JobSchedulerIntegrationTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.**

**Is Azure DevOps pranking us?**
As you can see, in the last run, without any custom test adapter path, it logs **"Path to custom adapters : null"**, but nonetheless proceeds to run with **"/TestAdapterPath:"D:\a\r1\a"**, and thus failing to locate the tests, as per the repro.

Is there anything we can "tick off" (or "on") in the test task to avoid this option being set, even though we don't specify anything?

I don't know for sure whether the old extension is installed in Azure DevOps, and whether that could interfere in any way, but it doesn't seem like the Azure DevOps project has the extension:
![bilde](https://user-images.githubusercontent.com/9464822/93389797-f8a5e700-f86c-11ea-94ba-23b879c44d1e.png)

**Comment by OsirisTerje** [comment]
@mgroetan I tested your repro on AzDoServices, and got into similar problems, not finding the tests properly.  So there is something going on there.  If I use the ```dotnet test``` it will run all .net core test projects without any adapter added.  Didn't have too much time to figure out the vstest options there.  I used the yaml builds btw.  I will reach out to a few people to check their experience with these kind of mixed builds. This is not an adapter issue though, so you could raise an issue on the vstest task github repo (if you do, please link here to it, and backwards :-) ) .
