### ISSUE TITLE
Documentation: Broken links in user guide [vs-test-adapter/Resources.html]

### ISSUE THREAD

**Issue by smitavarghese** [nunit/nunit3-vs-adapter#788]
Steps:
1. Go to https://docs.nunit.org/articles/vs-test-adapter/Resources.html
2. Verify links on the page

Actual:
Clicking these links results in an HTTP 404 error

Details:
<ul>
<li><p><a href="http://blogs.msdn.com/b/visualstudioalm/archive/2012/11/09/how-to-manage-unit-tests-in-visual-studio-2012-update-1-part-1-using-traits-in-the-unit-test-explorer.aspx">Part 1–Using Traits in the Unit Test Explorer</a></p>
</li>
<li><p><a href="http://blogs.msdn.com/b/visualstudioalm/archive/2012/11/20/part-2-using-traits-with-different-test-frameworks-in-the-unit-test-explorer.aspx">Part 2–Using Traits with different test frameworks in the Unit Test Explorer</a></p>
</li>
<li><p><a href="http://blogs.msdn.com/b/visualstudioalm/archive/2013/06/11/part-3-unit-testing-with-traits-and-code-coverage-in-visual-studio-2012-using-the-tfs-build-and-the-new-nuget-adapter-approach.aspx">Part 3: Unit testing with Traits and code coverage in Visual Studio 2012 using the TFS Build</a></p>
</li>
</ul>

**Comment by OsirisTerje** [comment]
@smitavarghese  Thanks!

**Comment by mikkelbu** [comment]
I've made a PR as I needed a simple task to make time pass :)

**Comment by mikkelbu** [comment]
@OsirisTerje please note that the PR did not close this issue, despite the linking
![image](https://user-images.githubusercontent.com/1007631/94183527-d6325000-fea2-11ea-9a10-4b6864ec0930.png)

**Comment by smitavarghese** [comment]
Thank you for the fix.
