### ISSUE TITLE
Tests decorated with TestCaseSource attribute do not expand to individual tests in Test Explorer 

### ISSUE THREAD

**Issue by kdubau** [nunit/nunit3-vs-adapter#79]
Consider the test: 
```csharp
[Test, TestCaseSource(typeof(TestDataFactory), "DotNetTests") ]
public void TestDotNet (Options options)
{
  ...
}
```

This appears as a single test in the Test Explorer. However it should show a test for each item in the `DotNetTests` collection.

Let me know if you need any further information!

**Comment by CharliePoole** [comment]
This duplicates #78. Please feel free to add comments there about how we might deal with it.

**Comment by kdubau** [comment]
Thanks for the quick response. I saw https://github.com/nunit/nunit3-vs-adapter/issues/78 but wasn't sure it was the same.
