### ISSUE TITLE
Result XML file doesn't contain test results

### ISSUE THREAD

**Issue by sauravwcm** [nunit/nunit3-vs-adapter#793]
* NUnit 3.12.0 and NUnit3TestAdapter 3.17.0
 
* Visual Studio 2017 Version 15.9.26

* What .net platform and version is being targeted: .Net Framework 4.5.2

output xml file consists of the following:
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<command-line><![CDATA["C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\PROFESSIONAL\COMMON7\IDE\EXTENSIONS\TESTPLATFORM\Extensions\..//testhost.exe"  --port 50635 --endpoint 127.0.0.1:050635 --role client --parentprocessid 30692 --telemetryoptedin true]]></command-line>

**Comment by OsirisTerje** [comment]
@sauravwcm Is this the same as #780 ?
