### ISSUE TITLE
Resharper unit testing is not compatible with 3.17 and above

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit3-vs-adapter#796]
Reported from Nuget user:

"'NUnit3TestAdapter 4.0.0-alpha.1'.  You may already be aware. I couldn't get this alpha version to play nice with DotCover. In the unit test sessions window, I could not get unit tests to run."

Checking the logs of the resharper test runner, we see the following:

```txt
System.TypeLoadException: Method 'get_AssemblyPath' in type 'NUnit.Engine.Extensibility.ExtensionNode' from assembly 'nunit.engine, Version=3.10.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' does not have an implementation.
System.TypeLoadException: Method 'get_AssemblyPath' in type 'NUnit.Engine.Extensibility.ExtensionNode' from assembly 'nunit.engine, Version=3.10.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' does not have an implementation.
   at NUnit.Engine.Services.ExtensionService..ctor()
   at NUnit.Engine.TestEngine.Initialize()
   at NUnit.Engine.TestEngine.GetRunner(TestPackage package)
   at JetBrains.ReSharper.UnitTestRunner.nUnit30.NUnitRunner.Run(String assembly, IDictionary`2 testParameters) in /Product.Root/Psi.Features/UnitTesting/nUnit/Runner30/Src/NUnitRunner.cs:line 40
   at JetBrains.ReSharper.UnitTestRunner.nUnit30.BuiltInNUnitRunner.WithExtensiveErrorHandling(IRemoteTaskServer server, Action action) in /Product.Root/Psi.Features/UnitTesting/nUnit/Runner30/Src/BuiltInNUnitRunner.cs:line 73
```

This applies to version 3.17.0 as well.  

Both 3.17.0 and 4.0.0-alpha.1 is build on the NUnit.Engine version 3.11, and the resharper log states a mismatch with 3.10.

**Comment by ChrisMaddock** [comment]
This is an engine issue we're aware of, although not yet sure how to fix. 

See https://github.com/nunit/nunit-console/issues/800. Is this an old version of ReSharper? My understanding was that they'd "fixed" this in the latest version by updating the version of the nunit engine that ReSharper relies on.

**Comment by OsirisTerje** [comment]
@ChrisMaddock   Yes, it is from version 2019.3.1.

Trying with version 2020.2.4 (latest right now), it all works as it should, 

![image](https://user-images.githubusercontent.com/203432/97541677-d2c04600-19c5-11eb-887a-8020d286b741.png)

So based on that, the solution is to upgrade to latest Resharper version (at least 2020.2.4).
