### ISSUE TITLE
VS Test explorer doesn't organize test results properly and "go to test" doesn't work

### ISSUE THREAD

**Issue by JGCreator** [nunit/nunit3-vs-adapter#810]
NUnit and NUnit3TestAdapter versions are thus
![image](https://user-images.githubusercontent.com/5280734/102833880-9a2e5e80-43af-11eb-8593-34ac606c389b.png)

VS info:
![image](https://user-images.githubusercontent.com/5280734/102833945-cba72a00-43af-11eb-9af8-7e4fa710ce7f.png)

When using the latest adapter, it seems as though the issue described in #607 (fixed in 3.16) is back.

**Comment by OsirisTerje** [comment]
That bugfix caused other regression errors, and was made optional in 3.16.1, look at the release notes and see more details there, also how to enable it again.

**Comment by OsirisTerje** [comment]
For those who have this issue, you can reenable the 3.16 behaviour by setting the following two runsettings properties to true,
[UseParentFQNForParametrizedTests](https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#useparentfqnforparametrizedtests) and [UseNUnitIdforTestCaseId](https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#usenunitidfortestcaseid).   This issue will hopefully be fully resolved once we get access to the Real Time Discovery source code.
