### ISSUE TITLE
Method using TestCaseSource with SetName are shown in Tests explorer

### ISSUE THREAD

**Issue by Remy-F** [nunit/nunit3-vs-adapter#813]
Hi,

I have several problems with the tests explorer when i'm using testCaseSource with SetName method.
The tests explorer is trying to execute the method whereas the method is taking a list in parameter. So it does not work.

Exemple my test : 
![image](https://user-images.githubusercontent.com/44093500/105715239-a4e39280-5f1d-11eb-9069-fa417f12d10f.png)

Tests explorer : 
![image](https://user-images.githubusercontent.com/44093500/105714182-52ee3d00-5f1c-11eb-8af0-cb866322462f.png)

"MyMethodTest" stay in "no executed test" tab.

I'am using : 
NUnit v3.13.0
Nunit3TestAdapter : v3.17.0
VS 2019 16.8.4
.net 5 (but it's same with .net 3)

**Comment by OsirisTerje** [comment]
Thanks!  Can you please check if this is the same as https://github.com/nunit/nunit3-vs-adapter/issues/721 ?
