### ISSUE TITLE
Test explorer's copy details option add namespace twice in the full test fullname

### ISSUE THREAD

**Issue by ashishdawale20** [nunit/nunit3-vs-adapter#814]
Visual Studio:  Visual Studio Professional 2019 
VS version: 16.8.2
VS Extension: NUnit 3 Test Adapter 3.17.0
```
namespace ConsoleApp5.tests
{
    public class Class1
    {
        [Test]
        public void Test1()
        {

        }
    }
}

```

Test explorer shows the tests as below:
![image](https://user-images.githubusercontent.com/43884208/106131248-774e5180-6188-11eb-9ade-e9f961001d12.png)

When I click on "copy details" I get the below content: 

Test Name:	Test1
Test FullName:	***ConsoleApp5.tests.ConsoleApp5.tests.Class1.Test1***
Test Source:	C:\Users\ade18\Source\Repos\ConsoleApp5\ConsoleApp5.tests\Class1.cs : line 13
Test Outcome:	Not Run
Test Duration:	0:00:00

**Take a look at TestFullName:** The namespace is appearing twice in the name.

***Note:*** This issue is only in the VS 2019 and it is working fine with the VS 2017 and lower version.

**Comment by OsirisTerje** [comment]
@kendrahavens This looks like a Test Explorer bug
@ashishdawale20 Suggest you post this on the DeveloperComminity site.  Use the Report a Problem in VS for this: 
![image](https://user-images.githubusercontent.com/203432/106305863-85ba6d00-625d-11eb-80d1-4df90f648853.png)

**Comment by YugandharaDawale** [comment]
https://developercommunity2.visualstudio.com/t/test-explorers-copy-details-option-adds-namespace/1326000?from=email
Reported it to the VS team.

**Comment by ashishdawale20** [comment]
https://developercommunity2.visualstudio.com/t/test-explorers-copy-details-option-adds-namespace/1326000?from=email
Reported it the VS team

**Comment by OsirisTerje** [comment]
Seems to have been fixed in later VS versions.
