### ISSUE TITLE
Cannot run separate tests using NUnit3.0

### ISSUE THREAD

**Issue by besteffects** [nunit/nunit3-vs-adapter#82]
Conditions: Win10, VS2015, TestAdapter 3.0.7.0
After update to NUnit 3.0 I cannot run or debug tests separately. Only if I use "Run all" option. 

![cannot run separate tests](https://cloud.githubusercontent.com/assets/14294615/11298830/81f6714c-8f8a-11e5-99a8-28d7bdc4e445.jpg)

**Comment by appel1** [comment]
What version of the test adapter do you have installed?

**Comment by besteffects** [comment]
3.0.7.0
I forgot to mention that I use tests with Selenium WebDriver

**Comment by rprouse** [comment]
I am using the adapter to run individual tests, but we haven't tested
selenium. Is there anything else special about your tests that may be
causing this? We need to reproduce to fix it. Any chance you can create a
minimal test solution to demonstrate?

**Comment by besteffects** [comment]
Ok, I have created a separate very simple project with new NUnit 3.0 and Selenium 2.48.2. Everything works as expected. However, my current project still has the same problem.
I think you can close this issue because currently I am not able to provide you with more details about it.
I will try to resolve my problem and will inform you if there will be details that will need your attention.
Thank you.

**Comment by rprouse** [comment]
Thanks, please report back what you find. It may be a bug in the adapter exposed by some odd combination in your tests. To track it down, I would try bisecting your tests to find the one that is causing problems.

- Unload half of your test projects (if you have more than 1), see if it still happens. If so, unload half remaining and try again until you find the test assembly that is causing problems.
- Once you have the test assembly, comment out half your tests and continue until you narrow in on the problem.

Or something like that. Good luck. :smile:

**Comment by besteffects** [comment]
Ok. Thanks.
My Test class is inherited from base a class, where following NUnit options
exist: [OneTimeSetUp],  [OneTimeTearDown], [TearDown],
[TestFixture(typeof(FirefoxDriver))],
After the update I have changed TestFixtureSetUp], and
[TestFixtureTearDown] to [OneTimeSetUp] and  [OneTimeTearDown] accordingly.
I have tried to disable all tests one by one, but it did not help to find
the solution.

**Comment by besteffects** [comment]
Now I have rolled back to NUnit 2.6.4 and to relevant Test Adapter. Every test can be run separately. I will wait till someone else will discover this bug, because I cannot find out what is the reason, yet.
