### ISSUE TITLE
CI with Gitlab runner and .NET5.0 failed with no informations

### ISSUE THREAD

**Issue by xas** [nunit/nunit3-vs-adapter#820]
OK, I am trying to use a CI process with a hosted gitlab repos.

I have created a simple .NET Core v3.1 test project with this simple test :
```
public class Tests
{
    [Test]
    public void Test1()
    {
        Assert.That(true, Is.True);
    }
}
```

My csproj contains the packages :
```
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.1" />
  </ItemGroup>
```

On local command line (Win10 + latest .NET v5.200) everything is successful

Now, I am using a shared gitlab runner (a linux docker) with a simple yaml file, with verbosity enabled :
```
image: mcr.microsoft.com/dotnet/sdk:latest

stages:
    - test

test:
    stage: test
    script: 
        - dotnet test tests/ProjectFile.csproj -v d
```
and the test _failed successfully_ 😅 
```
Using "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task from assembly "/usr/share/dotnet/sdk/5.0.200/Microsoft.TestPlatform.Build.dll".
       Task "Microsoft.TestPlatform.Build.Tasks.VSTestTask"
Microsoft (R) Test Execution Command Line Tool Version 16.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: . Please check the diagnostic logs for more information.
Test Run Aborted.
       Done executing task "Microsoft.TestPlatform.Build.Tasks.VSTestTask" -- FAILED.
   1:7>Done building target "VSTest" in project "FileProject.csproj" -- FAILED.
   1:7>Done Building Project "/builds/xxx/xxx/tests/FileProject.csproj" (VSTest target(s)) -- FAILED.
Build FAILED.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:01:57.79
```

I can see I am missing the line `NUnit Adapter 3.17.0.0: Test execution started`

I did a lot of try and at the end my last idea was to use the 3.1 version instead of the v5.200 : `image: mcr.microsoft.com/dotnet/sdk:3.1`

And everything worked.

I don't know if it's an adapter issue or Microsoft related and no exception information `Testhost process exited with error: .`
I can't use the flag _-v diag_ as it produces too much data (the gitlab log is size limited and I can't change it)

It's strange as I didn't found any informations on the net about this kind of issue, so maybe I missed some settings on the csproj file ?

**Comment by mikkelbu** [comment]
5.0.200 corresponds to Visual Studio 16.9, so perhaps something have changed in vsTest in this release?

**Comment by xas** [comment]
I am not sure, as I said it worked on local with .net 5.0.200

**Comment by OsirisTerje** [comment]
Did you raise an issue with the GitLab people?  This looks like something on their system ?   This works on Linux local, as you also mentioned, so must be something with the Gitlab CI:
