### ISSUE TITLE
dotnet test not working for net35

### ISSUE THREAD

**Issue by andygonzalez2010** [nunit/nunit3-vs-adapter#822]
Steps to reproduce:

```
dotnet new -i NUnit3.DotNetNew.Template
dotnet new nunit -n CSharpNet35  --framework net35 -lang c#
msbuild /p:FrameworkPathOverride="%programfiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client" CSharpNet35
dotnet test CSharpNet35 --no-build
```
It runs without errors but it shows nothing in the cmd (it should show the test results).

**Comment by OsirisTerje** [comment]
This error is in the vstest system, see issues  https://github.com/microsoft/vstest/issues/2763 and https://github.com/microsoft/vstest/issues/1850.   Please help with voting 2763 up. 

To get it to work, add the following property 
```xml
<IsTestProject>true</IsTestProject>
```

Also use the ```-v n ``` option when running the tests to see any actual output.
