### ISSUE TITLE
"Not a TestFixture or TestSuite, but SetUpFixture" exception is being thrown in case of more than one [SetUpFixture]

### ISSUE THREAD

**Issue by shupoval** [nunit/nunit3-vs-adapter#824]
When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions - **4.0.0-beta.1**
* Visual Studio edition and full version number (see Help About) - **Microsoft Visual Studio Professional 2019 Version 16.9.2**
* A short repro, preferably attached or pointing to a git repo or gist - **https://github.com/nunit/nunit3-vs-adapter.issues/pull/3**
* What .net platform and version is being targeted - **.net 5**

Please note, that it works perfectly well on **NUnit3TestAdapter 3.17.0**

**Comment by OsirisTerje** [comment]
Thanks for reporting this, and thanks for a well done repro :-)
