### ISSUE TITLE
While running test using Nunittestadapter 3.17 not able to see output in testoutput.xml file using runsettings

### ISSUE THREAD

**Issue by gnaneswarreddy** [nunit/nunit3-vs-adapter#825]
When reporting a bug, please provide the following information to speed up triage:

NunitTestAdapter 3.17, Nunit 3.13.1
VS 2019
.net 4.7

ConsoleOuput not getting displayed in the xml output file while my test would be running in the selenium grid but console output is being seeing on the test explorer window but not in xml file.

<?xml version='1.0" encoding="utf-8"?>
<RunSettings>
<Nunit>
<TestOuputXml> C:\Result</TestOutputXml>
<ConsoleOut>1<ConsoleOut>
</Nunit>
</RunSettings>

In the xml file i am getting 

<command-line><![CDATA path to testhostx86.exe --port --telemetryoptedin true></command-line>

I want to see the console output in the xml file.

**Comment by gnaneswarreddy** [comment]
I see this is being fixed in 4.0.0 so closing this issue

**Comment by OsirisTerje** [comment]
I see you use .net4.7.  May I ask you if you're using the sdk csproj format or the legacy one?  And if legacy, do you use package.config or packagereferences ?   The reason is that we will probably remove support for the legacy csproj using package.config files.

**Comment by gnaneswarreddy** [comment]
We are using legacy with packages.config
