### ISSUE TITLE
NuGet library Shouldly will cause "No source available", so that double click on test fails.

### ISSUE THREAD

**Issue by BentTranberg** [nunit/nunit3-vs-adapter#833]
Shouldly 4.0.3 - latest
NUnit 3.13.1 - latest
NUnit3TestAdapter 3.17.0 - latest
Microsoft.NET.Test.Sdk 16.9.4 - latest
F# (FSharp.Core 5.0.0)
Visual Studio 2019, v 16.9.3 - latest
TargetFramework net5.0

Minimal repro included in the attached BugHunt.zip, no binaries, clean compileable source only.
[BugHunt.zip](https://github.com/nunit/nunit3-vs-adapter/files/6252590/BugHunt.zip)

There are two failures in the Test Explorer, likely originating from the same problem:

1) When the NuGet package Shouldly is used in the unit test project, then the Test Explorer shows "No source available" in the Test Detail Summary pane,

2) and double clicking on the unit test item in the unit test list will have no effect.

The second problem is what made me start to investigate this problem, since it's really annoying to have to look up the tests manually.

Additional observation: When running the tests, any test failure is still shown with a valid link, and clicking a link takes you to the line with the failure.

When Shouldly is removed from the test project, then everything works as it should. Source and all links are present, and double clicking a test will take you to the test.

**Comment by jnm2** [comment]
I don't recognize this right off, but it may be related to https://github.com/shouldly/shouldly/issues/795.

**Comment by OsirisTerje** [comment]
It seems to be related to the same thing.  Adding the properties @jnm2 refers to to the project after removing the Shouldly package causes the same error to appear.  Further, it is enough to only comment out the DebugType to bring back the source tracking.  So this is an error in the Shouldly package.

**Comment by BentTranberg** [comment]
```
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
    <DebugType>embedded</DebugType>
    <Deterministic>false</Deterministic>
    <DeterministicSourcePaths>false</DeterministicSourcePaths>
```

Thanks! You are right, this had the same nasty effect. Shouldly is obviously to blame for this problem. Not what I would have guessed - that a library would do something like that - but at least I am very happy that it has nothing to do with NUnit.

I don't use Shouldly, and so I have pretty much no interest in pursuing the issue. I just happened to stumble on it. If anybody else using F# and Shouldly should happen to read this, I can recommend Unquote as a replacement. Used it for years with F# and NUnit.

**Comment by jnm2** [comment]
@OsirisTerje I don't understand why `<DebugType>embedded</DebugType>` is not a bug against the adapter though. Wouldn't it be a good thing for the adapter to support this setting? Some people set it in their Directory.Build.props.

**Comment by OsirisTerje** [comment]
We're relying on the DiaSession from MS (Microsoft.VisualStudio.TestPlatform.ObjectModel)  for this, so the adapter doesn't really do anything here.  The error might be down in that part.  We're using both the ObjectModel version 11 for the older stuff, and version 15.0 for the newer stuff.  All we do is to give the GetNavigationDataForMethod the typename and the methodname to get back the information and send that up to the explorer.  We could raise the issue with the TestPlatform team, but then we also rely on an older version to maintain backwards compatibility, so we might then have to enable a newer version.

**Comment by jnm2** [comment]
I see, so this issue is upstream with the test platform team. It's good to clarify that it's not an issue that is unique to Shouldly since I have seen that debug type used without Shouldly.
