### ISSUE TITLE
Reporting random seed for a test case

### ISSUE THREAD

**Issue by codito** [nunit/nunit3-vs-adapter#843]
**Scenario**

For the test case below, the nunit console runner produces a xml output with the `seed` value to enable repro. We'd like to support this behavior in the [nunitxml.testlogger][] for `dotnet test`. This information is not available today in the TestPlatform object model (`TestCase` or `TestResult`) data.

[nunitxml.testlogger]: https://github.com/spekt/nunit.testlogger/

**Ask**

Would it be possible/desirable for the adapter to expose the `seed` value as an additional data on the `TestCase`? May be as a custom property (`TestCase.SetPropertyValue`); similar mechanism is already used for test category.

**Repro**

```csharp
	[TestFixture]
	public class RandomizerTests
	{
		[Test]
		public void Sort_RandomData_IsSorted()
		{
			var random = TestContext.CurrentContext.Random;
			var data = Enumerable.Range(0, 2).Select(i => random.Next()).ToArray();

			Array.Sort(data);

			Assert.That(data, Is.Ordered);
		}
	}
```

**Additional Information**

* NUnit and NUnit3TestAdapter versions: `3.13.1, 4.0.0-beta.2`
* Visual Studio edition and full version number (see Help About) - `NA`. Trying with `dotnet test`
* A short repro, preferably attached or pointing to a git repo or gist. See above
* What .net platform and version is being targeted: `.netcoreapp 3.1`
* If TFS/VSTS issue, what version, hosted, on-premises, and what build task you see this in: `NA`

**Comment by OsirisTerje** [comment]
@codito Please check if the enclosed dev package of the adapter solves the issue for you.  The Seed value is added to both the test case and the test result.  If you set the NUnit.Verbosity=5, it will also be output to the console.  
[NUnit3TestAdapter.4.0.0-dev.570.zip](https://github.com/nunit/nunit3-vs-adapter/files/6534527/NUnit3TestAdapter.4.0.0-dev.570.zip)

**Comment by codito** [comment]
@OsirisTerje thank you! I can confirm the fix is working great. Will look forward to the availability of next prerelease in nuget.

**Comment by OsirisTerje** [comment]
Thanks!  It will be part of the proper 4.0 release, early next week.   You can grab it off the myget feed once I have the PR merged until then.
