### ISSUE TITLE
[ProcessUtils] Simplify reading the process sdtout and stderr.

### ISSUE THREAD

**Issue by AraHaan** [nunit/nunit3-vs-adapter#844]
Not a bug more like a little optimization request, I looked at the code at https://github.com/nunit/nunit3-vs-adapter/blob/9b38318f46aac06326c455e17efc205741ca3482/src/NUnit.TestAdapter.Tests.Acceptance/WorkspaceTools/ProcessUtils.cs#L38-L68 which @jnm2 pointed out to me, I then realized the code could be simplified further yet still do the same thing (just with a few less lines of code to maintain).

I have successfully commited the change to a fork, I will open a draft pr for it too for review as well.

**Comment by AraHaan** [comment]
Sorry, accidentally pressed wrong button and it opened as a non-draft pr 😭.

**Comment by OsirisTerje** [comment]
Non-draft is ok, but perhaps good if the acceptance tests are green :-)
