### ISSUE TITLE
Adapter doesn't report TestCase properties

### ISSUE THREAD

**Issue by codito** [nunit/nunit3-vs-adapter#847]
`Description` property is not provided by the adapter in `TestCase.Traits` or `TestCase.Properties` for the [loggers][nunitxml] to consume. Related issue https://github.com/spekt/nunit.testlogger/issues/79, https://github.com/spekt/nunit.testlogger/issues/71, https://github.com/spekt/nunit.testlogger/issues/69

[nunitxml]: https://github.com/spekt/nunit.testlogger/

## Sample test case

```csharp
using NUnit.Framework;

namespace trial
{
    public class Tests
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        [Description("some text here")]
        public void Test1()
        {
            Assert.Pass();
        }
    }
}
```

When reporting a bug, please provide the following information to speed up triage:

* NUnit and NUnit3TestAdapter versions: **3.12** and **4.0.0-beta.2**
* Visual Studio edition and full version number (see Help About): **NA, trying with dotnet test with .NET 5 sdk`
* A short repro, preferably attached or pointing to a git repo or gist: **See above**
* What .net platform and version is being targeted: **.NET 5**
* If TFS/VSTS issue, what version, hosted, on-premises, and what build task you see this in: **NA**

**Comment by OsirisTerje** [comment]
This is the default behaviour, as Description is listed as an internal property.  There is a runsetting to change this, NUnit.ShowInternalProperties.  Setting this to true, give the following output:

```
<test-case id="0-1001" name="Test1" fullname="Issue847.Tests.Test1" methodname="Test1" classname="Issue847.Tests" runstate="Runnable" seed="1322471594" result="Passed" start-time="2021-05-22T14:44:40.0192547Z" end-time="2021-05-22T14:44:49.6630803Z" duration="9.643983" asserts="0">
          <properties>
            <property name="Category" value="Whatever" />
            <property name="Description" value="some text here" />
          </properties>
        </test-case>
```

The NUnit output can be enabled using another property: TestOutputXml
See  https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#testoutputxml 

I expected to now see the property in the Traits column in the Test Explorer (as that was an issue earlier), but it could not be seen there.

**Comment by OsirisTerje** [comment]
@codito Are there any need to change anything in the adapter wrt this ?
