### ISSUE TITLE
Failure to run tests under vstest.console from VS2015

### ISSUE THREAD

**Issue by kkm000** [nunit/nunit3-vs-adapter#85]
This is what I am getting with the latest ctp7 version (after [enabling Copy Local](https://github.com/nunit/nunit3-vs-adapter/issues/84) on the 4 DLLs):

```
>vstest.console.exe bin\Release\SmartAction.Build.Tasks.NuGet.unittest.dll /TestAdapterPath:bin\Release
Microsoft (R) Test Execution Command Line Tool Version 14.0.23107.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Information: NUnit Adapter 3.0.7.0 executing tests is started

Information: Running all tests in C:\projects\SmartAction.Build\test\SmartAction.Build.Tasks.NuGet.unittest\bin\Release\SmartAction.Build.Tasks.NuGet.unittest.dll

Error: Exception Mono.Cecil.AssemblyResolutionException, Exception thrown executing tests

Error: Failed to resolve assembly: 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral,PublicKeyToken=b03f5f7f11d50a3a'

Information: NUnit Adapter 3.0.7.0 executing tests is finished
```

Somehow the binding succeeds under VS2015, but fails with the console runner, apparently because the two have different binding redirection policies.

xUnit's apparent solution to that is to use [the package `Microsoft.VisualStudio.TestPlatform.ObjectModel`](https://github.com/xunit/visualstudio.xunit/blob/master/xunit.runner.visualstudio.testadapter/packages.config#L3) not available anywhere else but from their [private feed](https://github.com/xunit/visualstudio.xunit/blob/master/NuGet.Config#L5).

**Addedndum 1**

What I cannot get my head around is this redirection clause in `vstest.console.exe.config` that comes with VS2105:

```XML
      <!-- Test adapters compiled against version 11/12, need to be redirected to version 14. -->
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.VisualStudio.TestPlatform.ObjectModel" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="11.0.0.0-12.0.0.0"  newVersion="14.0.0.0"/>
      </dependentAssembly>
```
For some reason the redirect does not happen though!

**Addedndum 1**

Even though the fusion log shows a successful binding:

```
*** Assembly Binder Log Entry  (151123 @ 184437) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\_PX\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\te.processhost.managed.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/_PX/MICROSOFT VISUAL STUDIO 14.0/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = te.processhost.managed.exe
Calling assembly : NUnit3.TestAdapter, Version=3.0.7.0, Culture=neutral, PublicKeyToken=4cb40d35494691ac.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\_PX\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\te.processhost.managed.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 11.0.0.0 redirected to 14.0.0.0.
LOG: Post-policy reference: Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Switch from LoadFrom context to default context.
LOG: Binding succeeds. Returns assembly from C:\_PX\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll.
LOG: Assembly is loaded in default load context.
```

**Comment by CharliePoole** [comment]
The NUnit test engine is **not** intended to be in the same directory as your tests. That's why we turn off copy local for our components. What is happening in your first snip has nothing to do with binding redirects. It's simply that the engine is searching for extensions, using Mono.Cecil, starting in the directory in which it finds itself. It encounters an error trying to find extensions in the object model assembly.

This does not happen with the VS adapter because we added a zero-length .addins file to the directory. A .addins file gives the engine info about where to search for extensions. If the file is empty, it does nothing. In the absence of a file, it looks at every assembly in the directory.

The problem does not arise under nunit3-console, because your code never references the engine and there is never any question of being copied.

Can you explain why you want to have these files copied?

**Comment by CharliePoole** [comment]
The NUnit adapter uses the VS2012 object model and relies on reflection to access features only available in later versions. It's an interesting side note that this approach is what the MS guys recommended to us when we first created the adapter! 

I think it's likely that the redirect you find in vstest.console.exe.config is what is causing the problem.

**Comment by CharliePoole** [comment]
Try putting a zero-length file of type .addins in the directory with the tests.

**Comment by kkm000** [comment]
> Try putting a zero-length file of type .addins in the directory with the tests.

This indeed made the tests run!

Now, I do not understand probably a simple thing, and would appreciate if you could give me some pointers: How does VS know where to look for adapters? When I add the package to a test project, the full set of adapter DLLs is somewhere in a directory like `packages/NUnitTestAdapter.3.2.1/tools` off the solution folder. How does the VS test system know even to look into this folder? Ideally, I think I should use the same trick in my testing scripts, if I knew it...

**Comment by CharliePoole** [comment]
I take it you mean adapters installed by a nuget package. The answer for my part is "I wish I knew."

In the early days of this project, we had very close cooperation from Microsoft. Even so, the devs were not allowed to tell us how they did this.  Nowadays, we have even less information!

My guess is that they look in the nuget packages and examine the assemblies to find an interface implementation. But it's only a guess.

**Comment by CharliePoole** [comment]
I'm ready to mark this closed. AFAIK everything that is referenced in this issue has been dealt with.

Comments anyone?
