### ISSUE TITLE
Explicit `TestCase`s are automatically run in Visual Studio 2019

### ISSUE THREAD

**Issue by eduherminio** [nunit/nunit3-vs-adapter#851]
Repro:

```csharp
[TestCase("1")]
[TestCase("2", Explicit = true, Category = "LongRunning")]
[TestCase("3", Explicit = true)]
public void MyTest(string str)
{
     Assert.Pass();
}
```

All test cases are executed when clicking 'Run all' from VS, when only the first one is expected to be executed.

<details>
<Summary>Versions</summary>

* Microsoft Visual Studio Community 2019 - Version 16.9.2
* NUnit 3.13.2
* NUnit3TestAdapter 3.17.0
* .NET 5.0

</details>

**Comment by OsirisTerje** [comment]
Upgrade to version 4.0.0-beta.2.

(PS:  Remember to clean and rebuild you project)

**Comment by eduherminio** [comment]
I can confirm it works as expected in 4.0.0-beta.2, thanks.
