### ISSUE TITLE
nUnit test adapter exception

### ISSUE THREAD

**Issue by Sanan07** [nunit/nunit3-vs-adapter#856]
NUnit adapter gives exception in Visual Studio 17.0 using Live Unit Testing.
This issue reported in our internal system, so after investigation we think that it is related to NUnit adapter itself.
It is reproducible in new Visual Studio 64 bit, which we are working on. Here is announcement of new VS [link](https://devblogs.microsoft.com/visualstudio/visual-studio-2022/)

Repro steps : 
1. Open VS and create a new NUnit (fx, C#/VB) Test Project
2. Click Test->Live Unit Testing->Start from menu bar

Actual behavior : 
This is what user gets in Output window : 
`NUnit Adapter 3.16.1.0: Test execution started
Running all tests in C:\Users\sayuzbas\source\repos\TestProject8\.vs\TestProject8\v17\lut\0\t\TestProject8\Debug\net472\TestProject8.dll
Exception System.IO.FileLoadException,    Exception thrown executing tests in C:\Users\sayuzbas\source\repos\TestProject8\.vs\TestProject8\v17\lut\0\t\TestProject8\Debug\net472\TestProject8.dll
Could not load file or assembly 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at NUnit.Engine.Internal.TargetFrameworkHelper..ctor(String assemblyPath)
   at NUnit.Engine.Services.RuntimeFrameworkService.ApplyImageData(TestPackage package)
   at NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework(TestPackage package)
   at NUnit.Engine.Runners.MasterTestRunner.InitializePackage()
   at NUnit.Engine.TestEngine.GetRunner(TestPackage package)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping2 testCases, TestFilter filter) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 218
Innerexception: System.IO.FileLoadException: The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
NUnit Adapter 3.16.1.0: Test execution complete
No test matches the given testcase filter 
TestCategory!=SkipWhenLiveUnitTesting&Category!=SkipWhenLiveUnitTesting in C:\Users\sayuzbas\source\repos\TestProject8\.vs\TestProject8\v17\lut\0\t\TestProject8\Debug\net472\TestProject8.dll`

![LUT](https://user-images.githubusercontent.com/8465726/118337144-6c3ee780-b513-11eb-8321-c61ee4066cd1.PNG)

* NUnit and NUnit3TestAdapter versions : 3.16.1.0
* Visual Studio edition and full version number : 17.0.0 Preview 1.0
* What .net platform and version is being targeted : .net framework version (4.7.2 or 4.8). Works fine in .net Core projects (f.e .net 5)

**Comment by OsirisTerje** [comment]
This is something I can't reproduce, as I have no access to the preview.  

The Mono.Cecil is embedded with the adapter, and the only reason I can think of is that you're having the same in your test project.  That is what we have seen earlier, however, after we embedded Mono.Cecil, we have had no such issues. 
If you can share your test project, that might help. 

Further, you should use the latest template, not the VS2019 based one, or simply update the adapter to the latest version, which is 3.17.  It would also be valuable to upgrade to version 4.0.0-beta.2, which will release before preview 1 anyway.

**Comment by Sanan07** [comment]
Thank you. After updating to latest versions both of NUnit packages, it works fine : 
`
"NUnit" Version="3.13.2"
"NUnit3TestAdapter" Version="4.0.0-beta.2"
`

**Comment by OsirisTerje** [comment]
Thanks @Sanan07 .  

Then 4.0 version might be needed for VS 2022.....
