### ISSUE TITLE
Generic Test Fixtures are not getting triggered

### ISSUE THREAD

**Issue by stormoz** [nunit/nunit3-vs-adapter#86]
We have upgraded NUnit 3 -pre to recently released version:

Was:

- nunit-3.0.0-beta-3
- assembly version: nunit.framework, Version=3.0.5674.19279
- NUnit 3 Test Adapter 3.0.2.0

Now:

- package: package id="NUnit" version="3.0.0" targetFramework="net45"
- assembly version: nunit.framework, Version=3.0.5797.27534
- NUnit 3 Test Adapter 3.0.7.0

We had to upgrade NUnit 3 Test Adapter as well as the old version did not work with the latest version of NUnit 3 framework.

The latest version of test adapter is working great in case of non-generic test fixtures but fails to execute generic ones.
When trying to execute tests that are part of generic test fixtures from Test Explorer, such tests are not getting triggered. This was working before the upgrade.

Also, the generic test fixtures are working fine when executed via nunit3-console.exe.

The below example is to reproduce the issue:

```C#
namespace NUnit3TestAdapterIssue.GenericTestFixtures
{
    using System;
    using NUnit.Framework;

    public class One
    { }

    public class Two
    { }

    [TestFixture(typeof(One), Category = "One")]
    [TestFixture(typeof(Two), Category = "Two")]
    public class GenericTestFixture<T>
    {
        [Test]
        public void MyGenericTest()
        {
            Console.WriteLine(typeof(T).Name + "I am not getting triggered");
        }
    }

    [TestFixture]
    public class NonGenericTestFixture
    {
        [Test]
        public void MyNormalTest()
        {
            Console.WriteLine("I am working");
        }
    }
}
```

**Comment by CharliePoole** [comment]
This is most likely caused by the same problem that causes #81, which is basically a reflection of nunit/nunit#1049. We'll need to do a new release incorporating the NUnit fix in order to resolve this.

**Comment by besteffects** [comment]
I think  #82 relates to this. I use similar framework structure.
