### ISSUE TITLE
NUnitTestAdapter - Discovery exception

### ISSUE THREAD

**Issue by Tr00d** [nunit/nunit3-vs-adapter#869]
Hi! 😄 

Environment:
VS2019
.NetCore 3.1
NUnit 3.13.2
NUnit3TestAdapter 4.0.0

We recently upgraded from NUnit3TestAdapter package from 3.17.0 to 4.0.0 and we realized several tests were not executed anymore.
After investigation, we were able to notice it happened for all tests using generics and a TestFixtureSource to define which types to use.

Example:
`[TestFixtureSource(typeof(Sources), nameof(Sources.GetTypes))]`
`public class Tests<T>`

Also, the test output provided an exception coming from the NUnitEngine:
`Exception NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryException`
`Not a TestFixture, SetUpFixture or TestSuite, but ParameterizedFixture`
`   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractTestFixtures(NUnitDiscoveryCanHaveTestFixture parent, XElement node) in XXX\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 252`
`   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in XXX\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 218`
`   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractAllFixtures(NUnitDiscoveryTestSuite parent, XElement node) in XXX\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 192`
`   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ConvertXml(NUnitResults discovery) in XXX\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 180`
`   at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.Convert(NUnitResults discoveryResults, String assemblyPath) in XXX\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 134`
`   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping2 testCases, TestFilter filter) in XXX\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 280`

Downgrading NUnit3TestAdapter back to 3.17.0 (clean & package restore) made it working again. So, for the moment, it seems we're stuck with this version. Still, we can't consider this being an a final solution as internal policies require us to have up-to-date packages.

You can find [here](https://github.com/Tr00d/NUnitTestAdapterIssue) a public repo with a small solution. It also contains a log files with details from the test output.

**Comment by OsirisTerje** [comment]
Thanks for reporting and thanks for the repro
You can still use the 4.0, if you change the DiscoveryMode to Legacy in a runsettings file.  See https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#discoverymethod for details.

**Comment by OsirisTerje** [comment]
@Tr00d @Valdiralita This has been fixed with PR #886.   Running on your repro it now looks like:
 
![image](https://user-images.githubusercontent.com/203432/134584807-cfebd7f2-7fec-49a3-8fcc-a3814902e5b6.png)

Attached the alpha01 package with the fix here:
[NUnit3TestAdapter.4.1.0-alpha01.zip](https://github.com/nunit/nunit3-vs-adapter/files/7220867/NUnit3TestAdapter.4.1.0-alpha01.zip)
