### ISSUE TITLE
Parametrized test not run from TestCaseSource when one argument is an array of tuple

### ISSUE THREAD

**Issue by DmitryKondratenko1986** [nunit/nunit3-vs-adapter#873]
Hello!

### Environment:
    NUnit v3.12.0
    NUnit3TestAdapter v3.15.1
    Microsoft.NET.Test.Sdk v16.4.0
    Visual Studio Community 2019 16.10.2
    .NET Core 3.1

### Summary:
Unit tests parameterized with two parameters: the int and the array of tuples (int, int) (via TestCaseSource) is not run with Test Explorer's Run All button.

### Expected Behavior:
All test cases are enumerated in Test Explorer with Fail or Pass statuses upon pressing Run All. In sample provided, it is expected that the test case will fail with a red X badge in Test Explorer.

### Current Behavior:
Test Cases are not run, status for tests are unfilled blue badges. Outputs the following error:
========== Test discovery finished: 1 Tests found in 57 ms ========== ---------- Starting test run ---------- NUnit Adapter 3.17.0.0: Test execution started An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Error: Missing '('. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed. ========== Test run finished: 0 Tests run in 57 ms (0 Passed, 0 Failed, 0 Skipped) ==========

### Additional Notes:
My issue is very similar to [https://github.com/nunit/nunit3-vs-adapter/issues/782]
A workaround is observed: test runs if uncheck option "Discover tests in real time from C# and Visual Basic .NET source files" in Test/Option/General in the main menu. But in the test explorer in the "test detail symmary" section test marked as "No source available" so I can't swith to the test method if I press F12 button.

### Repro steps:
1.  Create new .NET Core 3.1 class library project
2. Add NUnit Test project to solution (w/ Nuget packages Microsoft.NET.Test.Sdk, NUnit and NUnit3TestAdapter )
3. Add simple test class with the code below
4. Open Visual Studio Test Explorer and press Run All.
5. Observe blue unfilled status icons of tests, error in Output/Tests

### Sample
```c#
[TestFixture]
public class SomeTests
{
    private static IEnumerable<TestCaseData> DataCases
    {
        get
        {
            yield return new TestCaseData(1, new (int, int)[] { (1, 2) });
        }
    }
    [TestCaseSource(nameof(DataCases))]
    public void SomeTest(int x1, (int, int)[] expected)
    {
        var actual = new (int, int)[] { (1, 2) };
        Assert.AreEqual(expected, actual);
    }
}
```

**Comment by OsirisTerje** [comment]
This may be a FQN issue, but first try to upgrade adapter to either 3.17 or 4.0.0.

**Comment by OsirisTerje** [comment]
This is a FQN issue, so we just have to wait for MS.  It can't handle the parentheses coming in with the tests.

**Comment by OsirisTerje** [comment]
@DmitryKondratenko1986 Checked this now with the latest adapter (and also version 4.1.), with SDK at 16.11.0 and VS 2022,  (17.0.4), and it works now.  So seems something has been fixed on the road here. 
![image](https://user-images.githubusercontent.com/203432/147606413-584799a2-be96-4fc0-ac3b-52ba63e0f283.png)

Issue code is here:  https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue873
