### ISSUE TITLE
An exception occurred while invoking executor 'executor://nunit3testexecutor/': Exception encountered unloading application domain

### ISSUE THREAD

**Issue by sivakumarss** [nunit/nunit3-vs-adapter#879]
When reporting a bug, please provide the following information to speed up triage:

* NUnit.3.13.2 and  NUnit Adapter 4.0.0.0
* Microsoft Visual Studio Professional 2019 Version 16.8.4  => Working good when ran in Visual studio Test explorer
* **Issue in Azure Devops build** 
* .Net 4.8 is being targeted
* **Tried with several combination of NUnit and NunitTest Adapter**. If the Test Adapter is removed Build runs good else breaks

Detailed Error
##[error]An exception occurred while invoking executor 'executor://nunit3testexecutor/': Exception encountered unloading application domain
##[error]Stack trace:
##[error]   at NUnit.Engine.Services.DomainManager.DomainUnloader.Unload()
##[error]   at NUnit.Engine.Services.DomainManager.Unload(AppDomain domain)
##[error]   at NUnit.Engine.Runners.TestDomainRunner.UnloadPackage()
##[error]   at NUnit.Engine.Runners.AbstractTestRunner.Unload()
##[error]   at NUnit.Engine.Runners.MasterTestRunner.UnloadPackage()
##[error]   at NUnit.Engine.Runners.MasterTestRunner.Unload()
##[error]   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.CloseRunner() in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 125
##[error]   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Dispose() in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 132
##[error]   at NUnit.VisualStudio.TestAdapter.NUnitTestAdapter.Unload() in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitTestAdapter.cs:line 318
##[error]   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 142
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass48_0.<RunTestInternalWithExecutors>b__0()
##[error]   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
##[error]--- End of stack trace from previous location where exception was thrown ---
##[error]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
##[error]   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInSTAThread(Action action, Boolean waitForCompletion)
##[error]   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)
##[error]Inner exception: Exception encountered unloading application domain: Attempted to access an unloaded appdomain. (Exception from HRESULT: 0x80131014)

**Comment by sivakumarss** [comment]
I tried to reproduce the issue in the local Visual studio environment but in vain.  
I will try with  Azure devops side.  

In mean time please find our yml information for the  VisualStudioTest  step in our pipe line  and might be helpful to investigate.
Thanks

`variables:
    NUnitMatchPattern: **\*Test.dll

steps:
- task: VSTest@2
  displayName: 'Run NUnit Tests'
  inputs:
    testAssemblyVer2: '$(NUnitMatchPattern)'
    searchFolder: '$(Build.ArtifactStagingDirectory)'
    runOnlyImpactedTests: true
    vsTestVersion: toolsInstaller
    runSettingsFile: Solutions/CodeCoverage.runsettings
    pathtoCustomTestAdapters: '$(Build.SourcesDirectory)/Solutions/Packages'
    codeCoverageEnabled: false
    testRunTitle: 'NUnit Tests'
    diagnosticsEnabled: true
  condition: and(succeeded(), eq(variables['RunUnitTests'], 'true'))`

**Comment by OsirisTerje** [comment]
How does your csproj file look ?
What packages are you including?
Are you using sdk or legacy format ?

It would be easier with a repro project......
