### ISSUE TITLE
Nunit 3 Test Adapter 

### ISSUE THREAD

**Issue by BitBucketStruggles** [nunit/nunit3-vs-adapter#883]
Hello- Below are some details on the environment I am working on.  The problem is while running a test case I keep getting this error,

 System.MissingMethodException : Method not found: 'NUnit.Framework.Interfaces.IPropertyBag TestAdapter.get_Properties()'.
TearDown : System.MissingMethodException : Method not found: 'NUnit.Framework.Interfaces.IPropertyBag TestAdapter.get_Properties()'.

The adapter has been added as an extension , however I have tried alternately adding it via nuget package as well and the same has thrown same error. I have now gone back to having Nunit adapter setup via the vsix file.

Dev Environment details
* NUnit (3.13.2) and NUnit3 TestAdapter version(3.14.0.0)
* Visual Studio 2017 professional edition and full version number (4.8.04084)
* .Net Platform( 4.6.2)

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".
