### ISSUE TITLE
Tests marked as "Explicit" are reported as "Inconclusive"

### ISSUE THREAD

**Issue by codito** [nunit/nunit3-vs-adapter#909]
Should the adapter mark tests with `Explicit` as `Skipped` instead of `Inconclusive` in the TestResult?

Original issue: https://github.com/spekt/nunit.testlogger/issues/86

Additional information:

* NUnit and NUnit3TestAdapter versions: 4.0.0
* Visual Studio edition and full version number (see Help About): NA
* What .net platform and version is being targeted: .netcore 3.1

**Comment by OsirisTerje** [comment]
It is marked as "Not Run" byt the Test Explorer, because it is actually not being run at all.  All Explicit tests received from VS will be filtered out in the adapter (for non-explicit runs).    Where do you see it reported as Inconclusive?

Given a set of tests like this:
![image](https://user-images.githubusercontent.com/203432/140623839-fe67efbc-8f24-4131-9e37-3baa6fbe3ab7.png)

Looking at the codelens it says (for the explicit one):
![image](https://user-images.githubusercontent.com/203432/140623851-464838fd-314d-47ef-8436-02f27aa3e817.png)
same as in the Test Explorer

RUnning it through dotnet test like:
```
dotnet test -v:n --logger="Console"
```
it is reported as Skipped, but as can be seen only two tests as being actually run, the Normal and Ignore.  

![image](https://user-images.githubusercontent.com/203432/140623820-a51889a6-3e52-4af1-b0bd-14e23c913941.png)

The ignore is marked as Skipped in Test Explorer, with the warning icon, which is correct, since it is work in progress.  The Explicit is not work in progress, it is simply not run.

**Comment by OsirisTerje** [comment]
Looked at the original issue, and see the output.  Not used to the logger, but what input does the logger use?

**Comment by OsirisTerje** [comment]
I added the nunit.logger to my test project, and I don't get any Inconclusive out:

```xml
<test-suite type="TestFixture" name="Tests" fullname="Issue909.Tests" classname="Issue909.Tests" total="3" passed="1" failed="0" inconclusive="1" skipped="1" result="Passed" start-time="2021-11-06T 23:19:31Z" end-time="2021-11-06T 23:19:31Z" duration="0.027205">
        <test-case name="TestAsExplicit" fullname="Issue909.Tests.TestAsExplicit" methodname="TestAsExplicit" classname="Tests" result="Inconclusive" start-time="2021-11-06T 23:19:31Z" end-time="2021-11-06T 23:19:31Z" duration="0.00297" asserts="0" seed="1487872350">
          <properties>
            <property name="Explicit" value="" />
          </properties>
        </test-case>
        <test-case name="TestAsIgnore" fullname="Issue909.Tests.TestAsIgnore" methodname="TestAsIgnore" classname="Tests" result="Skipped" start-time="2021-11-06T 23:19:31Z" end-time="2021-11-06T 23:19:31Z" duration="3.8E-05" asserts="0" seed="621909961" />
        <test-case name="TestAsNormal" fullname="Issue909.Tests.TestAsNormal" methodname="TestAsNormal" classname="Tests" result="Passed" start-time="2021-11-06T 23:19:31Z" end-time="2021-11-06T 23:19:31Z" duration="0.024197" asserts="0" seed="1204684245" />
      </test-suite>
```

**Comment by OsirisTerje** [comment]
If I add the spekt nunit.logger to my test project, I do see the Inconclusive there:
```xml
<test-case name="TestAsExplicit" fullname="Issue909.Tests.TestAsExplicit" methodname="TestAsExplicit" classname="Tests" result="Inconclusive" start-time="2021-11-06T 23:28:52Z" end-time="2021-11-06T 23:28:52Z" duration="0.0024589" asserts="0" seed="975204596">
          <properties>
            <property name="Explicit" value="" />
          </properties>
        </test-case>
        <test-case name="TestAsIgnore" fullname="Issue909.Tests.TestAsIgnore" methodname="TestAsIgnore" classname="Tests" result="Skipped" start-time="2021-11-06T 23:28:52Z" end-time="2021-11-06T 23:28:52Z" duration="4.1E-05" asserts="0" seed="1110187453" />
        <test-case name="TestAsNormal" fullname="Issue909.Tests.TestAsNormal" methodname="TestAsNormal" classname="Tests" result="Passed" start-time="2021-11-06T 23:28:52Z" end-time="2021-11-06T 23:28:52Z" duration="0.024062" asserts="0" seed="368966932" />      
```
But if I output the NUnit XML, it is not there, but reported as Skipped:
```xml
<test-case id="0-1001" name="TestAsExplicit" fullname="Issue909.Tests.TestAsExplicit" methodname="TestAsExplicit" classname="Issue909.Tests" runstate="Explicit" seed="975204596" result="Skipped" label="Explicit" start-time="2021-11-06T23:28:52.7948958Z" end-time="2021-11-06T23:28:52.7972569Z" duration="0.002459" asserts="0" />
        <test-case id="0-1002" name="TestAsIgnore" fullname="Issue909.Tests.TestAsIgnore" methodname="TestAsIgnore" classname="Issue909.Tests" runstate="Ignored" seed="1110187453" result="Skipped" label="Ignored" start-time="2021-11-06T23:28:52.7989413Z" end-time="2021-11-06T23:28:52.7989824Z" duration="0.000041" asserts="0">
          <properties>
            <property name="_SKIPREASON" value="" />
          </properties>
        </test-case>
        <test-case id="0-1003" name="TestAsNormal" fullname="Issue909.Tests.TestAsNormal" methodname="TestAsNormal" classname="Issue909.Tests" runstate="Runnable" seed="368966932" result="Passed" start-time="2021-11-06T23:28:52.7990555Z" end-time="2021-11-06T23:28:52.8231152Z" duration="0.024062" asserts="0" />
```
The adapter doesn't set anything to "Inconclusive", but may set tests to "Not found".  Also, this test is not returned in the results, so it might be that the testrunner (testhost) is simple translating anything that is not found into Inconclusive.  I also see that the nunit.logger doesn't do anything there wrt to this.

**Comment by codito** [comment]
@OsirisTerje thank you for the detailed notes. Upon debugging the `dotnet test` workflow, I can confirm that console runner sends a `TestOutcome.None` for Explicit tests. We will fix this case in the nunit testlogger.

![image](https://user-images.githubusercontent.com/28766/140629488-44b0259c-21f0-46af-8810-0fb0c692660c.png)

With VS 2022 preview and corresponding dotnet console, there is a behavior change since https://github.com/nunit/nunit3-vs-adapter/issues/909#issuecomment-962510637

**dotnet test** summarizes incorrectly as `Skipped: 0`.
![image](https://user-images.githubusercontent.com/28766/140629567-98ea9dd7-1208-4daa-b212-65aaafaa08a4.png)

**VS Test Explorer** runs the test incorrectly and marks it failed. I'm using VS Community.
![image](https://user-images.githubusercontent.com/28766/140629620-1f65088e-dcae-4d26-95c0-58af2ecce8f2.png)

**Comment by OsirisTerje** [comment]
Thanks!  If I understand you correctly, this is outside the NUnit Adapter, so we can close this issue here?  Would be good if you could come back with info when it is fixed and which version that will be.

**Comment by codito** [comment]
We have worked around the logger issue in nunit test logger package. Original issue reported is fixed for us. 

I'm not sure if the VS 2022/.net 6 runner result discrepancy mentioned above for Explicit tests are in adapter or the vstest platform. They may need additional investigation.
