### ISSUE TITLE
Update Adapter Documentation for Current Usage

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#916]
The Adapter install information is dated, https://docs.nunit.org/articles/vs-test-adapter/Adapter-Installation.html

We should include referencing `Microsoft.NET.Test.Sdk` as it is almost always needed. We should also more strongly deprecate the VSIX. @OsirisTerje thoughts?

**Comment by OsirisTerje** [comment]
Agree, on both the install docs and the vsix. 

Also, I think we should consider marking these as dependencies of the adapter,  also including NUnit framework.

**Comment by OsirisTerje** [comment]
@rprouse Please review https://github.com/nunit/docs/pull/603
