### ISSUE TITLE
Launching 32-bit .NET processes fail in .NET6

### ISSUE THREAD

**Issue by handerss-tibco** [nunit/nunit3-vs-adapter#917]
Repository with a minimal reproducible example + COREHOST tracefile: https://github.com/handerss-tibco/net6-nunit-32bit-fail 

**Versions:**
.NET SDK: 6.0.100
Microsoft.NET.Test.Sdk 17.0.0
NUnit 3.13.2
NUnit3TestAdapter: 4.1.0

Tests which try to launch a 32-bit .NET process fail since the process cannot be started due to:

```
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\6.0.0\hostfxr.dll failed
   - Installing .NET prerequisites might help resolve this problem.
      https://go.microsoft.com/fwlink/?linkid=798306
```

It looks like the 32-bit exe is trying to run using the 64-bit hostfxr.dll.

This only occurs in .NET6 when running tests via the NUnit3 test adapter, e.g. `dotnet test`. Running directly in Visual Studio works as expected.

This is the COREHOST tracefile produced when running `dotnet test` on the test dll: https://github.com/handerss-tibco/net6-nunit-32bit-fail/blob/main/trace.txt

**Comment by OsirisTerje** [comment]
Interesting find!  But, I don't think this is related to the adapter.  As you notice, all work well in Visual Studio, and YES the adapter is also at work there!  
Googling that error message points to x86/x64 issues in Windows/dotnet, so my guess would be it is related to that.  I would suggest you post this issue to Developercommunity.

**Comment by handerss-tibco** [comment]
The reason why I thought the adapter might have been the cause is that the dependency is not necessary when running tests from VS via the ReSharper runner. I see now that the adapter is required when running using the built in test explorer (the issue is still not reproducible in VS, only when using the CLI).

Closing this and reporting this issue on the SDK instead: https://github.com/dotnet/sdk/issues/22647
