### ISSUE TITLE
Provide option to run in parallel for paralellized tests

### ISSUE THREAD

**Issue by JDunn3** [nunit/nunit3-vs-adapter#92]
Currently the test adapter forces tests(even when with the [Parallelizable] attribute) to run in series; a way to choose whether or not that override happens would provide an easier way to debug parallelized tests rather than attaching the debugger to another runner. #49 would be a precursor to this as there is not currently a reliable way to inform the adapter of settings.

More discussion on the merits of this here: https://groups.google.com/forum/#!topic/nunit-discuss/X3z2kMac04U

**Comment by rprouse** [comment]
This can probably be done as part of #49. The few settings we currently have are manually edited in the registry, but that isn't a workable long term solution.

**Comment by CharliePoole** [comment]
Blocked by #49

**Comment by CharliePoole** [comment]
Fixed as part of  #49
