### ISSUE TITLE
Target netstandard2.0

### ISSUE THREAD

**Issue by christianbumann** [nunit/nunit3-vs-adapter#937]
It would be nice to have in addition to net35 and netcoreapp2.1 targets also the netstandard2.0 target.
This would allow to convert the test-project which uses this adapter also to netstandard2.0

**Comment by OsirisTerje** [comment]
Have you read https://docs.nunit.org/articles/nunit/getting-started/dotnet-core-and-dotnet-standard.html#why-cant-my-tests-target-net-standard ?

Your `software under test` can be netstandard, but your Test project has to be something that can be executed.

**Comment by christianbumann** [comment]
No I didn't read that. But now it's clear. You can close this issue. 
Many thanks for the link
