### ISSUE TITLE
When running dotnet test with filter, all tests are run and all console output is logged.

### ISSUE THREAD

**Issue by ptmclean** [nunit/nunit3-vs-adapter#941]
When running a test using the cli(`dotnet test`) and using a `--filter` all tests are run but only the results from the filtered tests are reported. A simple repro can be found [here](https://github.com/ptmclean/nunit-repro). The output from the test run only includes information from the matching test but the non-matching tests also run.

The NUnit version here is 3.13.2 and Adapter version 4.2.0 with dotnet 6.0.101 on an ARM Mac. I can't be sure it is not an engine issue, but changing the version of the adapter back to 4.1.0 returns to the previous behaviour.

There is another change with this version where the console output is logged for all tests whether they pass or fail. This may well be OS/console specific...
![image](https://user-images.githubusercontent.com/5698624/148723345-fe14ab8f-93a8-4489-b481-22098b99ae09.png)

**Comment by JohnDoeKyrgyz** [comment]
Also seeing this issue on Windows

**Comment by OsirisTerje** [comment]
Thanks @ptmclean and @JohnDoeKyrgyz .   

This seems to happen when an assembly doesn't have any tests matching that filter.  Please confirm if that is what you see. 
I have made a fix for that issue, and have enclosed a dev version.  Would be awesome if you could verify if that fixes it in your cases.  

About the console output, that was a change introduced in Version 4.2.0, responding to issue #934. 



[NUnit3TestAdapter.4.2.1-dev.02-dbg.zip](https://github.com/nunit/nunit3-vs-adapter/files/7865785/NUnit3TestAdapter.4.2.1-dev.02-dbg.zip)

**Comment by Sebazzz** [comment]
> This seems to happen when an assembly doesn't have any tests matching that filter. Please confirm if that is what you see.

Yes, and an assembly that actually doesn't contain any tests at all does output the warning as expected.

That NuPKG does fix the issue btw 👍

**Comment by ptmclean** [comment]
Great thanks @OsirisTerje! Sorry I've been slow to get back to you. I think that works well. I've pushed up the reference to the test package in the repro repo. 

Looks good to me!

**Comment by OsirisTerje** [comment]
Thanks!   I'll get it out as soon as possible :-)

**Comment by OsirisTerje** [comment]
Release 4.2.1 is on nuget.org.

**Comment by tmx7777** [comment]
Works for me as well. Great 👍
