### ISSUE TITLE
BadImageFormatException from testhost.dll when using Visual Studio 2022 Preview

### ISSUE THREAD

**Issue by Stolpe** [nunit/nunit3-vs-adapter#946]
I am unable to run NUnit tests on the latest Visual Studio 2022 Preview. I get the following error, which I don't know is due to a bug in the Preview, or a sign of changes to inevitably come.

```
Log level is set to Informational (Default).
Connected to test environment '< Local Windows Environment >'
Test data store opened in 0,159 sec.
========== Starting test discovery ==========
========== Test discovery skipped: All test containers are up to date ==========
Starting test discovery for requested test run
========== Starting test discovery ==========
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Source\NUnitExplicitTest\Tests\bin\Debug\net6.0\testhost.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\Source\NUnitExplicitTest\Tests\bin\Debug\net6.0\testhost.dll'
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
========== Test discovery aborted: 0 Tests found in 2,6 sec ==========
========== Starting test run ==========
Testhost process exited with error: Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Source\NUnitExplicitTest\Tests\bin\Debug\net6.0\testhost.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\Source\NUnitExplicitTest\Tests\bin\Debug\net6.0\testhost.dll'
. Please check the diagnostic logs for more information.
Testhost process exited with error: Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\Source\NUnitExplicitTest\Tests\bin\Debug\net6.0\testhost.dll'. An attempt was made to load a program with an incorrect format.
File name: 'C:\Source\NUnitExplicitTest\Tests\bin\Debug\net6.0\testhost.dll'
. Please check the diagnostic logs for more information.
========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
```

* NUnit and NUnit3TestAdapter versions
  * NUnit 3.13.2
  * NUnit3TestAdapter 4.2.0
* Visual Studio edition and full version number (see Help About)
  * Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
     Version 17.1.0 Preview 3.0
* A short repro, preferably attached or pointing to a git repo or gist
  * https://github.com/Stolpe/NUnitExplicitTest/tree/net60 (I lazily reused a repo from an earlier issue :))
* What .net platform and version is being targeted
  * .NET 6.0

**Comment by OsirisTerje** [comment]
Working here:  
![image](https://user-images.githubusercontent.com/203432/150329245-5d759712-31bf-49a6-a918-2bc4dde81ad9.png)

**Comment by OsirisTerje** [comment]
Thanks!   I've also notified @kendrahavens MS-PG directly.

**Comment by kendrahavens** [comment]
Thank you for creating a report! We'll get back to you shortly.

**Comment by kendrahavens** [comment]
@Stolpe Thank you for the repro solution. I've responded on the developer community ticket you've filed. The repro solution also appears to execute correctly for me. I included some more notes and asked for more information on the developer community ticket.

**Comment by Stolpe** [comment]
@kendrahavens,

I have replied to you over at Developer Community. Thanks for your time!

**Comment by OsirisTerje** [comment]
@Stolpe Just tried it here with Preview 3, and it worked here too,  and in the net60 branch.

![image](https://user-images.githubusercontent.com/203432/150424948-3089be0d-2270-4695-9a62-423dd64d4a4e.png)

**Comment by OsirisTerje** [comment]
@Stolpe Assume you have it working too on your other machine, right?   So there is something strange with the one you have this issue on?

**Comment by Stolpe** [comment]
> @Stolpe Assume you have it working too on your other machine, right? So there is something strange with the one you have this issue on?

I have only tried it on one machine, where I have multiple instances of Visual Studio installed.

**Comment by OsirisTerje** [comment]
@Stolpe The machine I checked on also had multiple versions installed, so I don't think that is the issue.   Since it complains on testhost.dll - that is a common dll from the VS test platform - does MSTest or XUnit work?

**Comment by Stolpe** [comment]
@OsirisTerje,

I tried with MSTest and XUnit too, both of which failed for me. I guess that excludes NUnit from any wrong, so I will continue this in my Developer Community report instead.

Again, thank you for your time and the good work you do!
