### ISSUE TITLE
Console output doesn't seem to show up in Tests output window

### ISSUE THREAD

**Issue by DerekSMorin** [nunit/nunit3-vs-adapter#95]
I'm talking about the kind of stuff that shows up in the "output" tag of the generated reports.

**Comment by rprouse** [comment]
We are limited by what Visual Studio provides and there may not be anywhere to add this, but a good idea if there is. @OsirisTerje do you think it is possible?

**Comment by CharliePoole** [comment]
@DerekSMorin I think you must have used an html tag, so something isn't showing up in your request, but I think you are referring to the output element in the XML.

We could indeed show this in the output window, if desired. I'm concerned that it would seem like too much output for some folks, so I'd like to be able to enable it selectively. For that reason, I think this has to wait until we implement #49.

**Comment by OsirisTerje** [comment]
I assume you mean the Output window, set to output from Tests:
![image](https://cloud.githubusercontent.com/assets/203432/11636393/4441f354-9d1c-11e5-9f97-e5465100d65b.png)

Given this code
```[Test]
        public void CheckConsoleOutput()
        {
            Console.WriteLine("Hi Hi World");
            Trace.WriteLine("Trace Trace the World");
            Debug.WriteLine("Debug Debug WOrld");
            Assert.That(true);
        }```

The Test output will be 
![image](https://cloud.githubusercontent.com/assets/203432/11636530/e2f094d8-9d1c-11e5-9149-3843a915ab3d.png)



The adapter writes to this window today, but information from the tests, but from the execution of the test.  That is what this is intended for.  We could add things to this window, but I am unsure if that would not be confusing.

The Trace and Debug Writeline  will appear in Output Debug window. 
![image](https://cloud.githubusercontent.com/assets/203432/11636480/9e707c42-9d1c-11e5-88b5-f4850671166a.png)


If this what you meant?
If so, I think we need to clarify what is really wanted and needed here.

**Comment by CharliePoole** [comment]
I'd say that putting the output into the Test Output, as we now do, should be sufficient. But let's wait a beat to hear from @DerekSMorin about why he feels it isn't.

**Comment by DerekSMorin** [comment]
The Console.WriteLine messages are not showing up in the "Test" output window.  That is where I was expecting to see them.  I think part of it is that when running the tests, the output window switches to show the "Test" output - so I'm expecting to see the same output there as I would see when running from the command line.  To be clear, I'm talking about the first picture in OsirisTerje's post.

**Comment by rprouse** [comment]
Isn't the fact that the console output is going to the test window (3rd image) what you would expect? That at least groups the output with the tests themselves giving context.

**Comment by CharliePoole** [comment]
Note that it wasn't possible to group the output this way under NUnit 2.6.4. NUnit 3.0 enables it by grouping output with each result and the NUnit 3 adapter takes advantage of it.

**Comment by DerekSMorin** [comment]
As you start to run you see messages like:

------ Run test started ------
NUnit Adapter 3.0.8.0 executing tests is started
Running selected tests in C:\Development\Source\DotNet\bin\x64\Debug\ActivityReport.dll
Loading tests from C:\Development\Source\DotNet\bin\x64\Debug\ActivityReport.dll

Then I am waiting to see more output but nothing shows up.


The window in the first picture says:

Show output from: Tests

I would expect to see output from the tests here.  I do see now that I can see the output by clicking on a test, and then clicking the Output link.   

I looks like regular visual studio tests operate the same way - I guess I was misintepreting the phrase: "Show output from: Tests"

**Comment by OsirisTerje** [comment]
The problem with sending the Console output to the Output/Tests window is that it is normally filled with a lot of execution information, and as @rprouse says, the context will be lost, because there is no information there about which test is being executed.  It will also deviate from the way MSTest and XUnit is working.  
Also, with the new parallell execution in VS2015 U1 (and NUnit and XUnit), a simple text output may not make much sense.

**Comment by CharliePoole** [comment]
@OsirisTerje I agree with your conclusion but I have to add to it that a simple text output is actually not even possible with NUnit 3.0 if by that we mean one line at a time as the test executes. All output is now trapped and is included in the test result from NUnit. 

I have wondered if we should handle console error output one line at a time, but that would require a change in the code.

@DerekSMorin In both NUnit and the adapter, associating the output with the test was designed as an improvement and most people find that to be the case. The console output works that way as well now except, of course there is only one place to look for it. :-)

**Comment by CharliePoole** [comment]
@OsirisTerje I intended to close this as well. I'll add the label.

**Comment by snboisen** [comment]
So now we have to switch to the Test Explorer, click on the test, then click on the output link to see our test output?
:-1:  for productivity :frowning:

**Comment by dmorsebu** [comment]
I have the same issue where I don't see output in the Output:Tests window, but I do see it in the log4net log, and the output generated by the test. I'm using VS2012. With NUnit 2.6.4 I saw output to the **Output:Tests** window as expected, but after upgrading to 3.4.1 (to match the version on our Bamboo server) we no longer get output to the **Output:Tests** window. 

When it was working I would see output like this:
```
NUnit VS Adapter 2.0.0.0 executing tests is started
Loading tests from C:\[...]\TestFixtures.dll
Run started: C:\[...]\TestFixtures.dll
2016-11-10 09:54:40,078 [TestRunnerThread] INFO - Starting SimpleTest
2016-11-10 09:54:40,102 [TestRunnerThread] INFO - Navigate to Home Page
NUnit VS Adapter 2.0.0.0 executing tests is finished
```
Now the **Output:Tests** looks like this
```
------ Run test started ------
NUnit Adapter 3.5.1.0: Test execution started
Running selected tests in C:\[removed]\TestFixtures.dll
NUnit3TestExecutor converted 440 of 440 NUnit test cases
NUnit Adapter 3.5.1.0: Test execution complete
========== Run test finished: 1 run (0:00:25.013) ==========
```
Where are my log4net and Console.Write statements in the **Output:Tests** window?

**Comment by CharliePoole** [comment]
@dmorsebu Note that you are commenting on an issue that was closed almost a year ago. The location of your output is explained in the earlier comments. Start a new issue if it's absolutely necessary but please consider the explanations given as to the reasons for the change before you do.

**Comment by malikmahak91** [comment]
After the test are run.I can just see the status as passed or failed but i want to see the results of test cases such as which id was fetched and etc.But right now there seams to be no way of doing that.

**Comment by OsirisTerje** [comment]
@malikmahak91 If you just want to see that information, you can enable the dump files using the runsettings for that.  You will then get a file with all the information that comes from the NUnit.Engine.  See https://github.com/nunit/docs/wiki/Tips-And-Tricks

**Comment by malikmahak91** [comment]
okay i will try that

**Comment by malikmahak91** [comment]
where do we save the settings file and is it different from config file? 
and the name of settings file is .runsettings?

**Comment by malikmahak91** [comment]
I am not using nunit in my test.I have build the unit test using selenium(C#)

**Comment by OsirisTerje** [comment]
Selenium is using nunit and the nunitadapter under the hood, so it will honor a runsettings file.
And yes, it should have the extension .runsettings and name can be whatever.  You need however to tell selenium/nunittestadapter that it should use the particular runsettings file, and I am not so familiar with Selenium, but it should be there somewhere.   You can download an item template for the runsettings from the marketplace (https://marketplace.visualstudio.com/items?itemName=OsirisTerje.Runsettings-19151), which has the general layout and the NUnit section.  Just add the dump statements within the NUNit section (you dont need anything of the rest there, so let that stay commented).   If you run crom command line, you should be able to do like:  vstest.console  whatever.test.dll /Settings:selenium.runsettings.   You can also add the runsettings in Visual Studio using the Test/Test settings menu.

**Comment by malikmahak91** [comment]
I downloaded the template and it got installed in visual studio but how we access it?
sorry, I am a newbie.

**Comment by OsirisTerje** [comment]
@malikmahak91 1. You have added a testsettings file, please delete that.  You need a runsettings file.    2.  As you have installed the template (and restarted VS), you go to the Solution root, right click, and Add new item.  
![bilde](https://user-images.githubusercontent.com/203432/43249829-12da3ac4-90bc-11e8-9959-2045f77bd8fc.png)

You should then see a list of possible types.
![bilde](https://user-images.githubusercontent.com/203432/43249848-1cd68438-90bc-11e8-8c03-e6265abc0b85.png)
Choose the Parallel one, not because it does parallel, but just because this is the simplest one.
After adding it, open it, 
![bilde](https://user-images.githubusercontent.com/203432/43249903-42ef28f0-90bc-11e8-807d-afa4ba13d9f4.png)
Add the section marked with red.  This enables the execution dump.  
Now, enable this settings file, the same way as mentioned above
![bilde](https://user-images.githubusercontent.com/203432/43249940-61a512f0-90bc-11e8-9497-b6a1adfe46a8.png)
RUn your tests in Visual Studio, and then look in your test projects binary output folder, there should now be a Dump folder there, containing the dump file
![bilde](https://user-images.githubusercontent.com/203432/43250100-d4fb1ab0-90bc-11e8-8a89-8f72d518491f.png)
In my case it is the bin/Debug/net471 folder that is my output (1), and the Dump folder contains the 
dump file (2).  
Hope this helps :-)

**Comment by malikmahak91** [comment]
Thankyou so much for explaining so beautifully.
All the results are getting pushed to i think some file.But i am not able to find a dump file yet.

**Comment by malikmahak91** [comment]
@OsirisTerje

**Comment by malikmahak91** [comment]
I found the file. :)

**Comment by chaitradangat** [comment]
conversation with ~~KINGS~~ **GODS** on GitHub Rocks!!

**Comment by chaitradangat** [comment]
we get to discuss with ~~KINGS~~ **GODS** , GitHub Rocks!!

**Comment by xboxpants** [comment]
I'm having this issue (on 2019). I read the above, I know why you don't want console output in Tests Output (even though the name suggests it should be). I realize it sometimes shows up in Standard Output under the test run details. But it doesn't always. I'm working on a project with a very common failure mode for tests being to hang. When a test run is aborted, no test details are generated, so there's no way see any of the console output (or is there?)... but I need the console output to diagnose the reason for the hang.

What's the solution? I wish there was just a Test Standard Output or something as another Output window stream in addition to Tests and Debug.

**Comment by OsirisTerje** [comment]
@xboxpants Are you on 3.17 ?  It has the new consoleout option, it should be default on, so you should get console output into the  VS Output/Tests "console" window.  See https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#consoleout.  Is there anything you miss there ?

**Comment by tarekahf** [comment]
How we can see the test output in VS Code for NUnit tests?
