### ISSUE TITLE
Does not show results or run tests when [TestCaseSource] with builders

### ISSUE THREAD

**Issue by Murstv** [nunit/nunit3-vs-adapter#951]
NUnit 3.13.1, 3.13.2; NUnit3TestAdapter 3.17.0, 4.2.1
Microsoft Visual Studio Community 2022 17.0.5 and Microsoft Visual Studio Community 2019 16.11.9
https://github.com/Murstv/NUnitAdapterTestDataSourceBug
.net 5.0
```
static IEnumerable Data_Test2()
{
    return new object[]
    {
        new object[]
        {
            BuildInt(), 1
        },
    };
}

static int BuildInt() {
    var random = new Random();
    return random.Next(); 
}

[TestCaseSource(nameof(Data_Test2))]
public void Test2NotShowing(int a, int b)
{
    Assert.AreEqual(a, b);
}
```
doesn't show or run in test explorer
![image](https://user-images.githubusercontent.com/77624896/152109626-fcb6e578-037b-49a0-b49d-06e41b031992.png)
but dotnet tests ok
![image](https://user-images.githubusercontent.com/77624896/152110177-a499041d-e6ee-4c24-b86f-22eee11b0b56.png)

**Comment by Prodigio** [comment]
Is the `BuildInt()` method executed when the test run or is it simply stored in `object[]` as a delegate?

**Comment by Murstv** [comment]
> Is the `BuildInt()` method executed when the test run or is it simply stored in `object[]` as a delegate?

it executed.
Its looks like https://github.com/nunit/nunit3-vs-adapter/issues/782
and solution for add .runsettings helps me
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
    <NUnit>
        <UseParentFQNForParametrizedTests>true</UseParentFQNForParametrizedTests>
        <UseNUnitIdforTestCaseId>true</UseNUnitIdforTestCaseId>
    </NUnit>
</RunSettings>

```

**Comment by m4ggo** [comment]
The problem here is that you are 'randomizing' your test name together with your test data. VS first disocovers the test name with one random number to list it in the TestExplorer and when it is executed you get a new random number and thus also a new test name. 
If you configure your testname as something fixed, e.g. via configuring the display names of the arguments 
```
static IEnumerable Data_Test2()
{
  yield return new TestCaseData(BuildInt(), 1).SetArgDisplayNames("Random", "1");
}
```
this will work.

But in my opinion randomizing your 'test input data' is not a good idea at 'unit' test level - if you really have an error for any  number in your code the test will just sporadically fail at some point in time - which might already be too late to fix it.

**Comment by Murstv** [comment]
> The problem here is that you are 'randomizing' your test name together with your test data. VS first disocovers the test name with one random number to list it in the TestExplorer and when it is executed you get a new random number and thus also a new test name. If you configure your testname as something fixed, e.g. via configuring the display names of the arguments
> 
> ```
> static IEnumerable Data_Test2()
> {
>   yield return new TestCaseData(BuildInt(), 1).SetArgDisplayNames("Random", "1");
> }
> ```
> 
> this will work.
> 
> But in my opinion randomizing your 'test input data' is not a good idea at 'unit' test level - if you really have an error for any number in your code the test will just sporadically fail at some point in time - which might already be too late to fix it.

I got it, thanks
