### ISSUE TITLE
Explicit run of selected tests could result in full test run

### ISSUE THREAD

**Issue by MaceWindu** [nunit/nunit3-vs-adapter#953]
When I select tests in test explorer and run them it works fine if selection is less than some magic number (for me it's around 1500-2000 tests, don't have exact number, e.g. in test example below it happens around 2k tests).

But if I select more tests it runs all tests in test project (which is not good in my case as it will take a lot of time).

I've tested same scenario with xunit to reduce chances of it being VS issue and it doesn't reproduce even with much bigger numbers like 9k tests.

sample nunit fixture
```cs
[TestFixture]
    public class MyFixture
    {
        private static int[] _cases = Enumerable.Range(1, 10000).Select(i => i).ToArray();
        [TestCaseSource(nameof(_cases))]
        public void Test(int id)
        {
        }
    }
```

sample xunit fixture
```cs
public class UnitTest1
    {

        public static class TestDataSource
        {
            private static object[][] _cases = Enumerable.Range(1, 10000).Select(i => new object[] { i }).ToArray();

            public static IEnumerable<object[]> TestData => _cases;
        }

        [Theory]
        [MemberData("TestData", MemberType = typeof(TestDataSource))]
        public void Test1(int id)
        {
        }
    }
```

All versions are latest release versions:
- Visual Studio 2022 17.0.5
- Microsoft.NET.Test.Sdk 17.0.0
- NUnit3TestAdapter 4.2.1
- NUnit 3.13.2
- xunit 2.4.1
- xunit.runner.visualstudio 2.4.3

**Comment by OsirisTerje** [comment]
Correct, the default limit is 2000.  There is a runsetting for adjusting this, you can set any number there:    https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#assemblyselectlimit

**Comment by MaceWindu** [comment]
Oh, cool. Didn't know it's intentional and configurable.

**Comment by OsirisTerje** [comment]
The reason for this limit is that the more tests that are in that selection the more of a performance hit you get.  So if you actually have more than a very high number (in this case 2000) you could just as well run all the tests, and it would actually go faster.  In some cases, like in yours, that would not be the case, and then you can adjust that limit yourselves.  

That said, a test project with too many tests like this - it could be wise to make a second check to verify if that is really beneficial or really contributes more information to your testing.  That at least, is the thinking behind this limit :-)  And again, ymmv !
