### ISSUE TITLE
TestEventListener not being called when running a test from VS test adapter.

### ISSUE THREAD

**Issue by quldude** [nunit/nunit3-vs-adapter#964]
* NUnit v3.13.2 and NUnit3TestAdapter v4.2.1.
* Microsoft Visual Studio Professional 2019 v16.11.11
* .net framework 4.7.1

With the latest version of testadapter and nunit I'm not seeing my ITestEventListener implementation being initialized when I run a test from visual studio test adapter. I've placed my addins file in {Solution folder}\packages\NUnit3TestAdapter.4.2.1\build\net35\my.nunit.addins. In nunit v3.6.1 I did the same with a previous version of testadapter (v3.9) and it worked. If I use the console runner v3.15, then it works fine. Do you know what I'm missing for the test adapter piece?

**Comment by OsirisTerje** [comment]
@quldude  Have this worked for any version of the adapter earlier or is this a regression in the 4.X series ?
Do you have any repro code ?
