### ISSUE TITLE
Create (beta) version that can be used in NUnit4 development

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit3-vs-adapter#965]
Now that the engine is tested to work with nunit4 (https://github.com/nunit/nunit-console/issues/1139) can we create a pre-release version of the adapter using nunit.engine 4, which can be referenced in the nunit framework so we can test it again from within Visual Studio.
This would then fix https://github.com/nunit/nunit/issues/3867

**Comment by OsirisTerje** [comment]
Sure.  Will you create a PR ?

**Comment by CharliePoole** [comment]
Using the unreleased 4.0 engine in the adapter seems at best premature. It may help discover certain issues, but we know of several quite important issues in advance:

* The engine no longer supports in-process execution, which the adapter makes use of. In fact, it no longer supports _any_ `ProcessModel` settings. (Breaking Change #861)
* The engine no longer supports `DomainUsage` settings, which the adapter used in the past. I don't know if it still does. (Breaking Change #860)
* The engine nuget package doesn't put things in the right place, so as to allow consuming projects to properly make use of it. This has existed for a long time but was only documented recently. Up to now, the adapter has compensated for this by copying all the needed engine assemblies to the correct place. The adapter package will have to be revised to compensate for the changes in the 4.0 engine layout. (# 1023)

The "new" (several years now) governance structure of the overall NUnit project has many advantages. But one disadvantage is that the dependencies among the independent component projects require dealing with issues in a certain order. IMO so long as we _know_ about reasons why the current development builds for the engine won't work with the adapter, it's not worth your time to do trial builds. There are probably other issues, but the well-known ones will hide them.

Reading the PR, I think you are running into all three of those I listed. :-(

The positive side of things is that Terje is now involved in the planning for engine changes, which he wasn't before, and that you are becoming involved in engine development!

**Comment by manfred-brands** [comment]
> Using the unreleased 4.0 engine in the adapter seems at best premature.

I'm happy with any version of the 3.x engine that supports the Nunit.Framework Version >= 3, which was my original PR.
That would be a small change and as NUnit.Framework 4 is not released only affect Nunit Framework developers.

**Comment by CharliePoole** [comment]
I'm taking it that you mean "doesn't crash" rather than "supports" fully, since that's all that the 4.0 build does as well. :-)

Just create an issue to port the changes to 3.x and assign it to yourself. We can create a release branch from the tag and do a point release on it, rather than on main.

**Comment by manfred-brands** [comment]
I'm going to close this issue in favour of a new one using an updated 3.x engine which recognized Nunit.Framework 4 (and .NET 7)
