### ISSUE TITLE
Filtering tests based on browser in NUNIT

### ISSUE THREAD

**Issue by gnaneswarreddy** [nunit/nunit3-vs-adapter#969]
I am using the below scenario to run in test explorer and it works fine but when i try to run the same using dotnet test it runs the three test cases.

Test Explorer

TestClass: SampleClass
Test Fixture: Tests("chrome), Tests("edge"), Tests("chromeheadless") ( i can run this in test explorer seperately)
Tests: SampleMethod(parameter1,parameter2,parameter3..parameter40)

CommandPrompt

dotnet test SampleProject.dll --tests SampleClass.Tests("chrome").SampleMethod 
(This is running all the browser mentioned in the fixture, I want to run only single browser)

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?

You can a) Add it as a PR to https://github.com/nunit/nunit3-vs-adapter.issues, add it as a separate folder named IssueXXX where the XXX is the issue number, or b) Add it as a zipped attachment here , or c) Add it to your own repo and just post the link. 

Make it as small as you can, it should compile "as is".

**Comment by OsirisTerje** [comment]
This might fall under the FQN issues ,  please have a look at https://github.com/nunit/nunit3-vs-adapter/issues?q=is%3Aissue+project%3Anunit%2Fnunit3-vs-adapter%2F1+is%3Aopen and see if yours already is listed.  
The workaround is to add categories to the tests, and use those for filtering.
