### ISSUE TITLE
Add .NET Core (DNX) Support

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#99]
We should be able to execute .NET Core tests from the adapter. I marked this as status:design because we need to figure out how to do this. I also added status:blocked because it will depend on similar engine related issues to be completed first.

**Comment by hanssens** [comment]
:+1: Indeed. Adding the NUnit 3 Test Adapter to a Core project (DNX) will now result in the following compile error:

```
Error NU1002 - The dependency NUnit3TestAdapter 3.0.8-ctp-8 in project XXX 
does not support framework .NETPlatform,Version=v5.4.
```

Steps te reproduce the error:

1. Create a new DNX (Core) Package
2. Use `Install-Package NUnit3TestAdapter -Pre` (for 3.0.8-CTP8)
3. Compile, which fails

**Comment by tdurova** [comment]
I have the same problem, and withot it I can't see any tests =(

**Comment by rprouse** [comment]
This adapter is compiled with the desktop version of ,NET and run by Visual Studio using .NET 4.5, so it turns out it is not capable of running .NET Core tests. Since I entered this issue, we have create a .NET Core test runner that allows you to run tests on the command line, or in Visual Studio. It is not documented here yet, but I have written a blog post describing how to [test .NET Core using NUnit and our .NET Core test adapter](http://www.alteridem.net/2016/06/18/nunit-3-testing-net-core-rc2/).

I am closing this issue. We will not (can not) add that capability to this adapter.
