### ISSUE TITLE
Missing output with failed test stack traces for Assert.Multiple

### ISSUE THREAD

**Issue by gps7** [nunit/nunit3-vs-adapter#990]
Hi,
I am missing test output with stack traces for failed tests if Assert.Multiple is used. For running below example test fails in VS2022 (Test Explorer) but output not showing all required information about failures inside of Multiple assert scope but only single stack trace to the test itself:

[Test]
public void AssertMultiple()
{
Assert.Multiple(() =>
{
ValidateInteger();
Assert.That("a", Is.EqualTo("b"), "String");
ValidateInteger();
});
}

private void ValidateInteger() => Assert.That(1, Is.EqualTo(2), "Integer");

![VS2022-assert-multiple_failure_message](https://user-images.githubusercontent.com/21167960/177100123-e86c7ce4-8081-4a58-aca1-d3424910f0a7.PNG)

I've expect to see not single stack trace but 3 stack traces for 3 failures in single Assert.Multiple request which leads to failed assert. 

This is a fallow up issue after creating issue #4129 https://github.com/nunit/nunit/issues/4129 at Nunit and issue #1192 https://github.com/nunit/nunit-console/issues/1192 at Nunit-Console and issue #907 https://github.com/TestCentric/testcentric-gui/issues/907 at Test-centric. Please refer to the lined items for more details if needed.

**Comment by OsirisTerje** [comment]
Fixed.

See attached nupkg 
[NUnit3TestAdapter.4.3.0-alpha-107.zip](https://github.com/nunit/nunit3-vs-adapter/files/9086208/NUnit3TestAdapter.4.3.0-alpha-107.zip)

**Comment by gps7** [comment]
Great, works.
