### ISSUE TITLE
FullyQualifiedName filter not working when the filter contains more than 2000 test cases

### ISSUE THREAD

**Issue by Jagadeesh19** [nunit/nunit3-vs-adapter#998]
Nunit version: 3.13.3
NUnit3TestAdapter version: 4.2.1
Tests run in linux command line 
dotnet version: 6.0

Observations:
1. When the filter with FullyQualifiedName is run, if the number of tests in the filter are more than 2000, the dotnet test command is executing all the tests in the project along with the filter.
2. whereas if the filter with TestCategory is run, even if the number of tests in the filter are more than 2000, the dotnet test command is executing only the tests in the filter.
3. In both cases the test Result will only show test cases in the filter.

Steps to reproduce:
1. Clone the public repository https://github.com/Jagadeesh19/NunitIssueReproduce
2. The project contains 2 classes class1 and class2
3. class1 contains 2001 test cases
4. class2 contains 1 test case.
5. the one test in class2 contains a print statement to identify if the test is run.
6. running the command `dotnet test --filter FullyQualifiedName="NunitIssueReproduce.Class1"` runs all the tests in class1 along with test in class2
7. whereas running the command `dotnet test --filter TestCategory="Class1"` runs only the tests in class1

**Comment by OsirisTerje** [comment]
That is the default limit set by the AssemblySelectLimit property in the runsettings.
See https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#assemblyselectlimit, and adjust it there :-)

**Comment by Jagadeesh19** [comment]
Oh okay. Thank you @OsirisTerje
